### ISSUE TITLE
Client crashes after entering server URL

### ISSUE THREAD

**Issue by DougBeney** [nextcloud/desktop#1036]
### Behaviour

On Linux Mint 19.1, I have Nextcloud 2.5.1 installed via Flatpak. I also have tried this with the Nextcloud PPA with the same result.

I open Nextcloud and the 'first time setup' popup comes up where I would enter my server URL. I enter my server URL and it crashes.

### Steps to reproduce

1. Install the Nextcloud client on a fresh install of Linux Mint 19.1.
2. Enter your server URL.
3. It should crash.

### Client configuration

Client version: 2.5.1git (From Flatpak)

Operating system: Linux Mint 19.1 (Cinnamon)

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): Using Qt 5.12.0, built against Qt 5.12.0

Client package (From Nextcloud or distro) (Linux only): Flatpak

Installation path of client: N/A?

### Server configuration

Operating system: Ubuntu 18.04

I am using the official [Docker image](https://github.com/nextcloud/docker) and am using Nginx as a reverse proxy to Docker.

Web server: 

Reverse proxy to Docker: nginx version: nginx/1.14.0 (Ubuntu)

```
$ docker exec nextcloud apache2 -v
Server version: Apache/2.4.25 (Debian)
Server built:   2018-11-03T18:46:19
```

Database: MariaDB

PHP version: 7.3.1 

Nextcloud version: 15.0.2

Storage backend (external storage): Mariadb

### Logs

1. Client logfile: https://hastebin.com/xelirebayo

**Comment by brtptrs** [comment]
Is the nc-client behind a proxy? We are have problems with 2.5.1 clients when they connect to the server through an authenticating proxy.

**Comment by DougBeney** [comment]
Nope. And I was doing a fresh install of Linux Mint and Nextcloud was one of the first programs I installed. Should hopefully be easily reproducible unless there is something wrong with my server, https://cloud.dougie.io - Which there shouldn't since I'm using the official Docker image.

**Comment by TotallyGeeky** [comment]
I'm also experiencing this, same exact issues, different server, different host. 

Client Configuration:

**Comment by zicklag** [comment]
I'm using the official Docker image for the server, I'm behind an HTTP proxy that requires authentication, and I'm using the AppImage on Ubuntu 16.04, and I'm having the same problem. It crashes with a stack trace after clicking next from the server URL page.

**Comment by wunderlich** [comment]
Same issue here.

## Behaviour 

I already use an account without any problems. Now I want to add a second account and after entering the URL (and one or two seconds) the desktop client crashes.

## Client Configuration

Linux Mint 19.1 (Cinnamon), Desktop Client 2.5.1

## Server Configuration

Nextcloud Server Version 15.0.4 (not hosted by me)

## Logs (excerpt)

### Command Line

```
nextcloud --logfile logfile.log
qt5ct: using qt5ct plugin
Abgebrochen (Speicherabzug geschrieben)
```

I don't exactly know, what *Speicherabzug geschrieben* means. Segfault?

### Client-Log

```
[OCC::Application::setupLogging 	"################## Nextcloud locale:[de_DE] ui_lang:[] version:[2.5.1git] os:[Linux Mint 19.1]"
[OCC::Application::setupTranslations 	Using "de_DE" translation
[OCC::SocketApi::SocketApi 	server started, listening at  "/run/user/1000/Nextcloud/socket"
[OCC::FolderMan::FolderMan 	setting remote poll timer interval to 30000 msec
[OCC::AccountManager::loadAccountHelper 	Account for QUrl("https://[url1]") using auth type "webflow"
[OCC::WebFlowCredentials::createQNAM 	Get QNAM
[unknown 	D-Bus system tray: no
[OCC::ownCloudGui::setupContextMenu 	Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false
[OCC::AccessManager::createRequest 	6 "GET" "https://[url1]/ocs/v2.php/core/navigation/apps?absolute=true&format=json" has X-Request-ID "dc3bb424-3942-4bf4-b76a-519ed0d89d35"
[OCC::AbstractNetworkJob::start 	OCC::OcsNavigationAppsJob created for "https://[url1]" + "ocs/v2.php/core/navigation/apps" ""
[OCC::FolderMan::setupFolders 	Setup folders from settings file

[… some sync stuff from my already existing account …]

[OCC::OwncloudSetupWizard::slotSystemProxyLookupDone 	No system proxy set by OS
[OCC::AccessManager::createRequest 	2 "" "https://[newurl]/login/status.php" has X-Request-ID "f81ba728-e76b-4b3d-a410-6bc9002c90ef"
[OCC::AbstractNetworkJob::start 	OCC::CheckServerJob created for "https://[newurl]/login" + "status.php" "OCC::OwncloudSetupWizard"
[OCC::CheckServerJob::finished 	No SSL session identifier / session ticket is used, this might impact sync performance negatively.
[OCC::CheckServerJob::finished 	status.php returns:  QJsonDocument({"edition":"","installed":true,"maintenance":false,"needsDbUpgrade":false,"productname":"[Cloud Name]","version":"15.0.4.0","versionstring":"15.0.4"})   QNetworkReply::NetworkError(NoError)  Reply:  QNetworkReplyHttpImpl(0x558e205d0e50)
[OCC::DetermineAuthTypeJob::start 	Determining auth type for QUrl("https://[newurl]/login/remote.php/webdav/")
[OCC::AccessManager::createRequest 	2 "" "https://[newurl]/login/remote.php/webdav/" has X-Request-ID "2486897b-a2f5-4f5e-bdae-9994efbb6cff"
[OCC::AbstractNetworkJob::start 	OCC::SimpleNetworkJob created for "https://[newurl]/login" + "" "OCC::Account"
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://[newurl]/login/remote.php/webdav/" has X-Request-ID "3a36b4bb-483d-439a-a434-14f27982fa71"
[OCC::AbstractNetworkJob::start 	OCC::SimpleNetworkJob created for "https://[newurl]/login" + "" "OCC::Account"
[OCC::DetermineAuthTypeJob::checkBothDone 	Auth type for QUrl("[newurl]/login/remote.php/webdav/") is 3
[OCC::WebViewPage::initializePage 	Url to auth at:  "https://[newurl]/login/index.php/login/flow"
[unknown 	Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) 
```

**Comment by tenspd137hp** [comment]
I can also confirm this happens on Gentoo.....

**Comment by tenspd137** [comment]
I can confirm this happens on Gentoo as well.

`[OCC::AbstractNetworkJob::start 	OCC::SimpleNetworkJob created for "https://[url]" + "" "OCC::Account"
[OCC::DetermineAuthTypeJob::checkBothDone 	Auth type for QUrl("https://[url]/remote.php/webdav/") is 3
[OCC::WebViewPage::initializePage 	Url to auth at:  "https://[url]/index.php/login/flow"
[unknown 	Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) `

**Comment by NiklasMM** [comment]
I have the same experience with Version Version 2.5.2git from flatpack on Linux Mint 19.1, when I try to add a second server.

Here's the output, I can see on the console:

```
 -> /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=nextcloud org.nextcloud.Nextcloud
Received signal 6
#0 0x7fd9ff223e6e <unknown>
#1 0x7fd9ff222d13 <unknown>
#2 0x7fd9ff223de5 <unknown>
#3 0x7fd9fb62c2d0 <unknown>
#4 0x7fd9fb62c24f gsignal
#5 0x7fd9fb616545 abort
#6 0x7fd9fbb8a8a7 QMessageLogger::fatal()
#7 0x7fd9fa5bbd72 <unknown>
#8 0x7fd9fa5bc09a <unknown>
#9 0x7fd9fa5be216 QQuickWidget::resizeEvent()
#10 0x7fda03ac19ed <unknown>
#11 0x7fd9fc8126fe QWidget::event()
#12 0x7fd9fa5beeb5 QQuickWidget::event()
#13 0x7fda03ac1d70 <unknown>
#14 0x7fd9fc7d25b1 QApplicationPrivate::notify_helper()
#15 0x7fd9fc7d9960 QApplication::notify()
#16 0x7fd9fbd85e99 QCoreApplication::notifyInternal2()
#17 0x7fd9fc80a856 QWidgetPrivate::sendPendingMoveAndResizeEvents()
#18 0x7fd9fc80e6e3 QWidgetPrivate::show_helper()
#19 0x7fd9fc80e68a QWidgetPrivate::showChildren()
#20 0x7fd9fc80e6ff QWidgetPrivate::show_helper()
#21 0x7fd9fc811873 QWidgetPrivate::setVisible()
#22 0x7fd9fc80e6a0 QWidgetPrivate::showChildren()
#23 0x7fd9fc80e6ff QWidgetPrivate::show_helper()
#24 0x7fd9fc811873 QWidgetPrivate::setVisible()
#25 0x7fd9fc80e6a0 QWidgetPrivate::showChildren()
#26 0x7fd9fc80e6ff QWidgetPrivate::show_helper()
#27 0x7fd9fc80e68a QWidgetPrivate::showChildren()
#28 0x7fd9fc80e6ff QWidgetPrivate::show_helper()
#29 0x7fd9fc80e68a QWidgetPrivate::showChildren()
#30 0x7fd9fc80e6ff QWidgetPrivate::show_helper()
#31 0x7fd9fc811873 QWidgetPrivate::setVisible()
#32 0x7fd9fc9f9d2c <unknown>
#33 0x7fd9fc9fe08b <unknown>
#34 0x7fd9fc9fe403 QWizard::next()
#35 0x7fd9fbdb00e3 QMetaObject::activate()
#36 0x7fda03ca4d12 OCC::DetermineAuthTypeJob::authType()
#37 0x7fda03c1b079 OCC::DetermineAuthTypeJob::checkBothDone()
#38 0x7fda03c1b19f <unknown>
#39 0x7fd9fbdb00e3 QMetaObject::activate()
#40 0x7fda03ca4d73 OCC::SimpleNetworkJob::finishedSignal()
#41 0x7fda03c1b481 OCC::SimpleNetworkJob::finished()
#42 0x7fda03c1493b OCC::AbstractNetworkJob::slotFinished()
#43 0x7fd9fbdb00e3 QMetaObject::activate()
#44 0x7fd9fcd89fd4 <unknown>
#45 0x7fd9fce2c259 <unknown>
#46 0x7fd9fbdb0822 QObject::event()
#47 0x7fd9fc7d25b1 QApplicationPrivate::notify_helper()
#48 0x7fd9fc7d9960 QApplication::notify()
#49 0x7fd9fbd85e99 QCoreApplication::notifyInternal2()
#50 0x7fd9fbd88ee7 QCoreApplicationPrivate::sendPostedEvents()
#51 0x7fd9fbdda5f3 <unknown>
#52 0x7fd9fb09a4ae g_main_context_dispatch
#53 0x7fd9fb09a748 <unknown>
#54 0x7fd9fb09a7e0 g_main_context_iteration
#55 0x7fd9fbdd9c03 QEventDispatcherGlib::processEvents()
#56 0x7fd9fbd84b6b QEventLoop::exec()
#57 0x7fd9fbd8cba2 QCoreApplication::exec()
#58 0x563fc81edba8 main
#59 0x7fd9fb6180d3 __libc_start_main
#60 0x563fc81ee10a _start
  r8: 0000000000000000  r9: 00007ffc5f891b70 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007ffc5f891eb8 r13: 0000563fc909db60 r14: 0000000000000001 r15: 00007ffc5f8924c0
  di: 0000000000000002  si: 00007ffc5f891b70  bp: 0000563fc909db60  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007fd9fb62c24f  sp: 00007ffc5f891b70
  ip: 00007fd9fb62c24f efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

**Comment by markmcb** [comment]
Similar issues. Fedora 30, fresh install using distro-included nextcloud client package. I get to the confirmation dialog after providing login credentials and then core dump (core dump attached).

[core_dump_20190406.txt](https://github.com/nextcloud/desktop/files/3050777/core_dump_20190406.txt)

**Comment by andreas-glaser** [comment]
same here... mint 19

**Comment by camilasan** [comment]
Could #1218 be  related?

**Comment by markmcb** [comment]
Just following up. Not sure what changed, but the package manager for Fedora 30 posted an update and the client works now without crashing.

**Comment by camilasan** [comment]
Ok, thanks. Will close the issue.

**Comment by Ezwen** [comment]
Same problem here with Mint 19 and nextcloud-client installed using flatpak.

**Comment by karozagorus** [comment]
This is still happening, this is blasphemous. Nobody here took their sweet ass time to fix the problem.

**Comment by elumbella** [comment]
This was referenced somewhere else, but this crash might be related to nvidia graphics drivers.
Starting nextcloud with
`LD_PREFIX=/usr/lib/libGL.so.1 nextcloud` (your path may vary)
fixed the issue, at least for me. It might be a problem of the nvidia drivers, not of nextcloud.

(I was experiencing similar crashes of firefox, launching it the same way seems to have corrected it)

**Comment by karozagorus** [comment]
> This was referenced somewhere else, but this crash might be related to nvidia graphics drivers.
> Starting nextcloud with
> `LD_PREFIX=/usr/lib/libGL.so.1 nextcloud` (your path may vary)
> fixed the issue, at least for me. It might be a problem of the nvidia drivers, not of nextcloud.
> 
> (I was experiencing similar crashes of firefox, launching it the same way seems to have corrected it)

Only issue is that, I'm using AMD drivers, there are no Nvidia drivers at all.

**Comment by fancycode** [comment]
@camilasan could you please reopen this issue? The client is still crashing for me (Ubuntu 18.04, just compiled from 04a08bfb23a4de73996a3790e84c3b8c290996d9) immediately after entering a custom server address and clicking "Next":
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fffed268801 in __GI_abort () at abort.c:79
#2  0x00007fffedfeefb7 in QMessageLogger::fatal(char const*, ...) const () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007fffebf549f0 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5QuickWidgets.so.5
#4  0x00007fffebf54d5a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5QuickWidgets.so.5
#5  0x00007fffebf56f8e in QQuickWidget::resizeEvent(QResizeEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5QuickWidgets.so.5
#6  0x00007ffff6b287fd in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebEngineWidgets.so.5
#7  0x00007fffeef9fbf2 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007fffebf579eb in QQuickWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5QuickWidgets.so.5
#9  0x00007ffff6b28b1b in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebEngineWidgets.so.5
#10 0x00007fffeef6083c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007fffeef68104 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007fffee1e29c8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007fffeef980fb in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007fffeef9bed3 in QWidgetPrivate::show_helper() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007fffeef9bdee in QWidgetPrivate::showChildren(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007fffeef9beef in QWidgetPrivate::show_helper() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007fffeef9ebeb in QWidget::setVisible(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007fffeef9be40 in QWidgetPrivate::showChildren(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007fffeef9beef in QWidgetPrivate::show_helper() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007fffeef9ebeb in QWidget::setVisible(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007fffeef9be40 in QWidgetPrivate::showChildren(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007fffeef9beef in QWidgetPrivate::show_helper() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007fffeef9bdee in QWidgetPrivate::showChildren(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007fffeef9beef in QWidgetPrivate::show_helper() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007fffeef9bdee in QWidgetPrivate::showChildren(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007fffeef9beef in QWidgetPrivate::show_helper() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007fffeef9ebeb in QWidget::setVisible(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007fffef1852cc in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007fffef189307 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007fffef189753 in QWizard::next() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00005555558276cd in OCC::OwncloudWizard::setAuthType(OCC::DetermineAuthTypeJob::AuthType) ()
#32 0x000055555577b88c in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<OCC::DetermineAuthTypeJob::AuthType>, void, void (OCC::OwncloudWizard::*)(OCC::DetermineAuthTypeJob::AuthType)>::call(void (OCC::OwncloudWizard::*)(OCC::DetermineAuthTypeJob::AuthType), OCC::OwncloudWizard*, void**) ()
#33 0x000055555577b0de in void QtPrivate::FunctionPointer<void (OCC::OwncloudWizard::*)(OCC::DetermineAuthTypeJob::AuthType)>::call<QtPrivate::List<OCC::DetermineAuthTypeJob::AuthType>, void>(void (OCC::OwncloudWizard::*)(OCC::DetermineAuthTypeJob::AuthType), OCC::OwncloudWizard*, void**) ()
#34 0x000055555577ab5a in QtPrivate::QSlotObject<void (OCC::OwncloudWizard::*)(OCC::DetermineAuthTypeJob::AuthType), QtPrivate::List<OCC::DetermineAuthTypeJob::AuthType>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()
#35 0x00007fffee21175f in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x00007ffff7432463 in OCC::DetermineAuthTypeJob::authType(OCC::DetermineAuthTypeJob::AuthType) ()
   from /home/domain/jojo/devel/nextcloud/desktop/build/src/libsync/libnextcloudsync.so.0
#37 0x00007ffff7385ed5 in OCC::DetermineAuthTypeJob::checkAllDone() ()
   from /home/domain/jojo/devel/nextcloud/desktop/build/src/libsync/libnextcloudsync.so.0
---Type <return> to continue, or q <return> to quit---
#38 0x00007ffff738540e in OCC::DetermineAuthTypeJob::start()::{lambda(QJsonDocument const&, int)#4}::operator()(QJsonDocument const&, int) const () from /home/domain/jojo/devel/nextcloud/desktop/build/src/libsync/libnextcloudsync.so.0
#39 0x00007ffff7387f9e in QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1>, QtPrivate::List<QJsonDocument const&, int>, void, OCC::DetermineAuthTypeJob::start()::{lambda(QJsonDocument const&, int)#4}>::call({lambda(QJsonDocument const&, int)#4}&, void**) ()
   from /home/domain/jojo/devel/nextcloud/desktop/build/src/libsync/libnextcloudsync.so.0
#40 0x00007ffff7387dc2 in void QtPrivate::Functor<OCC::DetermineAuthTypeJob::start()::{lambda(QJsonDocument const&, int)#4}, 2>::call<QtPrivate::List<QJsonDocument const&, int>, void>({lambda(QJsonDocument const&, int)#4}&, void*, {lambda(QJsonDocument const&, int)#4}&*) ()
   from /home/domain/jojo/devel/nextcloud/desktop/build/src/libsync/libnextcloudsync.so.0
#41 0x00007ffff7387bda in QtPrivate::QFunctorSlotObject<OCC::DetermineAuthTypeJob::start()::{lambda(QJsonDocument const&, int)#4}, 2, QtPrivate::List<QJsonDocument const&, int>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()
   from /home/domain/jojo/devel/nextcloud/desktop/build/src/libsync/libnextcloudsync.so.0
#42 0x00007fffee21175f in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#43 0x00007ffff743219b in OCC::JsonApiJob::jsonReceived(QJsonDocument const&, int) ()
   from /home/domain/jojo/devel/nextcloud/desktop/build/src/libsync/libnextcloudsync.so.0
#44 0x00007ffff7384b8f in OCC::JsonApiJob::finished() () from /home/domain/jojo/devel/nextcloud/desktop/build/src/libsync/libnextcloudsync.so.0
#45 0x00007ffff73784b3 in OCC::AbstractNetworkJob::slotFinished() ()
   from /home/domain/jojo/devel/nextcloud/desktop/build/src/libsync/libnextcloudsync.so.0
#46 0x00007ffff737ba36 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (OCC::AbstractNetworkJob::*)()>::call(void (OCC::AbstractNetworkJob::*)(), OCC::AbstractNetworkJob*, void**) ()
   from /home/domain/jojo/devel/nextcloud/desktop/build/src/libsync/libnextcloudsync.so.0
#47 0x00007ffff737b927 in void QtPrivate::FunctionPointer<void (OCC::AbstractNetworkJob::*)()>::call<QtPrivate::List<>, void>(void (OCC::AbstractNetworkJob::*)(), OCC::AbstractNetworkJob*, void**) () from /home/domain/jojo/devel/nextcloud/desktop/build/src/libsync/libnextcloudsync.so.0
#48 0x00007ffff737b85e in QtPrivate::QSlotObject<void (OCC::AbstractNetworkJob::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) () from /home/domain/jojo/devel/nextcloud/desktop/build/src/libsync/libnextcloudsync.so.0
#49 0x00007fffee21175f in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#50 0x00007fffef6fa75f in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#51 0x00007fffef78ad49 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#52 0x00007fffee2121b2 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#53 0x00007fffeef6083c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#54 0x00007fffeef68104 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#55 0x00007fffee1e29c8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#56 0x00007fffee1e513d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#57 0x00007fffee23c353 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#58 0x00007fffeb3f7417 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#59 0x00007fffeb3f7650 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#60 0x00007fffeb3f76dc in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#61 0x00007fffee23b97f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#62 0x00007fffee1e09fa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#63 0x00007fffee1e9aa4 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#64 0x00005555556c6d79 in main ()
```

I'm happy to provide additional details / test possible solutions if necessary, email is in my profile.

**Comment by claell** [comment]
@fancycode reopening.

**Comment by vincentqb** [comment]
The nextcloud client on the server machine (hosting the nextcloud server) started to crash (core dump) after entering the URL. This occurred after updating nextcloud server from 12.* to 13.* (old indeed).

The nextcloud client on another client machine was fine.

However, once I updated nextcloud server all the way to 17.*, the nextcloud client (on the server machine) successfully launched and started syncing again.
