### ISSUE TITLE
Mac Client does not synchronize files in subfolders

### ISSUE THREAD

**Issue by alberto464** [nextcloud/desktop#1083]
When loading multiple files, the subfolders are not synchronized. Only the empty folders are created but the files are not seen.

### Steps to reproduce
Copy and paste a tree structure with folders and subfolders.

### Client configuration
Client version: 2.5.1

Operating system: MAC OS 10.14.2

OS language: Italian

**Comment by zocker-160** [comment]
I second that.

I can reproduce this issue with Client version 2.5.2 on both Linux (Ubuntu 18.04) and Windows 10
OS Language is English and German.

When I copy a folder to a synced folder, only the folder itself fgets uploaded, but without the files in it.

**Comment by zocker-160** [comment]
this is related to #1000 and should be fixed in the upcoming version

**Comment by markoste** [comment]
Im currently using Version 2.6.0stable (build 20190927) of the Nextcloud client on Mac OS Catalina 10.15.1 (19B88) and can still confirm this bug.

**Comment by erictt** [comment]
Me too. On Mac OS, version 2.6.1stable (build 20191105) still having this issue.

**Comment by ogarai** [comment]
I see this on OSX 10.15.3 with nextcloud desktop client version 2.6.4stable (build 20200303)

**Comment by DerHOgi** [comment]
I have the same issues!!!
macOS 10.15.5 using latest nextcloud client version 2.6.4stable (build 20200303).

It's really a shame that this bug that obviously exists (was reported) since january 2019 is still not fixed. Sorry guys, but this is really a deal-breaker. Is any of the dev's aware about this? Closing the client and reopen it helps to sync the missing files, but this can't be a solution!
