### ISSUE TITLE
White text on almost-white background

### ISSUE THREAD

**Issue by despens** [nextcloud/desktop#1237]
### Expected behaviour

All text should be readable.

### Actual behaviour

White text on almost-white background appears.

### Steps to reproduce
1. Sync directory
2. Some sync error appears
3. Sync progress text turns from black to white

### Client configuration
Client version: 2.5.2git

Operating system: Ubuntu 18.04

OS language: US English

Qt version used by client package (Linux only, see also Settings dialog): not available

Client package (From Nextcloud or distro) (Linux only): 
``ii  nextcloud-client                           2.5.2-20190319.015224~bionic1                amd64        Nextcloud desktop sync client`` from ppa.launchpad.net/nextcloud-devs/client/ubuntu

Installation path of client: `/usr/bin/nextcloud`

![Screenshot-20190507122042-909x112](https://user-images.githubusercontent.com/571494/57293563-5fd25980-70c5-11e9-876d-b390ed7b0b1e.png)

**Comment by camilasan** [comment]
I believe we have fixed this. Could you try 2.5.3 or the release candidate for 2.6?
https://github.com/nextcloud/desktop/releases

**Comment by despens** [comment]
I don't seem to be able to trigger an sync error when I need it :smile: — but will keep an eye out for the rendering bug in the new sync client!

**Comment by RubenFixit** [comment]
I just installed and 2.5.3 and then 2.6, and the issue still exists. I only tested this on my Win 10 Laptop.

**Comment by merrx** [comment]
I have the same issue with the white font.
Ubuntu 18.04, using the PPA to install nextcloud.
Nextcloud 2.5.x (don't know which version) and 2.6.0

**Comment by RubenFixit** [comment]
Just upgraded my desktop client to Version 2.6.1stable-Win64 (build 20191105)
The issue still exists.

**Comment by tobias-richter** [comment]
I can confirm that this issue also exists on Windows 10 (Version 1903 Build 18362.535) with Nextcloud 2.6.1stable-Win64 (build 20191105)
