### ISSUE TITLE
crash of 2.6.1stable for Windows caused by Qt5Core.dll

### ISSUE THREAD

**Issue by laarisyko** [nextcloud/desktop#1662]
Hi, we have the same problem here for 2.6.1stable for Windows. It runs for several hours and it mainly crashs during idel time. If it has to sync something it does not crash normally. This issue basically makes it imposible to work with the sync client, we already had several double editing problems during our daily work. Is there a workaorund even before the next version will be released?

The windows crash report says the following:
Name der fehlerhaften Anwendung: nextcloud.exe, Version: 2.6.1.6017, Zeitstempel: 0x5dc0b373
Name des fehlerhaften Moduls: Qt5Core.dll, Version: 5.12.5.0, Zeitstempel: 0x5d6ebdfc
Ausnahmecode: 0xc0000409
Fehleroffset: 0x0000000000028978
ID des fehlerhaften Prozesses: 0x3db0
Startzeit der fehlerhaften Anwendung: 0x01d5aa7db907ccf9
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\Nextcloud\nextcloud.exe
Pfad des fehlerhaften Moduls: C:\Program Files (x86)\Nextcloud\Qt5Core.dll
Berichtskennung: 05eb1916-2ecc-4f51-be13-d0c257265069
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

_Originally posted by @laarisyko in https://github.com/nextcloud/desktop/issues/915#issuecomment-561790749_

**Comment by kasinjsh** [comment]
Downgrade till issues are resolved.

**Comment by laarisyko** [comment]
I have tried to downgrade one version number 2.6.1 to 2.6.0, but still the same problem. Seems, that this issue already exists for a longer time. It is really a big thing, if you want to work with others in a team. I can try to even go back in the version number, but this is not really the way how it should be. Any ideas, comments how this could be solved. From the error report it seems to be a Qt error. Normaly I click on the symbol region in Windows 10 and then I can see the client logo for one second and then it disapears.

**Comment by obiper** [comment]
I'm in the same boat. I've tried every client version since 2.5.0. Every client crashes after a while (could be after 1 or 4 days). I've tried to install the client on another system to exlude a client system problem. This also happens only on one of my 5 nextcloud server. I'm going to update to 17.0.5 today. Maybe the serverupdate helps...

**Comment by daskydasky** [comment]
I just migrated from OwnCloud client to the latest NextCloud 2.6.4 and got this issue. Had to roll it back to OwnCloud. So I'm running Nextcloud Server 18.0.4 with OwnCloud 2.6.1 windows client. No issues at all.
