### ISSUE TITLE
Auto update not working

### ISSUE THREAD

**Issue by drikqlis** [nextcloud/desktop#1798]
### Expected behaviour
When new version is released client should download and silent update according to documentation:

> The Nextcloud client checks for updates and downloads them when available. You can view the update status under Settings -> General -> Updates in the Nextcloud client. If an update is available, and has been successfully downloaded, the Nextcloud client starts a silent update prior to its next launch and then restarts itself. Should the silent update fail, the client offers a manual download.

### Actual behaviour
Every time there is new release client prompts to manually download and install update. Tested on 5 different PCs in different networks with admin privileges. 

### Steps to reproduce
1. Install older version of the client.
2. Wait for update check.
3. Client prompts to manually download.

### Client configuration
Client version: 2.6.3

Operating system: Windows 10 1909

OS language: Polish

Installation path of client: Default

**Comment by josselex** [comment]
Same issue here on all clients on windows 10 and windows 8.1

**Comment by misch7** [comment]
Known issue, work in progress, see #1847 

The updating functionality deserves some more attention, it had to step back for bug fixing and providing releases more regularly.

**Comment by claell** [comment]
@misch7 Nice to see, thanks for referencing. Is this already available, since #1847 got merged or are there other additional chanegs needed?

Also I assume this is not a bug, but currently actually wanted, so this is rather a feature request, correct?

**Comment by antonyanimator** [comment]
Was this fixed? I still have this problem and is quite frustrating to have to log in to every computer and do an update.

**Comment by DrCarsonBeckett** [comment]
It's is seemingly not. I got that issue since I use the nextcloud client, which was version 2.3.* . And its still not working for me.
Since I manually also check for updates, because of such issues, I nocited that there was a nupdate (3.0 to 3.0.1 and 3.0.1 to 3.0.2). But the auto updater said, that its the latest version and that there are no updates.

**Comment by claell** [comment]
Given this is still open, I'd assume it is still not fixed. Also your comments indicate so.

Ping @er-vin @misch7 @camilasan

**Comment by er-vin** [comment]
Well, code wise I see that on Windows it should propose the install and just do it. This is not the case on Mac and Linux though there you should get the notification and that's it.

@DrCarsonBeckett you sure your config doesn't prevent the auto update? Please check your nextcloud.cfg just in case.

**Comment by drikqlis** [comment]
That's not the case on Windows, I have it installed on multiple different PCs and it always asks to download or skip. When download is chosen it opens browser and downloads the file (very slowly). After that you have to open it yourself and press "Next" a few times and it will uninstall the previous version and install the new one. No automatic update ever happened to me.

**Comment by er-vin** [comment]
OK, something got broken I guess. @misch7 any idea what happened, I think you were last to look into this?

**Comment by DrCarsonBeckett** [comment]
@er-vin There's nothing in there which disables it. Plus, I have that issues on multiple computers. Never worked before. I already ones tested to actually disable auto update checks and re-enable them after a restart. Also tried to delete the file and reboot. Same issue.

**Comment by misch7** [comment]
@er-vin When I looked at the code I discovered that the auto-update functionality once was working but was disabled in the code for Windows ages ago. For macOS the Sparkle library once did the job but also was disabled (and outdated) on our build server.

So there was no way an automatic update could have worked for anyone ;-)

Since I already did some work on the code side for both platforms this year, let me keep it on my list. Just had to be postponed ever since because of priorities.

**Comment by DrCarsonBeckett** [comment]
Its still not working. Currently installed version: 3.0.2. The Nextcloud client says its up to date but the fact that I just downloaded the 3.0.3 client tells me something else. 😄

**Comment by claell** [comment]
@DrCarsonBeckett What you are talking about seems to be a not working update notification, while this seems to be mainly about a not working auto update.

Also note that auto update is not working currently and will hopefully be fixed in future versions.

**Comment by DrCarsonBeckett** [comment]
@claell While yes its true, this topic is about the auto update and its still not working. I also meant the notification, but actually more the update function itself. Sorry if that wasn't clear.

**Comment by claell** [comment]
Thanks for opening a separate issue.

This issue's description says:

> Every time there is new release client prompts to manually download and install update. Tested on 5 different PCs in different networks with admin privileges.

So the update notification itself seems to be working for the author of this issue.

**Comment by DrCarsonBeckett** [comment]
Thats why I thought it's better to open a seperate issue. 😃

**Comment by tgp1994** [comment]
I could have sworn I remember Nextcloud working like this for the longest time, where it would prompt you to update and then automatically download the installer and install it for you. I thing this was changed at one point so now that I've updated (3.0.3), I hit Get Update and it opens my browser to Nextclooud's download page. This seems to be the current functionality at this point if I'm reading correctly?

**Comment by er-vin** [comment]
I'm interested to know in which cases this doesn't work. We made changes lately so I'd expect most clients to at least get to the point where it triggers the update now (this update succeeding or failing is a different matter in a way, this is not the updater code anymore at that point).
