### ISSUE TITLE
Copy public link creates a new one

### ISSUE THREAD

**Issue by biva** [nextcloud/desktop#1903]
## What I do
- Right-click on a file
- Share via Nextcloud
- Copy public link

## Expected behaviour
- If a public link already exists, this existing link is copied

## Current behaviour
- While a public link already exists, a new public link is created and copied

## Might be related to:
- https://github.com/nextcloud/desktop/issues/858
- https://github.com/nextcloud/desktop/issues/1179
- https://github.com/nextcloud/desktop/issues/1304

## Environment:
- Windows 10
- NC desktop client 2.6.4 Win64

**Comment by biva** [comment]
Hello, any news on this issue?

**Comment by biva** [comment]
Hello, any update on this issue?

**Comment by camilasan** [comment]
Hi @biva, I couldn't reproduce this error anymore with the latest client and Nextcloud server 19.
Could you try the desktop client 2.6.5 and 2.7 rc1?
Thanks.

**Comment by biva** [comment]
@camilasan My server is still on 18 (no update proposed yet) and the problem is still there with client 2.6.5. As my server is in production, I would prefer to not test RC versions, sorry for that, I hope you understand :/ I will update you here when these versions will be final.

**Comment by biva** [comment]
@camilasan Tested on 19.0.3 ad 3.0.1: same problem, not solved :(

**Comment by biva** [comment]
@camilasan Tested on 20.0.5 and 3.1.2: same problem, what's the status?

**Comment by camilasan** [comment]
I will have to check what is the status. I thought I had fixed it.

**Comment by biva** [comment]
Hello @camilasan 
Were you able to reproduce it? I still have the issue (Client 3.1.3 on Server 20.0.8)

**Comment by biva** [comment]
Hello @camilasan 
Just tested on server 21.0.1: still the same issue (client 3.1.3)

**Comment by dowe** [comment]
Same thing happens on linux (3.1.1) and dolphin (default KDE file manager).
Just fyi

**Comment by biva** [comment]
Hello @FlexW , I understand that you were able to reproduce the bug, right? Do you have any idea how to solve it?

**Comment by FlexW** [comment]
@biva yes I was able to reproduce it. I haven't looked at the code yet, but it should not be too hard to solve, but I'm currently busy with other things, so don't expect a fix soon. If you want you can give it a try yourself :)

**Comment by biva** [comment]
Understood and thanks! Unfortunately, I have no skills in coding :(

**Comment by biva** [comment]
Hello @FlexW , I really like the last version 3.7 of the desktop client. I just tested it, and this bug is still there. Do you think you'll have the time to fix it?

**Comment by claucambra** [comment]
This has been fixed with the new share UI introduced in 3.7.0 -- thanks for opening this issue!

**Comment by biva** [comment]
Hello @claucambra , I run 3.9.3 on Windows 11 and the issue is still there for me. Could you please reopen the issue?

**Comment by dowe** [comment]
Hmm, this just bit me again. Client version 3.11.0
@claucambra could you please reopen the issue this is not yet fixed or broke again.

**Comment by Go-rom** [comment]
Hi,

i'm sorry to post the same kind of message but this issue is still present with NC Desktop 3.12.3 (Linux Mint 21.3)

Can someone from NC team reopen this issue please ?
Allow me to notify @camilasan @claucambra @tobiasKaminsky @marcoambrosini 

[NC_Desktop_issue#1903.webm](https://github.com/nextcloud/desktop/assets/1423386/c2f511f4-c449-47a8-8d9d-0151fb71c709)

Please note that i did the same test with 3.13.0 RC1 (AppImage) with no luck
