### ISSUE TITLE
Nextcloud client 2.6.4 always hangs on Win10 after syncing started

### ISSUE THREAD

**Issue by portar-git** [nextcloud/desktop#1908]
Dear Support,

This is a resolved case. I posted it here to get your attention and see if this issue can help to improve something.

Below is the issue I posted on https://help.nextcloud.com/t/nextcloud-client-2-6-4-always-stop-responding-on-win10-after-a-while/76233

Hi Guys,
I use nextcloud as the private cloud to backup my data for some time and it always works normally and helps me lot.
I usually disable the auto sync and only start the sync once a week manually and it worked always normally.
Today, when I tried to do the same thing, it soon stopped and after I clicked its window for several times, it stopped responding and even after quite long time waiting, it won’t back.
I tried many times and also tried to reinstall the client but seems even I configured a new account and only sync the default files, it still stopped to response soon.
Meanwhile, I installed the same client on my other laptop. It worked normally and no issue happened during syncing about 30G data. So seems the issue is with my this laptop. Both two laptops are running Win10.

I’m appreciated if somebody could guide me on the TS. It’s important for me
Thanks in advance.

==============================================================
Nemskiller suggested to downgrade the client and it works.
Try the v2.3.3 https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-2.3.3.1-setup.exe 1

==============================================================

This is just FYI. If something you want to check, I'm glad to help.

Thx
![1](https://user-images.githubusercontent.com/58390661/78262618-6a92aa00-7533-11ea-9147-052be43d19e6.jpg)

**Comment by claell** [comment]
As far as I understand this is not really resolved, as your "solution" is rather a workaround to use v2.3.3, correct?

**Comment by warnerbryce** [comment]
For him it is resolved, but it's not really a solution because he needs to use the old version. 
For my experience i get this same behaviour on every V.2.5.X to V.2.6.3 on Window / Os X and linux. 
Sync that don't go to the end, freezed client... 
Everytime that i saw this behaviour, i delete this version on the desktop and put 2.3.3
Since 2.6.4 i don't have this kind of behaviour for my clients, but... as you can see some people can get it too with this version.

**Comment by claell** [comment]
Alright. With resolved I meant the issue with Nextcloud Desktop. Thanks for adding additional info. I will add the appropriate labels.

**Comment by portar-git** [comment]
> As far as I understand this is not really resolved, as your "solution" is rather a workaround to use v2.3.3, correct?

thanks for checking. 
Yes, you're right. I in fact should not talked it as a resolution as the hanging issue on 2.6.4 still exist on my laptop. I just downgraded to old version 2.3.3 and the old version works good on this laptop.
BTW, I installed two clients with same version on my two laptops and one met this issue but the other works fine and synced 30G files without any issue. Both of my two laptops are running on Win10.
Please let me know if something I can check.

**Comment by claell** [comment]
Alright. What might be helpful is providing the logs of the machine where the problem occurred.

**Comment by djamps** [comment]
We're running exclusively 2.3.3 on our systems (20+ clients).   Can't do an initial sync without it erroring out on 2.5.x+.   The only way we can get >2.5 working is if we do initial sync with 2.3.3 then let it upgrade after the 100+gb of data is downloaded.   Also random crashing and sync issues with >2.5.  Sadly I've asked all staff to never upgrade from 2.3.3 for the past year, I've been waiting for a solution but thank god for 2.3.3.

**Comment by warnerbryce** [comment]
Having logs is quite difficult because taping F12 and waiting for error to occurs will break sooner the sync, the nc client freeze, and won’t be working anymore, can’t copy paste the logs.

**Comment by claell** [comment]
@warnerbryce yes, that is true, did not think about that. However, there is a way to directly save log files, which will probbaly work: https://docs.nextcloud.com/desktop/2.6/troubleshooting.html#saving-files-directly

@djamps Thanks for your input, but it would help if you could keep it to relevant information for this issue. Apparently you have some other issues with the Client as well which are unrelated to this, so please refer to already existing issues or create a new one for them. This will help staying focused and avoid confusion. Maybe you can update your comment, so it only contains relating information.

**Comment by djamps** [comment]
@claell I removed some of the irrelevant information.   But in line with the original comment it's relevant - only 2.3.3 works for us, and it's been that way for a LONG time.

**Comment by claell** [comment]
@djamps thanks! I was mainly concerned about the "random crashing and sync issues" you mentioned, since I guess that is not belonging to this issue.

**Comment by theCalcaholic** [comment]
I'm experiencing the same issue with client 2.6.5.

From the looks it looks like the remote URL for the files (where the client tries to access them) is incorrect.

I'm only syncing a (shared) directory in my cloud "/Brackeys 2020-08" which contains - among others a folder named "resources". When trying to download files from said folder, the following appears in the logs:

```
2020-08-05 13:45:19:510 [ warning nextcloud.sync.networkjob ]:	QNetworkReply::ContentNotFoundError "Server hat \"404 Not Found\" auf \"PROPFIND https://my-domain.org/remote.php/webdav/resources/Images\" geantwortet" QVariant(int, 404)
2020-08-05 13:45:19:510 [ warning nextcloud.sync.credentials.webflow ]:	QNetworkReply::ContentNotFoundError
2020-08-05 13:45:19:510 [ warning nextcloud.sync.credentials.webflow ]:	"Error transferring https://my-domain.org/remote.php/webdav/resources/Images - server replied: Not Found"
2020-08-05 13:45:19:519 [ info nextcloud.sync.networkjob.clientsideencrypt ]:	GetFolderEncryptStatus of QUrl("https://my-domain.org/remote.php/webdav/resources/Images") finished with status QNetworkReply::ContentNotFoundError "Server hat \"404 Not Found\" auf \"PROPFIND https://my-domain.org/remote.php/webdav/resources/Images\" geantwortet"
2020-08-05 13:45:19:519 [ warning nextcloud.sync.networkjob.clientsideencrypt ]:	*not* successful, http result code is 404 ""
2020-08-05 13:45:19:519 [ debug nextcloud.sync.propagator.upload.encrypted ]	[ OCC::PropagateUploadEncrypted::slotFolderEncryptedStatusError ]:	Failed to retrieve the status of the folders. 404
2020-08-05 13:45:19:519 [ debug nextcloud.sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job OCC::GetFolderEncryptStatusJob finished for "remote.php/webdav"
```

Which would be correct, because the path  `https://my-domain.org/remote.php/webdav/resources/Images` does indeed not exist - it would have to be ` https://my-domain.org/remote.php/webdav/Brackeys 2020-08/resources/Images`

**Comment by er-vin** [comment]
Since this seems to involve the code path checking for E2EE status on the folder (which indeed goes through PROPFIND), I'd advise testing against 2.7.0-rc1 this might well be fixed.

**Comment by theCalcaholic** [comment]
I'm glad to report, that the issue is indeed fixed in 2.7.0-rc1. :+1: 

Also, great Job on the new Systray popup! It's super intuitive and nicely integrated with the Notifications.
I'm especially fond of it since I had many users that were confused about where to find their files after setting up nextcloud - they expected them in the Nextcloud client instead of the sync directory)

**Comment by er-vin** [comment]
Thanks for the confirmation, I'll mark it closed then.
