### ISSUE TITLE
System tray doesn't initialise properly on Ubuntu 20.04

### ISSUE THREAD

**Issue by veddox** [nextcloud/desktop#1977]
### Expected behaviour

NC client should start immediately after (or soon after) the first login when booting.

### Actual behaviour

A placeholder icon (not clickable) appears instead of the systray. ~~Nautilus plugin file overlays don't appear.~~ After logging out/locking the screen and logging in again, everything works as expected.

After first login:
![nc-systray-1](https://user-images.githubusercontent.com/12843207/81910950-e836e480-95cc-11ea-8545-56db63454541.png)

After second login:
![nc-systray-2](https://user-images.githubusercontent.com/12843207/81910971-ecfb9880-95cc-11ea-87a9-c259cbc13224.png)

### Steps to reproduce

1. Boot & login - systray ~~and Nautilus plugin~~ don't work yet
2. Wait a few minutes, then log out or lock the screen
3. Login again - everything should work now

### Client configuration

* Client version: 2.6.2-1build1
* Operating system: Ubuntu 20.04
* Desktop environment: GNOME 3.36.1
* OS language: English
* Qt version used by client package (Linux only, see also Settings dialog): Using Qt 5.12.8, built against Qt 5.12.5
* Client package (From Nextcloud or distro) (Linux only): Ubuntu distro repos

**Comment by veddox** [comment]
OK, so having trawled the logs and trying to understand how the client works under the hood, I realise I mischaracterised the bug:

1. Half of the issue is that the client simply takes several minutes until it has a working connection to the server. Once the connection is there, the Nautilus plugin works as intended, no renewed login required.

2. When the connection is there, the systray icon (though still incorrectly displayed as three dots as in image 1 above) can be double-clicked and will open the settings window.

3. However, the systray icon only changes to its correct icon if the user logs in again. Until then, it cannot be right-clicked to display the drop-down menu.

**Summary:** The systray icon is not initialised with the correct "offline" icon (as specified in [owncloudgui.cpp](https://github.com/nextcloud/desktop/blob/34c9eea4137174f7d0268aadbfa645934b921585/src/gui/owncloudgui.cpp#L71)) and it is not refreshed until the desktop environment is reloaded. Also, until that happens, functionality is restricted.

**Comment by yagodlt** [comment]
Not sure I should put this here but my problem is definitely defined by the title of this bug and I have the feeling that if I created another bug report I'd just have it marked as a duplicate... : /

In my case the workaround that @veddox mentions doesn't work. I get the "not connected" icon even when it obviously syncs (tried changing a couple of lines in a file and checking it in the server, and yep, it syncs)

### Expected behaviour
When NC desktop client initialises and concludes that all is in sync, the notification icon should change to the green tick.
### Actual behaviour
The icon never changes from the three dots
### Steps to reproduce
Initialise NC (either on boot or manually)
### Configuration
* OS: Ubuntu Studio 20.04 (fresh install)
* Desktop environment: Gnome 3.36.2
* NC Client: 2.6.4git
* NC Server: 18.0.4 )installed in a shared hosting account).

Thanks!

**Comment by veddox** [comment]
Do I understand you correctly that in your case, the 3-dot icon persists even after renewed login?

**Comment by yagodlt** [comment]
> Do I understand you correctly that in your case, the 3-dot icon persists even after renewed login?

Indeed. I can try logging out, restarting the system, quiting and restarting NC client... the three dots icon remains. Not the end of the world because, as I said, the synchronization is happening, but still, buggy behaviour.

**Comment by veddox** [comment]
When compiling from the newest version, the error persists - except that the systray icon now completely disappears after the second login (although the `nextcloud` task is still running).

Nextcloud version 2.7.0git
Git revision 0693d6126323aa10bcfd17bdd723c33fd4e9a242
Using Qt 5.12.8, built against Qt 5.12.8
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1f  31 Mar 2020'
Running on Ubuntu 20.04 LTS, x86_64

**Comment by veddox** [comment]
Possibly relevant error messages:

**On startup, in the log file:**

```[unknown 	qrc:/qml/src/gui/tray/Window.qml:462:25: QML Menu: Binding loop detected for property "width"
[unknown 	QPainter::begin: Paint device returned engine == 0, type: 3
[unknown 	QPainter::setRenderHint: Painter must be active to set rendering hints
[unknown 	QPainter::setClipPath: Painter not active
[unknown 	QPainter::end: Painter not active, aborted
[unknown 	QPainter::begin: Paint device returned engine == 0, type: 3
[unknown 	QPainter::setRenderHint: Painter must be active to set rendering hints
[unknown 	QPainter::setClipPath: Painter not active
[unknown 	QPainter::end: Painter not active, aborted
[unknown 	QPainter::begin: Paint device returned engine == 0, type: 3
[unknown 	QPainter::setRenderHint: Painter must be active to set rendering hints
[unknown 	QPainter::setClipPath: Painter not active
[unknown 	QPainter::end: Painter not active, aborted
[unknown 	QPainter::begin: Paint device returned engine == 0, type: 3
[unknown 	QPainter::setRenderHint: Painter must be active to set rendering hints
[unknown 	QPainter::setClipPath: Painter not active
[unknown 	QPainter::end: Painter not active, aborted
```

**After renewed login, printed to console (`stderr`?):**

```
Gtk-Message: 10:34:20.314: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:34:20.488: Failed to load module "canberra-gtk-module"
```

**Comment by veddox** [comment]
Seems to be an upstream issue with the GNOME shell extension `appindicator`: https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/232

**Comment by veddox** [comment]
I'm reopening this. Having spent the last two days trying to figure out how the Ubuntu system tray actually works, I believe I now understand what causes this problem, although I am not entirely sure how best to fix it yet.

## The Ubuntu systray stack

So what happens when the Nextcloud client tries to create its systray icon? First of all, it uses its own [`Systray`](https://github.com/nextcloud/desktop/blob/master/src/gui/systray.cpp) class for that. This is a subclass of `QSystemTrayIcon`, which in turn ends up exposing a systray icon object on D-Bus. (D-Bus is a Linux system for inter-process communication.) The vanilla GNOME Shell doesn't actually have its own system tray area anymore, at least not in the classical sense, so Ubuntu ships a default extension to compensate (`appindicator`). Appindicator, then, is what listens to the D-Bus and sets up the actual clickable systray icon.

## What's the problem?

When the Nextcloud client starts, the following error message can be seen in `journalctl /usr/bin/gnome-shell`:

```
Jul 23 12:04:45 gnome-shell[2351]: JS ERROR: Exception in callback for signal: ready: TypeError: this._indicator.id is null
                                          _updateIconClass@/home/veddox/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:344:34
```

This error is thrown in [this line](https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/32f2f34ae382a4af850471a131cf9b5e42231ac5/appIndicator.js#L339) and happens because appindicator's [`_checkIfReady()`](https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/32f2f34ae382a4af850471a131cf9b5e42231ac5/appIndicator.js#L104) function signalled that the client is ready - although it isn't.

The reason for this is that the client takes a *long* time to completely start up, at least on its first startup after booting the computer. For some reason, subsequent startups are a lot quicker (~20-30 seconds faster if you compare the log time stamps - are we doing any caching here?), and thus in that case the client is ready when appindicator expects it and everything works fine. This is also the reason why locking the screen fixes the icon - locking forces appindicator to reset all its icons, but this time round, the client is still running and ready to answer.

## Possible solutions

Well, we could ask the appindicator team to adjust their `_checkIfReady()` function to take slow-starting applications into account. However, I tend to think that we should work on our end first.

I suspect (but haven't yet tested) that the client's problem is a two-stage initialisation of the systray. If we look at the `Application` class, the class `ownCloudGui` is constructed in [line 226](https://github.com/nextcloud/desktop/blob/3fd32e55f99bf3e9190e77778c410624ec4555cc/src/gui/application.cpp#L226). This constructor includes code to start up the systray:

https://github.com/nextcloud/desktop/blob/3fd32e55f99bf3e9190e77778c410624ec4555cc/src/gui/owncloudgui.cpp#L69-L74

However, `Systray::create()` is only called in `Application` [line 277](https://github.com/nextcloud/desktop/blob/3fd32e55f99bf3e9190e77778c410624ec4555cc/src/gui/application.cpp#L277), and it is only now that the `activated` signal is emited:

https://github.com/nextcloud/desktop/blob/3fd32e55f99bf3e9190e77778c410624ec4555cc/src/gui/systray.cpp#L98-L107

Unfortunately, I do not yet fully understand the clients complete initialisation process, and therefore do not understand why these two stages are necessary, or why they are so far apart. However, I suspect that if we were to move them closer together, that would fix the systray issue.

@DominiqueFuchs, perhaps you could weigh in on this?

**Comment by DominiqueFuchs** [comment]
Hi @veddox 

1. Thanks for one of the most-well prepared bug-reports I've ever encountered in this repo 😆 👍 
2. Seeing this for the first time, I'll try to reproduce and look into this, have to re-establish my Ubuntu VM for this
3. Generally you're right, Systray initialization != App initialization but I'm most wondering wth it takes so long to start in the case you described. Gonna have to check this on my VM

    - That said: Any infor about your (NC) environment? I see your initial report mentioned distro package stable client, does your newest report is also base on latest stable in the ubuntu repo?
    - Anything special about your NC server connection?
    - Anything special about your client sync connections (accounts/folders)?

**Comment by er-vin** [comment]
I'm not sure I see the link with `Systray::create()` though... apart from emitting the `activated()` signal, there's nothing related to QSystemTrayIcon API happening in there. In turn, I don't get why the `activated()` signal would make the Ubuntu systray fall on its feet... If that's really just about emitting this signal this could simply be tested by emitting it right away after the `_tray->show()` call. Just to at least verify the theory that it's what gets the `id` seen on the appindicator side.

**Comment by DominiqueFuchs** [comment]
In a quick test I wasn't able to reproduce this: Fresh 20.04 (GNOME) latest stable distro package (2.6.2), one account in client configured with several folders.

- Worked directly after setup & login
- Worked immediately after application start
- Worked immediately on boot/login with autostart active

Seems like the behaviour described needs some specific environment or condition to occur.

**Comment by veddox** [comment]
@DominiqueFuchs thanks for the quick response :slightly_smiling_face: 

I'm currently running the development version of both the client and appindicator, but the bug also appeared with the official packages. My setup is:

> Nextcloud version 2.7.0git
> Git revision 5c442af1caa1841381e2955d2cc78a57f25147b5
> Using Qt 5.12.8, built against Qt 5.12.8
> Using Qt platform plugin 'xcb'
> Using 'OpenSSL 1.1.1f  31 Mar 2020'
> Running on Ubuntu 20.04 LTS, x86_64
> Nextcloud server version 15.0.14.1

I'm syncing 78GB of data across 7 folders. I'm not aware of anything special about my server or the connection - the NC web interface can be a bit sluggish, but nothing out of the ordinary (and the server definitely isn't overloaded).

Attached are three log file excerpts:
1. the client log during the startup that had the error: [nc-client-error.log](https://github.com/nextcloud/desktop/files/4971010/nc-client-error.log)
2. the appindicator log from that startup: [appindicator-error.log](https://github.com/nextcloud/desktop/files/4971014/appindicator-error.log)
3. the client log from a subsequent startup that worked normally: [nc-client-working.log](https://github.com/nextcloud/desktop/files/4971012/nc-client-working.log)

Note the difference in initialisation times between 1 and 3.

**Comment by veddox** [comment]
> I'm not sure I see the link with `Systray::create()` though... apart from emitting the `activated()` signal, there's nothing related to QSystemTrayIcon API happening in there. In turn, I don't get why the `activated()` signal would make the Ubuntu systray fall on its feet... If that's really just about emitting this signal this could simply be tested by emitting it right away after the `_tray->show()` call. Just to at least verify the theory that it's what gets the `id` seen on the appindicator side.

@er-vin you seem to be right. I just tried moving the `_gui->createTray()` call to right after the GUI initialisation, but that didn't change the behaviour.

**Comment by veddox** [comment]
Interesting note on the side: turns out, the Electron developers were so fed up with Ubuntu/GNOME's handling of the D-Bus based system tray they reverted their code to using the old GTK method (https://github.com/vladimiry/ElectronMail/issues/254, https://github.com/electron/electron/pull/23674).

**Comment by er-vin** [comment]
> Interesting note on the side: turns out, the Electron developers were so fed up with Ubuntu/GNOME's handling of the D-Bus based system tray they reverted their code to using the old GTK method ([vladimiry/ElectronMail#254](https://github.com/vladimiry/ElectronMail/issues/254), [electron/electron#23674](https://github.com/electron/electron/pull/23674)).

Yeah, I've seen that at places... IIRC there's a trick to do something similar with QSystemTrayIcon (via an env var?) but that'd be kind of sad to cripple it for everyone else (because it's likely to involve XEmbed in some way which is going to bite us back as the transition to Wayland progresses).

**Comment by loulou921222** [comment]
I have the same problem and same error message with TeamViewer

**Comment by rogercreagh** [comment]
Is there any progress on this issue? A recent update to appindicator on gnome on ubuntu 20.04 killed most of the tray icons on both of my systems (desktop and laptop). Downgrading appindicator to v 33-1 ( `sudo apt install gnome-shell-extension-appindicator=33-1`) brought them back, but nextcloud is still showing 3 dots on one system but not the other.
Both using client 3.1.1.

This appears to happen either because the the app takes too long to report 'ready' to appindicator (which causes appindicator to update the default three dots icon with the one the app wants) or because the app reports an error back to appinicator so appindicator doesn't update the icon.

Since the nextcloud desktop client is working on both systems, but sticking at three dots on the other I am guessing it is taking too long to send the ready signal. But I'm not sure how to proceed to prove that.

Just to re-iterate both systems are using nextcloud desktop 3.1.1 and Ubuntu 20.04.1 Gnome version 3.36.8 Appindicator 33-1
The one that works ok is a N4200 4 core proc & 1.1GHz the one that doesn't is an i3-5005 4 core at 2GHz, so slightly faster. Both have 8GB memory.
Both are syncing the same server and the same folders. The difference possibly relevant between them is that one is syncing onto a usb ssd drive and the other onto an internal ssd, and it is the one that is using an (internal) usb ssd that is showing 3 dots. Maybe access to that drive is slower, although not apparent in use. Other than that it is a n annoying mystery to me.

**Comment by XxTRAINEExX** [comment]
This worked! Looking forward to a fix on this.

> Is there any progress on this issue? A recent update to appindicator on gnome on ubuntu 20.04 killed most of the tray icons on both of my systems (desktop and laptop). Downgrading appindicator to v 33-1 ( `sudo apt install gnome-shell-extension-appindicator=33-1`) brought them back, but nextcloud is still showing 3 dots on one system but not the other.
> Both using client 3.1.1.

**Comment by dregad** [comment]
Wondering if ubuntu/gnome-shell-extension-appindicator#260 might fix this issue...

**Comment by er-vin** [comment]
From the look of it, indeed it looks like it'll be fixed with that patch to the extension.

I'll thus close this ticket (actually should have probably done it before) since it's now clear this will be dealt with downstream (as it should IMHO).

**Comment by emichael** [comment]
FYI, that change (https://github.com/ubuntu/gnome-shell-extension-appindicator/pull/260) doesn't completely fix the issue. Even with that patch and a 30 second delay on the autostart, I'm still occasionally seeing an improperly initialized tray icon. This problem seems quite persistent, so it might be worth it to try and workaround whatever issues the gnome extension has.

**Comment by sylvainfaivre** [comment]
@FlexW to nitpick on your comment, I see no option to run the main dialog in a normal window, using `Version 3.3.0 (Ubuntu)`.

I would love such an option, because I always hated this "false window" which disappears as soon as you click somewhere else.

I also do not see a merged PR that would add an option to do this with, even though you published several PRs to show the window as a normal window, when some circumstances are met (#3468 #3596 #3582 #3574)

Feel free to correct me if I missed something here.

**Comment by FlexW** [comment]
@sylvainfaivre The setting is not available in the gui. It's only available by setting a option `nextcloud.cfg`. See: https://docs.nextcloud.com/desktop/3.3/advancedusage.html#configuration-file in the section `General`. The option is named `showMainDialogAsNormalWindow`.

**Comment by sylvainfaivre** [comment]
@FlexW Thanks a lot for this info, this is an awesome and long waited improvement ! Now at least, I can see long filenames in this dialog :-)

Any plans on adding this setting to the GUI so more people can take advantage of it ?

I always wondered why this was not a standard window. I guess there was an UI choice there, but I don't see the benefit of this system.

**Comment by FlexW** [comment]
@sylvainfaivre No not at the moment. Feel free to create a pr for it :) Nextcloud tries to align with OneDrive, Dropbox etc in this regard to make it users easier to transition. They all have a tray menu, that's the reason why Nextcloud has one too.
