### ISSUE TITLE
Add option to disable file explorer integration

### ISSUE THREAD

**Issue by toxpal** [nextcloud/desktop#1982]
It would be useful if desktop client offers option to enable/disable file explorer integration, which is now forced by default (at least on Linux).

Once I install NC Desktop on KDE (didn't test other DEs), it "hijacks" file picker dialog (system-wide) by immediately adding synced folders to it. I realize some users might appreciate this feature, but we really need a way to disable this behavior because not everyone wants it.

**Comment by jirizaj** [comment]
I agree. The behavior is the same on Win10 as well. It might be nice to have the option to disable the integration per account. I have some accounts only for sync of backups and I don't really want to have such accounts visible in my explorer's navigation pane.

**Comment by er-vin** [comment]
> I agree. The behavior is the same on Win10 as well. It might be nice to have the option to disable the integration per account. I have some accounts only for sync of backups and I don't really want to have such accounts visible in my explorer's navigation pane.

This is already possible to disable on Windows (globally though, not per account and honestly we don't plan to go there). It's in the General tab of the settings dialog, one checkbox away.

**Comment by er-vin** [comment]
Currently on Linux this goes through the libcloudproviders facilities... I guess we could have the checkbox there as well to allow to opt out like it's done on Windows.

**Comment by toxpal** [comment]
> I guess we could have the checkbox there as well to allow to opt out like it's done on Windows.

That would be great. No need to go into account level, a global setting is more than enough in my opinion.

**Comment by ericpre** [comment]
Putting a workaround as a note, because after each update, it takes me a while to figure it out again! To remove the nextcloud bookmarks on nautilus, remove the corresponding file in `/usr/share/cloud-providers/`.

But yes, a nextcloud settings would be good!

**Comment by ruffson** [comment]
Is there any progress update on this?

I must say for people like me who sync a bunch of nextcloud folders to local directories that are scattered around the system, this is one of the worst recent "features" to come to nextcloud on GNOME systems. Thanks to this I have a long list of all synced folders in nautilus and the only way to get rid of it is removing `/usr/share/cloud-providers/com.nextcloudgmbh.Nextcloud.ini` which after every system update (like now to Fedora 35) returns. 

I would greatly appreciate if it was possible to disable this or reconsider the kind of integration into nautilus.

Example (and note how long the scroll bar is, only showing a fraction of all nextcloud folders which appear BEFORE the actual bookmarks)
![nautilus](https://user-images.githubusercontent.com/1185812/141931471-ea981b5c-8825-41f8-a019-451abfc9ec08.png)

**Comment by FlexW** [comment]
@ruffson Depends on your distro, but in most distros you can simply uninstall the Nautilus integration of Nextcloud. That should solve it for you.

**Comment by imsedgar** [comment]
No, it doesn't solve the problem. Linux systems are multi-user systems, so I want to provide all features that the system offers. If I uninstall the package, then nobody can use it.
So, on Fedora 34 / 35, if I install package nextcloud-client-nautilus, which contains only file /usr/share/nautilus-python/extensions/syncstate-Nextcloud.py , then all users have the Nextcloud integrated in Nautilus, and there are pop-up windows asking about Nextcloud login etc.

There should be a global and a user option to turn this feature on and off
1. as a system default for all users, who don't set user specific settings
2. as a user option to overwrite the system default
Setting the default to off is different from uninstalling the package because users can individually switch it on.

**Comment by rysiekpl** [comment]
> @ruffson Depends on your distro, but in most distros you can simply uninstall the Nautilus integration of Nextcloud. That should solve it for you.

This in no way solves the problem.

For one, as @imsedgar noted above, the user affected by this bug might not have enough control over the system to remove that package.

Secondly, I do *not* have the package `nextcloud-client-nautilus` installed, and I am *still* affected by this bug:

```
$ rpm -qa | grep nextcloud
nextcloud-client-libs-3.3.5-1.fc34.x86_64
nextcloud-client-3.3.5-1.fc34.x86_64
```

Fourth, I am running Qubes, a system where I am using VMs based on templates. My Fedora template is used as basis for multiple VMs, only some actively use Nextcloud, but having the client installed makes sense in all makes sense. So I have it in the template. But now, I am getting Nextcloud dialog every time I open a file manager in *any* of the VMs. This is extremely frustrating and not user-friendly.

And finally: why do you insist on removing agency form the users? As a user I know if I want that integration or not, what is wrong with giving me that configuration option? You already do that with "start on system startup", so what gives?

**Comment by rysiekpl** [comment]
For the record, here is a thread about Arch Linux being affected and users finding it just as confusing and annoying:\
https://bbs.archlinux.org/viewtopic.php?id=259764

**Comment by albgus** [comment]
This is an issue on Windows as well. What's even worse is that it's no longer possible to disable the integrations at all because the updated will apparently always install with the integration enabled.

**Comment by KopfKrieg** [comment]
> I would greatly appreciate if it was possible to disable this or reconsider the kind of integration into nautilus.

I'd like to add that disabling on a per-account basis would be ideal. I sync to multiple Nextcloud instances, and all show up in my sidebar. However, the only one I want to see in the sidebar is my own, personal account on my own server. I'd like to disable all others.

**Comment by bbkz** [comment]
The same here on Fedora 34, having multiple users login to the same linux makes it impossible to provide the nextcloud-client.

You cannot really work when all the time a popup comes... remember the time we used webbrowser popups.

As well for provisioning clients the decision must be made to not provide the nextcloud-client to the default software list. As for existing installations i need to figure out which users have the nextcloud-client configured and uninstall it accordingly.

A other approch is to run

`mkdir -p ~/.local/share/dbus-1/services/; grep -v ^Exec /usr/share/dbus-1/services/com.nextcloudgmbh.Nextcloud.service > ~/.local/share/dbus-1/services/com.nextcloudgmbh.Nextcloud.service`

for every existing user and new users. They still will be able to setup and use the nextcloud-client.

**Comment by endurance1968** [comment]
Windows explorer becomes unusable slow for bigger? installations. A simple rename of a file or folder takes 10s (SSD and AMD R9 with 128GB RAM so on a fast machine). You start editing then the systems hangs wait then continue to type.. wait again until synced.
As consequence I alway pause sync and only manually trigger a sync - but this is not the idea of nextcloud. Frequently I have also all desktop icons with an overlay checkbox (which should not be there as desktop is not part of nc path). But this is a different annoying bug with the overlay.
I now also remove the DLL let see if this temporarily helps.

**Comment by wedeen** [comment]
Please make it possible to completly disable all icons in the explorer. I only want to use it like all other folders in my computer. 
I disable the explorer integration but have the "Status" column in explorer with icons in every nextcloud folder. This is horrible. Why do you do this. I only want to have some folders I can use from other computers too, without such senseless things. When I choose to disable the explorer integration, I would have a normal explorer with my files. Nothing else.

I am afraid for every update, what comes next...?

**Comment by FernandoMarques-Santos** [comment]
The user may uninstall the integration via the installer to get rid of the overlays. However, you will lose the context menu.

I see some of you saying something about a status column. I had it once, but now I don't know what sorcery is this that I can't have it anymore. It is a way to make the status being less obtrusive than hundreds of green circles popping up on the screen over the icons.

**Comment by rysiekpl** [comment]
> The user may uninstall the integration via the installer to get rid of the overlays. However, you will lose the context menu.

This is in no way a solution to this problem, as mentioned [time](https://github.com/nextcloud/desktop/issues/1982#issuecomment-971507560) and [again](https://github.com/nextcloud/desktop/issues/1982#issuecomment-998926582) in this very thread.

Can we please stop blaming the users for bad decisions made by the developers finally? Thanks.

For the record, I use Nextcloud (in fact, I run three instances currently, and had set-up at least three more in the past) and I think it is an amazing piece of software. But this issue really grates me, as it seems to do to so many others in this thread. The change is intrusive and unwelcome by a lot of users. There is no good remedy for many of them. It is extremely disappointing that such a change was deployed to the users.

Can this be fixed please?

**Comment by jcharaoui** [comment]
On Debian 12, the workaround is to run this command:

    # dpkg-divert --divert /usr/share/dbus-1/services/com.nextcloudgmbh.Nextcloud.service.disabled --rename /usr/share/dbus-1/services/com.nextcloudgmbh.Nextcloud.service

This will prevent Nextcloud from starting automatically when Nautilus is launched.

To revert:

     # dpkg-divert --rename --remove /usr/share/dbus-1/services/com.nextcloudgmbh.Nextcloud.service

**Comment by emes81** [comment]
> removing `/usr/share/cloud-providers/com.nextcloudgmbh.Nextcloud.ini` which after every system update (like now to Fedora 35) returns.

This fix worked for me on Fedora 36-38 but is currently not working on Arch. There is no /usr/share/cloud-providers/ folder, and I have not been able to locate the ini file elsewhere.

**Comment by rickdkk** [comment]
Same here, can't seem to disable this on Fedora 39...

**Comment by minosimo** [comment]
As of Fedora 39, I also needed to edit the nextcloud .desktop file in /usr/share/applications and remove ~three lines related to cloud providers. Unfortunately as I have removed them I cannot be more specific, but they were towards the end of the file and pretty obvious.

**Comment by JosuaCarl** [comment]
I also got it to quit restarting on my EndeavourOS (Arch derived) + GNOME by commenting out the mentioned lines
 in  `/usr/share/applications/com.nextcloud.desktopclient.nextcloud.desktop`. Thanks a lot :)
 
> Implements=org.freedesktop.CloudProviders
> 
> [org.freedesktop.CloudProviders]
> BusName=com.nextcloudgmbh.Nextcloud
> ObjectPath=/com/nextcloudgmbh/Nextcloud
> ```

**Comment by K4LCIFER** [comment]
Kinda weird that Nextcloud Desktop forces integrations into the file manager...

**Comment by sophiedkk** [comment]
The workaround stopped working for me. I removed the application for now, but if anyone knows a way to disable this please let me know!

**Comment by cli-ish** [comment]
This is kind of annoying to handle, i tried the following things without any effect:

### nano /usr/share/applications/com.nextcloud.desktopclient.nextcloud.desktop
uncomment this out.
```
Implements=org.freedesktop.CloudProviders

[org.freedesktop.CloudProviders]
BusName=com.nextcloudgmbh.Nextcloud
ObjectPath=/com/nextcloudgmbh/Nextcloud
```
### nano /usr/share/dbus-1/services/com.nextcloudgmbh.Nextcloud.service

Set the Exec attribute to /bin/false:
```
[D-BUS Service]
Name=com.nextcloudgmbh.Nextcloud
Exec=/bin/false
```

### cp /usr/share/dbus-1/services/com.nextcloudgmbh.Nextcloud.service ~/.local/share/dbus-1/services
And then set the Exec to /bin/false
`nano ~/.local/share/dbus-1/services/com.nextcloudgmbh.Nextcloud.service `
```
[D-BUS Service]
Name=com.nextcloudgmbh.Nextcloud
Exec=/bin/false
```


But none of these worked, my assumption is that dolphin my file manager or kde somehow autoloads the app even when CloudProviders is disabled.

**Comment by narcisgarcia** [comment]
When implementing this feature, please allow to configure it also from command line.
This can help to provisioning setups.

**Comment by vimpostor** [comment]
To the people saying that the [workaround from above](https://github.com/nextcloud/desktop/issues/1982#issuecomment-1008865047) doesn't work for them, you likely need to log out and relogin (your Linux user) for the override to take effect, that was the case for me.

**Comment by alystair** [comment]
My main concern is that the 'OK' icons clutter interfaces - if there was an option to hide the green checkbox icon and only show icons for items that have issues - I feel that would declutter the UI enough to not have to add a feature to disable it outright. See screenshot below:

<img width="342" height="219" alt="Windows Explorer interface showcasing side bar and file list covered in checkmarks" src="https://github.com/user-attachments/assets/fe1f5e1a-deb3-449e-a6e1-ca113641adb3" />

**Comment by alystair** [comment]
I was able to make the modification myself by renaming the relevant Nextcloud folders under  `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ShellIconOverlayIdentifiers` inside the Windows Registry.
