### ISSUE TITLE
Desktop stops syncing after deleting/renaming a file inside encrypted folder

### ISSUE THREAD

**Issue by candrea21** [nextcloud/desktop#2314]
### Expected behaviour
File should be synced.

### Actual behaviour
File is not synced inside an encrypted folder.

### Steps to reproduce
1. Put a file inside an encrypted folder (in the mac os file system)
2. Rename the file, or remove it

### Client configuration
Client version: 3.0.0

Operating system: MacOS 10.14.6

OS language: German

### Server configuration

Nextcloud version: 19.0.1

Storage backend (external storage): none

**Comment by camilasan** [comment]
We need the logs :) - please run the client with --logdebug 
https://docs.nextcloud.com/desktop/2.6/troubleshooting.html#log-files

**Comment by candrea21** [comment]
```
2020-08-25 12:43:31:227 [ warning nextcloud.sync.networkjob ]:	QNetworkReply::ContentAccessDenied "Server hat \"403 Forbidden\" auf \"POST https://domain.com/nextcloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/354?format=json\" geantwortet" QVariant(int, 403)
2020-08-25 12:43:31:228 [ warning nextcloud.sync.credentials.webflow ]:	QNetworkReply::ContentAccessDenied
2020-08-25 12:43:31:228 [ warning nextcloud.sync.credentials.webflow ]:	"Error transferring https://domain.com/nextcloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/354?format=json - server replied: Forbidden"
2020-08-25 12:43:31:228 [ info nextcloud.sync.networkjob.clientsideencrypt ]:	error locking file "ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/354" "Server hat \"403 Forbidden\" auf \"POST https://domain.com/nextcloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/354?format=json\" geantwortet" 403
2020-08-25 12:43:31:229 [ debug nextcloud.sync.propagator.upload.encrypted ]	[ OCC::PropagateUploadEncrypted::slotFolderLockedError ]:	Folder "354" Coundn't be locked.
2020-08-25 12:43:31:229 [ debug nextcloud.sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job OCC::LockEncryptFolderApiJob finished for "ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/354"
2020-08-25 12:43:36:032 [ debug nextcloud.sync.propagator.upload.encrypted ]	[ OCC::PropagateUploadEncrypted::slotFolderLockedError(const QByteArray &, int)::(anonymous class)::operator() ]:	Error locking the folder while no other update is locking it up.
2020-08-25 12:43:36:033 [ debug nextcloud.sync.propagator.upload.encrypted ]	[ OCC::PropagateUploadEncrypted::slotFolderLockedError(const QByteArray &, int)::(anonymous class)::operator() ]:	Perhaps another client locked it.
2020-08-25 12:43:36:033 [ debug nextcloud.sync.propagator.upload.encrypted ]	[ OCC::PropagateUploadEncrypted::slotFolderLockedError(const QByteArray &, int)::(anonymous class)::operator() ]:	Abort
2020-08-25 12:43:42:032 [ debug nextcloud.sync.connectionvalidator ]	[ OCC::ConnectionValidator::checkAuthentication ]:	# Check whether authenticated propfind works.
```

**Comment by camilasan** [comment]
What is the version of the end to end encryption app in the server?

**Comment by candrea21** [comment]
1.5.2

**Comment by camilasan** [comment]
If you ever tried end-to-end encryption before version 3.0, please follow the instructions from this post:
https://help.nextcloud.com/t/help-test-the-latest-version-of-e2ee/87590

to clean up the keys as that can break the functioning of >3.0 if you had a malformed key.

**Comment by candrea21** [comment]
Thank you, but unfortunately it is a fresh installation...

**Comment by jospoortvliet** [comment]
Please, fill in the full template. We also need the server logs etc... Either update this issue on the top with the complete template, or close this issue and create a new one. We can't reproduce this problem and thus we will need the complete logs.

For the client, it is best to run it this way: `nextcloud --logdebug --logfile log.txt` - this creates a rather big log file but gives all the info we might need.

**Comment by er-vin** [comment]
Note that there is an extra difficulty with that one, we need the log at the time of the delete/rename that failed. Indeed from the log extract you provided so far it looks like there's a stale lock server side and we need to know why it happened. All the sync done after the first failure will exhibit that 403 but won't give us enough information.

**Comment by candrea21** [comment]
Maybe that helps:
```
{"reqId":"X2x8yy-OYh5NdSek@YzTFQAAAAA","level":4,"time":"2020-09-24T11:02:35+00:00","remoteAddr":"x.x.x.x","user":"xxx","app":"webdav","method":"DELETE","url":"/nextcloud/remote.php/dav/files/xxx/PrivateE2EE/edf0f8f6cfe34176b6ee5772775df06b","message":{"Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\Forbidden","Message":"Write access to end-to-end encrypted folder requires token - no token sent","Code":0,"Trace":[{"file":"/home/httpd/vhosts/xxx/subdomains/cloud/httpdocs/nextcloud/apps/end_to_end_encryption/lib/Connector/Sabre/LockPlugin.php","line":153,"function":"verifyTokenOnWriteAccess","class":"OCA\\EndToEndEncryption\\Connector\\Sabre\\LockPlugin","type":"->","args":[{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"},null]},{"file":"/home/httpd/vhosts/xxx/subdomains/cloud/httpdocs/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"checkLock","class":"OCA\\EndToEndEncryption\\Connector\\Sabre\\LockPlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/home/httpd/vhosts/xxx/subdomains/cloud/httpdocs/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":458,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["beforeMethod:DELETE",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/home/httpd/vhosts/xxx/subdomains/cloud/httpdocs/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/home/httpd/vhosts/xxx/subdomains/cloud/httpdocs/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/home/httpd/vhosts/xxx/subdomains/cloud/httpdocs/nextcloud/apps/dav/lib/Server.php","line":320,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/home/httpd/vhosts/xxx/subdomains/cloud/httpdocs/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/home/httpd/vhosts/xxx/subdomains/cloud/httpdocs/nextcloud/remote.php","line":167,"args":["/home/httpd/vhosts/xxx/subdomains/cloud/httpdocs/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/home/httpd/vhosts/xxx/subdomains/cloud/httpdocs/nextcloud/apps/end_to_end_encryption/lib/Connector/Sabre/LockPlugin.php","Line":169,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh) mirall/3.0.1git (build 3355) (Nextcloud)","version":"19.0.3.1","id":"5f6c7cf8ddab6"}
```

**Comment by er-vin** [comment]
OK... that's odd, that token should be sent though.

Could you provide us the client debug log as well? Clearly we didn't send the token to the server as we should, now the client logs would help us trace the decision which led there.

**Comment by WhiteBahamut** [comment]
**Server version:**
docker image nextcloud:20, arm64 (with traefik as reverse proxy, no headers removed)
Apps are all up-to-date

**Client version:**
3.0.2 (💻)
3.13.1 (📱)

I see the same issue on win client and my server when adding a file. It worked already some weeks ago (after some trouble..)
**Win client Log:**
```
2020-10-21 17:22:00:495 [ info nextcloud.gui.folder ]:	#### Propagation start ####################################################
2020-10-21 17:22:00:499 [ info nextcloud.gui.application ]:	Sync state changed for folder  "https://<server>/remote.php/dav/files/<User>/" :  "Sync Running"
2020-10-21 17:22:00:500 [ info nextcloud.sync.server.capabilities ]:	E2EE API version: "1.1"
2020-10-21 17:22:00:501 [ info nextcloud.sync.propagator ]:	Starting INSTRUCTION_NEW propagation of "Privat/<file>" by OCC::PropagateUploadFileV1(0x265251ec160)
2020-10-21 17:22:00:501 [ info nextcloud.sync.server.capabilities ]:	E2EE API version: "1.1"
2020-10-21 17:22:00:502 [ info nextcloud.sync.checksums ]:	Computing "SHA1" checksum of "C:/Users/<User>/Nextcloud/Privat/<file>" in a thread
2020-10-21 17:22:00:522 [ info nextcloud.sync.checksums ]:	Computing "" checksum of "C:/Users/<User>/Nextcloud/Privat/<file>" in a thread
2020-10-21 17:22:00:527 [ info nextcloud.sync.accessmanager ]:	3 "" "https://<server>/remote.php/dav/files/<User>/Privat/<file>" has X-Request-ID "fed8caf0-21cd-446b-9de5-9a1bf09eaaaf"
2020-10-21 17:22:00:527 [ info nextcloud.sync.networkjob ]:	OCC::PUTFileJob created for "https://<server>" + "/Privat/<file>" "OCC::PropagateUploadFileV1"
2020-10-21 17:22:01:139 [ info nextcloud.sync.credentials.webflow ]:	request finished
2020-10-21 17:22:01:141 [ warning nextcloud.sync.networkjob ]:	QNetworkReply::ContentAccessDenied "Server hat \"403 Forbidden\" auf \"PUT https://<server>/remote.php/dav/files/<User>/Privat/<file>\" geantwortet" QVariant(int, 403)
2020-10-21 17:22:01:142 [ warning nextcloud.sync.credentials.webflow ]:	QNetworkReply::ContentAccessDenied
2020-10-21 17:22:01:143 [ warning nextcloud.sync.credentials.webflow ]:	"Error transferring https://<server>/remote.php/dav/files/<User>/Privat/<file> - server replied: Forbidden"
2020-10-21 17:22:01:144 [ info nextcloud.sync.networkjob.put ]:	PUT of "https://<server>/remote.php/dav/files/<User>/Privat/<file>" FINISHED WITH STATUS "ContentAccessDenied Server hat \"403 Forbidden\" auf \"PUT https://<server>/remote.php/dav/files/<User>/Privat/<file>\" geantwortet" QVariant(int, 403) QVariant(QString, "Forbidden")
2020-10-21 17:22:01:146 [ warning nextcloud.sync.propagator ]:	Probably firewall error:  403 , blacklisting up to 1h only
2020-10-21 17:22:01:147 [ info nextcloud.sync.database ]:	Setting blacklist entry for  "Privat/<file>" 4 "Server hat \"403 Forbidden\" auf \"PUT https://<server>/remote.php/dav/files/<User>/Privat/<file>\" geantwortet (Write access to end-to-end encrypted folder requires token - no token sent)" 1603293721 3125 1603120567 "" "" 0
2020-10-21 17:22:01:149 [ info nextcloud.sync.propagator ]:	blacklisting  "Privat/<file>"  for  3125 , retry count  4
2020-10-21 17:22:01:150 [ warning nextcloud.sync.propagator ]:	Could not complete propagation of "Privat/<file>" by OCC::PropagateUploadFileV1(0x265251ec160) with status 10 and error: "Server hat \"403 Forbidden\" auf \"PUT https://<server>/remote.php/dav/files/<User>/Privat/<file>\" geantwortet (Write access to end-to-end encrypted folder requires token - no token sent)"
2020-10-21 17:22:01:153 [ warning nextcloud.gui.activity ]:	Item  "Privat/<file>"  retrieved resulted in  "Server hat \"403 Forbidden\" auf \"PUT https://<server>/remote.php/dav/files/<User>/Privat/<file>\" geantwortet (Write access to end-to-end encrypted folder requires token - no token sent)"
2020-10-21 17:22:01:154 [ warning nextcloud.gui.activity ]:	Item  "Privat/<file>"  retrieved resulted in error  "Server hat \"403 Forbidden\" auf \"PUT https://<server>/remote.php/dav/files/<User>/Privat/<file>\" geantwortet (Write access to end-to-end encrypted folder requires token - no token sent)"
2020-10-21 17:22:01:156 [ info nextcloud.gui.activity ]:	Error successfully added to the notification list:  "Server hat \"403 Forbidden\" auf \"PUT https://<server>/remote.php/dav/files/<User>/Privat/<file>\" geantwortet (Write access to end-to-end encrypted folder requires token - no token sent)"
2020-10-21 17:22:01:163 [ info nextcloud.sync.database ]:	Closing DB "C:/Users/<User>/AppData/Roaming/Nextcloud/._sync_01505fe75d09.db-shm"
```

**Server Log:**
```
    OCA\DAV\Connector\Sabre\Exception\Forbidden: Write access to end-to-end encrypted folder requires token - no token sent
    /var/www/html/custom_apps/end_to_end_encryption/lib/Connector/Sabre/LockPlugin.php - line 153:
    OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->verifyTokenOnWriteAccess(OCA\DAV\Conn ... {}, null)
    /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:
    OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->checkLock(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
    /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 458:
    Sabre\DAV\Server->emit("beforeMethod:PUT", [ Sabre\HTTP ... }])
    /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 251:
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
    /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 319:
    Sabre\DAV\Server->start()
    /var/www/html/apps/dav/lib/Server.php - line 325:
    Sabre\DAV\Server->exec()
    /var/www/html/apps/dav/appinfo/v2/remote.php - line 35:
    OCA\DAV\Server->exec()
    /var/www/html/remote.php - line 167:
    require_once("/var/www/ht ... p")
```

Adding a file with the Android app works, not yet tried on Ubuntu.

**Comment by er-vin** [comment]
Hm, it's odd, it looks like somehow the client decided that this "Privat" folder wasn't encrypted... Could you turn on the debug level on your client logs and look for the nextcloud.sync.clientsideencryption lines? There should be a few saying "Retrieved correctly the encrypted status"... Are they there? The line should end with a dump of the status found, is Privat really listed there as encrypted?

**Comment by er-vin** [comment]
Ah that starts to sound like the failing PROPFIND call I've been working on this week. Should be fixed with 3.0.3 if that's the case.

**Comment by WhiteBahamut** [comment]
Let me know if I can test/verify a thing :)

**Comment by er-vin** [comment]
The fix was merged yesterday, so you can try the daily build it should contain said fix.

**Comment by WhiteBahamut** [comment]
Used a daily 3.1.0 client. Still not fixed :(. I uninstalled the old version, then the daily (nextcloud-3.1.0.15934-daily-20201022-Release).
```
2020-10-24 11:49:47:394 [ info nextcloud.sync.clientsideencryption ]:	Initializing
2020-10-24 11:49:47:395 [ info nextcloud.sync.server.capabilities ]:	E2EE API version: "1.1"
2020-10-24 11:49:47:396 [ debug nextcloud.sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job OCC::AvatarJob finished for ""
2020-10-24 11:49:47:398 [ info nextcloud.sync.clientsideencryption ]:	Public key fetched from keychain
2020-10-24 11:49:47:402 [ info nextcloud.sync.clientsideencryption ]:	Private key fetched from keychain
2020-10-24 11:49:47:404 [ info nextcloud.sync.clientsideencryption ]:	Mnemonic key fetched from keychain:  "LOREM IPSUM"
```
All my files in the "Private" are encrypted and just displayed with their hash as name.

My server logs is bombarded with the following messages:
```
Info: Deprecated event type for OCA\Files::loadAdditionalScripts: Symfony\Component\EventDispatcher\GenericEvent is used
``` 
and
```
Deprecated event type for {"[object] (OCP\SabrePluginEvent)":{"*statusCode":200,"*message":"","*server":{"[object] (OCA\DAV\Connector\Sabre\Server)":{"tree":"[object] (OCA\DAV\Connector\Sabre\ObjectTree)","*baseUri":"/remote.php/webdav/","httpResponse":"[object] (Sabre\HTTP\Response)","httpRequest":"[object] (Sabre\HTTP\Request)","sapi":"[object] (Sabre\HTTP\Sapi)","*plugins":[],"transactionType":null,"protectedProperties":{"...":"Over 20 items, aborting normalization"},"debugExceptions":false,"resourceTypeMapping":[],"enablePropfindDepthInfinity":true,"xml":"[object] (Sabre\DAV\Xml\Service)","*listeners":{"...":"Over 20 items, aborting normalization"},"*wildcardListeners":[],"*listenerIndex":[],"*logger":null}},"Symfony\Contracts\EventDispatcher\EventpropagationStopped":false}}: null
```

The first one seems to be looking for something in my "Privat" folder, the second one just crawls my files in general.

**Comment by WhiteBahamut** [comment]
Also the Linux client is not working. Looks to me like the same error.

**Comment by zacha81** [comment]
I suppose I have the same problem.
Server is 19.0.3 on Linux, this is a managed instance, I don't have console access.

Client  is 3.0.2 on Fedora
and 3.1.3 on android.

I can setup E2EE correctly for a folder. I can upload files to that folder and download and decrypt on the other device.
I CAN delete files from the encrypted folder as long as it is a flat structure.

e.g. I create a folder 
"Photos"

and within a.png, b.png

I can delete the files.
As soon as an encrypted sub directory (e.g. Photos/Upload) comes into play I cannot delete any files anymore and I cannot remove the sub directories anymore. I either get a 404 or a 403 error when trying to delete files and folder. I cannot remove the folder in any way, as it has no  "delete" option in the web app either.

Steps to reproduce:
- create Folder on Linux client
- setup Encryption for folder
- create Sub folder
- put files in
- try to delete files

client side debug log: (ain't got server logs, b/c managed instance, this is the reason I am trying to use E2EE)

2020-10-24 13:37:45:141 [ info nextcloud.sync.propagator ]:	Starting INSTRUCTION_IGNORE propagation of "SofortUploads/Camera/IMG_20201021_180157.jpg" by OCC::PropagateIgnoreJob(0x560271723ec0)
2020-10-24 13:37:45:142 [ warning nextcloud.sync.propagator ]:	Could not complete propagation of "SofortUploads/Camera/IMG_20201021_180157.jpg" by OCC::PropagateIgnoreJob(0x560271723ec0) with status 10 and error: "Server replied \"403 Forbidden\" to \"DELETE https://nextcloud.exampledomain.de/remote.php/dav/files/user/SofortUploads/6aea33fdb15444e18775fded0d858146/02ddbf8febf344c799995088567a6d09\" (skipped due to earlier error, trying again in 11 second(s))"
2020-10-24 13:37:45:142 [ debug nextcloud.sync.statustracker ]	[ OCC::SyncFileStatusTracker::slotItemCompleted ]:	Item completed "SofortUploads/Camera/IMG_20201021_180157.jpg" 10 32
2020-10-24 13:37:45:143 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 QVariant(qlonglong, 5984633726403509493)
2020-10-24 13:37:45:143 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path, inode, modtime, type, md5, fileid, remotePerm, filesize,  ignoredChildrenRemote, contentchecksumtype.name || ':' || contentChecksum, e2eMangledName, isE2eEncrypted  FROM metadata  LEFT JOIN checksumtype as contentchecksumtype ON metadata.contentChecksumTypeId == contentchecksumtype.id WHERE phash=?1"
2020-10-24 13:37:45:143 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 QVariant(qlonglong, 1472275387683064896)
2020-10-24 13:37:45:144 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path, inode, modtime, type, md5, fileid, remotePerm, filesize,  ignoredChildrenRemote, contentchecksumtype.name || ':' || contentChecksum, e2eMangledName, isE2eEncrypted  FROM metadata  LEFT JOIN checksumtype as contentchecksumtype ON metadata.contentChecksumTypeId == contentchecksumtype.id WHERE phash=?1"
2020-10-24 13:37:45:144 [ debug nextcloud.gui.folder ]	[ OCC::Folder::slotItemCompleted ]:	local discovery: inserted "SofortUploads/Camera/IMG_20201021_180157.jpg" due to sync failure
2020-10-24 13:37:45:144 [ warning nextcloud.gui.activity ]:	Item  "SofortUploads/Camera/IMG_20201021_180157.jpg"  retrieved resulted in  "Server replied \"403 Forbidden\" to \"DELETE https://nextcloud.exampledomain.de/remote.php/dav/files/user/SofortUploads/6aea33fdb15444e18775fded0d858146/02ddbf8febf344c799995088567a6d09\" (skipped due to earlier error, trying again in 11 second(s))"
2020-10-24 13:37:45:145 [ warning nextcloud.gui.activity ]:	Item  "SofortUploads/Camera/IMG_20201021_180157.jpg"  retrieved resulted in error  "Server replied \"403 Forbidden\" to \"DELETE https://nextcloud.exampledomain.de/remote.php/dav/files/user/SofortUploads/6aea33fdb15444e18775fded0d858146/02ddbf8febf344c799995088567a6d09\" (skipped due to earlier error, trying again in 11 second(s))"
2020-10-24 13:37:45:145 [ info nextcloud.gui.activity ]:	Error successfully added to the notification list:  "Server replied \"403 Forbidden\" to \"DELETE https://nextcloud.exampledomain.de/remote.php/dav/files/user/SofortUploads/6aea33fdb15444e18775fded0d858146/02ddbf8febf344c799995088567a6d09\" (skipped due to earlier error, trying again in 11 second(s))"
2020-10-24 13:37:45:146 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT phash, path, e2eMangledName FROM metadata order by path"
2020-10-24 13:37:45:147 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "PRAGMA wal_checkpoint(FULL);"
2020-10-24 13:37:45:148 [ debug nextcloud.sync.database ]	[ OCC::SyncJournalDb::walCheckpoint ]:	took 0 msec
2020-10-24 13:37:45:148 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path FROM conflicts"
2020-10-24 13:37:45:148 [ debug nextcloud.sync.database ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit  "All Finished." 
2020-10-24 13:37:45:150 [ info nextcloud.sync.database ]:	Closing DB "/home/fz/.local/share/Nextcloud/._sync_4738b41a7497.db"
2020-10-24 13:37:45:150 [ debug nextcloud.sync.database ]	[ OCC::SyncJournalDb::commitTransaction ]:	No database Transaction to commit
2020-10-24 13:37:45:169 [ info nextcloud.sync.engine ]:	CSync run took  1220 ms
2020-10-24 13:37:45:231 [ info nextcloud.gui.folder ]:	Client version 3.0.2git (build 3560)  Qt 5.12.9  SSL  OpenSSL 1.1.1g  21 Apr 2020
2020-10-24 13:37:45:231 [ info nextcloud.gui.folder ]:	SyncEngine finished without problem.
2020-10-24 13:37:45:232 [ info nextcloud.gui.folder ]:	Folder sync result:  3
2020-10-24 13:37:45:232 [ debug nextcloud.gui.folder ]	[ OCC::Folder::slotSyncFinished ]:	Sync failed, keeping last sync's local discovery path list

**Comment by WhiteBahamut** [comment]
Android client works. So seems to be something in the Desktop client :S

**Comment by zacha81** [comment]
Actually I have to say it is not so easy to reproduce, it seems somewhat more complicated. I you just created a structure again and tried to delete from the inner to the outer it does actually (while I could not delete the to top level folder from the Linux client I could delete it it from the Android Client after removing the encryption.)

In the first place I tried moving files from one encrypted to another encrypted folder, I suppose there is some kind of a race condition, which led me in a state where I cannot delete any of the both folders anymore.

**Comment by zacha81** [comment]
I managed to remove the stale folders by disabling End2End Acryption rpp from the Admin Panel. It seems End2End Encryption App prevents deletion on the serverside for some reason. Disabling the app reavealed a hidden file within one folder too, which seems a relict of a failed move/delete operation. It was named {hash-value}.e2e-to-save

**Comment by er-vin** [comment]
@WhiteBahamut since you've been testing with the daily and you got debug logs... could you look for the lines containing:
"Retrieved correctly the encrypted status of the folders for"
or containing:
"Failed to retrieve the status of the folders for"

I might have an idea I'd like to confirm. I'd also need to know which of the folders are supposed to be encrypted. I'm hunting for an inconsistency between the list of encrypted folders the sync engine knows about and the actual list of encrypted folders.

**Comment by WhiteBahamut** [comment]
Just installed today's daily (uninstall old, install new). 
```
2020-10-26 16:22:23:812 [ info nextcloud.sync.networkjob.clientsideencrypt ]:	GetFolderEncryptStatus of QUrl("https://<SERVER>/remote.php/webdav/Privat/") finished with status QNetworkReply::NoError ""
2020-10-26 16:22:23:815 [ debug nextcloud.sync.clientsideencryption ]	[ OCC::ClientSideEncryption::folderEncryptedStatusFetched ]:	Retrieved correctly the encrypted status of the folders for "Privat/" QHash(("Privat/", true))
2020-10-26 16:22:23:817 [ debug nextcloud.sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job OCC::GetFolderEncryptStatusJob finished for "remote.php/webdav"
```
It seems it get the correct information on the folder. My other folders get a `false` for the state. Which is correct
![image](https://user-images.githubusercontent.com/38832027/97197262-b944b180-17ad-11eb-9503-f9d60c041881.png)


I get quite a lot 
```
2020-10-26 16:58:33:245 [ warning nextcloud.sync.networkjob ]:	Network job timeout QUrl("remote.php/webdav")
2020-10-26 16:58:33:307 [ warning nextcloud.sync.networkjob ]:	Network job timeout QUrl("remote.php/webdav")
2020-10-26 16:58:33:308 [ warning nextcloud.sync.networkjob ]:	Network job timeout QUrl("remote.php/webdav")
```
Sync status als turns not to green (maybe this is an issue in the daily)

**Comment by er-vin** [comment]
> Just installed today's daily (uninstall old, install new).
> 
> ```
> 2020-10-26 16:22:23:812 [ info nextcloud.sync.networkjob.clientsideencrypt ]:	GetFolderEncryptStatus of QUrl("https://<SERVER>/remote.php/webdav/Privat/") finished with status QNetworkReply::NoError ""
> 2020-10-26 16:22:23:815 [ debug nextcloud.sync.clientsideencryption ]	[ OCC::ClientSideEncryption::folderEncryptedStatusFetched ]:	Retrieved correctly the encrypted status of the folders for "Privat/" QHash(("Privat/", true))
> 2020-10-26 16:22:23:817 [ debug nextcloud.sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job OCC::GetFolderEncryptStatusJob finished for "remote.php/webdav"
> ```
> 
> It seems it get the correct information on the folder. My other folders get a `false` for the state. Which is correct
> ![image](https://user-images.githubusercontent.com/38832027/97197262-b944b180-17ad-11eb-9503-f9d60c041881.png)

Just a word of caution: we do this querying when the settings dialog is displayed, but we do it as well at the beginning of each sync (to make sure we got fresh data). So make sure you're looking at the line of logs happening at the beginning of sync.

> I get quite a lot
> 
> ```
> 2020-10-26 16:58:33:245 [ warning nextcloud.sync.networkjob ]:	Network job timeout QUrl("remote.php/webdav")
> 2020-10-26 16:58:33:307 [ warning nextcloud.sync.networkjob ]:	Network job timeout QUrl("remote.php/webdav")
> 2020-10-26 16:58:33:308 [ warning nextcloud.sync.networkjob ]:	Network job timeout QUrl("remote.php/webdav")
> ```
> 
> Sync status als turns not to green (maybe this is an issue in the daily)

Those timeouts seem fairly different to your previous issue though. No more locking problems?
Also do you know which jobs are timing out?

I don't like those timeouts at all because it likely means the server is busy doing something again...

**Comment by WhiteBahamut** [comment]
Items are still not decrypted on my windows client... just seeing hash as filename. dont know which jobs times out :S

**Comment by WhiteBahamut** [comment]
Just had a look on my notebook client (win, 3.0.2). My encrypted folder is *not* recognized as encrypted folder. But it used to work, as the files there on my notebook are correctly downloaded

```
2020-10-26 20:39:43:989 [ info nextcloud.sync.networkjob.jsonapi ]:	JsonApiJob of QUrl("https://cloud.chromaticum.de/ocs/v2.php/apps/notifications/api/v2/notifications?format=json") FINISHED WITH STATUS "OK"
2020-10-26 20:39:43:992 [ info nextcloud.gui.activity ]:	Clear the notifications
2020-10-26 20:39:48:938 [ warning nextcloud.sync.networkjob ]:	Network job timeout QUrl("https://<SERVER>/remote.php/webdav")
2020-10-26 20:39:48:940 [ info nextcloud.sync.credentials.webflow ]:	request finished
2020-10-26 20:39:48:941 [ warning nextcloud.sync.networkjob ]:	QNetworkReply::OperationCanceledError "Zeitüberschreitung bei der Verbindung" QVariant(Invalid)
2020-10-26 20:39:48:944 [ warning nextcloud.sync.credentials.webflow ]:	QNetworkReply::OperationCanceledError
2020-10-26 20:39:48:945 [ warning nextcloud.sync.credentials.webflow ]:	"Operation abgebrochen"
2020-10-26 20:39:48:947 [ info nextcloud.sync.networkjob.clientsideencrypt ]:	GetFolderEncryptStatus of QUrl("https://<SERVER>/remote.php/webdav") finished with status QNetworkReply::OperationCanceledError "Zeitüberschreitung bei der Verbindung"
2020-10-26 20:39:48:948 [ warning nextcloud.sync.networkjob.clientsideencrypt ]:	*not* successful, http result code is 0 ""
```

**Comment by er-vin** [comment]
Yes, but 3.0.2 gets you back to your timeout issues from earlier, that's to be expected.
