### ISSUE TITLE
Client MacOS 3.0.1 don´t remove or ignore unchecked folders

### ISSUE THREAD

**Issue by solick** [nextcloud/desktop#2468]
### Expected behaviour
Unchecking folders in NC Client shall remove them from local computer and ignore them in future sync tasks

### Actual behaviour
Uncheck 3 folders in the NC client mark them locally with ignore icon in Finder but console shows constant sync with these folders.
-->

### Steps to reproduce
1.have a local synced NC with several folders
2. unceck folder in NC client
3.

### Client configuration
Client version: 3.0.1

Operating system: Mac OS 10.15.6 Catalina

OS language: German

Installation path of client: /Applications

### Server configuration

Nextcloud version: 19.0.3 self hostet Ubuntu 18.04

**Comment by solick** [comment]
anyone else has this problem?

**Comment by er-vin** [comment]
OK, first time I hear about this one. Did it appear with 3.0.1 only? You sure it wasn't present before? I admit I'm a bit surprised I don't remember changes related to this apart from the upgrade issue which got fixed in 3.0.2. From your description it seems to be post-upgrade though.

@DominiqueFuchs @camilasan @misch7 does that ring any bell to anyone?

**Comment by solick** [comment]
hmm cannot say that it happened before. I experienced the correct behavior before 3.0 but the problem remains with 3.0.2

in Finder i see the directories marked with the yellow symbol and the hover tooltip shows ignored.
the log shows that the client is still observing the unchecked folders.

**Comment by solick** [comment]
Update: It works with a very small folder but with large folder size (and/or large ammount of files) it seems not to work. Maybe I unchecked the folder before the sync was finished and now the client is stuck in a loop?

**Comment by camilasan** [comment]
Could anyone experiencing this issue run the client with --logdebug and send us the logs and the name of the folders that are supposed to be ignored/removed? 
https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files

**Comment by solick** [comment]
sorry because of movement of to a new server I cannot reproduce the behavior anymore.

**Comment by Joshuasony** [comment]
I am affected by this issue. :( 
I am using MacOS 12.1 with Nextcloud Client Version 3.3.6.
