### ISSUE TITLE
Nextcloud mac sync client cause OS UI to freeze, change, and sometimes lock up entirely.

### ISSUE THREAD

**Issue by p-sims** [nextcloud/desktop#3012]
I was in the process of writing this bug report, when nextcloud client freeze managed to lock up entire computer . . . So attempt two at writing this report. . .

### Expected behaviour
When you right click on Nextcloud client in menu bar it opens dropdown menu which is then responsive to clicks. Similar if you right click on a folder in you're nextcloud directory there nextcloud submenu should appear in the right click menu.

### Actual behaviour
Mostly what expected, but sometimes with a short freeze first. Sometimes menus appear but when you interact with them you get spinning beachball. Sometimes When you click on icon in status bar nothing happens, and then after a few click it pops up and then dissappears. Sometimes it works fine without issue. As I've just proved sometimes the UI can freeze and nextcloud menu can not disappear at all even though the focus has moved to another application. When this just happen to me the UI slowly locked up entirely and I had to hard reset entire computer.

Sometimes it takes a while for right click menu to show the nextcloud submenu at all, some times the right click menu locks up for a bit until it shows up. 

Sometimes 

### Client configuration
Client version: 3.1.3

Operating system: 10.14.6 (18G7016)
OS language: English

### Logs
[Nextcloud log 16-3-21.zip](https://github.com/nextcloud/desktop/files/6150541/Nextcloud.log.16-3-21.zip)
The log file after complete lock up and reboot was so large I can't upload it here so I've put it in nextcloud:
https://cloud.chiltern.org.uk/s/2mgRnfqdN52ALei

Here is a screen shot of lock up.
![Photo of screen during UI freeze just before it looked up completely](https://user-images.githubusercontent.com/64636731/111345725-72c8f400-8675-11eb-8ffb-e8c2add0027a.JPG)

I only recently upgraded from v2.7 to 3.1 on the understanding it was stable. Not sure if I should be downgrading back to v2.7 client . . .

**Comment by FlexW** [comment]
Is your computer unresponsive only if you open the main dialog or is it in general on high load? Could you tell me how many files, directories you try to sync and how big the data is you try to sync?

From your logs, I can see that most of the logging statements come from the sync engine. A huge amount of log statements can make your computer unresponsive because the client has to compress all the log files. We release in a few weeks an update (version 3.2.0) that contains a major overhaul for the sync engine. We already released a release candidate ([version 3.2.0-rc1](https://github.com/nextcloud/desktop/releases/tag/v3.2.0-rc1)). Would be great if you can test that version and tell us if you still have the same problems.

**Comment by p-sims** [comment]
>> Is your computer unresponsive only if you open the main dialog or is it in general on high load?
>> 
My computer wasn’t noticeable high CPU most of the time theses freezes happened, it’s more like its waiting for something. It might have been short on ram when it locked up entirely. It was almost like UI and background process weren’t running asynchronously so the UI sometimes had to wait for the background process to do something.
>> Could you tell me how many files, directories you try to sync and how big the data is you try to sync?
>> 
My local Nextcloud folder on this computer is 66 GB (50k files) but my folder on the cloud is closer to 100 GB as I’m selectively syncing. The server it’s synced to is running on a overspecifiy machine for future proofing.

> A huge amount of log statements can make your computer unresponsive because the client has to compress all the log files.
> 
These freezes never happened while sync client was running in the background. It only ever started to freeze when I was trying to interact with the UI. Does clicking on the menu trigger something to be added to a log file? If so I’m not sure why UI could not continue to response while such things are happening in the background. The right click menu and status menu don’t need information out of log files do they?

That said if rebooting resets some logs that might explain some of it. Up until I was forced to restart yesterday it was happening regularly (although not consistently) and my computer hand be up for a month or two, however since restarting it’s not happening at all (so far).
> We release in a few weeks an update (version 3.2.0) that contains a major overhaul for the sync engine. We already released a release candidate (version 3.2.0-rc1 <https://github.com/nextcloud/desktop/releases/tag/v3.2.0-rc1>). Would be great if you can test that version and tell us if you still have the same problems.
> 

I’d be happy to, but can’t see a macOS build on the github page linked. Would I need to build it from source using these instructions <https://github.com/nextcloud/desktop/wiki/How-to-compile-the-desktop-client>?

**Comment by FlexW** [comment]
> I’d be happy to, but can’t see a macOS build on the github page linked. Would I need to build it from source using these instructions <https://github.com/nextcloud/desktop/wiki/How-to-compile-the-desktop-client>?

There is a MacOS installer file. It's called "Nextcloud-3.2.0-rc1.pkg". That is the direct link to it:
https://github.com/nextcloud/desktop/releases/download/v3.2.0-rc1/Nextcloud-3.2.0-rc1.pkg

**Comment by p-sims** [comment]
Thanks, I tried installing this but unfortunately it’s says it’s not compatible with the nextcloud server version . . .



I’ve just tried up update the nextcloud server and it is on the latest stable version. I don’t want put an unstable version on the server.

**Comment by FlexW** [comment]
It's fine, that was a bug. The fix will be delivered with the next rc. It's save to proceed. See also:
https://github.com/nextcloud/desktop/issues/3001
https://github.com/nextcloud/desktop/pull/3009

**Comment by TheTrueTom** [comment]
> > I’d be happy to, but can’t see a macOS build on the github page linked. Would I need to build it from source using these instructions https://github.com/nextcloud/desktop/wiki/How-to-compile-the-desktop-client?
> 
> There is a MacOS installer file. It's called "Nextcloud-3.2.0-rc1.pkg". That is the direct link to it:
> https://github.com/nextcloud/desktop/releases/download/v3.2.0-rc1/Nextcloud-3.2.0-rc1.pkg

I had the same problem. Hanging never occurred right after application launch but rather when it had been running for some time.
3.2.0 rc1 seems to fix the problem as I have not experienced any hang since the installation.

**Comment by p-sims** [comment]
> We release in a few weeks an update (version 3.2.0) that contains a major overhaul for the sync engine. We already released a release candidate (version 3.2.0-rc1 <https://github.com/nextcloud/desktop/releases/tag/v3.2.0-rc1>). Would be great if you can test that version and tell us if you still have the same problems.

So a few weeks ago I downloaded and installed this, Initially it was fine, but after a week or so it started becoming unresponsive occasionally. I almost managed to lock computer up entirely again, but I think that was because it was trying to sync an 8GB .gpkg over slow wifi connections. I wouldn't say it's as bad as it was before (although that might just be because it's not been running for 3months), but it's defiantly not entirely resolved.
![Screenshot 2021-03-30 at 23 34 29](https://user-images.githubusercontent.com/64636731/113400133-41506800-9399-11eb-8171-1e428610967b.png)
[31-3-21_Nextcloud-3.1.81_Debug.zip](https://github.com/nextcloud/desktop/files/6248654/31-3-21_Nextcloud-3.1.81_Debug.zip)

However when I came to submit this comment, I discovered that the version of nextcloud client I had running stated it was '3.1.81git (build 5080)'. I have proved that even if I delete the nextcloud app and reinstall version 3.2.0-rc1 <https://github.com/nextcloud/desktop/releases/tag/v3.2.0-rc1> it still says version '3.1.81git (build 5080)'

**Comment by nalt** [comment]
For me, the freezes got much worse when the notifications where moved to the menu of the desktop icon. Before, it happened only when the notifications where shown. So I assume that the freezes are caused by my long list of notifications.

There is no quick way to remove all notifications, and some just come back. So I guess the list of notifications added to the GUI  must be limited.

If this sounds like a separate bug, let me know.

**Comment by FlexW** [comment]
@p-sims 3.2.0-rc1 is a pre release. Therefore the version number is a little bit lower than 3.2.0. If the release is stable, the version number will be 3.2.0. From your newest comment it is unclear to me, if you still have these freeezes?

> There is no quick way to remove all notifications, and some just come back. So I guess the list of notifications added to the GUI must be limited. If this sounds like a separate bug, let me know.

Indeed this sounds like a separate issue, please open a separate issue about that :) Btw, you can dismiss all your notifications in the web ui.

**Comment by p-sims** [comment]
> From your newest comment it is unclear to me, if you still have these freeezes?
Yes I still have these freeze. I've just tried to click on nextcloud item in the menu bar and initially, I click and nothing happen. I then click again, then again, then menu pops up and then immediately disappears. I think click again and it come up immediately and then it work as expect.

I also had a instance today when I right clicked on a folder in finder and right click menu came up, but when you hovered over next cloud submenu it didn't appear. After trying a few times or using the arrow key to navigate to it, it then works fine. I'm not sure if these issues are related.
[6-4-21_Nextcloud-3.1.81_Debug.zip](https://github.com/nextcloud/desktop/files/6267085/6-4-21_Nextcloud-3.1.81_Debug.zip)

**Comment by dblatner** [comment]
In addition to the issues mentioned above, my Nextcloud macOS desktop client (3.1.3) crashes after some time waiting for the UI (or any blocked processes). My files are stored on an external exFAT SSD.

I also noticed a network performance degradation with uploading files, 200 kb/sec instead of 2.5 mb/sec, not sure if this is related to the blocked UI/processes.

When running in the background, files are synchronized.

I'd like to test it with the new client version 3.2.0, but could you say when a stable release is available?

**Comment by p-sims** [comment]
Today (still running 3.1.81git Mac Client), I tried to un pause synconisation and UI was mostly unresponsive with lots of spinning beachballs. Below photo's of trying to interact with menu after finally getting it to appear. Interestingly, once I'd quit process using activity monitor and restarted it, the UI then ran beautifully. It's almost like it gets clogged up.

![UI Hang with Beachball before restart 2](https://user-images.githubusercontent.com/64636731/116981481-72d19180-acbf-11eb-9729-09988cb4fad7.JPG)

![UI Hang with Beachball before restart 1](https://user-images.githubusercontent.com/64636731/116981468-6d744700-acbf-11eb-920a-3c048289a872.JPG)

This is the logs zip after restarting client:
[after restarting client when is was freezing on UI interactions.zip](https://github.com/nextcloud/desktop/files/6420035/after.restarting.client.when.is.was.freezing.on.UI.interactions.zip)

**Comment by znerol** [comment]
I observed macOS UI freeze and high CPU loads after rolling out Nextcloud Desktop 3.3.0 in a mixed Catalina / Mojave environment. In our case it was enough to just _install_ Nextcloud Desktop to corruption of the [Launch Services](https://developer.apple.com/documentation/coreservices/launch_services) database. If that happens, macOS will try and fail to rebuild the database in a tight loop. Symptoms of this scenario is very high log traffic (1k log messages per second in `Console.app`, see attached sample) and `lsd` and `pkd` processes running with constantly high CPU. Note that Nextcloud Desktop does not even need to be started to trigger this condition.

**Console.app logs:** [havoc-pkd-lsd.log](https://github.com/nextcloud/desktop/files/6983058/havoc-pkd-lsd.log)

**Activity Monitor:**
![havoc-pkd-lsd](https://user-images.githubusercontent.com/23288/129371429-ccd25ce4-e5ee-48c3-ae87-3fc9d393b031.png)

In order to fix the problem it is regrettably not enough to simply uninstall Nextcloud Desktop. The Launch Services database needs a rebuild as well. Exact steps:
1. Delete Nextcloud Desktop from the affected machine and empty the trash.
2. Rebuild the launch service database using `lsregister` the following command (curtesy of [routers blog](https://www.logcg.com/en/archives/3382.html)):
  `sudo /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user `

**Comment by KLEPTOROTH** [comment]
> I observed macOS UI freeze and high CPU loads after rolling out Nextcloud Desktop 3.3.0 in a mixed Catalina / Mojave environment. In our case it was enough to just _install_ Nextcloud Desktop to corrupt the [Launch Services](https://developer.apple.com/documentation/coreservices/launch_services) database. If that happens, macOS will try and fail to rebuild the database in a tight loop. Symptoms of this scenario is very high log traffic (1k log messages per second in `Console.app`, see attached sample) and `lsd` and `pkd` processes running with constantly high CPU. Note that Nextcloud Desktop does not even need to be started to trigger this condition.
> 
> **Console.app logs:** [havoc-pkd-lsd.log](https://github.com/nextcloud/desktop/files/6983058/havoc-pkd-lsd.log)
> 
> **Activity Monitor:** ![havoc-pkd-lsd](https://user-images.githubusercontent.com/23288/129371429-ccd25ce4-e5ee-48c3-ae87-3fc9d393b031.png)
> 
> In order to fix the problem it is regrettably not enough to simply uninstall Nextcloud Desktop. The Launch Services database needs a rebuild as well. Exact steps:
> 
> 1. Delete Nextcloud Desktop from the affected machine and empty the trash.
> 2. Rebuild the launch service database using `lsregister` (curtesy of [routers blog](https://www.logcg.com/en/archives/3382.html)):
>    `sudo /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user `

I'm seeing the exact same issue right now.  I ended up using AppCleaner to remove NextCloud - after reboot pkd and lsd didn't freak out.  Updating NextCloud didn't do anything for me either.  Oddly, this is happening randomly now, just started last week.  Not sure what triggered it, but it happens even if the user has never opened NextCloud, as you mentioned.  

Also interesting is the version we have deployed is 3.3.6 - weird why it just suddenly started happening, seemingly with no reason.  Perhaps some macOS update caused issues with 3.3.6 as well.

**Comment by znerol** [comment]
Regrettably I am still observing this with 3.3.6 as well. I suspect that there might still be metadata in `Info.plist` which can be problematic under certain scenarios (e.g. updates). Maybe `UTExportedTypeDeclarations` and `CFBundleDocumentTypes` are triggering these issues. But honestly I cannot pinpoint the exact problem.

More info on UTI can be found here:
* https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_conc/understand_utis_conc.html
* https://www.cocoanetics.com/2012/09/fun-with-uti/

**Comment by bendschs** [comment]
this issue came up for me on 3.3.6 with NC23 (so both most recent versions). Client is on MacOS Catalina.

**Comment by nigelhorne** [comment]
It's still happening.  I landed here after a Google search of "nextcloud osx client locks up".  Mine is stuck in the 'R' state and the app is unresponsive.

**Comment by pjrobertson** [comment]
I also have this problem on 10.14 with the latest version of Nextcloud (3.4.1git (build 8596) (3.4.1.8596)).

If I click the icon in the menu bar at any point, Nextcloud proceeds with a really high CPU, for about 1-2 minutes.

I've attached a spindump. It looks like it's something to do with locale, and `CFLocaleCreateCanonicalLanguageIdentifierFromString` or `CFLocaleGetLanguageRegionEncodingForLocaleIdentifier` in particulare. Not sure. But my computer locale is set as follows:
![Screenshot 2022-02-24 at 12 41 42](https://user-images.githubusercontent.com/150431/155459323-fb0c5cbd-4ef1-4008-bfcc-d279181dfcf4.png)
[Nextcloud_spindump1.txt](https://github.com/nextcloud/desktop/files/8129703/Nextcloud_spindump1.txt)
[](url)

**Comment by claucambra** [comment]
Hi all, is this issue still happening for you on 3.5.1?

**Comment by pjrobertson** [comment]
Thanks for the notification @claucambra . I have just downlaoded 3.5.1 and can confirm that the hangs are gone for me. There still is a small lag between clicking the icon and the window appearing, but it no longer hangs for 10s+.

Thanks for your hard work!

**Comment by pjrobertson** [comment]
I think I spoke too soon. I've just experienced a very long hang with the app. Please see the attached spindump.txt
[spindump.txt](https://github.com/nextcloud/desktop/files/8896187/spindump.txt)

**Comment by nigelhorne** [comment]
Hurrah!

**Comment by dnlfrst** [comment]
This still happens for me on 3.6.4 on macOS Ventura (13.1). Occasionally, the whole system hangs such that I can still click on elements of the user interface but there won't be any response for an undetermined amount of time. During this period, I cannot start programs or issue commands on the terminal, for example. This is very annoying, especially since these periods can be for up to a few minutes.

**Comment by swirly** [comment]
Same problem for me. Nextcloud client get frozen and has a 99.98% of processor usage. Thanks to a 8 core computer, I can continue to work (only one core affected), but no more sync.
Everything start suddenly, without any update. 
Client is 3.7
Server is 25
osX is last version of Big Sur
This started after the computer went to sleep although
I tried to de-install nextcloud, and the lsregister hack, but nothing works
Client useless, just used as a warming source.
Nothing in nextcloud logs (tries to sync a file and hangs)
nothing revelant in system log
I don't know what to do

**Comment by victormylle** [comment]
I also have the same issue, my MacBook keeps lagging until I close the Nextcloud Client.

**Comment by p-sims** [comment]
Hi All, I'm currently running next cloud 3.9.1 on MacOS 10.14 and I've not seen CPU clock up issue since I last reported here. This is with server version 24.0.12, but I will upgrade to 25 soon so will confirm whether that creates any issues.

That said, ever since I updated to 3.5.2 a year ago I've had an issue where the finder intergeneration disappears silently. After boot or restarting nextcloud client finder looks like this:
![Screenshot 2023-08-06 at 11 48 01](https://github.com/nextcloud/desktop/assets/64636731/48df5231-5135-499b-97c6-96e233f5de9e)
However after a while (currently not been able to observe or trigger change) the green ticket disappear and 'nextcloud' submenu in the right click menu disappears. This is annoying but easily worked round by restarting client.

I've proved that sleeping computer doesn't trigger this, but not sure what does. All I can see is that it always happens within a few days.

I have know idea whether this is related to the UI lock up issue or worth raising as a separate issue.

**Comment by p-sims** [comment]
Sorry, didn't mean to close the issue.

**Comment by Nowaker** [comment]
<img width="441" alt="image" src="https://github.com/nextcloud/desktop/assets/611746/375f0f8c-f29f-41cb-b1fa-bd6dcb5d55c0">


My Nextcloud on Mac hangs consistently hangs at syncing the last file.

```
nowaker          90583 100.0  0.5 410534400  87936   ??  R     8:45PM   0:35.24 /Applications/Nextcloud.app/Contents/MacOS/Nextcloud
```

100% CPU usage, never finishes.

kill -9, start again, same 7 files sync (which ones is unknown to me), and same issue.

**Comment by petertorelli** [comment]
Using MacOS Sonoma 14.5 and 3.13 of client GUI. The GUI will randomly render off-screen and become unclickable, requiring a force kill and restart:

<img width="513" alt="image" src="https://github.com/nextcloud/desktop/assets/8249735/0a19484c-2187-41d9-9ed9-53e667b2a930">

**Comment by kupietools** [comment]
Using latest Nextcloud client 3.13.2 on Monterey 12.7.5 . Menu extra frozen with a beachball and CPU use inned at between 99.6%-99.9%. 

This is my very first experience with Nextcloud, I just installed it and paid for managed hosting a few hours ago, and chose this over Seafile because there was managed hosting and a straightforward Mac client available, it seemed like I wouldn't have to deal with troubleshooting and arcane technical details. It's discouraging that it didn't run for even 2 hours before becoming another item on the list of things I have to babysit and give attention to. I hope there is a simple fix for this. 

I have no idea if anything is syncing or not. It's totally locked up.  I guess I'm going to force quit it and restart.  Spindump:
[Spindump.txt](https://github.com/user-attachments/files/16309789/Spindump.txt)

**Comment by kupietools** [comment]
OK, so it ran OK for a day or two and then I let it run and now I just discovered it’s locked up again. I have no idea how many days it’s been locked up for or if anything is syncing at all or how long this is going to take, but I really needed this not to be another thing that I was going have to babysit and spend weeks troubleshooting and struggling with to try and get to work while issues sit here ignored.  There’s no reason for this to be pinnjng one of my processor at 100 and freezing and locking me out. Part of my used case was going to be to have this running on headless servers, and if it requires constant babysitting and constant troubleshooting then it’s not usable for that purpose. Obviously this project isn’t ready for prime time. Is this project even still alive, or is it abandonware? Has anybody figured out how to get this to work on Mac so that it’s actually usable?

**Comment by joshtrichards** [comment]
Going to close this since OP's matter was addressed awhile ago: https://github.com/nextcloud/desktop/issues/3012#issuecomment-1184485841

Anyone else on this thread: please open a distinct issue for your situation since it's presumably unrelated. The specifics of your situation in your own issue will be needed to determine what may be going on.

**Comment by Nowaker** [comment]
This was still broken this year. https://github.com/nextcloud/desktop/issues/3012#issuecomment-1955775119
