### ISSUE TITLE
Client 3.2 VFS "Error writing metadata to the database"

### ISSUE THREAD

**Issue by Lars1963** [nextcloud/desktop#3158]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
VFS-Sync should be flawless

### Actual behaviour
VFS-sync gives error 
in German: "Filepath\Filename: Fehler beim Schreiben der Daten in der Metadatenbank"

### Steps to reproduce
dunno

### Client configuration
Client version: 3.2.0 (Windows) x64

Operating system: Wndows 10 Pro Build: 19041.928

OS language: German

Installation path of client: C:\Program Files\Nextcloud

### Server configuration
Nextcloud version: 21.01

### Logs
1. Client logfile:  
 ;-) Yowza, that's a big file

Please provide uplink for 20 MB file

**Comment by Lars1963** [comment]
could be the same / related to #

**Comment by Lars1963** [comment]
Update: changing to latest daily build did not solve the problem.

**Comment by allexzander** [comment]
@Lars1963 Could you kindly share desktop client logs created when the issue happens? You can do it via the "Settings" dialog "Create Debug Archive" button. Please use it after you face the issue to make sure those logs are not overwritten.

**Comment by vasyugan** [comment]
> 
> 
> @Lars1963 Could you kindly share desktop client logs created when the issue happens?

I have share what I think is the relevant part of my client log at #3165

**Comment by szaimen** [comment]
This might also be helpful: https://help.nextcloud.com/t/windows-client-3-2-vfs-error-writing-metadata-to-the-database/113771/4

**Comment by allexzander** [comment]
@szaimen @vasyugan 

I am going to need full logs (archive with all logs) created right after you reproduce the issue. Logs mentioned, do not contain valuable information to help me with investigation.

**Comment by szaimen** [comment]
Sry, I haven't experienced this issue for myself. I just linked to the log in the forum.

**Comment by Lars1963** [comment]
> @Lars1963 Could you kindly share desktop client logs created when the issue happens? You can do it via the "Settings" dialog "Create Debug Archive" button. Please use it after you face the issue to make sure those logs are not overwritten.
> 
> I have just read your original post about the logs archive, where you've mentioned the size of logs is big. What you can do is - exit the Nextcloud client app, go to "C:/Users/<your_user_name>/AppData/Roaming/Nextcloud" and remove the "logs" folder prior to lunching the app. Then you will need to launch it and reproduce the issue. If you create logs right away - they shouldn't be too big.

@allexzander 
We were having massive sync-issues with 3.2 (no reliable syncing with and without VFS) on local lan with 25 Windows-PCs. I had to downgrade all of them.

Seems to me, it's a combination of NC 21.01 with `groupfolders`- and `client push`-app with `desktop 3.2`. I'll setup a testserver tomorrow to further investigate and provide some logs.

**Comment by allexzander** [comment]
@Lars1963 I am really looking forward to getting more details on that. Sounds very unfortunate. Kindly keep me posted. Also, I'd need both server and client-side logs generated right after you've experienced sync issues.

**Comment by Lars1963** [comment]
> @Lars1963 I am really looking forward to getting more details on that. Sounds very unfortunate. Kindly keep me posted. Also, I'd need both server and client-side logs generated right after you've experienced sync issues.

@allexzander Setting up a duplicate-testserver is on its way. Give me a few days to investigate (probably this weekend).

**Comment by vasyugan** [comment]
> 
> 
> @Lars1963 I am really looking forward to getting more details on that. Sounds very unfortunate. Kindly keep me posted. Also, I'd need both server and client-side logs generated right after you've experienced sync issues.

I can provide full debug logs, yet I won't publish them on github as they contain lots of personal data. If you give me your federated could ID, I can share the archive with you that way.

**Comment by allexzander** [comment]
> @allexzander
> I can provide full debug logs, yet I won't publish them on github as they contain lots of personal data. If you give me your federated cloud ID, I can share the archive with you that way.

@vasyugan Try this one https://cloud.nextcloud.com/s/s4Air7J7LBLXHiJ

**Comment by allexzander** [comment]
> @allexzander
> I can provide full debug logs, yet I won't publish them on github as they contain lots of personal data. If you give me your federated cloud ID, I can share the archive with you that way.

@vasyugan Or, actually, I guess you mean my email in the cloud? Here you are alex@nextcloud.com

**Comment by vasyugan** [comment]
> > @allexzander
> > I can provide full debug logs, yet I won't publish them on github as they contain lots of personal data. If you give me your federated cloud ID, I can share the archive with you that way.
> 
> @vasyugan I guess you mean my email in the cloud? Here you are [alex@nextcloud.com](mailto:alex@nextcloud.com)
> 
> You can also share on your server with a password and send the password to that email.

Actually I meant your [federated cloud ID](https://nextcloud.com/federation/).  Working for Nextcloud, I am surprised that you don't know what that is. I would assume that you have Nextcloud account at Nextcloud GmbH, your federated cloud ID should be [your username]@[your nextcloud server].

**Comment by mgallien** [comment]
I am trying to fix that error and have some modification in this PR #3187 . If somebody wants to try the fix, that would be helpful !

**Comment by allexzander** [comment]
> > > @allexzander
> > > I can provide full debug logs, yet I won't publish them on github as they contain lots of personal data. If you give me your federated cloud ID, I can share the archive with you that way.
> > 
> > 
> > @vasyugan I guess you mean my email in the cloud? Here you are [alex@nextcloud.com](mailto:alex@nextcloud.com)
> > You can also share on your server with a password and send the password to that email.
> 
> Actually I meant your [federated cloud ID](https://nextcloud.com/federation/). Working for Nextcloud, I am surprised that you don't know what that is. I would assume that you have Nextcloud account at Nextcloud GmbH, your federated cloud ID should be [your username]@[your nextcloud server].

@vasyugan In fact I never used a federated cloud ID and am surprised myself I need one. I will ask some of my colleagues to provide me with that ID on Monday. Thank you.

**Comment by allexzander** [comment]
> > > @allexzander
> > > I can provide full debug logs, yet I won't publish them on github as they contain lots of personal data. If you give me your federated cloud ID, I can share the archive with you that way.
> > 
> > 
> > @vasyugan I guess you mean my email in the cloud? Here you are [alex@nextcloud.com](mailto:alex@nextcloud.com)
> > You can also share on your server with a password and send the password to that email.
> 
> Actually I meant your [federated cloud ID](https://nextcloud.com/federation/). Working for Nextcloud, I am surprised that you don't know what that is. I would assume that you have Nextcloud account at Nextcloud GmbH, your federated cloud ID should be [your username]@[your nextcloud server].

Actually @vasyugan I am a bit confused with this term - federated ID. I have this account "alex at Nextcloud.com". And you also mentioned that it should look like [your username]@[your nextcloud server]? How is alex@nextcloud.com different from what you mean? Should I host my own server for that? Or is Nextcloud.com server enough for this?

**Comment by allexzander** [comment]
@vasyugan I was able to get some help with federated cloud id now and it's **alex@cloud.nextcloud.com**

**Comment by vasyugan** [comment]
> > > > @allexzander


> @vasyugan In fact I never used a federated cloud ID and am surprised myself I need one. I will ask some of my colleagues to provide me with that ID on Monday. Thank you.

When you have an account on a Nextcloud server, you automatically _have_ a federated cloud ID. It is [your user name]@[your server]

**Comment by allexzander** [comment]
> > > > > @allexzander
> 
> > @vasyugan In fact I never used a federated cloud ID and am surprised myself I need one. I will ask some of my colleagues to provide me with that ID on Monday. Thank you.
> 
> When you have an account on a Nextcloud server, you automatically _have_ a federated cloud ID. It is [your user name]@[your server]

Ok. Now I see. I appreciate explaining. You can use this one alex@cloud.nextcloud.com to share logs with me.

**Comment by vasyugan** [comment]
@allexzander 
> 
> Ok. Now I see. I appreciate explaining. You can use this one [alex@cloud.nextcloud.com](mailto:alex@cloud.nextcloud.com) to share logs with me.

Actually, I have. You should see a notification in your Nextcloud, you have to accept the incoming share.

**Comment by allexzander** [comment]
> @allexzander
> 
> > Ok. Now I see. I appreciate explaining. You can use this one [alex@cloud.nextcloud.com](mailto:alex@cloud.nextcloud.com) to share logs with me.
> 
> Actually, I have. You should see a notification in your Nextcloud, you have to accept the incoming share.

@vasyugan 

Yes. Downloaded them last week. Many thanks.

**Comment by allexzander** [comment]
My colleague @mgallien has a fix for this specific issue https://github.com/nextcloud/desktop/pull/3187 should be in 3.2.1 soon.

**Comment by vasyugan** [comment]
> My colleague @mgallien has a fix for this specific issue #3187 should be in 3.2.1 soon.

Great, thanks!

**Comment by allexzander** [comment]
Fixed in https://github.com/nextcloud/desktop/pull/3187

**Comment by Lars1963** [comment]
> Fixed in #3187

@allexzander Please reopen. This issue still exists in 3.2.1 (newly installed)

**Comment by allexzander** [comment]
@Lars1963 Have you tried removing "C:/Users/<your_user_name>/AppData/Roaming/Nextcloud" after removing 3.2.0? I can't find errors related to the original issue in the logs attached.

**Comment by Lars1963** [comment]
@allexzander Yes, I deleted every remains of the desktop after deinstall and restarted my PC before I did a install of 3.2.1. Connecting to my NC (also a complete new install with 20.0.2RC) was flawless until I tried to use via VFS. A normal sync (without VFS) on a second identical maschine works as expected.

**Comment by Lars1963** [comment]
```
2021-05-01 12:47:49:731 [ warning default ]:	qrc:/qml/src/gui/tray/Window.qml:567:17: QML MouseArea: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
2021-05-01 12:47:49:731 [ warning default ]:	qrc:/qml/src/gui/tray/Window.qml:583:17: QML Image: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
2021-05-01 12:47:49:731 [ warning default ]:	qrc:/qml/src/gui/tray/Window.qml:597:17: QML Column: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
2021-05-01 12:47:49:731 [ warning default ]:	qrc:/qml/src/gui/tray/Window.qml:650:17: QML RowLayout: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
2021-05-01 12:47:49:734 [ warning default ]:	qrc:/qml/src/gui/tray/Window.qml:567:17: QML MouseArea: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
2021-05-01 12:47:49:734 [ warning default ]:	qrc:/qml/src/gui/tray/Window.qml:583:17: QML Image: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
2021-05-01 12:47:49:734 [ warning default ]:	qrc:/qml/src/gui/tray/Window.qml:597:17: QML Column: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
2021-05-01 12:47:49:734 [ warning default ]:	qrc:/qml/src/gui/tray/Window.qml:650:17: QML RowLayout: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
```

This part from log.2 is probably  not related?

**Comment by Lars1963** [comment]
I also find a lot of these warnings in log.1

```
[warnning nextcloud.sync.vfs.cfapi]: couldn'f find pin state for regular non-placeholder file.. 
```

Is that somehow related?

**Comment by Lars1963** [comment]
And what about this? 
```
2021-05-01 12:39:48:611 [ info nextcloud.sync.engine ]:	#### Post-Reconcile end ####################################################  3194 ms
2021-05-01 12:39:48:611 [ info nextcloud.gui.folder ]:	#### Propagation start ####################################################
2021-05-01 12:39:48:611 [ debug nextcloud.gui.socketapi ]	[ OCC::SocketApi::slotUpdateFolderView ]:	Not sending UPDATE_VIEW for "1" because status() is OCC::SyncResult::SyncRunning
2021-05-01 12:39:48:615 [ info nextcloud.gui.application ]:	Sync state changed for folder  "https://datenhalde.therapiecenter.org/remote.php/dav/files/Ravenzwaaij/" :  "Sync Running"
2021-05-01 12:39:48:616 [ info nextcloud.sync.propagator ]:	Starting CSyncEnums::CSYNC_INSTRUCTION_NEW propagation of "1_Gemeinsam/11_Bibliothek" by OCC::PropagateLocalMkdir(0x2197095e870)
2021-05-01 12:39:48:616 [ debug nextcloud.sync.propagator ]	[ OCC::OwncloudPropagator::localFileNameClash ]:	CaseClashCheck for  "D:/1_Gemeinsam/11_Bibliothek"
2021-05-01 12:39:48:616 [ critical nextcloud.sync.vfs.cfapi.wrapper ]:	Couldn't convert to placeholder "" : 0x2197b96e9f0
2021-05-01 12:39:48:616 [ debug nextcloud.gui.folderwatcher ]	[ OCC::WatcherThread::watchChanges ]:	Skipping syncing of "D:/1_Gemeinsam"
2021-05-01 12:39:48:616 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 "1_Gemeinsam/11_Bibliothek"
2021-05-01 12:39:48:616 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT lastTryEtag, lastTryModtime, retrycount, errorstring, lastTryTime, ignoreDuration, renameTarget, errorCategory, requestId FROM blacklist WHERE path=?1 COLLATE NOCASE"
2021-05-01 12:39:48:616 [ warning nextcloud.sync.propagator ]:	Could not complete propagation of "1_Gemeinsam/11_Bibliothek" by OCC::PropagateLocalMkdir(0x2197095e870) with status OCC::SyncFileItem::FatalError and error: "Fehler beim Schreiben der Metadaten in die Datenbank"
2021-05-01 12:39:48:616 [ debug nextcloud.sync.statustracker ]	[ OCC::SyncFileStatusTracker::slotItemCompleted ]:	Item completed "1_Gemeinsam/11_Bibliothek" OCC::SyncFileItem::FatalError CSyncEnums::CSYNC_INSTRUCTION_NEW
2021-05-01 12:39:48:616 [ warning nextcloud.gui.activity ]:	Item  "1_Gemeinsam/11_Bibliothek"  retrieved resulted in  "Fehler beim Schreiben der Metadaten in die Datenbank"
2021-05-01 12:39:48:616 [ warning nextcloud.gui.activity ]:	Item  "1_Gemeinsam/11_Bibliothek"  retrieved resulted in error  "Fehler beim Schreiben der Metadaten in die Datenbank"
2021-05-01 12:39:48:616 [ info nextcloud.gui.activity ]:	Error successfully added to the notification list:  "Fehler beim Schreiben der Metadaten in die Datenbank"
2021-05-01 12:39:48:619 [ info nextcloud.gui.folderwatcher ]:	Detected changes in paths: QSet("D:/1_Gemeinsam/11_Bibliothek")
2021-05-01 12:39:48:619 [ debug nextcloud.gui.folder ]	[ OCC::Folder::slotWatchedPathChanged ]:	Changed path was touched by SyncEngine, ignoring: "D:/1_Gemeinsam/11_Bibliothek"
2021-05-01 12:39:48:619 [ warning nextcloud.sync.engine ]:	setDataFingerprint was overridden already for account "Ravenzwaaij@datenhalde.therapiecenter.org" on host "datenhalde.therapiecenter.org" but is failing again! Or, it's not the host that we are looking for.
2021-05-01 12:39:48:619 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path FROM conflicts"
2021-05-01 12:39:48:619 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "DELETE FROM flags WHERE path != '' AND path NOT IN (SELECT path from metadata);"
2021-05-01 12:39:48:619 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
2021-05-01 12:39:48:619 [ debug nextcloud.sync.database ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit "All Finished." 
2021-05-01 12:39:48:619 [ info nextcloud.sync.engine ]:	Sync run took  3203 ms
2021-05-01 12:39:48:654 [ info nextcloud.gui.folder ]:	Client version 3.2.1stable-Win64 (build 20210428)  Qt 5.12.9  SSL  OpenSSL 1.1.1g  21 Apr 2020
2021-05-01 12:39:48:654 [ warning nextcloud.gui.folder ]:	SyncEngine finished with ERROR
2021-05-01 12:39:48:654 [ info nextcloud.gui.folder ]:	Folder "" sync result:  OCC::SyncResult::SyncRunning
2021-05-01 12:39:48:654 [ info nextcloud.gui.folder ]:	the last 2 syncs failed
2021-05-01 12:39:48:654 [ debug nextcloud.gui.socketapi ]	[ OCC::SocketListener::sendMessage ]:	Sending SocketAPI message --> "UPDATE_VIEW:D:\\" to QLocalSocket(0x219787d5900)
2021-05-01 12:39:48:654 [ debug nextcloud.gui.socketapi ]	[ OCC::SocketListener::sendMessage ]:	Sending SocketAPI message --> "UPDATE_VIEW:D:\\" to QLocalSocket(0x2197b8b9f40)
2021-05-01 12:39:48:654 [ info nextcloud.gui.application ]:	Sync state changed for folder  "https://datenhalde.therapiecenter.org/remote.php/dav/files/Ravenzwaaij/" :  "Error"
```

**Comment by Lars1963** [comment]
@allexzander Any ideas on this. I can reproduce this on seperate 2 nc-installs with several win10-clients (Home and Pro, fully updated).

**Comment by tobru** [comment]
I'm seeing a similar issue on Nextclient client 3.2.1 on Linux:

```
2021-05-06 20:07:16:268 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote, contentChecksum, contentChecksumTypeId, e2eMangledName, isE2eEncrypted) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18);"
2021-05-06 20:07:18:270 [ warning nextcloud.sync.database.sql ]:	Sqlite exec statement error: 5 "database is locked" in "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote, contentChecksum, contentChecksumTypeId, e2eMangledName, isE2eEncrypted) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18);"
2021-05-06 20:07:18:270 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 "GroupFolder/mfile.pdf"
2021-05-06 20:07:18:270 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT lastTryEtag, lastTryModtime, retrycount, errorstring, lastTryTime, ignoreDuration, renameTarget, errorCategory, requestId FROM blacklist WHERE path=?1"
2021-05-06 20:07:18:270 [ warning nextcloud.sync.propagator ]:	Could not complete propagation of "GroupFolder/mfile.pdf" by OCC::PropagateDownloadFile(0x55f330caf960) with status OCC::SyncFileItem::FatalError and error: "Error writing metadata to the database"
2021-05-06 20:07:18:271 [ debug nextcloud.sync.statustracker ]	[ OCC::SyncFileStatusTracker::slotItemCompleted ]:	Item completed "GroupFolder/mfile.pdf" OCC::SyncFileItem::FatalError CSyncEnums::CSYNC_INSTRUCTION_CONFLICT
2021-05-06 20:07:18:271 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 6972173759921586598
2021-05-06 20:07:18:271 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path, inode, modtime, type, md5, fileid, remotePerm, filesize,  ignoredChildrenRemote, contentchecksumtype.name || ':' || contentChecksum, e2eMangledName, isE2eEncrypted  FROM metadata  LEFT JOIN checksumtype as contentchecksumtype ON metadata.contentChecksumTypeId == contentchecksumtype.id WHERE phash=?1"
2021-05-06 20:07:18:271 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 -4473702419529644197
2021-05-06 20:07:18:271 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path, inode, modtime, type, md5, fileid, remotePerm, filesize,  ignoredChildrenRemote, contentchecksumtype.name || ':' || contentChecksum, e2eMangledName, isE2eEncrypted  FROM metadata  LEFT JOIN checksumtype as contentchecksumtype ON metadata.contentChecksumTypeId == contentchecksumtype.id WHERE phash=?1"
2021-05-06 20:07:18:271 [ warning nextcloud.gui.activity ]:	Item  "GroupFolder/mfile.pdf"  retrieved resulted in  "Error writing metadata to the database"
2021-05-06 20:07:18:271 [ warning nextcloud.gui.activity ]:	Item  "GroupFolder/mfile.pdf"  retrieved resulted in error  "Error writing metadata to the database"
2021-05-06 20:07:18:271 [ info nextcloud.gui.activity ]:	Error successfully added to the notification list:  "Error writing metadata to the database"

```

**Comment by allexzander** [comment]
> @allexzander Any ideas on this? I can reproduce this on seperate 2 nc-installs with several win10-clients (Home and Pro, fully updated).

The root cause is much earlier in the logs:

`Initialization failed, couldn't connect sync root`

Currently, I am not sure why this happens, but, my teammate @mgallien may have some idea. I'll be checking this too in the meantime.

**Comment by allexzander** [comment]
@tobru

Is the error happening when the experimental VFS is enabled on Linux?

**Comment by tobru** [comment]
> Is the error happening when the experimental VFS is enabled on Linux?

I'm not sure about that, I haven't specifically configured anything in this regard. The GUI says: `Using virtual files plugin: suffix`.
Note: I'm using Arch Linux.

**Comment by allexzander** [comment]
> > Is the error happening when the experimental VFS is enabled on Linux?
> 
> I'm not sure about that, I haven't specifically configured anything in this regard. The GUI says: `Using virtual files plugin: suffix`.
> Note: I'm using Arch Linux.

@tobru if you try to add a new sync folder (the first one or more than one), you'll see "Virtual File System (Experimental)" radio button in GUI. But, since you haven't configured anything, this won't show up, and, this means your issue is not VFS specific. 

Would it be possible for you to create a separate issue with full logs attached? Seems like your issue is very different.

I am going to need full logs from you because I can't see any lines mentioning "placeholder" which is an indicator of having or not having a VFS enabled.

The log `Using virtual files plugin: suffix` is always being written, regardless of VFS enabled or not. It's just to indicate which plugin is currently supported.

**Comment by allexzander** [comment]
> @allexzander Any ideas on this? I can reproduce this on seperate 2 nc-installs with several win10-clients (Home and Pro, fully updated).

@Lars1963 

I think I've found the reason. I haven't noticed it before, because the error message is in German:

"Initialization failed, couldn't connect sync root: "Der Vorgang wird nur für Dateien in einem Stammverzeichnis für die Cloudsynchronisierung unterstützt.""

But now, I've translated it. So, looks like the VFS doesn't support selecting a sync folder as the root of the disk partition. In your config, I can see you've selected `D:/` as the local sync folder. I tried doing the same on my system, and I was able to reproduce the same issue with the same error: "The operation is only supported on files under a cloud sync root."

This is definitely an omission from our side which we are going to fix. Thank you for being persistent with this issue.

Now, just to confirm the workaround, could you try creating a subfolder in `D:/`? Something like `D:/Nextcloud_sync`, and then, will the issue be happening if you choose that path for your local sync folder?

**Comment by Lars1963** [comment]
@allexzander

Thanks for the follow up. I'll do as you suggested.

BTW: I didn't realize that the registry was involved, so I didn't cleanup it on a deinstall.🥴

To be completely sure, I'll setup an blank Server als well as a blank Windowsclient. We'll track this one done. 😄

**Comment by allexzander** [comment]
@Lars1963 Well, the Registry is for those Windows shell elements reporting progress and pin state to show up. They don't affect the issue much, just the indication. Looking forward to what the results of your test are, while preparing the fix.

**Comment by allexzander** [comment]
@Lars1963 
Frankly speaking, the entire thing of not being able to use VFS with partition root is a limitation of CfAPI by Microsoft. That's why they do not allow using a partition root with their OneDrive. They are always adding a subfolder to whatever folder one selects.

That's why, unfortunately, PR #3290 is a quick implementation of this limitation. Meaning that, if you want to use a root partition as a sync folder, you will not be able to use a VFS. A subfolder under D:/ in your case must be created. So, the PR is not a fix for the CfAPI limitation, but, it's rather an adjustment of the Nextcloud sync client to conform to that limitation.

Your case is quite rare, as, it is not often we face someone's using an entire drive partition as a sync root, but, this was a flaw in the sync folder connection logic that we're now fixing. Yet, this was a great opportunity for us to find out about this problem. So, your effort is really appreciated.

In regards to testing, it is not possible unless you build it, or, this will become available as a daily build next week if you're still interested in trying that after my explanation.

**Comment by PolyanskyAlex** [comment]
Hi!

Have same problem
Client version 3.2.1 X64 Win10 20H2
Crushes almost every time after 10 seconds work.
Path to Nextcloud folder is default, not whole partition.
Also tried VFS on/off, reinstall with fully delete all data in appdata and clear clean register - nothig changed...

[20210525_1648_owncloud.log](https://github.com/nextcloud/desktop/files/6539963/20210525_1648_owncloud.log)

**Comment by JustACasual** [comment]
@allexzander thank you very much for this explanation. Was investigating the whole day today as I was trying to achieve the exact same thing (sync home = D:) and it did not work. Now I understood this will sadly not be possible. Just letting you know, there are more people with this requirement ;)
But for now, thanks to your explanation, I will go for the subfolder
