### ISSUE TITLE
Client app crashes when click on status icon

### ISSUE THREAD

**Issue by helmut72** [nextcloud/desktop#4025]
### Expected behaviour
When clicking on status icon, Nextcloud Client shows a menu.

### Actual behaviour
When clicking on status icon, Nextcloud Client crashes. Behavior started after updating from 3.3.6 to 3.4.0 on my macOS Catalina. A downgrade of Nextcloud Client doesn't helped and even removing the configuration. After removing the configuration, initial wizard (Server URL, choose sync folders...) and syncing works, but Nextcloud Client crashes after clicking on status icon.

### Steps to reproduce
1. Start Nextcloud Client App
2. Click on status icon in the menubar

### Client configuration
Client version: 3.4.0

Operating system:
macOS 10.15.7 Catalina

OS language:
German

**Comment by helmut72** [comment]
When starting Nextcloud App from Shell it works until clicking on the status icon. Then it crashes and shows "abort trap: 6".

**Comment by fireeater112** [comment]
Same Behavior on W10 21H2. NC DT Client crashes right after systemstart

**Comment by helmut72** [comment]
No, syncing is working! Until I click on the status icon. 3.4.0 works on on macOS Montery, but not on Catalina. Also macOS and Windows is a bit different.

After deleting other files and folders in ~/Library called 'nextcloud', I got 3.3.6 working on Catalina.

**Comment by ilpssun** [comment]
Possible duplicate of #4024.

**Comment by helmut72** [comment]
looks like

**Comment by aakerbeere** [comment]
https://github.com/nextcloud/desktop/releases/download/v3.4.0/Nextcloud-3.4.0-x86_64.AppImage
seems to be ok (at least for me)

**Comment by helmut72** [comment]
problem happens on an older version of macOS, not Linux

**Comment by Tegenwind** [comment]
I encountered the same issue on a Catalina (10.15.7) machine. Sync works fine but when the icon is clicked it crashes.
When downgrading to 3.3.6 it works fine again.
This was on a headless Mac Mini, tested it on a MacBook Air (same OS version) and it works fine there.

**Comment by ilpssun** [comment]
For me, this behavior was fixed in 3.4.1.  The client is working fine now after the upgrade 3.3.6 → 3.4.1.

**Comment by Tegenwind** [comment]
I can also confirm the issue is fixed in 3.4.1.

**Comment by tfar** [comment]
This is reproducible for me on macOS 11.6.2 with version 3.4.1.8596 .

**Comment by helmut72** [comment]
Still the same error for me on macOS 10.15.7 Catalina with version 3.4.1

**Comment by khalsajing** [comment]
I wanted to post that on Microsoft Windows Version 21H2 (OS Build 22000.438) the desktop client keeps crashing. It would start a sync and stop after showing a few log files.  It shows in the taskbar corner icons, but when I mouse over to it, it disappears. Sorry, I won't be able to help troubleshoot. I'm outta the Windows world for now and wanted  to register this experience in case someone else faces this issue.

**Comment by helmut72** [comment]
Still the same error on macOS 10.15.7 Catalina with version 3.4.2

**Comment by tfar** [comment]
Can people still reproduce this issue with the 3.4.3 release? Asking to avoid automatic closure of this ticket.

**Comment by tfar** [comment]
> For me, this behavior has been fixed since 3.4.1. Version 3.4.3 is working fine, too.
@ilpssun what OS and OS version? Other people saw the bug on macOS 10.15.7.

**Comment by ilpssun** [comment]
I'm on macOS 10.15.7 (latest version supported by my current hardware).  I'm using a MacBook Air Mid-2012.

**Comment by helmut72** [comment]
Works for me on macOS 10.15.7 with 3.4.3. Looks like I've opened the issue, will close it.

Thank you! :)
