### ISSUE TITLE
Fixed mtimes (resulting from #4016) do not show in desktop client

### ISSUE THREAD

**Issue by PhilippSchlesinger** [nextcloud/desktop#4188]
Remainder from
https://github.com/nextcloud/desktop/issues/4016

Client version 3.4.1, still present in 3.5.0

My managed nextcloud provider fixed our nextcloud via https://github.com/nextcloud/desktop/wiki/How-to-fix-the-error-invalid-or-negative-modification-date.

The result is very good, the files got their mtimes back, thank you very much for your great work on fixing this.
There is a little issue nevertheless. The (fixed) mtimes do not get propagated to the desktop client with virtual files enabled _unless_ files are hydrated (downloaded on demand) or marked as 'always keep on device':

![grafik](https://user-images.githubusercontent.com/2735628/149936011-6cb2cd43-8a76-4887-816d-2265072c0ea3.png)

If I open a file without visible timestamp, the file downloads normally and afterwards you see a timestamp in explorer (after crtl+r).

_Originally posted by @PhilippSchlesinger in https://github.com/nextcloud/desktop/issues/4016#issuecomment-1015362785_

**Comment by Tie-fighter** [comment]
Can confirm.

**Comment by PhilippSchlesinger** [comment]
@Tie-fighter
I cannot check for some days if the error message appears. But I don't think so as the timestamp fix got applied by the hoster.
It is rather a problem about not syncing placeholder files to valid timestamps available on the server.

**Comment by PhilippSchlesinger** [comment]
@mgallien: I'd be happy to share my logs. As the logs contain confidential information, how can I provide the logs privately?

**Comment by PhilippSchlesinger** [comment]
The issue is still present with nextcloud client 3.4.4.
The client seems not to fetch the corrected and now valid timestamps for virtual files.

@mgallien: I'd be happy to provide more information to this issue.
Could you please guide me which information and how to provide logs in a private manner, as the logs contain confidential information.

**Comment by jaredthirsk** [comment]
Is this fixed in 3.5.0?

**Comment by PhilippSchlesinger** [comment]
The issue is still present with nextcloud client 3.5.0.
The client seems not to fetch the corrected and now valid timestamps for virtual files.

Please reopen.

**Comment by PhilippSchlesinger** [comment]
@jaredthirsk @mgallien The issue is still present in nextcloud client version 3.5.1.
Please re-open the issue, thx.

**Comment by PhilippSchlesinger** [comment]
The issue is still present in nextcloud client version 3.5.2

**Comment by PhilippSchlesinger** [comment]
The issue is still present in nextcloud client version 3.5.4

**Comment by PhilippSchlesinger** [comment]
@claucambra How to permanently block this issue from getting staled? Thx.

**Comment by PhilippSchlesinger** [comment]
The issue is still present in nextcloud client version 3.6.0

**Comment by PhilippSchlesinger** [comment]
@mgallien
As this issue probably resulted from #4016 that has been fixed long ago:
Would it be save to delete .sync_xxxxxxx.db (like in https://docs.nextcloud.com/desktop/3.6/troubleshooting.html#csync-unknown-error) when using virtual files?

**Comment by PhilippSchlesinger** [comment]
> @mgallien As this issue probably resulted from #4016 that has been fixed long ago: Would it be save to delete .sync_xxxxxxx.db (like in https://docs.nextcloud.com/desktop/3.6/troubleshooting.html#csync-unknown-error) when using virtual files?

I circumvented this by removing/re-adding the sync folder in the affected client.
After a complete resync of the VFS inodes, the problem was gone at least for me. All files in Windows Explorer got there actual timestamps. (and, as a side note, file thumbnail provider released with 3.6.0 started to work).

As I just fixed the results of this bug in the affected instance of the client and the initial issue is not fixed by that, I close this issue as "not planned".
