### ISSUE TITLE
fix behavior on "update and restart"

### ISSUE THREAD

**Issue by r2evans** [nextcloud/desktop#4377]
### Expected behaviour

On most applications, when they announce that there is an update available, "update and restart" implies a restart of the *application*. In the exception where it requires a restart of Windows, they tend to turnover the restart process to Windows itself, where it warns about open applications, unsaved documented, and even gives you the opportunity to cancel the restart process.

### Actual behaviour

In this case, "restart and update" [used to *just* crash `explorer.exe`](https://github.com/nextcloud/desktop/issues/3131) (which, while it can be disrupting and certainly annoying, other applications are typically not force-closed). Now (Win11), pressing the button immediately goes to a black screen that says "Restarting..." and gives no such warning or cancel/save/close opportunity. Here it is no longer a nuisance, it is a ***data-losing, process-breaking operation***.

### Steps to reproduce
1. With 3.4.3 installed, check `Settings...` and click on "Update and restart".

### Client configuration
Client version: 3.4.3 upgrading to 3.4.4

Operating system: Win11

OS language: English

Installation path of client: `C:\Program Files\Nextcloud`

### Server configuration

Nextcloud version: 23.0.0

Storage backend (external storage): n/a

**Comment by ThatCoffeeGuy** [comment]
Really concerning how it still requires a full machine restart in 2022.

**Comment by r2evans** [comment]
I feel that ignoring an issue until the bot closes it is not the best resolution. Does one of the NC developers have thoughts on this?

**Comment by max65482** [comment]
I didn't experience the issue when upgrading to 3.5.0 anymore. Instead, #4305 happened.

**Comment by dedors** [comment]
I got a popup that a new version is available. After it installed, my computer (win11) just did a force-reboot, ignoring all unsaved open documents.

**Comment by raimund-schluessler** [comment]
> I got a popup that a new version is available. After it installed, my computer (win11) just did a force-reboot, ignoring all unsaved open documents.

Same for me here. On Win 10 installing Client 3.5 first closed (crashed?) the explorer and then just restarted the whole PC without a warning (or saving any documents).

**Comment by staples1347** [comment]
I also just had this problem with Windows 10.  Here is the Event Log entry:
The process msiexec.exe has initiated the restart of computer <myhostname> on behalf of user NT AUTHORITY\SYSTEM for the following reason: No title for this reason could be found
 Reason Code: 0x80030002
 Shut-down Type: restart
 Comment: The Windows Installer initiated a system restart to complete or continue the configuration of 'Nextcloud'.

**Comment by r2evans** [comment]
Yeah, I tend to think that whether or not NC desktop updates should _require_ a reboot, I think the method being used is unforgiving (two different discussions): most times when I need a reboot for a driver update, there's a bit of back-and-forth between the OS and me saying apps are open and such, but the NC reboot process seems as if it's passed as super-urgent-reboot-right-this-minute. NC devs (notably silent on this issue), please look into softening the reboot mechanism.

**Comment by Andrysky** [comment]
this behavior (rebooting without user permission) was acceptable in the days of win xp, but now it is unacceptable!🤬

**Comment by Tie-fighter** [comment]
This is really not ok.

**Comment by r2evans** [comment]
I feel that ignoring an issue until the bot closes it is not the best resolution. Does one of the NC developers have thoughts on this?

I'll continue the commentary that in the current state of OSes, In 2022 there should be no reason for an app like this to require a full restart. As examples: [PowerToys](https://github.com/microsoft/PowerToys) and [Git-for-Windows](https://github.com/git-for-windows/git/) also integrate with Windows Explorer, and neither requires a restart. It is "inconvenient" (at best) that NC desktop client requires a restart allegedly for something that other tools worked out long ago.

Both of those tools are open-source, perhaps an NC-desktop dev can reach out for help and/or look at the code to see what is different? I recognize it's not always that simple, but it's a big deal to some people to have to reboot (for this) and disrupt whatever is currently running. (As an analyst, it's not uncommon for me to have processes running for days with no simple way to snapshot in an interim state. I don't believe that my use is the only or predominant use-case.)

**Comment by SommerEngineering** [comment]
Today I applied the update to 3.5.2 on Windows 11, and it happend again 😠 No fix, no reaction from the developers 🙁

**Comment by claucambra** [comment]
Hi folks, closing since this should be fixed for new updates on versions past 3.5.2 . Thanks for reporting!

**Comment by jernejs** [comment]
I just had NextCloud 3.5.3 update restart my Windows without any warning. The bug is not fixed.

**Comment by Denizzje** [comment]
> Hi folks, closing since this should be fixed for new updates on versions past 3.5.2 . Thanks for reporting!

It is not. I got prompted for 3 .5.3 update, and I pressed X to close it. It then started updating anyways, and rebooted my PC. Lost quite some work. Thanks man, great "feature".

**Comment by claucambra** [comment]
It seems like the fix for this issue was not back ported and is not a part of the 3.5 branch. This means that a fix should be present in the next release (likely 3.6.0). More here: https://github.com/nextcloud/desktop/issues/3551#issuecomment-1200101476

**Comment by jernejs** [comment]
3.5.4 was released today and it again rebooted my computer without any warnings.

**Comment by claucambra** [comment]
> 3.5.4 was released today and it again rebooted my computer without any warnings.

3.5.4 was explicitly released to fix this issue -- this means the reboots should stop happening on updates beyond 3.5.4

**Comment by r2evans** [comment]
I'm opening a new issue, since this issue is closed and the issue (with 3.8) is still there.

**Comment by RoyalCyan** [comment]
> 

I don't know about it being fixed. I have Nextcloud version 3.8.1 and it still asked me to restart my whole PC in order to finish the updtae.

**Comment by shufflerror** [comment]
Still a thing on update to 3.11.0 on Win 10 - first asks to restart Explorer than restarts the whole system

**Comment by platnub** [comment]
One year later. Still a problem. I remember reading an open issue about like something like 4 years ago when the developers mentioned they would look into it. I cannot believe this is **still** an issue. Wild
