### ISSUE TITLE
[Bug]: Couldn't convert to placeholder

### ISSUE THREAD

**Issue by geeklihui** [nextcloud/desktop#4401]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I added some files on 2022-03-25 and most of them are working fine, but 564 of them have been synced repeatedly by the client over and over again.

By comparing the SHA-1 checksum with webUI and local files, I can confirm that the files have actually been synced successfully.

The process of synchronizing these files by the client is: syncing in progress, syncing error, syncing successful. Then after a while it starts syncing again: syncing in progress, syncing error, syncing successful. As shown in the figure below.
<img width="233" alt="19fd3ae2341fbcb35d5ea23fa254f53" src="https://user-images.githubusercontent.com/28993319/161047538-0879d73f-58ac-4a26-80d9-be2475db6cd4.png">
<img width="223" alt="341187361649932a34c626ec0390892" src="https://user-images.githubusercontent.com/28993319/161047548-ea93a536-66a0-449d-a86c-1b867ee71c07.png">
<img width="224" alt="4a8022da76741a233ddd56cbee2dd43" src="https://user-images.githubusercontent.com/28993319/161047561-a07e7916-ebfe-453f-8546-ae7e00631d3a.png">

When I open the settings during the sync, I can see two prompts: one says "downloading files" and the other says "unable to upload files".
<img width="898" alt="1a3e6520c49a2d0c64b93622b0ae389" src="https://user-images.githubusercontent.com/28993319/161047670-c3fc56cd-cae7-4cd5-af90-2af7b3f27701.png">

In Windows Explorer, the status of these files is "Synchronization is pending".
![image](https://user-images.githubusercontent.com/28993319/161047740-55db8f9b-d04c-468b-b2e5-d176c8a38174.png)

I have exported the logs and the database to a zip file via https://docs.nextcloud.com/desktop/3.4/troubleshooting.html#create-debug-archive. Considering privacy, please give me an email address to send logs and affected file list.

### Steps to reproduce

Just open the desktop client.

### Expected behavior

1. The 564 files should not be transferred any more. 
2. The files status in Windows Explorer should be "OK" rather than "Synchronization is pending".

### Which files are affected by this bug

Considering privacy, I'll provide file list and logs via email, please give me an address.

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Official SNAP package

### Nextcloud Server version

23.0.3

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
Nothing special in data/nextcloud.log. I met this issue just from 2022-03-25, but the latest log is on 2022-03-06.
Nothing special in /settings/admin/logging either. Today I met this issues many times, but the latest log is on 2022-03-29.
```

**Comment by geeklihui** [comment]
Can anyone help me? It really annoyed me.

**Comment by rajendradewani** [comment]
We are also facing the same issue.
Removing files, force sync and re-adding files did not help.

Any suggestion or workaround is appreciated.

**Comment by jvalskis** [comment]
Having the same issue. In my case, I added a symbolic link to sync an additional folder that is outside of `/Nextcloud`.

VFS is turned on. Tried turning it off like it was suggested in #3198, but then the linked folder was not synced at all.

**Comment by D1StrX** [comment]
There is an additional issue with the `cannot replace non-existing placeholder` error. When replacing all files in a folder, when not all files are downloaded and locally available, it cannot upload/overwrite the files in the cloud. Thus not sync. 

Expected behavior is to overwrite everything in the cloud that has been overwritten locally. 
Windows 10 - NC Dekstop client v3.6.0

**Comment by GAPPSRefusenik** [comment]
> Do you still have this issue with 3.8.1?

Indeed I have. Just updated to 3.8.1. in hopes that this would have gotten resolved by now. Before this update, I reverted to 3.3.6 after a more recent version had caused the deletion of the affected 'non-placeholder' file and its parent folder. At least with 3.3.6, and now 3.8.1 no files have been deleted anymore, although I did spot the affected folder in the Nextcloud recycle bin the other day. The folder and all of its contents however remain intact on my client machines, so at the moment I can cope with the situation.

It might be of notice that the affected file is a KeePass database that is kept open for most of the time, and changed on several clients that are running simultaneously. This seems to cause irritation on the sync process. My approach to temporarily resolve the issue is to manually sync KeePass database files on all machines, and then transfer on of them to the server, overwriting the previous file.

**Comment by D1StrX** [comment]
Can confirm, the issue still exists in 3.8.**2**

![image](https://github.com/nextcloud/desktop/assets/40062371/68618f83-f8b6-4b6e-bbf9-0c63e9fd95f2)

**Comment by HEtchevers** [comment]
This issue STILL exists with a slightly different error message in version 3.9.1: Couldn't update placeholder info. It has happened for all of my nearly 6000 files and they all try to synchronize constantly and fruitlessly. They seem to be present on the server though.

![image](https://github.com/nextcloud/desktop/assets/45430373/92ff8771-018b-4a09-b17f-445947be5407)

**Comment by Ed1ks** [comment]
Same error after updating to 3.10

**Comment by MartinDerHettich** [comment]
A User of my NextCloud is affected since 2023-11. No synchronisation of her local files (see screenshot), the error message 'Couldn't convert to placeholder' on the client, no error message on the server, current version Nextcloud Desktop-Client 3.11.0. Yes, we tried every obvious instance of "Have you tried turning it off and on again?".

![NextCloudBug#4401_NewUserSJ2023-11_2024-01](https://github.com/nextcloud/desktop/assets/125260676/14caac8f-8a49-43ba-8710-12b6cdf96432)

**Comment by MartinDerHettich** [comment]
A remark to OP and Admins:

"5 of 8 tasks" is misleading, because checking a box right there is obviously optional:

    Are you using an external user-backend?
    [x] Default internal user-backend
    [ ] LDAP/ Active Directory
    [ ] SSO - SAML
    [ ] Other

Answering this question should be 1 (One) task, not 4.

**Comment by aiso-net** [comment]
Same issue here, but need VFS ability since the desktop doent have the needed free space, so need it to be all virtual, need this fixed ASAP.

**Comment by FloTheSysadmin** [comment]
Same issue here

**Comment by bMorgan01** [comment]
+1 to @aiso-net. Please fix asap.

**Comment by paddelboot** [comment]
This issue has suddenly appeared for me too,

![image](https://github.com/user-attachments/assets/041a6e10-eac5-4da3-9748-1a44242a7965)

Nextcloud Desktop-Client 3.14.1
Microsoft Windows 11 Pro 10.0.22631 Build 22631

**Comment by Medius7** [comment]
I activated the virtual file support; then, I got these messages. From the windows notification i knew, that over 20,000 files are affected.
![Image](https://github.com/user-attachments/assets/0ed47cab-277d-4a62-a2c0-e9c09630abd2)

**Comment by mmitech** [comment]
Having the same issue here as well

**Comment by ThaDaVos** [comment]
Is there a fix for this? I am running into this too and it's pretty cumbersome

**Comment by Medius7** [comment]
> Is there a fix for this? I am running into this too and it's pretty cumbersome

Just to give an feedback: I was not able to find any way to sync my data with virtual files.
After "deactivate virtual files" again, everything works fine. But it's not satisfying, because I had to delete huge parts of my nextcloud data.

**Comment by dkiper** [comment]
There is pretty good chance it is due to stopped/broken/... CldFlt service ([Windows Cloud Files Filter Driver](https://batcmd.com/windows/10/services/cldflt/)). The Nextcloud Windows Desktop client VFS implementation depends on it.

You can check CldFlt service runs using following command: `sc query CldFlt`

```shell
C:\>sc query CldFlt

SERVICE_NAME: CldFlt
        TYPE               : 2  FILE_SYSTEM_DRIVER
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

The `sc qc CldFlt` will give you more information about the CldFlt service.

```shell
C:\>sc qc CldFlt
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: CldFlt
        TYPE               : 2  FILE_SYSTEM_DRIVER
        START_TYPE         : 2   AUTO_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   : system32\drivers\cldflt.sys
        LOAD_ORDER_GROUP   : FSFilter HSM
        TAG                : 1
        DISPLAY_NAME       : Windows Cloud Files Filter Driver
        DEPENDENCIES       : FltMgr
        SERVICE_START_NAME :
```

The `START_TYPE` should be set to `AUTO_START` or `2`. If it is not then run `sc config CldFlt start= auto` command (note space after equal sign) and restart your machine.

**Comment by AlexeyQ13** [comment]
> There is pretty good chance it is due to stopped/broken/... CldFlt service ([Windows Cloud Files Filter Driver](https://batcmd.com/windows/10/services/cldflt/)). The Nextcloud Windows Desktop client VFS implementation depends on it.
> 
> You can check CldFlt service runs using following command: `sc query CldFlt`
> 
> C:\>sc query CldFlt
> 
> SERVICE_NAME: CldFlt
>         TYPE               : 2  FILE_SYSTEM_DRIVER
>         STATE              : 4  RUNNING
>                                 (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
>         WIN32_EXIT_CODE    : 0  (0x0)
>         SERVICE_EXIT_CODE  : 0  (0x0)
>         CHECKPOINT         : 0x0
>         WAIT_HINT          : 0x0
> The `sc qc CldFlt` will give you more information about the CldFlt service.
> 
> C:\>sc qc CldFlt
> [SC] QueryServiceConfig SUCCESS
> 
> SERVICE_NAME: CldFlt
>         TYPE               : 2  FILE_SYSTEM_DRIVER
>         START_TYPE         : 2   AUTO_START
>         ERROR_CONTROL      : 1   NORMAL
>         BINARY_PATH_NAME   : system32\drivers\cldflt.sys
>         LOAD_ORDER_GROUP   : FSFilter HSM
>         TAG                : 1
>         DISPLAY_NAME       : Windows Cloud Files Filter Driver
>         DEPENDENCIES       : FltMgr
>         SERVICE_START_NAME :
> The `START_TYPE` should be set to `AUTO_START` or `2`. If it is not then run `sc config CldFlt start= auto` command (note space after equal sign) and restart your machine.

It worked! Huge thanks to @dkiper for the solution. I started the service using the provided command, restarted my PC, and then successfully completed the sync. The issue was indeed with the CldFlt service. Really appreciate the clear explanation and steps!

**Comment by aryo-sr** [comment]
Regarding @dkiper workaround, in Windows 11 24H2, I can't find `CldFlt` service or even `FltMgr` that said to be the dependency. In registry, though, `CldFlt` exists and looks fine with auto start value 2, while `FltMgr` is quite sus which even doesn't have proper name and description.

Btw, I got this issue where the file is also belongs to a folder of google drive desktop mirrored sync. My workaround is to rename the file and rename it back.

**Comment by mgallien** [comment]
closing for now
this was reported on a much old release
please test the new releases (3.17.1 would be the best) and open new issues if needed
@ricky0829 thanks for the report and I am sorry for the delay
I am pretty much confident that the issue is now fixed

**Comment by Splinter9410** [comment]
@mgallien im facing the same issue today using v4.0.6 (Windows).

**Comment by godfuture** [comment]
Yet another issue with Nextcloud client. I run 33.0.2 and get "Couldn't convert to placeholder". 

Both clients, android and windows, never really felt stable. Dont get fooled by release branch name ;-)
