### ISSUE TITLE
[Bug]: After upgrading to the latest version, it force rebooted my machine without asking for any permission to do so, resulting in data-loss once again. 

### ISSUE THREAD

**Issue by ThatCoffeeGuy** [nextcloud/desktop#4524]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After upgrading to the latest version, it force rebooted my machine without asking for any permissions, resulting in data-loss once again. 

### Steps to reproduce

1. Once you booted up your machine, nextcloud is going to offer the upgrade.
2. Click on OK \ upgrade (can't exactly recall)
2. See your machine being force-rebooted without permission, making you lose data and unsaved documents

### Expected behavior

It shouldn't force-reboot my machine without permission under any circumstances. 

### Which files are affected by this bug

Nextcloud desktop 

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 

### Package

Appimage

### Nextcloud Server version

23.0.4

### Nextcloud Desktop Client version

3.5.0

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ThatCoffeeGuy** [comment]
And I am not the only one for sure.

https://github.com/nextcloud/desktop/issues/4377#issuecomment-1125024604

**Comment by ldoyle** [comment]
+1, did not expect the reboot without further prompt or option to defer to later, interrupted my current work. Most programs manage to display an option "Now or later (manually)", which would be highly appreciated here!

**Comment by Weishaupt** [comment]
Unfortunately I had the same "experience". A forced reboot without any prompt.

The event log for me reads:

MsiInstaller:
> Beginning a Windows Installer transaction: C:\Users\\$USER\AppData\Roaming\Nextcloud\Nextcloud-3.5.0-x64.msi. Client Process Id: 18500.

RestartManager:
> **Warning**: Application 'C:\Windows\explorer.exe' (pid 7664) cannot be restarted - Application SID does not match Conductor SID..

> Machine restart is required.

> Shutting down application or service 'Windows Explorer'.

MsiInstaller: 
> Windows Installer requires a system restart. Product Name: Nextcloud. Product Version: 3.4.4.20220318. Product Language: 1033. Manufacturer: Nextcloud GmbH. Type of System Restart: 1. Reason for Restart: 2.

> Product: Nextcloud -- Installation completed successfully.

> Windows Installer installed the product. Product Name: Nextcloud. Product Version: 3.5.0.20220502. Product Language: 1033. Manufacturer: Nextcloud GmbH. Installation success or error status: 0.

> Windows Installer requires a system restart. Product Name: Nextcloud. Product Version: 3.5.0.20220502. Product Language: 1033. Manufacturer: Nextcloud GmbH. Type of System Restart: 1. Reason for Restart: 2.

> Ending a Windows Installer transaction: C:\Users\\$USER\AppData\Roaming\Nextcloud\Nextcloud-3.5.0-x64.msi. Client Process Id: 18500.

> The Windows Installer initiated a system restart to complete or continue the configuration of 'Nextcloud'.

**Comment by Weishaupt** [comment]
Also mentioned here https://github.com/nextcloud/desktop/issues/831#issuecomment-1126699368

**Comment by ThatCoffeeGuy** [comment]
3.5.1 just done the same "it may be required to reboot your machine" "OK" and just force reboots.

**Comment by Tie-fighter** [comment]
This is really not ok.

**Comment by SirScythe** [comment]
Same issue here with the latest update on Windows 11

**Comment by pfeiferocks** [comment]
The same happend to me with the last 2 updates :/

Logfile Update from 3.5.0 to 3.5.1
[msi.log](https://github.com/nextcloud/desktop/files/8732674/msi.log)

**Comment by Gunsmithy** [comment]
Even clicking on the X on the prompt at boot still proceeds with the update and reboot.  
The verbiage even says "may reboot" your computer but the past 2 updates at least it has.  
If a reboot is truly necessary for the update, it should at least be able to deferred like any other installer does, or the update itself should be able to be deferred, as there is currently no way to do so other than ignoring the popup until you're ready.

**Comment by Gunsmithy** [comment]
Potentially fixed by [this commit?](https://github.com/nextcloud/desktop/commit/e40142847b0b66182904eea9c61c8483c6b59f96)

**Comment by bobbolous** [comment]
+1, same here

**Comment by Kraligor** [comment]
Same here. Could the reboot function please be disabled completely? An info "Reboot may be required to ensure full functionality" or similar after update should be enough.

**Comment by adripo** [comment]
Still happening

**Comment by twomoses** [comment]
I just got the same thing... It also seemed to crash Explorer during the installation process as my task bar vanished and only `CTRL-ALT-DEL `or `CTRL-SHIFT-ESC` worked until the reboot. Definitely odd behavior in my opinion.

**Comment by francofischer** [comment]
+1

**Comment by gbakeman** [comment]
Just had this happen with the 3.5.2 update. I've never seen Nextcloud do this before.

**Comment by LicoMonch** [comment]
> Just had this happen with the 3.5.2 update. I've never seen Nextcloud do this before.

me too, all (at least) last three updates (triggered via settings panel) did an unauthorized reboot .. that really has to stop
it's like playing russian roulette with my data and open programs 😥 

What I can read from event viewer:
The update succeeded but explorer.exe could not be restarted, so the system or installer decided somehow that a total reboot is required and did init that without asking.

I guess, there is a little switch: "ask for reboot if needed" and "reboot if needed" .. pls disable the 2nd one 😜

**Comment by LicoMonch** [comment]
just found my installer log ([msi.log](https://github.com/nextcloud/desktop/files/9041988/msi.log))
which states
```
MSI (s) (5C:38) [21:09:41:285]: Command Line: REBOOTPROMPT= REBOOTPROMPT=S CURRENTDIRECTORY=C:\WINDOWS\System32 CLIENTUILEVEL=2 CLIENTPROCESSID=17112
[..]
MSI (s) (5C:38) [21:09:44:229]: PROPERTY CHANGE: Adding REBOOTPROMPT property. Its value is 'S'.
```
see https://docs.microsoft.com/en-us/windows/win32/msi/rebootprompt
which tells you that this setting will force a reboot if the installer thinks it's needed

**Comment by LicoMonch** [comment]
A deeper search revealed https://github.com/nextcloud/desktop/issues/3551 where the author of https://github.com/nextcloud/desktop/pull/4566 states in https://github.com/nextcloud/desktop/issues/3551#issuecomment-1131490648 the fix works after upgrading to 3.5.2 .. which I did today

as I did not find away to redo the update via settings panel, I'll wait for 3.5.3 and see what's happening on that update

**Comment by ThatCoffeeGuy** [comment]
Today's update just did the same. Will add version later.

**Comment by jglitsch** [comment]
Just had that experience once again (had this before and was hoping it would not happen again) with the update to Windows client version 3.5.2 on Windows 10. If this remains the default behavior the Nextclout client is not helpful, but a serious data safety risk! NOT COOL!
Additional info:
- The update prompt basically says that the installer may ask for additional permissions during installation. That's it. Not info on an intended reboot.
- The computer just instantly reboots after the installation has been completed.

**Comment by jglitsch** [comment]
Apparently it should be fixed for the next updates...
"TL;DR; Expect the reboot issue to be fixed after updating to 3.5.2 and onwards." ( https://github.com/nextcloud/desktop/issues/3551#issuecomment-1131490648 )

**Comment by adripo** [comment]
> Just had that experience once again (had this before and was hoping it would not happen again) with the update to Windows client version 3.5.2 on Windows 10. If this remains the default behavior the Nextclout client is not helpful, but a serious data safety risk! NOT COOL! Additional info:
> 
> * The update prompt basically says that the installer may ask for additional permissions during installation. That's it. Not info on an intended reboot.
> * The computer just instantly reboots after the installation has been completed.

I can confirm, version 3.5.2 still reboots windows without a proper prompt.

**Comment by SamSirry** [comment]
The collateral damage this caused me today is very frustrating. The incompetence in the way this installer behavior is implemented .... is hurting me.

**Comment by claucambra** [comment]
Hi folks, this has been fixed with #3551 and the force reboots should stop happening on updates after version 3.5.2 . Thanks all for reporting!

**Comment by sryze** [comment]
@claucambra It happened to me during upgrade from 3.5.1 to 3.5.2 - is this normal?

**Comment by LicoMonch** [comment]
I was on 3.5.2 and got 3.5.3 today.
Guess what happened at install time?

Yeah, you got it: forced reboot without a warning

It seems, that's still not fixed -.-'

**Comment by claucambra** [comment]
It seems like the fix for this issue was not back ported and is not a part of the 3.5 branch. This means that a fix should be present in the next release (likely 3.6.0). More here: https://github.com/nextcloud/desktop/issues/3551#issuecomment-1200101476

**Comment by ThatCoffeeGuy** [comment]
> It seems like the fix for this issue was not back ported and is not a part of the 3.5 branch. This means that a fix should be present in the next release (likely 3.6.0). More here: [#3551 (comment)](https://github.com/nextcloud/desktop/issues/3551#issuecomment-1200101476)

Thank you! Today it just force-rebooted again, so since this bugfix will only appear in the next release (???????) I am simply uninstalling it and waiting until 3.6.0. 

Is there any info on when 3.6.0 will be live?

**Comment by twomoses** [comment]
@ThatCoffeeGuy, I came here with the **exact same experience** just a couple of minutes ago. Honestly, I'm ready to disable automatic updates, but after reading the recent comments on #3551, I will give it one last try.

[This comment](https://github.com/nextcloud/desktop/issues/3551#issuecomment-1203608570) in particular states that this last reboot was to actually deploy the fix, and it shouldn't happen again.

**Comment by claucambra** [comment]
We released an interim update (3.5.4) specifically to include the patch to stop force-updating. This means that future updates should no longer force reboot. Apologies for the annoyance -- forced reboots should not happen any longer

**Comment by adripo** [comment]
Thank you, let's hope to solve this issue with the next version.

**Comment by allexzander** [comment]
> interim

More specifically, this will start to work normally when updating from 3.5.4 and up. If you want to avoid rebooting when updating to 3.5.4, you need to run the MSI manually. The calling code is a part of the desktop client, so, it is something we have to deal with only this time.
