### ISSUE TITLE
BUG: Installer/update reboots Windows WITHOUT CONFIRMATION

### ISSUE THREAD

**Issue by mailinglists35** [nextcloud/desktop#5098]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

![Uploading 4A7D839F-FA9D-4B52-B439-D43DC3C4DF6A.jpeg…]()

### Steps to reproduce

download installer when prompted

start upgrade process but choose to not restart

open nextcloud

installer shows update dialog

THEN REBOOTS THE MACHINE WITHOUT USER CONFIRMATION

I'VE LOST HOURS OF WORK BECAUSE OF YOU 🤬🤬🤬🤬🤬🤬🤬

### Expected behavior

NEVER DO REBOOTS UNLESS USER CONFIRMED

### Which files are affected by this bug

I don't know

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 latest

### Package

Distro package manager

### Nextcloud Server version

not relevant

### Nextcloud Desktop Client version

I don't know what was installed

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
not relevant
```

**Comment by mailinglists35** [comment]
![6E49D7BE-ABA6-4E9E-B245-AE863CE311E8](https://user-images.githubusercontent.com/2054302/198021429-7e14d46b-7629-4e51-9965-bad636f8bf9e.jpeg)

**Comment by andyxheli** [comment]
@mailinglists35 this was fixed please see https://github.com/nextcloud/desktop/pull/4799

**Comment by r2evans** [comment]
@andyxheli  nope, still reboots (on update) with version 3.6.1. This is likely a dupe of #4377, which unfortunately was closed due to inactivity (and lack of acknowledgement by NC?).

**Comment by andyxheli** [comment]
That wired! I just upgraded to 3.6.1 from 3
6.0 and it didn't reboot? I know I hot rebooted when I upgraded from 3.5.x then it stopped for me

**Comment by chk1** [comment]
Happened to me today as well, when I upgraded from 3.5.1 to 3.6.1 initiated via the Nextcloud application settings update check.

**Comment by andyxheli** [comment]
I think that because you
Upgraded from 3.5.1 and the patch was applied on 3.5.3 or 3.5.4 I believe if you where on 3.5.3 or 4 then you upgraded to 3.6.x I shouldn’t have rebooted. Because when I upgraded from 3.5.1 to 3.5.3 or 4 it rebooted then after it stoped rebooting and asked me if I want to reboot and I’ve had the same results on 20 plus computers. See what happens when they release the next version if it still reboots there something is definitely wrong.

Sent from my iPhone

On Oct 30, 2022, at 9:40 PM, Christoph Kisfeld ***@***.***> wrote:

﻿

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Happened to me today as well, when I upgraded from 3.5.1 to 3.6.1 initiated via the Nextcloud application settings update check.

**Comment by claucambra** [comment]
This has been fixed, but the patch is only available since 3.5.4 -- meaning upgrades from earlier versions unfortunately still exhibit this behaviour.

However, since this issue has been fixed for the past 3 versions, I will close. Thanks for reporting!

**Comment by r2evans** [comment]
Not resolved.

I just updated a win10 client running nextcloud desktop 3.3.6 to 3.6.1, and it did not reboot the computer. Yay!

However, several days ago I uploaded a win11 client running desktop 3.6.0 to 3.6.1 and it forced a reboot.

@claucambra can you please confirm that the testing environment includes both win10/win11 and minor-version update versus patch-release upgrade?

**Comment by andyxheli** [comment]
I just update from 3.6.0 to 3.61 on Windows 11 and it did not force a reboot.

**Comment by r2evans** [comment]
To be clear: the win10 update (3.3.6 to 3.6.1) did not even suggest a reboot. The win11 (3.6.0 to 3.6.1) required a reboot to work, though it did say that it would reboot. It was not a choice, but at least it gave me an opportunity to save all work, which is an improvement from the original behavior.
