### ISSUE TITLE
[Bug]: Nextcloud client generates >100 GB worth of log files every day (800MB per sync run).

### ISSUE THREAD

**Issue by retnag** [nextcloud/desktop#5302]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

First of all, thank you for developing this awesome and completely "free" home cloud solution! I use it on a daily basis.

Perhaps I'm alone with this, but my Nextcloud client generates >100 GB (800MB per sync run) worth of log files every day. I use an SSD; therefore this behaviour is seriously and unnecessarily (I never read these logs) reducing the lifespan of my hardware, as you surely know, SSD-s can be written to only a limited amount of times.
I am on Windows and using Virtual files support, so every file in the cloud gets a go for sync. 

I have worked around this problem temporarily, by removing write permissions for every user for the logs folder, but now I get a pop-up Error from the client every half an hour or so, therefore I'm not satisfied with this solution. I had added the permissions back while writing this review, it generated 2.25 GB worth of logs in just 20 minutes. That's 162 GB of unnecessary data a day, contributing 57 TB a year, seriously bad for your SSD! That alone consumes an average SSD with 100TBW in less than 2 years!

### Possible solution suggestions/ideas:
Cheap: I suggest adding an option in the client settings to disable the saving of log files on disk. And/Or, alternatively, add an option to save the logs in a compressed file format.
More time consuming, but better alternative: add an option for the verbosity of the logs, with the usual options for the loglevel: "debug" (the current behaviour), "only errors" - only logs **unexpected** errors, 

The logs are VERY verbose, here is an excerpt: 
```
2022-12-31 10:03:41:389 [ debug nextcloud.sync.database.sql C:\Users\sysadmin\AppData\Local\Temp\2\windows-8634\client-building\desktop\src\common\ownsql.cpp:295 ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path, inode, modtime, type, md5, fileid, remotePerm, filesize,  ignoredChildrenRemote, contentchecksumtype.name || ':' || contentChecksum, e2eMangledName, isE2eEncrypted  FROM metadata  LEFT JOIN checksumtype as contentchecksumtype ON metadata.contentChecksumTypeId == contentchecksumtype.id WHERE parent_hash(path) = ?1 ORDER BY path||'/' ASC"
2022-12-31 10:03:41:389 [ info sync.discovery C:\Users\sysadmin\AppData\Local\Temp\2\windows-8634\client-building\desktop\src\libsync\discovery.cpp:362 ]:	Processing "Documents/Dokumentumok/Könyvtár/manuals/zwq_5100_user_manual.pdf" | valid: true/true/db | mtime: 1597998770/1597998770/0 | size: 2157020/2157020/0 | etag: "640d0ea5671d237e9363196c4c7f5557"//"" | checksum: ""//"" | perm: "WDNVR"//"" | fileid: "22247373ockyzphxy1jr"//"" | inode: 839869/839869/ | type: CSyncEnums::ItemTypeVirtualFile/CSyncEnums::ItemTypeVirtualFile/CSyncEnums::ItemTypeFile | e2ee: false/false | e2eeMangledName: ""/""
2022-12-31 10:03:41:389 [ info sync.discovery C:\Users\sysadmin\AppData\Local\Temp\2\windows-8634\client-building\desktop\src\libsync\discovery.cpp:1368 ]:	Discovered "Documents/Dokumentumok/Könyvtár/manuals/zwq_5100_user_manual.pdf" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeVirtualFile
2022-12-31 10:03:41:389 [ info sync.discovery C:\Users\sysadmin\AppData\Local\Temp\2\windows-8634\client-building\desktop\src\libsync\discovery.cpp:86 ]:	STARTING "Documents/Dokumentumok/Szerződések" OCC::ProcessDirectoryJob::ParentNotChanged "Documents/Dokumentumok/Szerződések" OCC::ProcessDirectoryJob::NormalQuery
2022-12-31 10:03:41:389 [ info sync.discovery C:\Users\sysadmin\AppData\Local\Temp\2\windows-8634\client-building\desktop\src\libsync\discovery.cpp:86 ]:	STARTING "Documents/Dokumentumok/UsersGuides" OCC::ProcessDirectoryJob::ParentNotChanged "Documents/Dokumentumok/UsersGuides" OCC::ProcessDirectoryJob::NormalQuery
2022-12-31 10:03:41:389 [ debug nextcloud.sync.database.sql C:\Users\sysadmin\AppData\Local\Temp\2\windows-8634\client-building\desktop\src\common/ownsql.h:145 ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 -1074047111436947454
2022-12-31 10:03:41:389 [ debug nextcloud.sync.database.sql C:\Users\sysadmin\AppData\Local\Temp\2\windows-8634\client-building\desktop\src\common\ownsql.cpp:295 ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path, inode, modtime, type, md5, fileid, remotePerm, filesize,  ignoredChildrenRemote, contentchecksumtype.name || ':' || contentChecksum, e2eMangledName, isE2eEncrypted  FROM metadata  LEFT JOIN checksumtype as contentchecksumtype ON metadata.contentChecksumTypeId == contentchecksumtype.id WHERE parent_hash(path) = ?1 ORDER BY path||'/' ASC"
2022-12-31 10:03:41:389 [ info sync.discovery C:\Users\sysadmin\AppData\Local\Temp\2\windows-8634\client-building\desktop\src\libsync\discovery.cpp:362 ]:	Processing "Documents/Dokumentumok/Other/inet számla/26105590_1629834850396710_813499199_n.jpg" | valid: true/true/db | mtime: 1514397316/1514397316/0 | size: 24795/24795/0 | etag: "615712d36cb8429729606950e7d7a49f"//"" | checksum: ""//"" | perm: "WDNVR"//"" | fileid: "20462908ockyzphxy1jr"//"" | inode: 839874/839874/ | type: CSyncEnums::ItemTypeVirtualFile/CSyncEnums::ItemTypeVirtualFile/CSyncEnums::ItemTypeFile | e2ee: false/false | e2eeMangledName: ""/""
2022-12-31 10:03:41:389 [ info sync.discovery C:\Users\sysadmin\AppData\Local\Temp\2\windows-8634\client-building\desktop\src\libsync\discovery.cpp:1368 ]:	Discovered "Documents/Dokumentumok/Other/inet számla/26105590_1629834850396710_813499199_n.jpg" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeVirtualFile
2022-12-31 10:03:41:389 [ info sync.discovery C:\Users\sysadmin\AppData\Local\Temp\2\windows-8634\client-building\desktop\src\libsync\discovery.cpp:362 ]:	Processing "Documents/Dokumentumok/Other/inet számla/26105684_1629834407063421_1422797738_n.jpg" | valid: true/true/db | mtime: 1514397324/1514397324/0 | size: 24719/24719/0 | etag: "097b00fd36fc9509755ac3bae1dbada2"//"" | checksum: ""//"" | perm: "WDNVR"//"" | fileid: "20462909ockyzphxy1jr"//"" | inode: 839875/839875/ | type: CSyncEnums::ItemTypeVirtualFile/CSyncEnums::ItemTypeVirtualFile/CSyncEnums::ItemTypeFile | e2ee: false/false | e2eeMangledName: ""/""
2022-12-31 10:03:41:389 [ info sync.discovery C:\Users\sysadmin\AppData\Local\Temp\2\windows-8634\client-building\desktop\src\libsync\discovery.cpp:1368 ]:	Discovered "Documents/Dokumentumok/Other/inet számla/26105684_1629834407063421_1422797738_n.jpg" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeVirtualFile
2022-12-31 10:03:41:389 [ info sync.discovery C:\Users\sysadmin\AppData\Local\Temp\2\windows-8634\client-building\desktop\src\libsync\discovery.cpp:362 ]:	Processing "Documents/Dokumentumok/Other/inet számla/26176926_1629834723730056_2018223740_n.jpg" | valid: true/true/db | mtime: 1514397321/1514397321/0 | size: 29817/29817/0 | etag: "cdbad2f8f7b8ce9c4f82583f38a9db20"//"" | checksum: ""//"" | perm: "WDNVR"//"" | fileid: "20462907ockyzphxy1jr"//"" | inode: 839876/839876/ | type: CSyncEnums::ItemTypeVirtualFile/CSyncEnums::ItemTypeVirtualFile/CSyncEnums::ItemTypeFile | e2ee: false/false | e2eeMangledName: ""/""
2022-12-31 10:03:41:389 [ info sync.discovery C:\Users\sysadmin\AppData\Local\Temp\2\windows-8634\client-building\desktop\src\libsync\discovery.cpp:1368 ]:	Discovered "Documents/Dokumentumok/Other/inet számla/26176926_1629834723730056_2018223740_n.jpg" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeVirtualFile
2022-12-31 10:03:41:389 [ debug nextcloud.sync.database.sql C:\Users\sysadmin\AppData\Local\Temp\2\windows-8634\client-building\desktop\src\common/ownsql.h:145 ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 -5541886882352546247
```
I would expect the log to only contain information about special cases - being no smaller than a 100KB per sync run - not a detailed explanation of every atomic step during the sync process (this is a debug log, not a production log).
For the people stumbling across this issue, and are wondering: you can find the logs under `%appdata%\Nextcloud\logs` on Windows, or `C:\Users\username\AppData\Roaming\Nextcloud\logs`.

### Steps to reproduce

1. Have about 300 000 files for your user, and sync them using Windows virtual file support. 
2. Check the size of your logs folder: `%appdata%\Nextcloud\logs`. It should have the size of multiple Gigabytes.

### Expected behavior

I'd expect log files to only contain data about unexpected runtime errors that can help the team fix those errors. Not a detailed log of every atomic step during an otherwise uneventful sync.

### Which files are affected by this bug

all of them

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 Pro 22H2, OS Build 19045.2364

### Package

Appimage

### Nextcloud Server version

25.0.2

### Nextcloud Desktop Client version

3.4.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by eibex** [comment]
Related: #3312

**Comment by eibex** [comment]
A temporary fix could be adding a radio button to enable/disable logging until verbosity can be reduced only to errors.

**Comment by JonathanxD** [comment]
On Linux I've literally set the logs folder to read-only, I've tried everything and nothing helped.

I was working and suddenly my SSD ran out of space and the editor was closed abruptly because it failed to save its data. Nextcloud generated over 200GB of logs and the directory was full of compressed log files and a single text file with more than 150GB+.

I've then traced the problem to Dolphin, but Dolphin was not the culprit, it was just requesting file status for every file in my `/home` directory (which has 4 million files), this directory is not even set to sync, it's my external drive directory that is. And Nextcloud log every file status request attempt, this also caused Dolphin to use 6GB of RAM, after setting the logs directory to read-only, it's now using 100MB.

I don't know if this will also work for Windows (maybe Nextcloud can just try to change the permission on Windows, on Linux it's not possible without root privileges), but you can try as well. The only downside is that you lose all logs, but it's better than losing an NVMe SSD because of the massive wear.

**Comment by user23498723452** [comment]
hmm, I use the appimage (previously a repo as well) on Ubuntu 20 (for years now) and have never had log file issues.

**Comment by retnag** [comment]
Iteresting. Just out of curiousity, did you check the size of the logs folder? What size is it?
What version is the client? Perhaps a later change introduced this behavoiur? (I have also been using the client for years, and noticed this problem only recently, because my disk got close to being full)

> hmm, I use the appimage (previously a repo as well) on Ubuntu 20 (for years now) and have never had log file issues.

**Comment by retnag** [comment]
Oh I just remembered, there is no virtual file support for linux, so maybe there is the culprit, and this issue only impacts Windows users using the virtual file support.

**Comment by bgeneto** [comment]
We should have an option to reduce log level in the client. My `nextcloud.cfg` config file has the following options:

```
logDebug=false
logExpire=24
```

But I still have hundreds of megabytes in compressed log files!

**Comment by gitskot** [comment]
I have this issue also, although I didn't enable virtual files yet, the log folder ballooning to hundreds of gigabytes!

I am on Windows 10, just reinstalled the client to confirm the issue (now 3.8.1)  My data is around 25GB,  ~50.000 files.

I had to symlink the log folder to a spinning HD to move it, but that is not a solution because its growing too fast.

I really hope this will be fixed soon, I am surprised that you don't have more reports on this.

**Comment by isdnfan** [comment]
Same here - version 3.7.4 has 239MBs of zipped logs from one day only and I don't have as many files (~1TB / 100k files on server) - and I didn't made any excessive changes in the last days..

In my case there are sets of 4 files every 2 hours.. where archives of the same size are created

![image](https://github.com/nextcloud/desktop/assets/18125597/0f90a06d-e4aa-46c8-bcf6-3c61f4dd119a)

30MB archive is ~600MB extracted and it looks like it contains some log records to literally each file stored in my account.. even it didn't change at this time..

on sample of random directory record :

```
2023-05-15 11:27:15:680 [ info nextcloud.sync.discovery C:\Users\sysadmin\AppData\Local\Temp\2\windows-14239\client-building\desktop\src\libsync\discovery.cpp:423 ]:	Processing "Fotos/2021_Kulinarische_Reise" | (db/local/remote) | valid: true/true/db | mtime: 1673359040/1673359040/0 | size: 0/131072/0 | etag: "63bd6ec0c1975"//"" | checksum: ""//"" | perm: "DNVCKRm"//"" | fileid: "01395102occ5uwmhix0f"//"" | inode: 395154/395154/ | type: CSyncEnums::ItemTypeDirectory/CSyncEnums::ItemTypeDirectory/CSyncEnums::ItemTypeFile | e2ee: false/false | e2eeMangledName: ""/"" | file lock: not locked//
2023-05-15 11:27:15:680 [ debug nextcloud.sync.discovery C:\Users\sysadmin\AppData\Local\Temp\2\windows-14239\client-building\desktop\src\libsync\discovery.cpp:911 ]	[ OCC::ProcessDirectoryJob::processFileAnalyzeLocalInfo ]:	File "Fotos/2021_Kulinarische_Reise" - servermodified: false noServerEntry: false
2023-05-15 11:27:15:680 [ info nextcloud.sync.discovery C:\Users\sysadmin\AppData\Local\Temp\2\windows-14239\client-building\desktop\src\libsync\discovery.cpp:1540 ]:	Discovered "Fotos/2021_Kulinarische_Reise" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeDirectory
2023-05-15 11:27:15:680 [ debug nextcloud.sync.discovery C:\Users\sysadmin\AppData\Local\Temp\2\windows-14239\client-building\desktop\src\libsync\discovery.cpp:59 ]	[ OCC::ProcessDirectoryJob::ProcessDirectoryJob ]:	"Fotos/2021_Kulinarische_Reise" OCC::ProcessDirectoryJob::ParentNotChanged "Fotos/2021_Kulinarische_Reise" OCC::ProcessDirectoryJob::NormalQuery 1684135631
2023-05-15 11:27:15:680 [ warning default C:\Users\sysadmin\AppData\Local\Temp\2\windows-14239\client-building\desktop\src\csync\csync_exclude.cpp:445 ]:	System exclude list file could not be read: "C:/Nextcloud/Fotos/2022_ZuHause/.sync-exclude.lst"
```
another sample is for a file:
```
2023-05-15 11:27:32:069 [ info nextcloud.sync.discovery C:\Users\sysadmin\AppData\Local\Temp\2\windows-14239\client-building\desktop\src\libsync\discovery.cpp:1540 ]:	Discovered "Fotos/#Archiv/2019/2019_wwe_handy/.@__thumb/default20190228_084338.jpg" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeVirtualFile
2023-05-15 11:27:32:069 [ info nextcloud.sync.discovery C:\Users\sysadmin\AppData\Local\Temp\2\windows-14239\client-building\desktop\src\libsync\discovery.cpp:423 ]:	Processing "Fotos/#Archiv/2019/2019_wwe_handy/.@__thumb/default20190301_111949.jpg" | (db/local/remote) | valid: true/true/db | mtime: 1551435589/1551435589/0 | size: 43794/43794/0 | etag: "e16afd6cfb80a1f98536bed3939e187e"//"" | checksum: ""//"" | perm: "WDNVRm"//"" | fileid: "01437551occ5uwmhix0f"//"" | inode: 1165765/1165765/ | type: CSyncEnums::ItemTypeVirtualFile/CSyncEnums::ItemTypeVirtualFile/CSyncEnums::ItemTypeFile | e2ee: false/false | e2eeMangledName: ""/"" | file lock: not locked//
2023-05-15 11:27:32:069 [ debug nextcloud.sync.discovery C:\Users\sysadmin\AppData\Local\Temp\2\windows-14239\client-building\desktop\src\libsync\discovery.cpp:911 ]	[ OCC::ProcessDirectoryJob::processFileAnalyzeLocalInfo ]:	File "Fotos/#Archiv/2019/2019_wwe_handy/.@__thumb/default20190301_111949.jpg" - servermodified: false noServerEntry: false
```

take a look at `servermodified: false` - this folder was not touched on either on the client nor on the server.. what is the reason to log it? In general constant looping over all known items doesn't sounds very resource effective.

**Comment by isdnfan** [comment]
hopefully the problem is improved due to #5634

**Comment by quicktrick** [comment]
The number of log files is growing at an alarming rate. We need to do something about it immediately.

**Comment by isdnfan** [comment]
I'm not very sure about the size of the logs.. I 'm under impression the size is reduced with the last version but there was a huge user experience regression - now an archive is generated for every 512K log - resulting in insane number of of log archives.. my first sync of the day consists of 1291 files (33Mb).. two hours later same files count/size..

I don't think it changes the whole size of logging but makes it harder to follow/understand.

definitely killing [useless logs](https://github.com/nextcloud/desktop/issues/5302#issuecomment-1559998997) by default is a **MUST**.

**Comment by isdnfan** [comment]
for me update to 3.9.0 reduces logging from 30MB archives every 2h to 20MB (likely due to #5796) not many but a right direction already.

**Comment by quicktrick** [comment]
I created a task in Task Scheduler that deletes all `*.gz` every hour.

**Comment by gitskot** [comment]
I just tried installing the Windows client again, now in version 3.9.0 - in only 1 hour I have 265MB of log files, logging every small action - this is totally weird behaviour and makes Nextcloud unusable for me, also - I can't recommend it to anyone in this state.

**Comment by godfuture** [comment]
Same here. For me it looks like the client keeps syncing in a loop. Every attempt a new logfile is created. A single attempt takes only a second till the next attempt is started.
%appdata%/Nextcloud is being filled with log.gz

2023-09-16 03:27:42:735 [ info nextcloud.gui.socketapi C:\Users\sysadmin\AppData\Local\Temp\2\windows-17553\client-building\desktop\src\gui\socketapi\socketapi.cpp:338 ]:	Lost connection  QLocalSocket(0x21764436660)

Being a Nextcloud user since many years now, my impression is that the Nextcloud client is tested very badly. Often there have been issues after updates. Problems with data being deleted, corrupted or now endlessly logged. Not good at all!

Win10 x64
NC Client 3.9.4

**Comment by isdnfan** [comment]
I hoped 3.10 will fix the the issue due to: "Bugfix/adjust log levels by @mgallien in" #5796

but still huge logs - in my case this are around zipped 20MB (~250MB) logs on each client start and awake from sleep..

now the logs lines look like this - including very strange **static** string '[ info nextcloud.sync.discovery C:\Users\sysadmin\AppData\Local\Temp\2\windows-17670\client-building\desktop\src\libsync\discovery.cpp:464 ]'

```
${timestamp} [ info nextcloud.sync.discovery C:\Users\sysadmin\AppData\Local\Temp\2\windows-17670\client-building\desktop\src\libsync\discovery.cpp:464 ]: ${filename} | (db/local/remote) | valid: true/true/db | mtime: 1457627598/1457627598/0 | size: 6090/6090/0 | etag: "155c38ffd623e2d576c46464d66b6022"//"" | checksum: ""//"" | perm: "WDNVRm"//"" | fileid: "01683291occ5uwmhix0f"//"" | type: CSyncEnums::ItemTypeVirtualFile/CSyncEnums::ItemTypeVirtualFile/CSyncEnums::ItemTypeFile | e2ee: false/false | e2eeMangledName: ""/"" | file lock: not locked// | metadata missing: /false/
```
@mgallien - can we please got it sorted? there is no value of logging **each** existing file.. normal logs should only log when files are changed and require replication to or from the server.

**Comment by retnag** [comment]
I feel like it is overlooked, that most of the users don't even need the logs... I'm pretty sure, most don't even know they exist. Can't there just be a switch to turn logging on/off? It should be relatively easy to implement, and it would solve the issue. What speaks against it?

**Comment by eibex** [comment]
> Can't there just be a switch to turn logging on/off? It should be relatively easy to implement, and it would solve the issue. What speaks against it?

Didn't look like a priority #3312

**Comment by JP95Git** [comment]
I also have this issue, it even persists in Nextcloud-3.11.0-x64.msi. 2 suggestions:
- Either lower the log level to warning or error
- Or do not log to much.

I had to delete the log-folder each day using manually or my partition runs out of space.

**Comment by thvitt** [comment]
BTW at least for Nextcloud 3.11 on Debian setting an environment variable QT_LOGGING_RULES for the Nextcloud process seems to help somewhat. `QT_LOGGING_RULES='*=false'` completely turns off all log messages, although the Nextcloud client still creates a gz file of compressed nothingness every minute or so.

**Comment by Julrob199** [comment]
I hope this gets fixed soon. For years this habit is wearing off my SSD.

**Comment by LordBaryhobal** [comment]
Currently facing the same issue with v3.13.2
It has become very painful to use Nextcloud because of the gigabytes of useless log. It is still viable on my PC but my laptop cannot handle constant writes without heating up like a barbecue
My current workaround is to simply pause sync while I work and modify files, and turn it back on at the end, which feels more like using git than a cloud service

How has still not been solved, or at least been improved ? Maybe I'm missing something

**Comment by isdnfan** [comment]
the was a pull request #5780 addressing the logs issue and setting the useless "discovered" and "processing" logs to debug level.. for some reason major developer is reluctant to accept it. for now the only workaround remains to write the logs onto nullfs or ramdisk

**Comment by chainria** [comment]
After numerous times Nextcloud filled up my /home, after numerous days of cleaning the log folder, I eventually decided for this step:

cd .config/Nextcloud
rm -rf logs && ln -s /tmp logs

My /tmp is a tmpfs with about 16 GB of space (using it to compile Gentoo Ebuilds). It can have it's fun there now.
The log size defeats the purpose of the logs anyway. Even IF Nextcloud decides to delete everything again, I won't bother to look up in Gigabytes of files what happened. I'll just restore the backup I maintain since the last times that happened.

Still, I really hope this gets adressed soon.

**Comment by limes007** [comment]
Setting env variable `QT_LOGGING_RULES='*=false'` as described by @thvitt helps. Thank you.
But empty gz-Files will still be created - every 7 seconds for me!

It would be great to fix this bug.

**Comment by gheesh** [comment]
> Setting env variable `QT_LOGGING_RULES='*=false'` as described by [@thvitt](https://github.com/thvitt) helps. Thank you. But empty gz-Files will still be created - every 7 seconds for me!
> 
> It would be great to fix this bug.

If you don't want to completely disable logging, this worked for me: `QT_LOGGING_RULES='*.debug=false'` Even with info messages it is now down to a few KB per minute, except for the initial run (as expected)

**Comment by isdnfan** [comment]
for me the line `desktop\src\libsync\discovery.cpp:481` was responsible for 99% of all log lines.

after setting environment variable `QT_LOGGING_RULES="nextcloud.sync.discovery=false"` the most "offending" log lines enumerating all files stored in the system is removed.

![Image](https://github.com/user-attachments/assets/4f887b1c-1940-4dfe-a431-5c85ddb9d2e5)

works very well on Windows with client 3.13.3. The log still shows basic client states and important operations like creating and removing files is still logged. new logs and corresponding .gz archives are created frequently but this is not a big deal IMO.

```
Name                              size(MB)
----                              --------
20241113_0735_nextcloud.log.10.gz    2.542
20241113_0735_nextcloud.log.11.gz    0.122
20241113_0735_nextcloud.log.12.gz     0.01
20241113_0735_nextcloud.log.13.gz     0.01
20241113_0735_nextcloud.log.2.gz     2.132
20241113_0735_nextcloud.log.3.gz     2.157
20241113_0735_nextcloud.log.4.gz     2.127
20241113_0735_nextcloud.log.5.gz     2.216
20241113_0735_nextcloud.log.6.gz      2.45
20241113_0735_nextcloud.log.7.gz     2.775
20241113_0735_nextcloud.log.8.gz     2.951
20241113_0735_nextcloud.log.9.gz      2.68
20241113_0736_nextcloud.log.0.gz     0.033
20241113_0736_nextcloud.log.1.gz      0.09
20241113_0736_nextcloud.log.2.gz     0.006
# set env variable and restart the client
20241113_0914_nextcloud.log.0.gz         0
20241113_0914_nextcloud.log.1.gz         0
20241113_0914_nextcloud.log.2.gz         0
20241113_0914_nextcloud.log.3.gz         0
20241113_0919_nextcloud.log.0.gz      0.01
20241113_0919_nextcloud.log.1.gz     0.002
20241113_0920_nextcloud.log.0.gz     0.003
20241113_0921_nextcloud.log.0.gz     0.001
20241113_0921_nextcloud.log.1.gz     0.002
20241113_0922_nextcloud.log.0.gz     0.001
20241113_0922_nextcloud.log.1.gz     0.003
20241113_0924_nextcloud.log.0.gz     0.002
20241113_0924_nextcloud.log.1.gz     0.001
20241113_0924_nextcloud.log.2.gz     0.001
20241113_0925_nextcloud.log.0            0
```

**Comment by Cjrbro1280** [comment]
I only have 11GB of files synced with NextCloud as I am testing it out.  However, I just discovered that the NextCloud desktop client I am using (3.15.3) is creating GBs of logs a day.  I noticed this as Backblaze was backing up my files, seeing my nextcloud.gz log files.

It does look like logs are being deleted and only kept for 24 hours, but I have 5.54GB of log files in my user directory now (AppData/Roaming/Nextcloud/logs).  To me, as well, this does seems like a lot of unnecessary wear on my SSD.

If Debug/Info logs are needed, perhaps there could be a way to add a setting to change the logging level, where it is something like Error by default and if an issue needs to be diagnosed, the level can be changed through the settings to Info or Debug?

**Comment by Cjrbro1280** [comment]
Ok, actually, I looked through the log and it appeared that perhaps my initial sync just hadn't completed.  There were three files that were constantly shown at the end as being modified ("Detected changes in paths..").  Once I moved those three files out of my NextCloud folder, the incessant logs stopped, and NextCloud stopped trying to sync every few seconds.

I then added one of the files back and got an error that mentions, "Cannot sync due to invalid modification time".

![Image](https://github.com/user-attachments/assets/75db3acf-7a71-45bc-99eb-03d1018aadcd)

I looked at the file and there was not time set for "Date modified" in the properties.  (This is an old file from a 3.5" floppy disk from my Grandfather back from at least 1986 or older.)

![Image](https://github.com/user-attachments/assets/19788cad-0548-4f5b-b3ee-7c3a8564da06)

This gives me enough to go on to fix the issue on my local machine.  Hopefully others might find it useful too.

**Comment by dtandersen** [comment]
Deleted 40Gb of this: why does it log every file at info level? Used https://github.com/nextcloud/desktop/issues/5302#issuecomment-2473088146 to greatly reduce it.

2025-08-08 01:31:56:767 [ info nextcloud.sync.discovery C:\Users\User\AppData\Local\Temp\windows-31590\client-building\desktop\src\libsync\discovery.cpp:599 ]:	"Processing \"Dropbox/screeps/node_modules/es-abstract/test/diffOps.js\" | (db/local/remote) | valid: true/true/db | mtime: 499162500/499162500/0 | size: 679/679/0 | etag: \"5ae7e13f61fdfedc7756aa367b1079ad\"//\"\" | checksum: \"MD5:d05abc3887df7f25aeb816f0303878b8\"//\"\" | perm: \"GWDNVR\"//\"\" | fileid: \"00127953ocuxln510sia\"//\"\" | inode: 119281/119281/ | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile | e2ee: false/false | e2eeMangledName: \"\"/\"\" | file lock: not locked// | file lock type: \"\"//\"\" | live photo: false//false | metadata missing: /false/"
2025-08-08 01:31:56:767 [ info nextcloud.sync.discovery C:\Users\User\AppData\Local\Temp\windows-31590\client-building\desktop\src\libsync\discovery.cpp:599 ]:	"Processing \"Dropbox/screeps/node_modules/es-abstract/test/es2015.js\" | (db/local/remote) | valid: true/true/db | mtime: 499162500/499162500/0 | size: 3289/3289/0 | etag: \"4c1e59db32a497db45b0358b6f99ba11\"//\"\" | checksum: \"MD5:0861905d7dc5a91e138c98b2aa98a9cb\"//\"\" | perm: \"GWDNVR\"//\"\" | fileid: \"00127959ocuxln510sia\"//\"\" | inode: 119282/119282/ | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile | e2ee: false/false | e2eeMangledName: \"\"/\"\" | file lock: not locked// | file lock type: \"\"//\"\" | live photo: false//false | metadata missing: /false/"

**Comment by mgallien** [comment]
I am closing this issue as the client improved a lot and we think this is solved

**Comment by wonx** [comment]
Hi, i can confirm this behavior is still present. My logfile folder grows to be 79GB during synchronization in a matter of minutes with the latest 4.04 windows client. Any input will be welcome.

**Comment by Cerberus-tm** [comment]
Still present for me with the latest Windows client. Two new log files have been created during the writing of this comment, and it continues at this pace 24/7.

**Comment by Mpic** [comment]
This is not solved at all, initial sync on my CachyOS with the 33.0.3 client is impossibly slow and generates log at debug level if I don't change set QT_LOGGING_RULES='*=false', which makes the client crash because of tmpfs filling.

**Comment by Julrob199** [comment]
@Mpic Is it just the initial run?

**Comment by Mpic** [comment]
@Julrob199 I have two Nextclouds linked to the desktop client.

One of them is an easy feat : simple complete sync, 5 GB total. The initial sync went through a long time ago and even with logs at debug level, it's not enough to fill tmpfs.

The other is 1.1 TB with several hundreds of thousands of files, set to VFS. I had to reset it due to VFS problems since a recent desktop update (it tried to download all files, filling my storage).
The initial sync post-reset never went through, even with debug logs disabled, so I can't say. I'm trying to make sense of the logs to understand if there is a real problem in my files preventing the sync, I don't really know.

**Comment by Cerberus-tm** [comment]
I have changed QT_LOGGING_RULES as per above, so that the log files are now small; thank you! I no longer have GBs of log files. Still, a new file is now created every minute. I only synchronise My Documents, which are about 10 GB total.
