### ISSUE TITLE
Avoid same shortcut name for different Nextcloud accounts on Windows

### ISSUE THREAD

**Issue by master-fuggi** [nextcloud/desktop#5656]
When adding several Nextcloud accounts to the Nextcloud client on Windows 11, the shortcuts/favorites created on Desktop with Windows Explorer are all named "Nextcloud" regardless of how the local folder for synchronization has been named — making it impossible for the user to distinguish between the different accounts.

![grafik](https://user-images.githubusercontent.com/40880549/236567946-41d2f5c5-5b0d-442b-8537-7704944ae304.png)

It would be more intuitive if either the name of the local sync folder was used or if the name was set in the settings.

![grafik](https://user-images.githubusercontent.com/40880549/236569543-cbd48154-be8f-492b-8670-17c84935b65e.png)

**Comment by allan2** [comment]
I noticed this when I added multiple accounts and they were all named "Nextcloud" in Windows Explorer quick access.

A feature to customize the quick access text would be nice.

## Current behaviour

1. the shortcut text for an account with VFS is `Nextcloud`
2. the shortcut text for an account without VFS is `Nextcloud - username@nchost.com`

Since #5714 has been marked as not planned, I am writing suggestions below.

## The issue

The current behaviour is inconsistent and breaks user expectations. For myself, I added two accounts and could not tell them apart easily in Windows Explorer. I saw screenshots online with `Nextcloud - username@nchost.com` but could not find how to rename my shortcuts, until I read #5714 and learned that the text changes depending on whether VFS is on or off.

Some users use an email address as their username, so an account without VFS would have a shortcut text of `Nextcloud - emailusername@emaildomain.com@nchost.com`. In addition to being unsightly, the imposed length could interfere with filesystem path limits (FAT 255 char limit).

##  ownCloud behaviour

I want to mention how ownCloud handles it because users may have similar expectations when adding accounts.

1. The shortcut text is the same as the folder name, with or without VFS

The default folder name is `C:\Users\windowsuser\ownCloud - username@ochost.com`.  If the folder path was changed to `C:\Users\windowsuser\oc_customname`, the quick access shortcut would read `oc_customname`.

## Suggested behaviour

1. The shortcut text defaults to the folder name, but there is an option to customize it in the add account options.

This is similar to ownCloud, with an additional option to customize the quick access shortcut if the user would like to do so.

**Comment by jpbourgeon** [comment]
Here is a manual workaround
1) in nextcloud parameters, uncheck "display sync folders in file explorer navigation pane" (the display is broken anyway)
2) in file explorer libraries : create a new library that point to the desired folder. Rename it and change the icon for `C:\Program Files\Nextcloud\nextcloud.ico`
3) pin the libraries to quick access

**Comment by sebastiaanveld** [comment]
I silently install my msi file and then start the nextcloud.exe the first time for the user with:
`--overrideserverurl "https://mynextcloudserver" --overridelocaldir "${USERPROFILE}\Nextcloud ${USERNAME}"`
(which could be %username% and %userprofile% pending your deployment solution)
This prevents the default folder be named Nextcloud, so now it would be nice if the Explorer shortcut would also default to that name.

Main reason why I need to know the foldername with the Nextcloud files for the logged on user is that I want to redirect Windows folders (Document, Pictures, etc) to the users Nextcloud folder. Case the user would manually ceate it's first account that probably would het "Nextcloud" as a foldername while additional profiles created would get "Netxcloud2" etc and redirection would take place to the wrong folder.

**Comment by dkiper** [comment]
Here is a workaround... The [nc-add-vjp.ps1](https://github.com/user-attachments/files/18353065/nc-add-vjp.txt) script (sadly GitHub does not permit uploading PowerShell scripts as is; so, I had to save it as `txt` file; you have to change extension to `ps1` when downloading; sorry about that) allows you creating any shortcut to any destination in the Explorer's Navigation Pane, e.g. `nc-add-vjp.ps1 C:\Users\user\Nextcloud nc`. The first argument is path to directory which contains data from Nextcloud server. The second argument specifies new shortcut name. It is optional. If not given the shortcut name is derived from first argument. The last optional argument can be used to hide/show new link on Windows desktop (by default it is hidden).

The [nc-del-vjp.ps1](https://github.com/user-attachments/files/18353066/nc-del-vjp.txt) script deletes shortcut from the Explorer's Navigation Pane. It takes shortcut name as an argument.

The `Show sync folders in Explorer's Navigation Pane` option in the Nextcloud Settings does not interfere with shortcuts created with `nc-add-vjp.ps1`. So, it can be disabled to avoid creation of default Nextcloud shortcuts in the Explorer's Navigation Pane.

**Comment by ralshut** [comment]
Unfortunately the script is not working for me. I Type:

`.\nc-add-vjp.ps1 C:\Users\RuedigerAlshut\My_Cloud\`

or
`
.\nc-add-vjp.ps1 C:\Users\RuedigerAlshut\My_Cloud\`

and I only get another shortcut named "Nextcloud" in the explorer

:(

**Comment by dkiper** [comment]
> Unfortunately the script is not working for me. I Type:
>
> `.\nc-add-vjp.ps1 C:\Users\RuedigerAlshut\My_Cloud\`
>
> or ` .\nc-add-vjp.ps1 C:\Users\RuedigerAlshut\My_Cloud\`
>
> and I only get another shortcut named "Nextcloud" in the explorer
>
> :(

Both examples are the same. Could you try `nc-add-vjp.ps1 C:\Users\RuedigerAlshut\My_Cloud My_Cloud`?
If it does not work could you disable `Show sync folders in Explorer's Navigation Pane` option in the Nextcloud Settings?
If it still does not work please share more details about your system, e.g. Windows version, Nextcloud version.

**Comment by dkiper** [comment]
> Thank you for your reply. I'm now using the libraries workaround mentioned above and its good for me.
>
> Accidentally I copy and pasted my full name in the folder name to My_Cloud. Would you mind removing it from your answer, as I can only edit the answer I posted? thanks!

Done! However, you should delete your original versions as well. Otherwise your full name is still visible in the history/edits.

**Comment by kleajmp** [comment]
I tried to change the "Nextcloud - [account_userName]" values in the Windows registry and rebooted but still the same names are showing for all my synced accounts. Any real solution yet to this problem? Can I change this value somewhere on the Nextcloud servers itselves? I am the server admin.

**Comment by calixtus** [comment]
Extremly annoying. Always a guessing game. A user would expect this to work out of the box without looking for a workaround.

![Image](https://github.com/user-attachments/assets/ec60b3b0-7491-4422-8643-a93a794f7320)

**Comment by l-uuz** [comment]
Please make this configurable.

Under Windows 10 it is at least usable if you have different account names. But under Windows 11 this only works via workarounds and shortcuts outside the Explorer integration - which makes this useless.

**Comment by pzwahlen** [comment]
+1 to this issue

**Comment by camilasan** [comment]
> Please make this configurable.

I don't think so.

I am fixing the initial reported issue at #8458 
it will look like 'Folder - account'.

**Comment by l-uuz** [comment]
> > Please make this configurable.
> 
> I don't think so.
> 
> I am fixing the initial reported issue at https://github.com/nextcloud/desktop/pull/8458
> it will look like 'Folder - account'.

I'm fine with the full account name appearing there. In my circle, it is often the case that people have multiple accounts with `firstname.lastname`, but on different servers, so e.g. `firstname.lastname@abc.com` should be fine.

**Comment by Rello** [comment]
Closing as completed. PR #8458 changed Windows navigation-pane favorites so root entries use URL and account information and other entries use the folder name, preventing multiple accounts from appearing as indistinguishable Nextcloud shortcuts.
