### ISSUE TITLE
SSL context creation failed

### ISSUE THREAD

**Issue by Nanoatic** [nextcloud/desktop#582]
when building the client and running it , i get the following error : 
![capture](https://user-images.githubusercontent.com/17166341/44596213-53220580-a7c3-11e8-9b75-75a783f3ce04.PNG)
and if i select retry i get this error :
![capture1](https://user-images.githubusercontent.com/17166341/44596269-7b116900-a7c3-11e8-82d4-9bae483f2d79.PNG)
built with :
Visual studio 2017
Openssl 1.1.0g (built with nmake + perl+nasm)

**Comment by camilasan** [comment]
Hi, you need to run windeployqt on the bin folder and copy the missing dll's listed here:
 https://github.com/nextcloud/client-building

**Comment by Nanoatic** [comment]
Thank you :) Iv done everything you mentioned , and what was really missing , were libeay32.dll and ssleay32.dll .

**Comment by Nanoatic** [comment]
strange , i got another error  :
 The webpage at https://server.com/nextcloud/index.php/login/flow might be temporarily down or it may have moved permanently to a new web address.
ERR_CERT_AUTHORITY_INVALID
ps : the build works well with a certified server

**Comment by pete2280** [comment]
Same issue here on mac Version 2.5.0daily (build 20180824)

**Comment by camilasan** [comment]
Self signed certificate problem...

**Comment by Nanoatic** [comment]
Still the same issue, maybe the bug comes from qt webview itself ?

**Comment by camilasan** [comment]
About the webview not loading: do you use a self signed certificate?

**Comment by Nanoatic** [comment]
yes i do.

**Comment by Nanoatic** [comment]
i thought we already identified the problem.

**Comment by camilasan** [comment]
The new web login doesn't work with a self signed certificate. This is still an issue. My comment about the build was just an invite to test it since you are using Windows.

**Comment by Nanoatic** [comment]
ah ok. well , ill look into it more when i get time.

**Comment by camilasan** [comment]
ok, thanks :)

**Comment by camilasan** [comment]
Will close this issue because the original issues is solved by copying libeay32.dll and ssleay32.dll to the bin folder.

**Comment by OverByThere** [comment]
Hi @camilasan, I've downloaded the latest beta Version 2.5.0daily (build 20180621), and I'm still experiencing issues logging in.

**Comment by vampiebar** [comment]
+1 Do we have fixed version for self signed domains?

**Comment by harsha5500** [comment]
+ 1 I would like a fix for Mac too

**Comment by Nanoatic** [comment]
i have already created a pull request , once i have time ill look in to it . https://github.com/nextcloud/desktop/pull/630#pullrequestreview-153435482

**Comment by jetcostar** [comment]
![1](https://user-images.githubusercontent.com/55017822/64478916-ec248400-d16c-11e9-85a5-032a709588cd.png)
![2](https://user-images.githubusercontent.com/55017822/64478917-ef1f7480-d16c-11e9-8758-62971e6e8bb6.png)

Hello 
Please help me with this issue.

I built qtkeychain successfully
I installed zlib, openssl using vcpkg.

OS : windows 8.1
Visual Studio 2017
CMake version : 3.15.2
QT : 5.13.1

I need your help .

**Comment by Nanoatic** [comment]
@jetcostar I just tested your url with the newest build, it works just fine. 
did you run windeployqt as mentioned in https://github.com/nextcloud/client-building and make sure you copy libeay32.dll and ssleay32.dll from openssl library folder to the location where the executable is located.

**Comment by jetcostar** [comment]
Thanks for your response . 
But I have already copied 2 files from open_ssl directory installed by vcpkg.

![1](https://user-images.githubusercontent.com/55017822/64479929-b8048f80-d17b-11e9-9c2d-ca6d82210a4d.png)
![2](https://user-images.githubusercontent.com/55017822/64479931-bb981680-d17b-11e9-95e9-12c696e19a96.png)

Please check this .

**Comment by jetcostar** [comment]
But this is strange problem.
This works fine in my another computer.
All are same in that computer too.
But I used that computer a long time without reinstalling OS.
Now errors happen in new computer which I just installed OS newly.
Please consider this problem.
Thanks.

**Comment by Nanoatic** [comment]
@jetcostar did all your machines have windows 8.1 installed?

**Comment by jetcostar** [comment]
Yes 
Both are Windows 8.1

**Comment by Nanoatic** [comment]
@jetcostar try including libssl-1_1-x64.dll

**Comment by jetcostar** [comment]
Thanks for your kind reply , @Nanoatic 
But still same errors happens.
Can you check my computer ?
I copied 2 files .

![3](https://user-images.githubusercontent.com/55017822/64486712-ba073680-d1ed-11e9-9a17-875b0cfdc30a.png)

**Comment by Nanoatic** [comment]
@jetcostar did you try the the daily build instead, did it produce the same result ?

**Comment by jetcostar** [comment]
![4](https://user-images.githubusercontent.com/55017822/64486756-7660fc80-d1ee-11e9-99a8-344c7feaf34b.png)

Same in development environment

**Comment by Nanoatic** [comment]
install nextcloud-2.7.0.5820-daily-20190908-Release.exe from https://download.nextcloud.com/desktop/daily/Windows/ and see if the error persist or not

**Comment by jetcostar** [comment]
![1](https://user-images.githubusercontent.com/55017822/64486840-ad83dd80-d1ef-11e9-8f38-f55a293d3e27.png)

That works fine in same computer.
But that opens in chrome browser not app.

**Comment by Nanoatic** [comment]
you re missing OCUtil.dll

**Comment by jetcostar** [comment]
![2](https://user-images.githubusercontent.com/55017822/64486890-4ca8d500-d1f0-11e9-875b-7c683d7c42e8.png)

**Comment by jetcostar** [comment]
That file has already existed in executable directory.

**Comment by Nanoatic** [comment]
really strange...are you building with the latest source ?

**Comment by Nanoatic** [comment]
@jetcostar can you do another screenshot of the files included with your executable?

**Comment by jetcostar** [comment]
https://github.com/nextcloud/desktop

I used this code.

![1](https://user-images.githubusercontent.com/55017822/64487258-541ead00-d1f5-11e9-89c8-b1ca27a3f485.png)
![2](https://user-images.githubusercontent.com/55017822/64487259-541ead00-d1f5-11e9-909e-1deeb9c6a986.png)

**Comment by jetcostar** [comment]
If possible , let me know your mail address .

**Comment by Nanoatic** [comment]
@jetcostar nanoaticorgix@hotmail.com

**Comment by jetcostar** [comment]
That problem was resolved successfully.
I used upgraded 2 files. ( libcrypto-1_1-x64.dll , libssl-1_1-x64.dll )
Everything is okay.
Thank you very much. @Nanoatic
