### ISSUE TITLE
[Bug]: System Error - libcrypto-1_1-x64.dll not found after update to 3.9.1 (Windows 11)

### ISSUE THREAD

**Issue by phil-lipp** [nextcloud/desktop#5924]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After updating to 3.9.1 my previously fully functional installation now throws an error on startup.

### Steps to reproduce

1. update to 3.9.1
2. (try to) start the programm

### Expected behavior

No error or provide the required dll.

### Which files are affected by this bug

libcrypto-1_1-x64.dll

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Other

### Nextcloud Server version

27.0.1

### Nextcloud Desktop Client version

3.9.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

![Screenshot 2023-07-25 140415](https://github.com/nextcloud/desktop/assets/52623794/04660088-7658-4377-b0d5-1121ac4e3f3a)

**Comment by mgallien** [comment]
this is already fixed and updated packages have been pushed
sorry for the trouble
please reinstall it or use the same installer in repair mode

**Comment by samanoskay** [comment]
Still getting this error from a fresh install using winget, soon as I install it requires upgrade to 3.9.1 and once upgraded says the dll file is not present and fails to run.

**Comment by bohni** [comment]
Using the msi package from nextcloud downlad page, the client starts after a reboot without error.

Using winget, after reboot an update is installed leading to the error, as mentioned from @samanoskay

**Comment by Olray** [comment]
Just experienced the same problem (updated at 17:59 CEST Europe/Berlin) so the auto updater is probably pulling the wrong package

**Comment by Liffecs** [comment]
> Just experienced the same problem (updated at 17:59 CEST Europe/Berlin) so the auto updater is probably pulling the wrong package

As @bohni  already said. You have to take the MSI. Winget is there like pypi, ziehmlich slow. Since aktuallisierung takes quite a long time, although the new packages are online :)

With the MSI there is in any case no more problem :)

**Comment by Olray** [comment]
And as I said, I never used Winget but installed from the original MSI package months ago. It's the **automatic update process** that trashed my install. Repair worked. But tens of thousands of long-term users might experience the same problem in the next few days.

**Comment by prissi** [comment]
This is not really fixed, on Japanese Windows the manual install with MSI still gets this message. Repair did not worked. Uninstalling, reboot, reinstall have nextclound complain about the update failing and "please update to nextcloud 3.9.1". Selecting manual update and doing nothing gives a working installation with companing about a failing update at every start.

**Comment by irdiOL** [comment]
Just got a report from a client with the same problem. Tried also rolling back to 3.9.0 with the same issue poping up.

**Comment by Liffecs** [comment]
> Just got a report from a client with the same problem. Tried also rolling back to 3.9.0 with the same issue poping up.

The easiest solution is to simply uninstall Nextcloud and then reinstall it via the installer. Works without problems. Please download the installer from the website. The issue or problem was closed a long time ago :)

**Comment by albgus** [comment]
This bug is not fixed. It still appears when doing the automatic updates.

Just because there's a workaround to manually download a installer from your website doesn't solve the issue for all installed clients that may run the regular manual update process suggested by the client.

**Comment by iwikus** [comment]
Bug is not fixed. Nextcloud did automatic update and now is unable to start!

![image](https://github.com/nextcloud/desktop/assets/30178330/6100600b-f1d4-4e36-98bb-379d49970b26)
