### ISSUE TITLE
Filters and sort in the Activities tab

### ISSUE THREAD

**Issue by camilasan** [nextcloud/desktop#608]
@jospoortvliet 's idea. 

What do you think @jancborchardt?

**Comment by vitaliis** [comment]
Hello @camilasan ,
That is a good suggestion! And such a filter functionality would be really-really helpful.

### One of the use cases:
When some folder has conflicts in it, in the list of all configured sync folders, there is a message box saying "There are unresolved conflicts. Click for details". But after click you see a list of completely unrelated messages and warnings, like "File/Folder is ignored because it is hidden" or "File is listed on the ignore list". Opened list is full of such messages and I have no idea which conflicts and where I have to resolve.

### Filters
It would be nice to have a line above these messages with some filters, such as:
* by type (conflict, warning or whichever types there are)
* by configured folder (like Documents, Photos, etc) to limit selection to particular folder
* maybe some other can be helpful (like filtering by some text). Not really relevant to my case, but could be useful in some cases I assume.

### Sorting
Implementing sort might be a separate issue. Although I am not sure how useful this would be. Sorting messages by date is already done. Maybe a switch to sort by date backwards can be useful. But for me other types of sorting are hard to imagine to be useful.

### Summary
So in my case, filtering "Activity" by type:"conflict" and folder:"Docs" would already help and be sufficient.

**Comment by jancborchardt** [comment]
@vitaliis your use case is not properly solved by filters. We rather need to improve the error and conflict display. 

@camilasan @jospoortvliet sure, a search box with additional filters might be nice. But I’m wondering if we are overengineering here and putting work into something no one will use. So I prefer to work based on specific cases and examples where you _actually_ needed this, rather than "hey we could add this". :)

**Comment by vitaliis** [comment]
@jancborchardt Ok, it is not completely solved, but it is at least some info and assistance in solving the problem at hand.

Instead of discussing this topic with conflicts here, I created a separate ticket for it. So we can move this discussion here #872

**Comment by vitaliis** [comment]
@jancborchardt I have one use case (at least with the current state of how things are displayed):
right now all the hidden files are being displayed on top of the list and you can't really see what has happened right now. It happens because **all** files that are hidden are being reported in this "Activity" view. And it results in all recent activities being somewhere down in the list.
I can elaborate on this if you need more details.

**Comment by jancborchardt** [comment]
@vitaliis hm … hidden files are set to sync by default though, so they should not receive special treatment?

But yes, all ignored files should be grouped in one entry rather than having a separate one for each. @camilasan what do you think?

**Comment by vitaliis** [comment]
Hm, but the list of hidden files can be really large. One of the issues it might introduce would be related to scrolling. You can not scroll somewhere to the middle of the list. I could say it is not position based, but item based. So you can not have the item on the top of the list to be displayed only by half, so either it or the second item, but not somewhere in the middle. 

Can somebody explain to me why scrolling is so weird in the UI? Is it because of a particular UI-framework being used? Or is it an intended feature? By weird I mean the lack of smooth scrolling (see above).

**Comment by jancborchardt** [comment]
Let’s continue in **Activity tray and activity list design improvements #889** to not have 3 different issues about basically the same thing. :)

**Comment by vitaliis** [comment]
Can somebody please still explain me this peculiarity with scrolling? Why scrolling is so discreet and not smooth?

**Comment by jancborchardt** [comment]
@vitaliis could I ask you to open a separate issue for that? Make sure to include info like app version, operating system etc. Thanks a lot! :)
