### ISSUE TITLE
[Bug]: Unable to sync with multiple accounts due to missing UI elements

### ISSUE THREAD

**Issue by taiBsu** [nextcloud/desktop#6167]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I recently reinstalled Nextcloud Desktop (3.10.0 (KDE); flatpak) on Pop!_OS (Ubuntu) 22.04 LTS. I was able to successfully connect to my primary account on my private instance, however when I opened the main window trying to sync my secondary account, I couldn't get to it because UI elements are missing - not only visually **but also physically** (I just can't click anything):
![grafik](https://github.com/nextcloud/desktop/assets/8024663/8f66358a-1ddf-4bf0-be18-7cec53d4502f)
Clicking anywhere in the white space below my account icon **doesn't do anything**, however clicking the buttons to the right of the folder icon on the top right corner works, so it doesn't seem to be a simple theming problem (or if so, there might be a Qt element scaling problem).

When running nextcloud via cli (`flatpak run com.nextcloud.desktopclient.nextcloud`), the only output I get is qt.qpa.qgnomeplatform: Could not find color scheme "".

When using the AppImage binary, my secondary account is automatically linked already (which however it doesn't seem to be when using the flatpak version since files don't synchronize at all on that account) and everything seems to work just fine.

I really don't want to use the AppImage version for multiple reasons, how can this problem be solved?

I've found a similar issue [here](https://github.com/nextcloud/desktop/issues/5847).

Thanks in advance.

### Steps to reproduce

1. Download Nextcloud via flatpak
2. Run nextcloud
3. Open main dialog

### Expected behavior

Main dialog should be shown properly.

### Which files are affected by this bug

flatpak version: com.nextcloud.desktopclient.nextcloud

### Operating system

Linux

### Which version of the operating system you are running.

Pop!_OS 22.04 LTS

### Package

Other

### Nextcloud Server version

27.1.2

### Nextcloud Desktop Client version

3.10.0 (KDE)

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by p-fruck** [comment]
Hey there, please note that this is an issue with the flatpak version of the nextcloud desktop client maintained [here](https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/).

I submitted a [PR](https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/pull/130/) which sets the app theme to kde instead of gnome which fixes this issue. You should be able to override the environment variables and set `QT_QPA_PLATFORMTHEME=kde` to fix the issue until a new version released

**Comment by BryanMaker** [comment]
@p-fruck Thanks for mentioning adding environment variables, for those who don't want to reinstall but just want to repair the current installation. It is recommended to use the tool Flatseal (https://www.linuxfordevices.com/tutorials/linux/themeing-flatpak-application) for modification, you just need to navigate to nextcloud and then navigate to the environment variables section and add QT_QPA_PLATFORMTHEME=kde and then restart nextcloud

**Comment by joshtrichards** [comment]
Fixed in https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/pull/130/

And outside the scope of this repository.  :-)

**Comment by thsnielsen** [comment]
This one is back (and has been a problem a while not just the version below )
I am using : 
nextcloud-desktop-3.12.3-1.1.x86_64
on 
lenovo@localhost ~> kinfo
Operating System: openSUSE Tumbleweed 20240412
KDE Plasma Version: 6.0.3
KDE Frameworks Version: 6.0.0
Qt Version: 6.7.0
Kernel Version: 6.8.4-rc1-1-default (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i7-2620M CPU @ 2.70GHz
Memory: 15.5 Gio of RAM
Graphics Processor: Mesa Intel® HD Graphics 3000


![image](https://github.com/nextcloud/desktop/assets/16719354/aea1d103-59e1-4494-b669-ba6098201507)

**Comment by TacticalLaptopBag** [comment]
Same problem here, and adding `QT_QPA_PLATFORMTHEME=kde` in FlatSeal did not resolve the issue. I am on GNOME though, so maybe this has an effect?

**Comment by TacticalLaptopBag** [comment]
Same problem here, and adding `QT_QPA_PLATFORMTHEME=kde` in FlatSeal did not resolve the issue. I am on GNOME though, so maybe this has an effect?

EDIT: On Debian 12, installing the `nextcloud-desktop` deb package via apt seems to work fine. I think I'll just use this for the time being.

**Comment by IPlayZed** [comment]
I am on Arch Linux, using 3.12.3 from Flathub, adding the `QT_QPA_PLATFORMTHEME=kde` does NOT solve this issue!

**Comment by sigreer** [comment]
Same issue on Manjaro using both AppImage and Flatpak. Issue is exists on both my desktop and laptop (both using KDE6 on Manjaro).

**Comment by mandrewsan** [comment]
Same issue. Fedora 40, KDE 6.1.1. Downloaded from Fedora repo via dnf.

**Comment by sigreer** [comment]
I can confirm that using the git repo on the AUR fixes the issue for Arch-based distros.
