### ISSUE TITLE
[Bug]: Invalid warning logged on start-up

### ISSUE THREAD

**Issue by robeke** [nextcloud/desktop#6201]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

During startup, the following warning is logged: `nextcloud[2402]: nextcloud.gui.application: Failed to move the old config directory to its new location ( "/home/xxxxxxx/.local/share/Nextcloud" to "/home/xxxxxxx/.config/Nextcloud" )`
I believe this is an invalid warning since my  `~/.config/Nextcloud` directory already contains `nextcloud.cfg` and a series of monthly backups.  The directory `~/.local/share/Nextcloud` does not contain `nextcloud.cfg` but does contain a `*_sync.log` file for each folder sync connection.  There is also a `*_sync.log` file for each folder sync connection under `~/.config/Nextcloud` but these no longer appear to be up-to-date compared to those under `~/.local/share/Nextcloud`.  Is it possible that the `*_sync.log` files in `~/.config/Nextcloud` are OBE and need to be removed?  The Desktop Client appears to work at this point but I would have no way to know if the cause of this warning would eventually lead to a break in client functionality.

### Steps to reproduce

Start the Nextcloud Client and view the message in the system log.

### Expected behavior

The message should either correctly state the condition it is warning about or not be generated.

### Which files are affected by this bug

nextcloud.cfg

### Operating system

Linux

### Which version of the operating system you are running.

Manjaro

### Package

Distro package manager

### Nextcloud Server version

24.0.12

### Nextcloud Desktop Client version

3.10.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by robeke** [comment]
I also observed one warning for each folder sync connection log immediately following the one above:
```
Nov 06 14:13:58 dv6-2150 nextcloud[2402]: nextcloud.gui.application: Fallback move of  "xxxxxx_sync.log" also failed
Nov 06 14:13:58 dv6-2150 nextcloud[2402]: nextcloud.gui.application: Fallback move of  "xxxx_sync.log" also failed
Nov 06 14:13:58 dv6-2150 nextcloud[2402]: nextcloud.gui.application: Fallback move of  "xxxxx_sync.log" also failed
```

**Comment by Janov911** [comment]
same here, on my steam deck (checking other machines this evening):

nextcloud.gui.application: Migrating old config from "/home/deck/.var/app/com.nextcloud.desktopclient.nextcloud/data/Nextcloud" to "/home/deck/.var/app/com.nextcloud.desktopclient.nextcloud/config/Nextcloud"
nextcloud.gui.application: Failed to move the old config directory to its new location ( "/home/deck/.var/app/com.nextcloud.desktopclient.nextcloud/data/Nextcloud" to "/home/deck/.var/app/com.nextcloud.desktopclient.nextcloud/config/Nextcloud" )
nextcloud.gui.application: Will move the individual files ("backup_sync.log", "crypto_sync.log", "Desktop_sync.log", "docker-workshop_sync.log", "Documents_sync.log", "joplin_sync.log", "tasks_sync.log", "temp_sync.log", "wallpapers_sync.log")
nextcloud.gui.application: Fallback move of  "backup_sync.log" also failed
nextcloud.gui.application: Fallback move of  "crypto_sync.log" also failed
nextcloud.gui.application: Fallback move of  "Desktop_sync.log" also failed
nextcloud.gui.application: Fallback move of  "docker-workshop_sync.log" also failed
nextcloud.gui.application: Fallback move of  "Documents_sync.log" also failed
nextcloud.gui.application: Fallback move of  "joplin_sync.log" also failed
nextcloud.gui.application: Fallback move of  "tasks_sync.log" also failed
nextcloud.gui.application: Fallback move of  "temp_sync.log" also failed
nextcloud.gui.application: Fallback move of  "wallpapers_sync.log" also failed

**Comment by joshtrichards** [comment]
The migration only runs if *oldDir* exists:

https://github.com/nextcloud/desktop/blob/ab3e4e724f18601e61dca0634f31ef7571f9b3f6/src/gui/application.cpp#L492-L493

The migration itself normally would rename *oldDir* to *newDir* (aka: `confDir`) and if that fails logs the message you're seeing:

https://github.com/nextcloud/desktop/blob/ab3e4e724f18601e61dca0634f31ef7571f9b3f6/src/gui/application.cpp#L504-L505

Then it falls back on trying to move the files within *oldDir* one-by-one:

https://github.com/nextcloud/desktop/blob/ab3e4e724f18601e61dca0634f31ef7571f9b3f6/src/gui/application.cpp#L507-L517

There are some other spots where migration can happen - e.g.:

https://github.com/nextcloud/desktop/blob/ab3e4e724f18601e61dca0634f31ef7571f9b3f6/src/libsync/configfile.cpp#L343-L366

Notably, the `_sync.log` files figure out their path here:

https://github.com/nextcloud/desktop/blob/ab3e4e724f18601e61dca0634f31ef7571f9b3f6/src/gui/syncrunfilelog.cpp#L35

> During startup, the following warning is logged: nextcloud[2402]: nextcloud.gui.application: Failed to move the old config directory to its new location ( "/home/xxxxxxx/.local/share/Nextcloud" to "/home/xxxxxxx/.config/Nextcloud" )
> I believe this is an invalid warning since my ~/.config/Nextcloud directory already contains nextcloud.cfg and a series of monthly backups. 

It's valid because for some reason the simple rename migration didn't originally cover you for some reason. It just means the fallback mode kicks in (one-by-one above). The fallback kicking in now makes sense because you have *both* old and new directories now so a simple rename of the old directory won't work.

The questions are:

- why weren't you migrated entirely previously? :thinking: 
  - any chance you had two clients running simultaneously - or two versions installed - at some point or something?
- why are your `_sync.log` logs being written to your *old* path? :thinking: 

> The directory ~/.local/share/Nextcloud does not contain nextcloud.cfg but does contain a *_sync.log file for each folder sync connection. There is also a *_sync.log file for each folder sync connection under ~/.config/Nextcloud but these no longer appear to be up-to-date compared to those under ~/.local/share/Nextcloud. Is it possible that the *_sync.log files in ~/.config/Nextcloud are OBE and need to be removed? The Desktop Client appears to work at this point but I would have no way to know if the cause of this warning would eventually lead to a break in client functionality.

P.S. Manjaro's package data is weird. It says 3.10.1 on the listing on their web site but when you click on it it's for 3.9 and links to an invalid broken build source link.

**Comment by robeke** [comment]
@joshtrichards Thanks for helpfull insight.  On my Manjaro desktop, the *_sync.log files under .local/share/Nextcloud have a current modification date (Nov 16) whereas those under .config/Nextcloud have not been modified since Nov 6.  The update history for my system shows `23-11-06T07:50:38-0500] [ALPM] upgraded nextcloud-client (2:3.10.0-2 -> 2:3.10.1-1)` so it appears that after that upgrade, the *_sync.log files under .config/Nextcloud are being ignored.  

Based on the code blocks you included, it makes sense that the *_sync.log files are expected to be found in the standard data location whereas the nextcloud.cfg is expected to be in the standard config location.  Given this, "oldDir" for the *_sync.log files would be .config/Nextcloud directory.  However, this was created by Nextcloud more than two years ago and as the standard config location is still being used to contain the nextcloud.cfg file (and backups) as well as cookies0.db, sync-exclude.lst, and a logs subdirectory containing the application log, i.e., 20231116_0812_nextcloud.log.1 with previous logs as archives.  In this configuration, renaming oldDir to newDir does not really make sense.  It may just be simply that the *_sync.log files under .config/Nextcloud are now OBE and should be removed.

**Comment by mephinet** [comment]
The old directory is re-created every time:
```sh
rm -rf ~/.local/share/Nextcloud/
nextcloud &
ls -d ~/.local/share/Nextcloud/
/home/.../.local/share/Nextcloud/
```
and it contains a new log file for each sync target. I'm here on Linux with version 3.10.1

**Comment by SlappyHours** [comment]
Same problem here on Linux with 3.10.1: `.local/share/Nextcloud` gets recreated. Next start shows error message because of failed migration.

**Comment by adrianvg** [comment]
Just updated the desktop client Linux Appimage from https://nextcloud.com/install/#install-clients from version 3.10.0 to the latest 3.11.0 and seeing the same thing. 


```
nextcloud.gui.application: Migrating old config from "/home/username/.local/share/Nextcloud" to "/home/username/.config/Nextcloud"
nextcloud.gui.application: Failed to move the old config directory to its new location ( "/home/username/.local/share/Nextcloud" to "/home/username/.config/Nextcloud" )
nextcloud.gui.application: Will move the individual files ("Nextcloud_sync.log")
nextcloud.gui.application: Fallback move of  "Nextcloud_sync.log" also failed
```


Tried deleteing /home/username/.local/share/Nextcloud but still getting the error message.
The client still seems to work though.

Is this is a cosmetical problem only, or may things keel over later?

**Comment by djtulan** [comment]
Also on 3.11.1 Appimage Client

**Comment by ecsgh** [comment]
I can confirm this. 
If you delete .local/share/Nextcloud and start nextcloud, no error message appears. 
But only on the first start. 
After that, however, the error "Failed to move the old config directory to its new location" occurs again and again
All files are migrated to ./config/Nextcloud except for the log file Nextcloud_sync.log. 
This is always created under .local/share/Nextcloud.

**Comment by Tachi107** [comment]
@joshtrichards said:

> why are your `_sync.log` logs being written to your _old_ path? 🤔

That's because, as you mentioned, the `_sync.log` files created by the [`SyncRunFileLog::start()`](https://github.com/nextcloud/desktop/blob/11900b708073d2b160b1b1d34493451a3587f0fe/src/gui/syncrunfilelog.cpp#L31) function are created in the `QStandardPaths::writableLocation(QStandardPaths::AppDataLocation)` directory, which expands to `~/.local/share/Nextcloud/`.

Then, on the following application launch, the [Application::setupConfigFile()](https://github.com/nextcloud/desktop/blob/11900b708073d2b160b1b1d34493451a3587f0fe/src/gui/application.cpp#L512-L514) function sees the previously created `~/.local/share/Nextcloud/` directory, and (wrongly) tries to move it to `~/.config/Nextcloud/`, failing because it already exists.

In my opinion, to properly fix this issue a couple of things have to change:

1. Logs shouldn't be written in `~/.local/share/Nextcloud/` nor in `~/.config/Nextcloud/logs/`, but should be instead be created in `$XDG_STATE_HOME` (`~/.local/state/`), as explicitly mentioned in the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).
2. The migration logic should be modified to only try to move `.cfg` files from `~/.local/share/Nextcloud/` to `/.config/Nextcloud/`, and not the whole directory. Then, it should remove all files from `~/.local/share/Nextcloud/` matching known patterns like `_sync.log`, and try to delete the `~/.local/share/Nextcloud/` folder as if using [`std::filesystem::remove()`](https://en.cppreference.com/w/cpp/filesystem/remove) so that the directory doesn't get deleted if users put some custom file there.

As far as I understand, this should fix this issue, and make the desktop client a bit more conforming to the XDG guidelines :)

**Comment by johanneskastl** [comment]
Any news on this?
(I am not sure if this issue is the cause, but I have 700MB of logs in .config/Nextcloud currently. Not sure if that is caused by the multiple attempts to migrate things or if it is unrelated)

**Comment by djtulan** [comment]
I use Nextcloud-3.13.0-x86_64.AppImage and recently I upgraded my Kubuntu from 22.04 to 24.04 LTS (maybe that has an impact?)

**Comment by leogzyl** [comment]
> Edit: `QStandardPaths` doesn't seem to have an enum value representing `$XDG_STATE_HOME`, but I guess `QStandardPaths::CacheLocation` (expanding to `~/.local/cache/`) should be a good enough alternative.

@Tachi107 Don't know if I'm missing something, but how about `StateLocation`? 
[https://doc.qt.io/qt-6/qstandardpaths.html](https://doc.qt.io/qt-6/qstandardpaths.html)

**Comment by tiesel** [comment]
I had the problem that nextcloud client was hangig for long times and sometimes even wasn't able to sync at all.
This could be worked around here under Fedora 40 with client 3.13.2-1 and now the client is responsive again and syncs as it should:

* Turn off the Settings - General - Launch on system startup option
* Exit the Nextcloud client if it is running (not only closing -- check that the process isn't running anymore)
* If there are newer (by date and time) bla_sync.log files in the old `~/.local/share/Nextcloud/` than in the new `~/.config/Nextcloud` folder: Copy them from old to new
* Move away the old `~/.local/share/Nextcloud/`
* Create a symlink (`ln -s ~/.config/Nextcloud ~/.local/share/Nextcloud`)

This creates even more journalctl entries "Failed to move" and "Fallback move ... also failed" but in the end it works.
We shouldn't forget to check from time to time if the problem is fixed and to take away the symlink then.

**Comment by erebion** [comment]
> If there are newer (by date and time) bla_sync.log files in the old `~/.local/share/Nextcloud/` than in the new `~/.config/Nextcloud` folder: Copy them from old to new

Hell no, it should **NEVER** place log files in the config directory!

Please, just read the spec everyone: https://specifications.freedesktop.org/basedir-spec/latest/index.html

It clearly states the following:

>$XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

And for the state directory:

>The $XDG_STATE_HOME contains state data that should persist between (application) restarts, but that is not important or portable enough to the user that it should be stored in $XDG_DATA_HOME. It may contain:
>
> actions history (logs, history, recently used files, …)
>
> current state of the application that can be reused on a restart (view, layout, open files, undo history, …)

Please... Just **don't** ever put **log files in a config directory**.

That like putting the Nextcloud server log in `/etc/nginx/nextcloud.log`, who the hell would do that?!

There's a standard for a reson.

One of those reasons is that **users could sync their config directories between machines if they only contained config... And not the state**. But this **just breaks** every time an application puts stuff there that is *definitely* not config. Electron, for instance, just puts the bloody cache in that damn directory. WTF, **cache is not config**.

Another one is that **users could easily backup their config**. If users backup their Nextcloud config, they will also **accidentally backup log files**, which just **unnecessarily** use up disk space, even though it has **never been intended** to backup those as well.


Just follow the standard please. Some very clever people put a lot of thought into it.

**Comment by erebion** [comment]
> If there are newer (by date and time) bla_sync.log files in the old `~/.local/share/Nextcloud/` than in the new `~/.config/Nextcloud` folder: Copy them from old to new

Hell no, it should **NEVER** place log files in the config directory!

Please, just read the spec everyone: https://specifications.freedesktop.org/basedir-spec/latest/index.html

It clearly states the following:

>$XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

And for the state directory:

>The $XDG_STATE_HOME contains state data that should persist between (application) restarts, but that is not important or portable enough to the user that it should be stored in $XDG_DATA_HOME. It may contain:
>
> actions history (logs, history, recently used files, …)
>
> current state of the application that can be reused on a restart (view, layout, open files, undo history, …)

Please... Just **don't** ever put **log files in a config directory**.

That's like putting the Nextcloud server log in `/etc/nginx/nextcloud.log`, who the hell would do that?!

There's a standard for a reson.

One of those reasons is that **users could sync their config directories between machines if they only contained config... And not the state**. But this **just breaks** every time an application puts stuff there that is *definitely* not config. Electron, for instance, just puts the bloody cache in that damn directory. WTF, **cache is not config**.

Another one is that **users could easily backup their config**. If users backup their Nextcloud config, they will also **accidentally backup log files**, which just **unnecessarily** use up disk space, even though it has **never been intended** to backup those as well.


Just follow the standard please. Some very clever people put a lot of thought into it.

**Comment by Tachi107** [comment]
Hi @erebion, we clearly all know that the Nextcloud client is currently doing stuff wrong, and in https://github.com/nextcloud/desktop/issues/6201#issuecomment-1962299217 I've already mentioned what should be done instead. Please calm down :)

**Comment by erebion** [comment]
I couldn't not spot any link to the spec yet, nor an excerpt. It seemeed only logical to clarify.

**Comment by JakobHeubl** [comment]
Can confirm that this issue is still open - I am currently experiencing this issue on manjaro linux:
`Failed to initialize instances shared memory:  "QSharedMemory::handle: existiert nicht"
QGuiApplication::setDesktopFileName: the specified desktop file name ends with .desktop. For compatibility reasons, the .desktop suffix will be removed. Please specify a desktop file name without .desktop suffix
nextcloud.gui.application: Migrating old config from "/home/jakob/.local/share/Nextcloud" to "/home/jakob/.config/Nextcloud"
nextcloud.gui.application: Failed to move the old config directory to its new location ( "/home/jakob/.local/share/Nextcloud" to "/home/jakob/.config/Nextcloud" )
nextcloud.gui.application: Will move the individual files QList()
zsh: IOT instruction (core dumped)  nextcloud`

**Comment by jrowberg** [comment]
> I had the problem that nextcloud client was hangig for long times and sometimes even wasn't able to sync at all. This could be worked around here under Fedora 40 with client 3.13.2-1 and now the client is responsive again and syncs as it should:
> ...
> but in the end it works. We shouldn't forget to check from time to time if the problem is fixed and to take away the symlink then.

Right or wrong, sane or insane, this change caused my official-APT-repo `nemo-nextcloud` client on Linux Mint 22 Cinnamon to start working normally again, no longer pegging one of my CPU cores, and presenting a responsive GUI again. Thanks!

**Comment by jrowberg** [comment]
I just implemented a stupidly effective solution which seems to be working on my machine once again, though I need to keep a close eye on it. I used the `nul1fs` simple flat black-hole filesystem utility from this rather old repo:

https://github.com/xrgtn/nullfs

...to give Nextcloud a `/dev/null`-like pit to dump all the log files in that I really don't care about:

```
[Exit/kill Nextcloud client]

$ rm ~/.config/Nextcloud/logs/*
$ ./nul1fs ~/.config/Nextcloud/logs

[Start Nextcloud client]
```

Voila! No more insane log file creation, no SSD wear, no frozen Nextcloud GUI, and Nextcloud is none the wiser.

**Comment by erebion** [comment]
I'd just prefer a setting that disables logging, I don't need it either.

**Comment by J0nas80** [comment]
can say the misbehavior still exists on nc client 3.15.3-1 on arch linux

**Comment by jrowberg** [comment]
Even with my workaround with nullfs, it still freezes if I let it run long enough. For the moment, I've taken to simply running the client once on demand if I switch over to use my laptop, so it can perform one full sync just at that moment. Switching between machines happens (for me) infrequently enough that this isn't a headache, but it's definitely defeating the purpose of an always-active live sync client.

**Comment by ShonkaiDJ** [comment]
Interesting.  After so many years.
On Ubuntu Studio 24.04 KDE 
App v 2.11.0-1 Build4

 Same log overflowing behavior. Same remedy on the next app-start. Same returning behavior o every start after the first one.

**Comment by radoeka** [comment]
Just installed Nextcloud-3.16.2-x86_64.AppImage from Nextcloud.com and got the following warning during launch of the image;

```
nextcloud.gui.application: Migrating old config from "/home/name/.local/share/Nextcloud" to "/home/name/.config/Nextcloud"
nextcloud.gui.application: Failed to move the old config directory to its new location ( "/home/name/.local/share/Nextcloud" to "/home/name/.config/Nextcloud" )
nextcloud.gui.application: Will move the individual files QList("ownCloud_sync.log", "name_ownCloud_sync.log")
nextcloud.gui.application: Fallback move of  "ownCloud_sync.log" also failed
nextcloud.gui.application: Fallback move of  "name_ownCloud_sync.log" also failed
```

Remove the directory `/home/name/.local/share/Nextcloud` does not help, as it is created with the next launch.
There is still some code that creates the "old" and unwanted directory.

**Solution?**

From @joshtrichards in a [comment above](https://github.com/nextcloud/desktop/issues/6201#issuecomment-1962299217) replace 
`const QString logpath = QStandardPaths::writableLocation(QStandardPaths::AppDataLocation);` with
`const QString logpath = QStandardPaths::writableLocation(QStandardPaths::CacheLocation);` in
[SyncRunFileLog::start()] (https://github.com/nextcloud/desktop/blob/11900b708073d2b160b1b1d34493451a3587f0fe/src/gui/syncrunfilelog.cpp#L31)

Hope to see this implemented soon.

**Comment by bernd-wechner** [comment]
I see this too. It's bizarre. Is there manual workaround? Perhaps stopping the client, deleting the target folder and starting the client? Actually I experimented and move the old one as it seemed to contain only a log file while the new one had all the configs:

```
mv ~/.local/share/Nextcloud ~/.local/share/Nextcloud.old
```

Starting the client then saw this error not issued. Success. A manual workaround. 

Interestingly t reports:

```
Failed to initialize instances shared memory:  "QSharedMemory::handle: doesn't exist"
```

and only that when run on the console. And seems to work fine.   Be nice to know why that is.

**Comment by radoeka** [comment]
@bernd-wechner restart again, and the issue is back as the directory is created by the client....

**Comment by 6502c** [comment]
Same problem with Nextcloud-3.16.6-x86_64.AppImage on Debian Bookworm.
The 
`.local/share/Nextcloud/Nextcloud_sync.log`
folder keeps getting recreated.
During the next start it throws the errors/warning/infos about not being able to migrate.

**Comment by nuke1984** [comment]
**Same here with Nextcloud on Ubuntu 22.04:**
Nextcloud version 3.16.6-20250619.170704.957b27497-1.0~jammy1
**from:**
https://ppa.launchpadcontent.net/nextcloud-devs/client/ubuntu jammy
**Error:**
```
nextcloud.gui.application: Migrating old config from (...)
nextcloud.gui.application: Failed to move the old config directory to its new location (...)
nextcloud.gui.application: Will move the individual files QList (...)
nextcloud.gui.application: Fallback move of  (...) also failed
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Invalid or incomplete multibyte or wide character
Aborted (core dumped)
```

**Comment by nocin** [comment]
Same issue on Linux Mint 22.1. The Nextcloud Desktop Client is crashing a few seconds after launching it.

Nextcloud version 3.16.6-20250619.170704.957b27497-1.0~jammy1
Using Qt 6.4.2, built against Qt 6.2.4
Using Qt platform plugin 'xcb'
Using 'OpenSSL 3.0.13 30 Jan 2024'
Running on Linux Mint 22.1, x86_64


```
nextcloud.gui.application: Migrating old config from "/home/xxx/.local/share/Nextcloud" to "/home/xxx/.config/Nextcloud"
nextcloud.gui.application: Failed to move the old config directory to its new location ( "/home/xxx/.local/share/Nextcloud" to "/home/xxx/.config/Nextcloud" )
nextcloud.gui.application: Will move the individual files QList("Fotos_sync.log", "Nextcloud_sync.log")
nextcloud.gui.application: Fallback move of  "Fotos_sync.log" also failed
nextcloud.gui.application: Fallback move of  "Nextcloud_sync.log" also failed
^[[Hterminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Invalid or incomplete multibyte or wide character
[1]    103536 IOT instruction (core dumped)  nextcloud

```

**Comment by nocin** [comment]
With the new version 3.16.6-20250628 the crashes are gone! The “Migration failed” messages are still there. Apparently these had nothing to do with the crashes...

```
nextcloud.gui.application: Migrating old config from "/home/xxx/.local/share/Nextcloud" to "/home/xxx/.config/Nextcloud"
nextcloud.gui.application: Failed to move the old config directory to its new location ( "/home/xxx/.local/share/Nextcloud" to "/home/xxx/.config/Nextcloud" )
nextcloud.gui.application: Will move the individual files QList("Fotos_sync.log", "Nextcloud_sync.log")
nextcloud.gui.application: Fallback move of  "Fotos_sync.log" also failed
nextcloud.gui.application: Fallback move of  "Nextcloud_sync.log" also failed
Nextcloud version 3.16.6-20250628.084039.957b27497-1.0~jammy1
Using Qt 6.4.2, built against Qt 6.2.4
Using Qt platform plugin 'xcb'
Using 'OpenSSL 3.0.13 30 Jan 2024'
Running on Linux Mint 22.1, x86_64

```

**Comment by timo-a** [comment]
Same error message (no crash) with flatpack version `3.16.6daily` on fedora 42.
```
$ flatpak run com.nextcloud.desktopclient.nextcloud
nextcloud.gui.application: Migrating old config from "/home/xxx/.var/app/com.nextcloud.desktopclient.nextcloud/data/Nextcloud" to "/home/xxx/.var/app/com.nextcloud.desktopclient.nextcloud/config/Nextcloud"
nextcloud.gui.application: Failed to move the old config directory to its new location ( "/home/xxx/.var/app/com.nextcloud.desktopclient.nextcloud/data/Nextcloud" to "/home/xxx/.var/app/com.nextcloud.desktopclient.nextcloud/config/Nextcloud" )
nextcloud.gui.application: Will move the individual files QList("myprovider_sync.log")
nextcloud.gui.application: Fallback move of  "myprovider_sync.log" also failed
```

detailed version:

```
$ flatpak run com.nextcloud.desktopclient.nextcloud --version
#same error message as above
Nextcloud version 3.16.6daily
Git revision 957b27497fbe7ca14c26a45e6967a097b96a0add
Using Qt 6.9.0, built against Qt 6.9.0
Using Qt platform plugin 'wayland'
Using 'OpenSSL 3.3.3 11 Feb 2025'
Running on KDE Flatpak runtime, x86_64
```

**Comment by Wikinaut** [comment]
Every version here, also the current `3.17.0`, shows the problematic warning lines, too. I hope, that finally a fix can be found and Nextcloud appimage can start one day without these warnings.

**Comment by bpmartin20** [comment]
Like others, I've found that if I delete .local/share/Nextcloud (while nextcloud-desktop is not running) it comes back on the next run, and the migration tries again on all subsequent runs. 

I'll add that I can stop the errors and the migration cycle by deleting ./local/share/Nextcloud and creating a file of the same name  (e.g. "touch ~/.local/share/Nextcloud"). Because the migration logic tests whether this a _directory_, it doesn't try to migrate. However, this also means all those log files don't get written, ever. So I've traded one problem for another. I consider it an improvement, but not great. I also tried a symlink to ~/.config/Nextcloud, but that had no functional effect.

Details:
Ubuntu 24.04.3 LTS
XFCE 4.18
nextcloud-client 3.17.0
nextcloud-desktop 3.17.0

**Comment by olberger** [comment]
FWIW, related/duplicate issues : #3406 and #7654, which may very well be addressed/fixed by #7868 unless I'm mistaken...

Hth,

**Comment by serge-vk** [comment]
This problem persists with the AppImage client v 4.0.1
The client keeps creating "/home/xxx/.local/share/Nextcloud/yyy_sync.log" files and complaining:
```
nextcloud.gui.application: Will move the individual files QList("yyy_sync.log")
nextcloud.gui.application: Fallback move of  "yyy_sync.log" also failed
```

**Comment by MarkMuth** [comment]
The Nextcloud-4.0.1-x86_64.AppImage does not work on Arch Linux. The graphical user interface only appears when it's run as `QT_QPA_PLATFORM=xcb nextcloud` which might be another bug.

But also the directory `~/.local/share/Nextcloud` has to be deleted manually before every start. This is a severe issue, since without those manual steps, the Nextcloud Client is simply unusable.

**Comment by timmwille** [comment]
I can confirm, since a while now, even after a fresh update to 3.17 the client fails to synch, at least all not token based (SSO) accounts! Leading to the mentioned error message above regarding the migration issue.

`nextcloud --version` 

Output:

```
Nextcloud version 3.17.2daily
Git revision d15dca2ae3b0d6e71c799fb4a439a71bc91cd4c4
Using Qt 6.9.2, built against Qt 6.9.2
Using Qt platform plugin 'xcb'
Using 'OpenSSL 3.5.3 16 Sep 2025'
Running on Manjaro Linux, x86_64
```

I first thought it is a Qt6 issue, but I am not entirely sure and found this issue here, sounds very similar.

(I also tried the symlink hack but it did not do the trick: https://github.com/nextcloud/desktop/issues/6201#issuecomment-2249860056 )

**Comment by tflidd** [comment]
Also still a probelm on [PPA version](https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client) on Ubuntu 24.04:U
```
clientPreviousVersion=4.0.1-20251029.160431.e81c242e13-1.0~noble1
clientVersion=4.0.2-20251125.202432.4d0e5a3a97-1.0~noble1
```
as well as this one
```
clientPreviousVersion=4.0.2-20251125.202432.4d0e5a3a97-1.0~noble1
clientVersion=4.0.3-20251204.181707.98ddb954f8-1.0~noble1
```

**Comment by hottehead** [comment]
Im having the same Issue on

-  MacOS 13.7.1 
- Nextcloud Desktop 4.0.3

```
nextcloud.gui.application: Migrating old config from "/Users/***/Library/Application Support/Nextcloud" to "/Users/***Library/Preferences/Nextcloud"
nextcloud.gui.application: Failed to move the old config directory to its new location ( "/Users/***Library/Application Support/Nextcloud" to "/Users/***/Library/Preferences/Nextcloud" )
nextcloud.gui.application: Will move the individual files QList("enjourney_sync.log", "Nextcloud_sync.log", "private_sync.log", "synapsen-safari_sync.log")
nextcloud.gui.application: Fallback move of  "***.log" also failed
nextcloud.gui.application: Fallback move of  "Nextcloud_sync.log" also failed
nextcloud.gui.application: Fallback move of  "private_sync.log" also failed
nextcloud.gui.application: Fallback move of  "***_sync.log" also failed
```

The Client also says "Some files could not be synced. See below", however I dont see any further information anywhere.

Most important: The VFS Locations  in Finder say "Nextcloud application has been closed. Reopen to reconnect". Currently im unable to use Nextcloud Desktop.


Here are some debug logs

```
2025-12-08 16:23:26:002 [ info nextcloud.sync.credentials.webflow /Volumes/builds/35545/macos-35545/src/gui/creds/webflowcredentials.cpp:411 ]:	request finished QUrl("https://nextcloud.some-domain.com/ocs/v2.php/apps/notifications/api/v2/notifications?format=json") with request id "e79715ca-5b7b-44fc-a441-c9a995026ffb"
2025-12-08 16:23:26:002 [ info nextcloud.sync.networkjob.jsonapi /Volumes/builds/35545/macos-35545/src/libsync/networkjobs.cpp:1118 ]:	JsonApiJob of QUrl("https://nextcloud.some-domain.com/ocs/v2.php/apps/notifications/api/v2/notifications?format=json") FINISHED WITH STATUS "OK"
2025-12-08 16:23:26:002 [ warning nextcloud.sync.networkjob.jsonapi /Volumes/builds/35545/macos-35545/src/libsync/networkjobs.cpp:1139 ]:	Nothing changed so nothing to retrieve - status code:  304
2025-12-08 16:23:26:002 [ info nextcloud.gui.servernotification /Volumes/builds/35545/macos-35545/src/gui/tray/notificationhandler.cpp:80 ]:	Status code  304  Not Modified - No new notifications.
2025-12-08 16:23:26:002 [ info nextcloud.sync.credentials.webflow /Volumes/builds/35545/macos-35545/src/gui/creds/webflowcredentials.cpp:411 ]:	request finished QUrl("https://nextcloud.some-domain.com/apps/firstrunwizard/img/apps/groupfolders.svg") with request id "e312fec5-6d2b-43ad-a063-98cc632fcc9b"
2025-12-08 16:23:26:027 [ info nextcloud.sync.credentials.webflow /Volumes/builds/35545/macos-35545/src/gui/creds/webflowcredentials.cpp:411 ]:	request finished QUrl("https://nextcloud.some-domain.com/ocs/v2.php/apps/activity/api/v2/activity?previews=true&since=0&limit=50&format=json") with request id "1166ba62-6d79-4d11-888d-7d15d2defede"
2025-12-08 16:23:26:027 [ info nextcloud.sync.networkjob.jsonapi /Volumes/builds/35545/macos-35545/src/libsync/networkjobs.cpp:1118 ]:	JsonApiJob of QUrl("https://nextcloud.some-domain.com/ocs/v2.php/apps/activity/api/v2/activity?previews=true&since=0&limit=50&format=json") FINISHED WITH STATUS "OK"
2025-12-08 16:23:26:042 [ info nextcloud.sync.accessmanager /Volumes/builds/35545/macos-35545/src/libsync/accessmanager.cpp:72 ]:	2 "" "https://nextcloud.some-domain.com/apps/theming/img/core/filetypes/folder.svg?v=37966e65" has X-Request-ID "a78f2c64-d472-4e92-b867-d9a996e228d9"
2025-12-08 16:23:26:042 [ info nextcloud.sync.accessmanager /Volumes/builds/35545/macos-35545/src/libsync/accessmanager.cpp:72 ]:	2 "" "https://nextcloud.some-domain.com/apps/files/img/delete-color.svg" has X-Request-ID "4f943953-ad1a-45c9-ae41-787aa7a6acf2"
2025-12-08 16:23:26:067 [ info nextcloud.sync.credentials.webflow /Volumes/builds/35545/macos-35545/src/gui/creds/webflowcredentials.cpp:411 ]:	request finished QUrl("https://nextcloud.some-domain.com/apps/files/img/delete-color.svg") with request id "4f943953-ad1a-45c9-ae41-787aa7a6acf2"
2025-12-08 16:23:26:087 [ info nextcloud.gui.mac.fileprovider.settingscontroller /Volumes/builds/35545/macos-35545/src/gui/macOS/fileprovidersettingscontroller_mac.mm:259 ]:	Fetching used storage space of materialized items.
2025-12-08 16:23:26:149 [ warning nextcloud.gui.mac.fileprovider.settingscontroller /Volumes/builds/35545/macos-35545/src/gui/macOS/fileprovidersettingscontroller_mac.mm:263 ]:	Could not get file provider domains: Das Programm kann gerade nicht verwendet werden. Will try again in 2 secs
2025-12-08 16:23:26:281 [ info nextcloud.sync.credentials.webflow /Volumes/builds/35545/macos-35545/src/gui/creds/webflowcredentials.cpp:411 ]:	request finished QUrl("https://nextcloud.some-domain.com/apps/theming/img/core/filetypes/folder.svg?v=37966e65") with request id "a78f2c64-d472-4e92-b867-d9a996e228d9"
2025-12-08 16:23:28:150 [ info nextcloud.gui.mac.fileprovider.settingscontroller /Volumes/builds/35545/macos-35545/src/gui/macOS/fileprovidersettingscontroller_mac.mm:259 ]:	Fetching used storage space of materialized items.
2025-12-08 16:23:28:219 [ warning nextcloud.gui.mac.fileprovider.settingscontroller /Volumes/builds/35545/macos-35545/src/gui/macOS/fileprovidersettingscontroller_mac.mm:263 ]:	Could not get file provider domains: Das Programm kann gerade nicht verwendet werden. Will try again in 2 secs
2025-12-08 16:23:30:220 [ info nextcloud.gui.mac.fileprovider.settingscontroller /Volumes/builds/35545/macos-35545/src/gui/macOS/fileprovidersettingscontroller_mac.mm:259 ]:	Fetching used storage space of materialized items.
2025-12-08 16:23:30:290 [ warning nextcloud.gui.mac.fileprovider.settingscontroller /Volumes/builds/35545/macos-35545/src/gui/macOS/fileprovidersettingscontroller_mac.mm:263 ]:	Could not get file provider domains: Das Programm kann gerade nicht verwendet werden. Will try again in 2 secs
2025-12-08 16:23:30:499 [ warning nextcloud.sync.configfile /Volumes/builds/35545/macos-35545/src/libsync/configfile.cpp:713 ]:	Default update channel is "stable"
2025-12-08 16:23:30:500 [ warning nextcloud.sync.configfile /Volumes/builds/35545/macos-35545/src/libsync/configfile.cpp:713 ]:	Default update channel is "stable"
2025-12-08 16:23:30:511 [ info nextcloud.gui.macos.fileprovider.xpc /Volumes/builds/35545/macos-35545/src/gui/macOS/fileproviderxpc_mac.mm:184 ]:	Checking if fast enumeration is enabled for file provider domain "2176ab1a-99b7-4036-9589-8e53e08ab60f"
2025-12-08 16:23:30:511 [ warning nextcloud.gui.macos.fileprovider.xpc /Volumes/builds/35545/macos-35545/src/gui/macOS/fileproviderxpc_mac.mm:188 ]:	Could not get service for file provider domain "2176ab1a-99b7-4036-9589-8e53e08ab60f"
2025-12-08 16:23:30:515 [ info nextcloud.sync.clientsideencryption /Volumes/builds/35545/macos-35545/src/libsync/clientsideencryption.cpp:1053 ]:	Initializing
2025-12-08 16:23:30:515 [ info nextcloud.sync.clientsideencryption /Volumes/builds/35545/macos-35545/src/libsync/clientsideencryption.cpp:1055 ]:	No Client side encryption available on server.
2025-12-08 16:23:30:516 [ info nextcloud.gui.account.settings /Volumes/builds/35545/macos-35545/src/gui/accountsettings.cpp:1392 ]:	Account "admin@nextcloud.some-domain.com" Client Side Encryption false
2025-12-08 16:23:30:517 [ info nextcloud.sync.accessmanager /Volumes/builds/35545/macos-35545/src/libsync/accessmanager.cpp:72 ]:	2 "" "https://nextcloud.some-domain.com/ocs/v1.php/cloud/user?format=json" has X-Request-ID "4a676ccb-af21-4ad6-aca6-d96cdaf5ae8a"
2025-12-08 16:23:30:517 [ info nextcloud.sync.networkjob /Volumes/builds/35545/macos-35545/src/libsync/abstractnetworkjob.cpp:368 ]:	OCC::JsonApiJob created for "https://nextcloud.some-domain.com" + "ocs/v1.php/cloud/user" "OCC::UserInfo"
2025-12-08 16:23:30:517 [ info nextcloud.sync.accessmanager /Volumes/builds/35545/macos-35545/src/libsync/accessmanager.cpp:72 ]:	2 "" "https://nextcloud.some-domain.com/ocs/v1.php/cloud/user?format=json" has X-Request-ID "149016d9-3161-4dd8-8d6e-f168b9602676"
2025-12-08 16:23:30:517 [ info nextcloud.sync.networkjob /Volumes/builds/35545/macos-35545/src/libsync/abstractnetworkjob.cpp:368 ]:	OCC::JsonApiJob created for "https://nextcloud.some-domain.com" + "ocs/v1.php/cloud/user" "OCC::UserInfo"
2025-12-08 16:23:30:519 [ info nextcloud.gui.macos.fileprovider.xpc /Volumes/builds/35545/macos-35545/src/gui/macOS/fileproviderxpc_mac.mm:184 ]:	Checking if fast enumeration is enabled for file provider domain "0cda3295-5d6e-4b72-870d-b9ef3bf11cb1"
2025-12-08 16:23:30:519 [ warning nextcloud.gui.macos.fileprovider.xpc /Volumes/builds/35545/macos-35545/src/gui/macOS/fileproviderxpc_mac.mm:188 ]:	Could not get service for file provider domain "0cda3295-5d6e-4b72-870d-b9ef3bf11cb1"
2025-12-08 16:23:30:521 [ info nextcloud.sync.clientsideencryption /Volumes/builds/35545/macos-35545/src/libsync/clientsideencryption.cpp:1053 ]:	Initializing
2025-12-08 16:23:30:521 [ info nextcloud.sync.clientsideencryption /Volumes/builds/35545/macos-35545/src/libsync/clientsideencryption.cpp:1055 ]:	No Client side encryption available on server.
2025-12-08 16:23:30:521 [ info nextcloud.gui.account.settings /Volumes/builds/35545/macos-35545/src/gui/accountsettings.cpp:1392 ]:	Account "torsten@cloud.some-other-domain.com" Client Side Encryption false
2025-12-08 16:23:30:522 [ info nextcloud.sync.accessmanager /Volumes/builds/35545/macos-35545/src/libsync/accessmanager.cpp:72 ]:	2 "" "https://cloud.some-other-domain.com/ocs/v1.php/cloud/user?format=json" has X-Request-ID "ee51a2ad-df4d-4a92-a1b1-957ba65a2014"
2025-12-08 16:23:30:522 [ info nextcloud.sync.networkjob /Volumes/builds/35545/macos-35545/src/libsync/abstractnetworkjob.cpp:368 ]:	OCC::JsonApiJob created for "https://cloud.some-other-domain.com" + "ocs/v1.php/cloud/user" "OCC::UserInfo"
2025-12-08 16:23:30:522 [ info nextcloud.sync.accessmanager /Volumes/builds/35545/macos-35545/src/libsync/accessmanager.cpp:72 ]:	2 "" "https://cloud.some-other-domain.com/ocs/v1.php/cloud/user?format=json" has X-Request-ID "2710861b-bb5b-4cdc-9d61-be906468c107"
2025-12-08 16:23:30:522 [ info nextcloud.sync.networkjob /Volumes/builds/35545/macos-35545/src/libsync/abstractnetworkjob.cpp:368 ]:	OCC::JsonApiJob created for "https://cloud.some-other-domain.com" + "ocs/v1.php/cloud/user" "OCC::UserInfo"
2025-12-08 16:23:30:534 [ info nextcloud.sync.accessmanager /Volumes/builds/35545/macos-35545/src/libsync/accessmanager.cpp:72 ]:	2 "" "https://cloud.some-other-domain.com/ocs/v1.php/cloud/user?format=json" has X-Request-ID "58d52c53-63eb-4c92-9175-71db7ccf8988"
2025-12-08 16:23:30:534 [ info nextcloud.sync.networkjob /Volumes/builds/35545/macos-35545/src/libsync/abstractnetworkjob.cpp:368 ]:	OCC::JsonApiJob created for "https://cloud.some-other-domain.com" + "ocs/v1.php/cloud/user" "OCC::UserInfo"
2025-12-08 16:23:30:543 [ warning qt.accessibility.table unknown:0 ]:	Cell requested for row 0 is out of bounds for table with 0 rows! Resizing table model.
2025-12-08 16:23:30:550 [ info nextcloud.sync.accessmanager /Volumes/builds/35545/macos-35545/src/libsync/accessmanager.cpp:72 ]:	2 "" "https://cloud.some-other-domain.com/ocs/v1.php/cloud/user?format=json" has X-Request-ID "02e4f734-7085-4d2d-9902-94a238f1947a"
2025-12-08 16:23:30:550 [ info nextcloud.sync.networkjob /Volumes/builds/35545/macos-35545/src/libsync/abstractnetworkjob.cpp:368 ]:	OCC::JsonApiJob created for "https://cloud.some-other-domain.com" + "ocs/v1.php/cloud/user" "OCC::UserInfo"
2025-12-08 16:23:30:575 [ info nextcloud.sync.credentials.webflow /Volumes/builds/35545/macos-35545/src/gui/creds/webflowcredentials.cpp:411 ]:	request finished QUrl("https://nextcloud.some-domain.com/ocs/v1.php/cloud/user?format=json") with request id "149016d9-3161-4dd8-8d6e-f168b9602676"
2025-12-08 16:23:30:575 [ info nextcloud.sync.networkjob.jsonapi /Volumes/builds/35545/macos-35545/src/libsync/networkjobs.cpp:1118 ]:	JsonApiJob of QUrl("https://nextcloud.some-domain.com/ocs/v1.php/cloud/user?format=json") FINISHED WITH STATUS "OK"
2025-12-08 16:23:30:575 [ info nextcloud.sync.accessmanager /Volumes/builds/35545/macos-35545/src/libsync/accessmanager.cpp:72 ]:	2 "" "https://nextcloud.some-domain.com/remote.php/dav/avatars/admin/128.png" has X-Request-ID "ac131e6d-b129-4a32-a055-88d052491ca9"
2025-12-08 16:23:30:575 [ info nextcloud.sync.networkjob /Volumes/builds/35545/macos-35545/src/libsync/abstractnetworkjob.cpp:368 ]:	OCC::AvatarJob created for "https://nextcloud.some-domain.com" + "" "OCC::UserInfo"
2025-12-08 16:23:30:715 [ info nextcloud.sync.credentials.webflow /Volumes/builds/35545/macos-35545/src/gui/creds/webflowcredentials.cpp:411 ]:	request finished QUrl("https://cloud.some-other-domain.com/ocs/v1.php/cloud/user?format=json") with request id "2710861b-bb5b-4cdc-9d61-be906468c107"
2025-12-08 16:23:30:715 [ info nextcloud.sync.networkjob.jsonapi /Volumes/builds/35545/macos-35545/src/libsync/networkjobs.cpp:1118 ]:	JsonApiJob of QUrl("https://cloud.some-other-domain.com/ocs/v1.php/cloud/user?format=json") FINISHED WITH STATUS "OK"
2025-12-08 16:23:30:715 [ info nextcloud.sync.accessmanager /Volumes/builds/35545/macos-35545/src/libsync/accessmanager.cpp:72 ]:	2 "" "https://cloud.some-other-domain.com/remote.php/dav/avatars/torsten/128.png" has X-Request-ID "4de023c8-d099-4c92-82f3-db25d9542bee"
2025-12-08 16:23:30:715 [ info nextcloud.sync.networkjob /Volumes/builds/35545/macos-35545/src/libsync/abstractnetworkjob.cpp:368 ]:	OCC::AvatarJob created for "https://cloud.some-other-domain.com" + "" "OCC::UserInfo"
2025-12-08 16:23:30:716 [ info nextcloud.sync.credentials.webflow /Volumes/builds/35545/macos-35545/src/gui/creds/webflowcredentials.cpp:411 ]:	request finished QUrl("https://cloud.some-other-domain.com/ocs/v1.php/cloud/user?format=json") with request id "02e4f734-7085-4d2d-9902-94a238f1947a"
2025-12-08 16:23:30:716 [ info nextcloud.sync.networkjob.jsonapi /Volumes/builds/35545/macos-35545/src/libsync/networkjobs.cpp:1118 ]:	JsonApiJob of QUrl("https://cloud.some-other-domain.com/ocs/v1.php/cloud/user?format=json") FINISHED WITH STATUS "OK"
2025-12-08 16:23:30:716 [ info nextcloud.sync.accessmanager /Volumes/builds/35545/macos-35545/src/libsync/accessmanager.cpp:72 ]:	2 "" "https://cloud.some-other-domain.com/remote.php/dav/avatars/torsten/128.png" has X-Request-ID "9243ea64-9a97-4a72-9069-962ce4fc162c"
2025-12-08 16:23:30:716 [ info nextcloud.sync.networkjob /Volumes/builds/35545/macos-35545/src/libsync/abstractnetworkjob.cpp:368 ]:	OCC::AvatarJob created for "https://cloud.some-other-domain.com" + "" "OCC::UserInfo"
2025-12-08 16:23:30:805 [ info nextcloud.sync.credentials.webflow /Volumes/builds/35545/macos-35545/src/gui/creds/webflowcredentials.cpp:411 ]:	request finished QUrl("https://nextcloud.some-domain.com/remote.php/dav/avatars/admin/128.png") with request id "ac131e6d-b129-4a32-a055-88d052491ca9"
2025-12-08 16:23:30:824 [ info nextcloud.sync.credentials.webflow /Volumes/builds/35545/macos-35545/src/gui/creds/webflowcredentials.cpp:411 ]:	request finished QUrl("https://cloud.some-other-domain.com/remote.php/dav/avatars/torsten/128.png") with request id "9243ea64-9a97-4a72-9069-962ce4fc162c"
2025-12-08 16:23:30:827 [ info nextcloud.sync.credentials.webflow /Volumes/builds/35545/macos-35545/src/gui/creds/webflowcredentials.cpp:411 ]:	request finished QUrl("https://cloud.some-other-domain.com/remote.php/dav/avatars/torsten/128.png") with request id "4de023c8-d099-4c92-82f3-db25d9542bee"
2025-12-08 16:23:32:291 [ info nextcloud.gui.mac.fileprovider.settingscontroller /Volumes/builds/35545/macos-35545/src/gui/macOS/fileprovidersettingscontroller_mac.mm:259 ]:	Fetching used storage space of materialized items.
2025-12-08 16:23:32:367 [ warning nextcloud.gui.mac.fileprovider.settingscontroller /Volumes/builds/35545/macos-35545/src/gui/macOS/fileprovidersettingscontroller_mac.mm:263 ]:	Could not get file provider domains: Das Programm kann gerade nicht verwendet werden. Will try again in 2 secs
2025-12-08 16:23:33:236 [ info nextcloud.gui.folder.manager /Volumes/builds/35545/macos-35545/src/gui/folderman.cpp:1028 ]:	Etag poll timer timeout
2025-12-08 16:23:33:236 [ info nextcloud.gui.folder.manager /Volumes/builds/35545/macos-35545/src/gui/folderman.cpp:1032 ]:	Folders to sync: 0
2025-12-08 16:23:33:236 [ info nextcloud.gui.folder.manager /Volumes/builds/35545/macos-35545/src/gui/folderman.cpp:1042 ]:	Number of folders that don't use push notifications: 0
2025-12-08 16:23:34:368 [ info nextcloud.gui.mac.fileprovider.settingscontroller /Volumes/builds/35545/macos-35545/src/gui/macOS/fileprovidersettingscontroller_mac.mm:259 ]:	Fetching used storage space of materialized items.
2025-12-08 16:23:34:441 [ warning nextcloud.gui.mac.fileprovider.settingscontroller /Volumes/builds/35545/macos-35545/src/gui/macOS/fileprovidersettingscontroller_mac.mm:263 ]:	Could not get file provider domains: Das Programm kann gerade nicht verwendet werden. Will try again in 2 secs
```

**Comment by Julhol-droid** [comment]
I might have found a solution (at least it worked for me)

1. Uninstall the Nextcloud client
2. Remove the whole directory **/home/xxxxxxx/.local/share/Nextcloud**
3. Remove the whole directory **/home/xxxxxxx/.config/share/Nextcloud**
4. After that install the client again

Keep in mind that you need to connect nextcloud again

**Comment by robeke** [comment]
Others have presumed success with similar actions only to discover after reboot (or just logout/login), the issues returns.  If the issue does not return in your @Julhol-droid  case, it would help if you would post your Nextcloud client version (previous and current if you installed a different version) and environment (OS, etc.).

**Comment by Julhol-droid** [comment]
> Others have presumed success with similar actions only to discover after reboot (or just logout/login), the issues returns. If the issue does not return in your [@Julhol-droid](https://github.com/Julhol-droid) case, it would help if you would post your Nextcloud client version (previous and current if you installed a different version) and environment (OS, etc.).

I have Fedora Linux 43 with KDE Plasma Desktop Edition. 
My Nextcloud Version "Nextcloud Desktop-Client Version 3.17.4daily" ([downloaded from official Fedora Package Repo](https://packages.fedoraproject.org/pkgs/nextcloud-client/nextcloud-client/fedora-43-updates.html))

And it seems to not work for me. So i still get the migrating error, when i run "nextcloud" command in terminal. However i managed to make the whole client with Virtual File Support work

**Comment by tcuje** [comment]
I debugged this issue on my Arch Linux system and found that https://github.com/nextcloud/desktop/blob/bc54b231246f455b8e54bd41f219d7984c5a91ee/src/gui/syncrunfilelog.cpp#L27 creates the `..._sync.log` files in the legacy location on non-Windows systems.
I changed this code part to look like this and it fixed the issue for me:
```
    QString logpath = "";
    if (!Utility::isWindows()) {
        logpath = QStandardPaths::writableLocation(QStandardPaths::AppConfigLocation);
    } else {
        logpath = QStandardPaths::writableLocation(QStandardPaths::AppDataLocation);
    }
```
After this I could restart the application multiple times without the legacy log directory being created.

**Comment by haschler** [comment]
Could you please create a PR for this? And we all cross our fingers that it gets integrated into the next release :-)

**Comment by tcuje** [comment]
Sorry, I miss the time to dig into the testing setup of this project and I don't own the Windows or MacOS Devices to at least smoke-test it there. Thumbs pressed someone else can do this

**Comment by rugk** [comment]
@MarvinSchwi you apparently created a fix in a fork? Do you want to contribute that upstream and open a PR?

**Comment by theking2** [comment]
After deleting the `$USER/.local/share/Nextcloud` and starting the client this error is not reported:

```
$ Applications/Nextcloud-33.0.2-x86_64.AppImage 
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
```

Starting the AppImage client creates these folders. Stoppen (**Exit Nextcloud**) and starting does report the error:
```

$ Applications/Nextcloud-33.0.2-x86_64.AppImage 
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
nextcloud.gui.application: Migrating old config from "/home/j/.local/share/Nextcloud" to "/home/j/.config/Nextcloud"
nextcloud.gui.application: Failed to move the old config directory to its new location ( "/home/j/.local/share/Nextcloud" to "/home/j/.config/Nextcloud" )
nextcloud.gui.application: Will move the individual files QList("Nextcloud_cloud.sbw.media_sync.log", "Nextcloud_kingma.cloud_sync.log", "Nextcloud_sync.log")
nextcloud.gui.application: Fallback move of  "Nextcloud_cloud1_sync.log" also failed
nextcloud.gui.application: Fallback move of  "Nextcloud_cloud2_sync.log" also failed
nextcloud.gui.application: Fallback move of  "Nextcloud_sync.log" also failed
```
