### ISSUE TITLE
[Bug]: Unlocking Office files fails since 3.11.1 (VFS)

### ISSUE THREAD

**Issue by Mika-6-9** [nextcloud/desktop#6401]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Since updating the client to version 3.11.1, office files lock properly when opened from Windows.
When closing files, they no longer unlock (or not always).
Too bad, the function had just worked more or less correctly.

### Steps to reproduce

open and close Office file

### Expected behavior

When the file is closed, the file unlocks

### Which files are affected by this bug

Office files

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11 et Windows 10

### Package

Official SNAP package

### Nextcloud Server version

27.1.1

### Nextcloud Desktop Client version

3.11.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by mgallien** [comment]
@Mika-6-9 could you try again and send us a debug archive ?
if you need, I can provide a share link for you to upload it only privately instead of uploading it on github

**Comment by Mika-6-9** [comment]
@mgallien Hello
I reverted to version 3.11.0.
I can redo tests in 3.11.1 and send you the files privately if you give me a link. I will ask collaborators if they can also do tests to have several logs

**Comment by forsgear** [comment]
I confirm  the problem. the same issue on my side.  3.11.0  works fine.

**Comment by BoMaGithop** [comment]
Same problem, not only with office files, also Xmind...

**Comment by JohanBoshoffWebAware** [comment]
Same problem on my side.  I was using Nextcloud 26, upgraded to 27 and the problem persists

**Comment by Ornanovitch** [comment]
I can confirm this problem since 3.11.1

**Comment by Ornanovitch** [comment]
And in my case, the NC desktop logs are spammed with this kind of msg for a locked file (which should be unlocked):

```log
2024-02-13 17:22:30:439 [ info nextcloud.sync.discovery /usr/src/debug/nextcloud-client/nextcloud-client/src/libsync/discovery.cpp:466 ]:	Processing "*************.txt" | (db/local/remote) | valid: true/db/true | mtime: 1707749204/0/1707749204 | size: 10474/0/10474 | etag: "65ca2f640613f"//"65ca2f640613f" | checksum: "SHA1:cbbfe9b75e0057e1e4e35edb7f094749027cd23e"//"SHA1:cbbfe9b75e0057e1e4e35edb7f094749027cd23e" | perm: "WDNVRm"//"WDNVRm" | fileid: "01915906ocane5i2ktyc"//"01915906ocane5i2ktyc" | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeSkip/CSyncEnums::ItemTypeFile | e2ee: false/false | e2eeMangledName: ""/"" | file lock: locked//locked | metadata missing: /false/
2024-02-13 17:23:11:269 [ info nextcloud.sync.discovery /usr/src/debug/nextcloud-client/nextcloud-client/src/libsync/discovery.cpp:466 ]:	Processing "*************.txt" | (db/local/remote) | valid: true/db/true | mtime: 1707749204/0/1707749204 | size: 10474/0/10474 | etag: "65ca2f640613f"//"65ca2f640613f" | checksum: "SHA1:cbbfe9b75e0057e1e4e35edb7f094749027cd23e"//"SHA1:cbbfe9b75e0057e1e4e35edb7f094749027cd23e" | perm: "WDNVRm"//"WDNVRm" | fileid: "01915906ocane5i2ktyc"//"01915906ocane5i2ktyc" | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeSkip/CSyncEnums::ItemTypeFile | e2ee: false/false | e2eeMangledName: ""/"" | file lock: locked//locked | metadata missing: /false/
2024-02-13 17:23:26:564 [ info nextcloud.sync.discovery /usr/src/debug/nextcloud-client/nextcloud-client/src/libsync/discovery.cpp:466 ]:	Processing "*************.txt" | (db/local/remote) | valid: true/db/true | mtime: 1707749204/0/1707749204 | size: 10474/0/10474 | etag: "65ca2f640613f"//"65ca2f640613f" | checksum: "SHA1:cbbfe9b75e0057e1e4e35edb7f094749027cd23e"//"SHA1:cbbfe9b75e0057e1e4e35edb7f094749027cd23e" | perm: "WDNVRm"//"WDNVRm" | fileid: "01915906ocane5i2ktyc"//"01915906ocane5i2ktyc" | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeSkip/CSyncEnums::ItemTypeFile | e2ee: false/false | e2eeMangledName: ""/"" | file lock: locked//locked | metadata missing: /false/
2024-02-13 17:23:41:860 [ info nextcloud.sync.discovery /usr/src/debug/nextcloud-client/nextcloud-client/src/libsync/discovery.cpp:466 ]:	Processing "*************.txt" | (db/local/remote) | valid: true/db/true | mtime: 1707749204/0/1707749204 | size: 10474/0/10474 | etag: "65ca2f640613f"//"65ca2f640613f" | checksum: "SHA1:cbbfe9b75e0057e1e4e35edb7f094749027cd23e"//"SHA1:cbbfe9b75e0057e1e4e35edb7f094749027cd23e" | perm: "WDNVRm"//"WDNVRm" | fileid: "01915906ocane5i2ktyc"//"01915906ocane5i2ktyc" | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeSkip/CSyncEnums::ItemTypeFile | e2ee: false/false | e2eeMangledName: ""/"" | file lock: locked//locked | metadata missing: /false/
2024-02-13 17:23:57:054 [ info nextcloud.sync.discovery /usr/src/debug/nextcloud-client/nextcloud-client/src/libsync/discovery.cpp:466 ]:	Processing "*************.txt" | (db/local/remote) | valid: true/db/true | mtime: 1707749204/0/1707749204 | size: 10474/0/10474 | etag: "65ca2f640613f"//"65ca2f640613f" | checksum: "SHA1:cbbfe9b75e0057e1e4e35edb7f094749027cd23e"//"SHA1:cbbfe9b75e0057e1e4e35edb7f094749027cd23e" | perm: "WDNVRm"//"WDNVRm" | fileid: "01915906ocane5i2ktyc"//"01915906ocane5i2ktyc" | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeSkip/CSyncEnums::ItemTypeFile | e2ee: false/false | e2eeMangledName: ""/"" | file lock: locked//locked | metadata missing: /false/
2024-02-13 17:24:00:111 [ info nextcloud.sync.discovery /usr/src/debug/nextcloud-client/nextcloud-client/src/libsync/discovery.cpp:466 ]:	Processing "*************.txt" | (db/local/remote) | valid: true/db/true | mtime: 1707749204/0/1707749204 | size: 10474/0/10474 | etag: "65ca2f640613f"//"65ca2f640613f" | checksum: "SHA1:cbbfe9b75e0057e1e4e35edb7f094749027cd23e"//"SHA1:cbbfe9b75e0057e1e4e35edb7f094749027cd23e" | perm: "WDNVRm"//"WDNVRm" | fileid: "01915906ocane5i2ktyc"//"01915906ocane5i2ktyc" | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeSkip/CSyncEnums::ItemTypeFile | e2ee: false/false | e2eeMangledName: ""/"" | file lock: locked//locked | metadata missing: /false/
```

**Comment by vagner-dias** [comment]
same issue here. automatic unlocking is not working anymore. 
Tested on V3.12.0

**Comment by JohanBoshoffWebAware** [comment]
I just tested on 3.12.0 and the problem seems to be resolved with this update.  I will test with the rest of our team tomorrow morning and post an update if not working.  So far so good.

**Comment by Ornanovitch** [comment]
Just tested on 3.12, unsolved for me :/

**Comment by pschopen** [comment]
For me it was solved with the file_locking update to 28.0.2

**Comment by smehrbrodt** [comment]
> For me it was solved with the files_lock update to 28.0.2

Confirmed, updating files_lock to 28.0.2 fixes the problem here too.

**Comment by Ornanovitch** [comment]
Updating files_lock to 27.0.4 does **not** fix it, so I guess this is a NC 27 problem now

**Comment by timaba** [comment]
I second that issue with following setup
Nextcloud Server 28.0.2
Temporary Files Lock 28.0.2
Clients 3.11.1 and 3.12.0 in Win10 and Win11.

Interesting fact: Not all file types are affected, but typical Office files such as docs/xlsx.
As described above, the save/close event does not seem to be communicated correctly. After unlocking the file via the context menu, the sync releases the files globally.

**Comment by AbeilleVerte** [comment]
hello 
Same issue on Linux Mint, did someone find a way to fix this? 

Nextcloud Server   28.0.2
Temporary Files Lock 27.0.4
Clients 3.12.0 on Mint.

**Comment by dirk80** [comment]
I have the same issue with
Nextcloud 27.1.5 Enterprise
Temporary Files Lock 27.0.2
Windows Desktop-Client 3.12.0

**Comment by Ornanovitch** [comment]
Related forum thread: https://help.nextcloud.com/t/files-not-unlocking-automatically/182250

This is more and more a serious issue as users are progressively upgrading to 3.11.1 or 3.12 :/

**Comment by JohanBoshoffWebAware** [comment]
Most of our problems are resolved on 3.12.0 client and using Nextcloud 27.0.4.  When using Redis for memory caching, make sure to double check that redis is running correctly, especially if configured using socket.  While I was busy debugging the locking issue prior to the bug release, I found that redis was running, but my sock file was using the wrong directory.

However, we have thousands of files that are still locked.  I have no locks in my oc_file_locks table and I cannot clear it as it is an empty set.

Does anyone know if the app Temporary File Lock stores the locks in another table that I can clear?  I just want to be able to clear all the files that still shows as locked.  Users are having a difficult time unlocking and wastes their time.  Even files the users have not worked on for years are now suddenly locked.

Any ideas please?  To prevent to conflicted copy, I am using the Temporary File Lock app.  Transactional file locking is enabled in nextcloud config and I use redis for that.  Restarting the server or services also does not remove the locks.

**Comment by Ornanovitch** [comment]
Okay, thanks Johan, problem solved but I don't know exactly how/why:

I checked that redis and php-redis were running correctly (and they were), and then I realized that since my last system upgrade, I had php8.3 running next to php8.2. Nextcloud is using php8.2 but after stopping php8.3, uninstalling it and restarting all the services, I am not experiencing this problem anymore :0

**Comment by Ornanovitch** [comment]
Did you try to disable the Temporary Files Lock app, then to restart php-fpm, then to re-enable the app and restart php-fpm again? I think I had this kind of problem just after the NC desktop upgrade, and that I managed to solve it that way, but I'm not sure

**Comment by Ornanovitch** [comment]
Too bad... I'll keep an eye open on this particular problem as I'm not sure it completely disappeared for all my users

**Comment by Mika-6-9** [comment]
With Nextcloud server 27.1.1 and Nextcloud desktop 3.12 **_AND_** Nextcloud files_lock 27.0.4
After the update to files_lock 27.0.4, no more problem unlocking office files.
I'm going to close this issue, but I'll still leave it open for a while so people with Nextcloud server 28 can say if it works for them

**Comment by JohanBoshoffWebAware** [comment]
Hi Mika.  I am sorry, but how can you close the issue it if you state that it is working with an older version 27.1.1.  We are on version 27.1.6 and still have the issue.  Yes, it did work on the previous versions.  The newest versions are causing the issues.

**Comment by JohanBoshoffWebAware** [comment]
I tried that, but existing locks does not get unlocked.

**Comment by vagner-dias** [comment]
> I tried that, but existing locks does not get unlocked.
same here... @mgallien - Any ideas on how to release all locks to start from scratch ?

**Comment by JohanBoshoffWebAware** [comment]
This is also exactly what I need to know.  I cannot believe there is no way to unlock all files that have been locked.  Since it does not use the database for locking, how does it keep track of files that are locked?

According to the Temporary Files Lock app there are ways to unlock or lock a file one at a time by knowing the ID of the file, but we have hundreds of thousands of locked files.

**Comment by AlxxxlA** [comment]
Hi, we got a similar issue here.
We tried some updates in the database to unlock the files.

1. You can remove the locks on the database : 

`TRUNCATE TABLE oc_files_lock`

This update unlock all the files but some desktop clients keep the files lock. You have to edit the file manually on the web interface and apply an update to force a resync of the desktop client.

2. Another way is to pass the value of the type to `0` to allowed the desktop client or the web interface to unlock the file ignoring the token :

`UPDATE oc_files_lock SET type = 0 WHERE type = 2`

I think this is the best way to clear the lock file as it just allow users to unlock on their side manually.

If you need the more informations on the lock file :

**Comment by Mika-6-9** [comment]
Another point, when you do "save as" from an open Office document, the "original" file does not unlock and the new one created does not lock even though it is open and you are going to work in it.

**Comment by JohanBoshoffWebAware** [comment]
@Mika-6-9 - I am glad you can leave open this thread as there are loads of bugs relating to the locking and unlocking and we can do it so wait for a fixed Desktop Client, or a command on the Temporary File Locks app to be able to unlock all locked files.

**Comment by vagner-dias** [comment]
> > With Nextcloud server 27.1.1 and Nextcloud desktop 3.12 **_AND_** Nextcloud files_lock 27.0.4 After the update to files_lock 27.0.4, no more problem unlocking office files. I'm going to close this issue, but I'll still leave it open for a while so people with Nextcloud server 28 can say if it works for them
> 
> I spoke too quickly, I have quite a few files that don't unlock, but not all the time ?!??

I spoke too quickly too. Some old files which were lock are not unlocking anymore. I am unable to unlock them even if I go to the web interface of the user who locked them and force the unlock operation. Files are stuck now.

**Comment by Mika-6-9** [comment]
For information.
With version 3.12, I have many more unlock errors with Excel than Word.

**Comment by allexzander** [comment]
FYI. If you lock a file manually (via the context menu in Windows Explorer or in the Web UI), then open that file with Word/Excel/etc., and then close it, it will not unlock automatically if the lock was imposed manually.

**Comment by vagner-dias** [comment]
> FYI. If you lock a file manually (via the context menu in Windows Explorer or in the Web UI), then open that file with Word/Excel/etc., and then close it, it will not unlock automatically if the lock was imposed manually.

That´s the exact problem. Using:
Desktop client: V3.12.0
NC: 27.1.5
files_lock: 27.0.4

everyone is experiencing cases where the file is locked by opening excel, word, etc, and after the file is saved and closed, thus deleting the lock file, the NC lock state is not removed. the file gets locked indefinetivley

**Comment by marcotrevisan** [comment]
@vagner-dias that does not seem the exact same use case @allexzander is describing. 
Seems like you're experiencing it:

- regardless the files were previously manually locked,
- in group folders.

**Comment by Ornanovitch** [comment]
I realize this problem happens in group folders in my case too. I thought I had solved it, but I still have problems with users upgrading to 3.11.1 or 3.12. I had to disable the File Lock app

**Comment by mgallien** [comment]
I am pretty much convinced that this issue has been fixed in the latest releases
if you want to test and report the status, please ensure you are running [3.12.1 release of desktop client](https://github.com/nextcloud-releases/desktop/releases/tag/v3.12.1) and release [27.0.4 of files_lock server application](https://github.com/nextcloud-releases/files_lock/releases/tag/v27.0.4) or [28.0.2 of files_lock server application](https://github.com/nextcloud-releases/files_lock/releases/tag/v28.0.2)

desktop client release 3.12.0 is known to have an issue with files_lock release older than 27.0.4 or 28.0.2, no need to provide feedback on this

**Comment by Mika-6-9** [comment]
Hi.
Unfortunately, there are still some files that do not unlock when closing the file (mostly Excel)
We are continuing the tests.

Other feedback?

**Comment by vagner-dias** [comment]
I encounter a similar issue, particularly when the Excel file remains open for an extended period. When a user opens and closes the office file within 1-2 hours, everything functions smoothly. However, if the user opens the file in the morning and closes it in the evening, the automatic unlock process fails to occur.

**Comment by ynott** [comment]
I see that the issue of the lock not being unlocked has not been fixed. 
In particular, it will not unlock when "Edit Locally" from the Nextcloud UI.

**Comment by marcotrevisan** [comment]
Hi all. I just noticed there's a new release of the Temporary Files Lock app. The changelog looks promising...

**Comment by ynott** [comment]
I have already tried it with the new desktop client(v3.12.2) and the new Temporary Files Lock(v27.0.5) app.
So far it is working perfectly.
Even If I select "Edit Locally" from the WebUI, it will still unlock correctly when I finish editing.

But files that are already locked need to be unlocked manually. (This works from the WebUI or from the Desktop client.)

### Thanks to all the developers for your hard work!

**Comment by JohanBoshoffWebAware** [comment]
Looks decent to me also.  Is there no command to remove all locks that are currently active for all users with an OCC command?  I am sure that will sort out most issues and clear all locked files that was locked incorrectly.  Please, developers, that feature will help a lot of users, especially users where there are thousands of locked files.  It is impossible to find them one by one and unlock them.

**Comment by vidlb** [comment]
Hi all, I kind of dropped the table "oc_files_lock" and re-installing the module does not repair it, how can I recreate ?

**Comment by ZID-TU-Graz** [comment]
Same issue here, 
In our case the files are only locked when inside a groupfolder AND the groupfolder is shared to another person.
On top of that, only under those specific circumstances:
When creating a new Excel/Word file locally by rightclicking->new Word Document (then give a chosen name)
It creates the new Word Document and another one with the generic name "Microsoft Word-document (new)"
Appereantly it instantly snycs the new File to the cloud and is seeing the "renamend" version as a new file.
Client 3.12.2
files_lock 27.0.4 (we will give an update when upgraded to 27.0.5)
NC 27.1.7
OS (install of Client) Windows

**Comment by Ornanovitch** [comment]
> I am pretty much convinced that this issue has been fixed in the latest releases if you want to test and report the status, please ensure you are running [3.12.1 release of desktop client](https://github.com/nextcloud-releases/desktop/releases/tag/v3.12.1) and release [27.0.4 of files_lock server application](https://github.com/nextcloud-releases/files_lock/releases/tag/v27.0.4) or [28.0.2 of files_lock server application](https://github.com/nextcloud-releases/files_lock/releases/tag/v28.0.2)
> 
> desktop client release 3.12.0 is known to have an issue with files_lock release older than 27.0.4 or 28.0.2, no need to provide feedback on this

@mgallien We just upgraded to all the latest releases and we are still experiencing issues of office files remaining locked after having been properly saved, closed and synced. I wonder if this has something to do with groupfolders as we only use groupfolders to collaborate. 

cc @juliushaertl if you suspect something on the groupfolder/office side?

**Comment by JohanBoshoffWebAware** [comment]
I agree that it appears the problem has been resolved. However, whenever a user opens a file, multiple log entries indicate that the file is locked for the duration it remains open. This behavior contrasts with the previous functionality, where only attempted access to a locked file triggered logging. Presently, Nextcloud logs the locked status of files specifically for the user who has them open.

**Comment by vidlb** [comment]
Not sure I think this is due to stale locks that couldn't be removed automatically.
I'm also using groupfolders and was able to remove log messages after a complete reset of the temporary locks app, and manually removing every locks in database. And of course everyone updated the client to 3.12.3

**Comment by JohanBoshoffWebAware** [comment]
Please could you explain where in the DB I can see file locks as I have been asking on forums and there is no clear answer.  Some of the threads spoke about the oc_filelocks table, but mine is empty.

Also, please explain how you totally reset the temp files lock app.  Thank you.

**Comment by Mika-6-9** [comment]
Hi,

With 3.12.3 this seems to work with groupfolders, but with classic Nextcloud folders (shared), unlocking does not work all the time

**Comment by JohanBoshoffWebAware** [comment]
Thank you.  Do you also first remove the temp file locks app, then do the steps above and re-download and enable the app?

**Comment by vidlb** [comment]
I did but it does not seems to do anything. You can enable / disable in the UI or using occ, but it doesn't seems to affect the DB, thus I went with the brute force way using `delete from`.

**Comment by rakurtz** [comment]
hello everyone,  we also have a lot of issues with file locks in our nc instance. i decided to at least get rid of file locks older than 24 continuously. this takes the pain away a little :)

feel free to check out my python script (added to crontab) here: 
[https://github.com/rakurtz/cleanup_oc_files_lock](https://github.com/rakurtz/cleanup_oc_files_lock)

**Comment by ZID-TU-Graz** [comment]
We did some extended testing and were able to reproduce this bug under specific circumstances
Client 3.13.   NC 27.1.7
1. File is located in a Groupfolder
2. (Groupfolder itself is shared ; was mandatory for reproudcing and fixed with client 3.12.3 or 3.12.4:  listed as we continued testing in this folder, so maybe this is not mandatory for reproducing)
3. File is **spearately shared** to another person (editing rights)
4. File is either a normal Word file (open via Nextcloud Client, do changes and save, then see this file locked)
5. or File is an excel file with Macros and(/or) a protected sheet  (we managed to lock an .xlsx without sheet protection aswell, but only as we tampered with macros and saved as .xlsx nontheless)

Hope this helps.
Please note that maybe not all points are mandatory for reproducing (such as sharing with editing rights, could maybe occour with reading rights aswell) as we did no "negativ-testing"

**Comment by Ornanovitch** [comment]
As many people here, we still have a lot of issues of locked files with Groupfolders... in appearance randomly.

Should it be investigated in the nextcloud/files_lock repo? cc @juliushaertl

**Comment by Ornanovitch** [comment]
The problems I'm talking about are difficult to reproduce, and I had to disable nextcloud/files_lock because there was too many missed sync.

In our logs, we see those errors regularly:

![Screenshot 2024-05-22 at 17-56-01 Journalisation - Paramètres d'administration - Brume](https://github.com/nextcloud/desktop/assets/34077099/7c0619dd-8dec-44f7-aefc-c7d6cd9ad55c)

As an example:

```json
{
  "reqId": "kWRDOOWqz1GWK62IIZGe",
  "level": 3,
  "time": "2024-05-22T14:30:51+00:00",
  "remoteAddr": "90.5.202.23",
  "user": "ornanovitch",
  "app": "webdav",
  "method": "PUT",
  "url": "/remote.php/dav/files/ornanovitch/*****/*****/*****.ods",
  "message": "Exception thrown: Sabre\\DAV\\Exception\\Locked",
  "userAgent": "Mozilla/5.0 (Linux) mirall/3.13.0git (Nextcloud, arch-6.9.1-arch1-1 ClientArchitecture: x86_64 OsArchitecture: x86_64)",
  "version": "28.0.5.1",
  "exception": {
    "Exception": "Sabre\\DAV\\Exception\\Locked",
    "Message": "",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "validateTokens",
        "class": "Sabre\\DAV\\Locks\\Plugin",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1448,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 466,
        "function": "checkPreconditions",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/dav/lib/Server.php",
        "line": 373,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/remote.php",
        "line": 172,
        "args": [
          "/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Locks/Plugin.php",
    "Line": 504,
    "message": "",
    "exception": [],
    "CustomMessage": "Exception thrown: Sabre\\DAV\\Exception\\Locked"
  },
  "id": "664e158616c99"
}
```

**Comment by Mika-6-9** [comment]
For us, no more worries about locking/unlocking files in groupfolders, but we have:
Nextcloud server 27
Temporary files lock 27.0.7
Nextcloud desktop 3.11.0 (or 3.12.4 in test) other clients cause too many problems
I'm keeping this ticket open because several people still have problems, and with classic Nextcloud folders (shared), unlocking does not work all the time, but we don't often use "classic folders"

**Comment by Mika-6-9** [comment]
HI
I have a clarification to make, a priori, the documents are not unlocked when we change networks (wired to wifi and vice versa)

**Comment by MaxXor** [comment]
Same issue as @Ornanovitch with latest NC server 29.0.4.

**Comment by Ornanovitch** [comment]
I don't notice this bug anymore (3.14 and 3.15 with NC 30.0.3 and 30.0.4), but our logs are spammed with `Locked Exception thrown`, I will open a new issue for this
