### ISSUE TITLE
[Bug]: The sync icon on mac is always on "pause"

### ISSUE THREAD

**Issue by thysm00** [nextcloud/desktop#6446]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The sync icon in the menu bar stays on pause all the time.

### Steps to reproduce

Just use two shared folders and have one of them on pause.

### Expected behavior

The icon should not be on pause of at least one of the folders isn't paused.
Also when there is a change on a file, the menu icon should change to the sync while uploading and then on the "validated" status once it's all in sync.

This was working just fine with the previous build 3.11.

### Which files are affected by this bug

All files

### Operating system

Mac OS

### Which version of the operating system you are running.

Ventura latest and Sonoma latest

### Package

Appimage

### Nextcloud Server version

27.1.5

### Nextcloud Desktop Client version

3.12.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by thysm00** [comment]
I am getting this on 3 different computers (2 M1 mac minis and an M1 pro macbook pro) on both latest ventura and sonoma.

**Comment by thysm00** [comment]
This is still happening with the latest version... I hope someone can do something about it because it's a huge regressin frol the previous 3.11 version.
I can't see the progress if the sync even if it does it in the background.
I don't want to remove the paused synced folders because i sync them only once in a while when i plug the drives in.
Here is a screenshot showing what's happening. It's even saying sync paused when i see that it's syncing the files in the finder.
<img width="604" alt="Screenshot 2024-03-16 at 22 53 02" src="https://github.com/nextcloud/desktop/assets/77436044/22e64f7e-6d08-45ad-a1cf-1630a2d1dc53">

**Comment by JWandscheer** [comment]
Can confirm this for the Client 3.13 with Virtual files on MacOS. I have the Virtual File Sync enabled and no "Classic" Sync, the icon always shows paused.
![Bildschirmfoto 2024-07-02 um 11 38 20](https://github.com/nextcloud/desktop/assets/5305887/43a921b0-1145-4bb3-84a8-39e3de22fb9e)

**Comment by evrim706** [comment]
Please fix this, this is very annnoying 😥 🙏

**Comment by apastuszak** [comment]
Still happening in client 3.14 with Virtual Files turned on and no classic files set.

**Comment by claucambra** [comment]
I have issued a couple of fixes for this that should land with 3.16.0 :)

**Comment by boti7** [comment]
This bug is still present in 3.16.0 on macOS.

**Comment by apastuszak** [comment]
It's working fine for me. The pause icon is now a checkbox.

**Comment by Xansala** [comment]
Issue still remains with 3.16.2 (on Windows):

![Image](https://github.com/user-attachments/assets/65251d06-2bf2-41a4-9253-21425044eadf)

![Image](https://github.com/user-attachments/assets/5b383d06-2183-4b5d-86ab-c5ec1c956473)

Would it be possible to only close issues once confirmed they are fixed (fine to ask and then close if there is no reply)? I find it not so community-friendly to just close the issue without that.

**Comment by jtiemer** [comment]
Can confirm issue persists on MB Pro M3 Pro, macOS Sequoia 15.4.1, Nextcloud Client 3.16.4.

The sync icon stays on pause regardless what I do, e.g. clicking 'sync now'.

There is a workaround, though: When opening the settings, I can access the individual folders to be synchronized, of which only one was syncing, and the others were on pause. Manually unpausing each folder there in the settings made the client as a whole show the syncstatus icon as desired.

**Comment by thysm00** [comment]
Issue persists as well over here.
And the above workaround is not a workaround, i leave paused folders on purpose for disks that are not connected.

So unpausing all folders sync does not resolve, what's needed is even if one folder is paused, the sync icon should still display the current status of the sync.

Please fix this, it's bee a year and a half now and has been confirmed by everyone on this thread.

**Comment by leonardo-mais** [comment]
ridiculus

**Comment by Rello** [comment]
Hello,

this was fixed with one of the recent releases.

**Comment by thysm00** [comment]
I'm afraid it hasn't... I still have the pause icon in the menu bar even if i have 8 synced folder that are synced or syncing and just one on pause.

**Comment by boti7** [comment]
Sadly it is still not fixed in 3.17.1. It is quite annoying that this used to work properly but it has been broken for almost two years now.
@Rello could you please reopen the issue until it is really fixed? Thanks!

**Comment by Rello** [comment]
> [@Rello](https://github.com/Rello) could you please reopen the issue until it is really fixed? Thanks!

Hello,
sure. if the issue exists, we will reopen.
thank you for supporting us with retesting

**Comment by thysm00** [comment]
Thanks @Rello , I can confirm that the issue still exists on 3 different macs using the latest version of the app and os.

**Comment by Rello** [comment]
Hi,

I just checked all the messages in detail.
This is how its supposed to work and will also not change anymore. thats why it was implemented.

There is only one tray icon - and this has to indicate the "worst" state of any accounts.
If the sync is not running for any of the accounts, the icon will indicate this.
The client cannot differentiate of on-purpose or on-error.

When it comes to data consistency, the user always needs to know as soon as there is anything irregular with the syncs because then the data is not synced and data is in risk.

The highest prio of the client is data consistency. if we would change the logic mentioned as above, it would put a risk on every regular sync user.
