### ISSUE TITLE
[Bug]: Plasma 6/KF6 Dolphin Shell Extension overlay icons not rendering

### ISSUE THREAD

**Issue by FGD-Garuda** [nextcloud/desktop#6577]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The sync overlay icons present in Dolphin prior to Plasma 6 upgrade are no longer present immediately after upgrading to Plasma 6.
Could be related to the need to port nexcloud-client to QT6/KF6, but I don't know. This seems to be taken care of [here](https://github.com/nextcloud/desktop/tree/master/shell_integration/dolphin), but it does not show any overlay icons.
...

### Steps to reproduce

1. Run Plasma 5 to see the sync overlay icons
2. Upgrade to Plasma 6 and reboot
3. Overlay icons no longer present
...

### Expected behavior

Sync overlay icons should remain.
...

### Which files are affected by this bug

All files part of a synced folder

### Operating system

Linux

### Which version of the operating system you are running.

Arch (Garuda)

### Package

Distro package manager

### Nextcloud Server version

28.0.2

### Nextcloud Desktop Client version

3.12.2 (also tested under 3.12.50)

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

[Nexctcloud-debug.zip](https://github.com/nextcloud/desktop/files/14736919/Nexctcloud-debug.zip)

**Comment by DemoFreak** [comment]
Same behaviour on Opensuse Tumbleweed also.
https://bugzilla.suse.com/show_bug.cgi?id=1221923

**Comment by guiodic** [comment]
Not only are there no icons in overlay but nothing in the integration works. Arch Linux developers could not compile the client with KF6 https://gitlab.archlinux.org/archlinux/packaging/packages/nextcloud-client/-/issues/3#note_174553

Could you help them (and us as users)?

**Comment by FGD-Garuda** [comment]
According to
> [gitlab.archlinux.org/archlinux/packaging/packages/nextcloud-client/-/issues/3#note_174553](https://gitlab.archlinux.org/archlinux/packaging/packages/nextcloud-client/-/issues/3#note_174553)

some newer than 3.12.x version would be compatible?

**Comment by jospoortvliet** [comment]
As @FGD-Garuda already said, I bet it requires the ability to build the client with Qt 6. This is WIP, hopefully done soon. Not sure if it'd be possible to 'just' do it only for the integration, though, maybe it is possible to build the dolphin plugin for both Qt6 and Qt5 without building the entire client with Qt 6.

I'm secretly hoping that one of the developers (most are KDE or GNOME users) will be motivated to do it soon as they are likely going to get Plasma 6 on their work stations soon ;-)

if only everyone was running OpenSUSE Tumbleweed, and thus already on Plasma 6 🙈

**Comment by FGD-Garuda** [comment]
This is fixed with 3.13.0.

**Comment by avatar1024** [comment]
Still does not seem to be working with 3.13 (at least not in fedora). I have no dolphin integration whatsoever. Anyone else experiencing this?

**Comment by alerque** [comment]
@avatar1024 That looks like a packaging issue, [the Fedora packages](https://packages.fedoraproject.org/pkgs/nextcloud-client/nextcloud-client/fedora-rawhide.html#dependencies) look like they are still built with Qt5. They need to be updated to use Qt6 for this to work. Please report that to the appropriate upstream packaging bug tracker. I'm not a Fedora user and not sure, but it might be here: https://src.fedoraproject.org/rpms/nextcloud-client

**Comment by avatar1024** [comment]
Thank you! I'll flag it up!

**Comment by avatar1024** [comment]
I've checked and it seems like the deb version is also built with Qt5. Is there a known issue regarding packaging it with Qt6? Has it been done anywhere?

**Comment by alerque** [comment]
Um, something else is up. I remembered wrong, check the issue history for the Arch Linux package. This came up there at some point and I thought we fixed it with qt6 (or maybe just saw that it was being worked on upstream?).

**Comment by avatar1024** [comment]
Not sure how to check the history but there again it is built with Qt5 https://archlinux.org/packages/extra/x86_64/nextcloud-client/

**Comment by septatrix** [comment]
Opensuse at least seems to build it with QT6 for the dolphin plugin https://build.opensuse.org/projects/network/packages/nextcloud-desktop/files/nextcloud-desktop.spec?expand=1

**Comment by valiksheva** [comment]
> avatar1024

I have the same issue, none of the integrations work for my Fedora Kinoite (KDE 6).

**Comment by avatar1024** [comment]
I have enquired [here](https://bugzilla.redhat.com/show_bug.cgi?id=2299950) and [here](https://bugzilla.redhat.com/show_bug.cgi?id=2296120) but no responses so far.

**Comment by avatar1024** [comment]
It's now working with a new package: 
https://koji.fedoraproject.org/koji/taskinfo?taskID=122098639

**Comment by valiksheva** [comment]
> It's now working with a new package: https://koji.fedoraproject.org/koji/taskinfo?taskID=122098639, thank to https://bugzilla.redhat.com/show_bug.cgi?id=2299950#c4

Is there a way to install this very package? 
I still get old package when using 'dnf install nextcloud-client'

**Comment by septatrix** [comment]
> Is there a way to install this very package? I still get old package when using 'dnf install nextcloud-client'

The packages do not seem to have found their way into the repo yet but you can download the rpm files from koji: https://koji.fedoraproject.org/koji/buildinfo?buildID=2531674

**Comment by smihael** [comment]
I reported a bug for KDE neon [here](https://bugs.kde.org/show_bug.cgi?id=495450).
