### ISSUE TITLE
[Bug]: Crash when using external/non-default path (in 3.14.x, 3.13.x, but 3.12.x okay)

### ISSUE THREAD

**Issue by matvit92** [nextcloud/desktop#6707]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After updating from version 3.12.3 to 3.13.0 client crash, when using external storage path for files. In my case on SD card. After downgrade to 3.12.4 it working OK.

Issue reported by another user here: https://github.com/nextcloud-releases/desktop/issues/9

### Steps to reproduce

Set files path to external media (SD card)

### Expected behavior

Client crash

### Which files are affected by this bug

No files affected

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Other

### Nextcloud Server version

24.0.4

### Nextcloud Desktop Client version

3.13.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by michael-r-elp** [comment]
Can confirm, got a call today from someone on 3.13.0 experiencing the same problem, after downgrade to 3.12.4 everything worked fine again.
Logs didn't say anything useful, the event viewer showed that nextcloud crashed with module ntdll with error code 0xc0000005.

**Comment by DavidS-ovm** [comment]
Same on my dad's machine.

**Comment by DavidS** [comment]
Same on my dad's machine: crashes with 3.13.0; works fine with 3.12.4; has the nextcloud storage on `N:\`, a mapped drive

**Comment by CWRMTM** [comment]
Can confirm this behaviour in 3.13.0.
I actually just signed up for this. ;-)

**Comment by hdmr14** [comment]
oh, that's interesting.
local SSD(SATA) -> crashed on my PC.

**Comment by matvit92** [comment]
> oh, that's interesting. local SSD(SATA) -> crashed on my PC.

Mapped in default directory?

**Comment by hdmr14** [comment]
> > oh, that's interesting. local SSD(SATA) -> crashed on my PC.
> 
> Mapped in default directory?

Ah, No.
I've set up a mapping to 'H:\Nextcloud'.

**Comment by digimbyte** [comment]
same issue, I thought this was related to a case insensitive issue as NextCloud is Case Sensative on the server but it maybe related to external media. 
I use a 12TB external HDD for our teams backup/media and its been crashing. I updated because files weren't updating prior.

**Comment by haziqnorisham** [comment]
Same issue here, sync to external usb hdd will crash on 3.13.0, downgrade to 3.12.4 & sync works.

**Comment by pascal142** [comment]
Same issue, windows client 3.13 crashes. Downgrade to 3.12.5 is working again
Nom de l’application défaillante nextcloud.exe, version : 3.13.0.55335, horodatage : 0x66280dc7
Nom du module défaillant : ntdll.dll, version : 10.0.22621.3374, horodatage : 0xeae8eecc
Code d’exception : 0xc0000005

**Comment by toniQva** [comment]
Tengo el mismo error,

**Comment by steinjo** [comment]
Exact same problem here, windows 11, drive is an encrypted container mapped to X:\
Downgrading to client 3.11.0 and it works again

**Comment by obriat** [comment]
Confirm I got the same problem Windows 10 + Sandisk external SSD on E: drive

**Comment by git-ikeda** [comment]
Same issue, windows client 3.13 crashes. Downgrade to 3.12.5 is working again.
Windows 11 + External network drive on \\network\example\

**Comment by unddef** [comment]
same issue here with client 3.13.0-x64 on win10
file directory hosted on a veracrypt container mounted to x:\

program starts up. task bar symbol shows up. you can even open the main window. sync process starts and after 1-4 files it crashes. the log files contained no significant error messages.

**Comment by ragsna** [comment]
Also here Nexcloud client 3.13.0 crashes 
- after a few seconds when synching with local sync drive being a Veracrypt-encrypted file container
- happens with two nextcloud server instances (synchronization with both servers was working previously)
- attempt to sync with unencrypted local drive works
- Windows event viewer on local client shows 
Level: Error; Source: ApplicationError
AppName: nextcloud.exe, AppVersion 3.13.0.55335
ModuleName: ntdll.dll, ModuleVersion

**Comment by DcryptedCA** [comment]
Same issue with crashing on both 3.13.1 or 3.13.0 . 
Drive is on SD Card. Runs for 30 seconds and then crashes.
Currently running on 3.12.6 without issues.

**Comment by matvit92** [comment]
Confirm, the problem still persists with the version 3.13.1.

**Comment by git-ikeda** [comment]
Windows client 3.13.1 also crashes again. Downgrade to 3.12.5 is working again.
Windows 11 + External network drive on \network\example\

**Comment by willie68** [comment]
After 3 months of silence from the development team, is there anything new?

**Comment by tigernero79** [comment]
News?

**Comment by tigernero79** [comment]
Is it possible that this bug still exists in release 3.13.x? and no one bothers or is there any solution? a bug that doesn't exist in version 3.12.x

**Comment by CleyFaye** [comment]
Last time I checked a 3.13.x patch a month ago or so, it was still there. I'll admit I've been reluctant to test more recently, as long as there is no news posted on this issue.

**Comment by willie68** [comment]
As me. On all my Devices I'm still on the latest 3.12, clicking all the time the "you have to update " box away.

**Comment by joshtrichards** [comment]
> Confirm: USB SDD -> crash, same pc local HDD -> works

Is this truly specific to *external* drives or merely any non-default drives (e.g. anything other than `C:\`)?

**Comment by joshtrichards** [comment]
Unfortunately, `0xc0000005` is a rather generic Windows error.

Is the log getting anything written to it just prior to these crashes?

Alternatively, try running the client from the command-line. I believe even on Windows you'll get the stdout/stderr output that one does on Linux when started in this way (I don't have my Windows box handy to confirm at the moment with certainty). (e.g. https://docs.nextcloud.com/desktop/3.14/troubleshooting.html#command-line)

If anyone experiencing this is able/willing, it would be interesting to see if this is reproducible on the 3.14.x RC. It's QT6 based so there's a possibility whatever this is is gone. DISCLAIMER: Pre-release software so use with a test account + folder and/or with good backups in-place. https://github.com/nextcloud/desktop/releases/tag/v3.14.0-rc1

**Comment by tigernero79** [comment]
Test on 3.14

**Comment by CleyFaye** [comment]
They are there: https://github.com/nextcloud-releases/desktop/releases

I'll run 3.14-rc1 for a bit and report back. It used to crash after less than a minute, so it should be easy to spot.

**Comment by CleyFaye** [comment]
Yep. My situation is a synchronized directory in a veracrypt mounted drive (say "k:\syncdir"). The client did work (it added a file I created on nextcloud), but just crashed.

`nextcloud --version` says "3.13.81rc1-Win64" (I assume this is normal, as it also shows Qt6?).

Running `nextcloud.exe --logwindow --logfile d:\nextcloud.log --logdebug` ends on the following output:

```
2024-08-31 23:43:39:485 [ info nextcloud.sync.discovery C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\libsync\discovery.cpp:526 ]:	Processing "<some relative file path>" | (db/local/remote) | valid: true/true/true | mtime: 1725034756/1725034756/1725034756 | size: 122/122/122 | etag: "7147555642d41ce074a776bf106b7566"//"7147555642d41ce074a776bf106b7566" | checksum: "SHA1:6945a36bce1f38747feaa4dd355a9505e1a0f7fa"//"" | perm: "WDNVR"//"WDNVR" | fileid: "01107873oc1df7jsllrw"//"01107873oc1df7jsllrw" | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile | e2ee: false/false | e2eeMangledName: ""/"" | file lock: not locked//not locked | file lock type: ""//"0" | metadata missing: /false/
2024-08-31 23:43:39:485 [ debug nextcloud.sync.discovery C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\libsync\discovery.cpp:714 ]	[ OCC::ProcessDirectoryJob::processFileAnalyzeRemoteInfo ]:	item lock for: "<some relative file path>" OCC::SyncFileItem::LockStatus::UnlockedItem "" "" OCC::SyncFileItem::LockOwnerType::UserLock "" 0 0
2024-08-31 23:43:39:485 [ debug nextcloud.sync.discovery C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\libsync\discovery.cpp:1051 ]	[ OCC::ProcessDirectoryJob::processFileAnalyzeLocalInfo ]:	File "<some relative file path>" - servermodified: false noServerEntry: false
2024-08-31 23:43:39:486 [ debug nextcloud.sync.discovery C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\libsync\discovery.cpp:1745 ]	[ OCC::ProcessDirectoryJob::processFileFinalize ]:	"<some relative file path2> 0 0 0"
2024-08-31 23:43:39:486 [ info nextcloud.sync.discovery C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\libsync\discovery.cpp:526 ]:	Processing "<some relative file path>" | (db/local/remote) | valid: true/true/true | mtime: 1725140385/1725140386/1725140385 | size: 27/27/27 | etag: "e0e60d7e367e3fa3f9f62b43289c574e"//"e0e60d7e367e3fa3f9f62b43289c574e" | checksum: "SHA1:4c7957d92b45ed613795ac8ac7954dee12e7dd14"//"" | perm: "WDNVR"//"WDNVR" | fileid: "01107888oc1df7jsllrw"//"01107888oc1df7jsllrw" | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile | e2ee: false/false | e2eeMangledName: ""/"" | file lock: not locked//not locked | file lock type: ""//"0" | metadata missing: /false/
2024-08-31 23:43:39:486 [ debug nextcloud.sync.discovery C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\libsync\discovery.cpp:714 ]	[ OCC::ProcessDirectoryJob::processFileAnalyzeRemoteInfo ]:	item lock for: "<some relative file path2>" OCC::SyncFileItem::LockStatus::UnlockedItem "" "" OCC::SyncFileItem::LockOwnerType::UserLock "" 0 0
2024-08-31 23:43:39:486 [ debug nextcloud.sync.discovery C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\libsync\discovery.cpp:1051 ]	[ OCC::ProcessDirectoryJob::processFileAnalyzeLocalInfo ]:	File "<some relative file path>" - servermodified: false noServerEntry: false
2024-08-31 23:43:39:486 [ debug nextcloud.sync.discovery C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\libsync\discovery.cpp:1252 ]	[ OCC::ProcessDirectoryJob::processFileAnalyzeLocalInfo ]:	Local file was changed: File "<some newer relative file path>" item->_instruction: CSyncEnums::CSYNC_INSTRUCTION_SYNC noServerEntry: false item->_direction: OCC::SyncFileItem::Up item->_size: 27 item->_modtime: 1725140386
2024-08-31 23:43:39:486 [ info nextcloud.sync.discovery C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\libsync\discovery.cpp:1743 ]:	"<some newer relative file path> 64 1 0"
2024-08-31 23:43:39:486 [ info nextcloud.sync.engine C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\libsync\syncengine.cpp:783 ]:	#### Discovery end ####################################################  935 ms
2024-08-31 23:43:39:487 [ info nextcloud.sync.engine C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\libsync\syncengine.cpp:833 ]:	#### Reconcile (aboutToPropagate) ####################################################  935 ms
2024-08-31 23:43:39:487 [ info nextcloud.sync.statustracker C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\libsync\syncfilestatustracker.cpp:239 ]:	Investigating "Journal" OCC::SyncFileItem::NoStatus CSyncEnums::CSYNC_INSTRUCTION_UPDATE_METADATA OCC::SyncFileItem::Down
2024-08-31 23:43:39:487 [ debug nextcloud.gui.socketapi C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\gui\socketapi\socketapi.cpp:228 ]	[ OCC::SocketListener::sendMessage ]:	Sending SocketAPI message --> "STATUS:OK:K:\\syncdir\\somepath" to QLocalSocket(0x1c91e8fc600)
2024-08-31 23:43:39:487 [ info nextcloud.sync.statustracker C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\libsync\syncfilestatustracker.cpp:239 ]:	Investigating "<some relative path>" OCC::SyncFileItem::NoStatus CSyncEnums::CSYNC_INSTRUCTION_UPDATE_METADATA OCC::SyncFileItem::Down
2024-08-31 23:43:39:487 [ info nextcloud.sync.statustracker C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\libsync\syncfilestatustracker.cpp:239 ]:	Investigating "<some relative path>" OCC::SyncFileItem::NoStatus CSyncEnums::CSYNC_INSTRUCTION_UPDATE_METADATA OCC::SyncFileItem::Down
2024-08-31 23:43:39:487 [ info nextcloud.sync.statustracker C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\libsync\syncfilestatustracker.cpp:239 ]:	Investigating "<some relative path>" OCC::SyncFileItem::NoStatus CSyncEnums::CSYNC_INSTRUCTION_SYNC OCC::SyncFileItem::Up
2024-08-31 23:43:39:487 [ debug nextcloud.gui.socketapi C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\gui\socketapi\socketapi.cpp:228 ]	[ OCC::SocketListener::sendMessage ]:	Sending SocketAPI message --> "STATUS:SYNC:K:\\syncdir\\somepath" to QLocalSocket(0x1c91e8fc600)
2024-08-31 23:43:39:487 [ debug nextcloud.gui.socketapi C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\gui\socketapi\socketapi.cpp:228 ]	[ OCC::SocketListener::sendMessage ]:	Sending SocketAPI message --> "STATUS:SYNC:K:\\syncdir" to QLocalSocket(0x1c91e8fc600)
2024-08-31 23:43:39:487 [ debug nextcloud.gui.socketapi C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\gui\socketapi\socketapi.cpp:228 ]	[ OCC::SocketListener::sendMessage ]:	Sending SocketAPI message --> "STATUS:IGNORE:K:\\syncdir\\.nextcloudsync.log" to QLocalSocket(0x1c91e8fc600)
2024-08-31 23:43:39:487 [ debug nextcloud.gui.socketapi C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\gui\socketapi\socketapi.cpp:228 ]	[ OCC::SocketListener::sendMessage ]:	Sending SocketAPI message --> "STATUS:IGNORE:K:\\syncdir\\.sync_34c5cd5d175d.db" to QLocalSocket(0x1c91e8fc600)
2024-08-31 23:43:39:487 [ debug nextcloud.gui.socketapi C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\gui\socketapi\socketapi.cpp:228 ]	[ OCC::SocketListener::sendMessage ]:	Sending SocketAPI message --> "STATUS:IGNORE:K:\\syncdir\\.sync_34c5cd5d175d.db-journal" to QLocalSocket(0x1c91e8fc600)
2024-08-31 23:43:39:487 [ info nextcloud.sync.engine C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\libsync\syncengine.cpp:840 ]:	#### Reconcile (aboutToPropagate OK) ####################################################  936 ms
2024-08-31 23:43:39:487 [ debug nextcloud.sync.database C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\common\syncjournaldb.cpp:2799 ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit "post treewalk" and starting new transaction
2024-08-31 23:43:39:487 [ debug nextcloud.sync.database C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\common\syncjournaldb.cpp:2799 ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit "post stale entry removal" and starting new transaction
2024-08-31 23:43:39:487 [ debug nextcloud.gui.socketapi C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\gui\socketapi\socketapi.cpp:228 ]	[ OCC::SocketListener::sendMessage ]:	Sending SocketAPI message --> "STATUS:SYNC:K:\\syncdir" to QLocalSocket(0x1c91e8fc600)
2024-08-31 23:43:39:487 [ info nextcloud.sync.engine C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\libsync\syncengine.cpp:894 ]:	#### Post-Reconcile end ####################################################  936 ms
2024-08-31 23:43:39:488 [ info nextcloud.gui.folder C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\gui\folder.cpp:1182 ]:	#### Propagation start ####################################################
2024-08-31 23:43:39:488 [ debug nextcloud.gui.socketapi C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\gui\socketapi\socketapi.cpp:515 ]	[ OCC::SocketApi::slotUpdateFolderView ]:	Not sending UPDATE_VIEW for "2" because status() is OCC::SyncResult::SyncRunning
2024-08-31 23:43:39:489 [ info nextcloud.gui.application C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\gui\owncloudgui.cpp:246 ]:	Sync state changed for folder  "https://server1_url/remote.php/dav/files/user2/" :  "Sync running"
2024-08-31 23:43:39:490 [ info nextcloud.sync.propagator.root.directory C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\libsync\owncloudpropagator.cpp:1582 ]:	scheduleSelfOrChild OCC::PropagatorJob::NotYetStarted pending uploads 0 subjobs state OCC::PropagatorJob::NotYetStarted
2024-08-31 23:43:39:490 [ warning nextcloud.sync.propagator.directory C:\Users\User\AppData\Local\Temp\windows-25183\client-building\desktop\src\libsync\owncloudpropagator.cpp:1261 ]:	Useless task found for file "<some newer relative file path>" instruction CSyncEnums::CSYNC_INSTRUCTION_SYNC
```

And it stops there. I'm not posting the whole thing (there's a lot of file names in it) but there is no error anywhere in the full log. Whatever kills the process do so without anything in the log.

**Comment by tigernero79** [comment]
Installed version 3.14 rc1 same problem starts and after 30 seconds application closes.  I have data on a 128gb microsd on my surfage go2

**Comment by tigernero79** [comment]
[20240831_2357_nextcloud.log.0.txt](https://github.com/user-attachments/files/16826167/20240831_2357_nextcloud.log.0.txt)

**Comment by SimJoSt** [comment]
Found this thread/issue while trying to solve my own issues.
At least some of my issues seem to be caused by the same stuff you are running into.
Version `3.12.x` work (`3.12.7` as the latest), version `3.13.x` crash.
Windows version is 10 Pro.

My synced folders are all not in the default directory but either on a second partition `D:\Nextcloud\InstanceA\` or on an external drive `F:\`.
I'm still checking if all issues have been solved by downgrading or if I am running into multiple.

**Comment by tigernero79** [comment]
News? even the latest version is affected by this bug. 3.14

**Comment by matvit92** [comment]
> News? even the latest version is affected by this bug. 3.14

I tried 3.14 on two computers (with external path settings) and working ok. So it seems fixed 🙂

**Comment by tigernero79** [comment]
I have three nextcloud instances that store on external microsd unit, I have a surface and 3.14 gives the same problem. I don't think the problem is solved

**Comment by CleyFaye** [comment]
I just tested the stable 3.14 release in the same setup as described above (synchronized directory on k:\somedir, with k: being a veracrypt mount). Nextcloud still just die without any error in any logging facility.

**Comment by matvit92** [comment]
You're right, it still not working. It started ok for me without crash only when it not syncing anything new. Today i sync some changes in external path and it instant crashed. Sorry for my mistake in previous comment.

**Comment by qardas** [comment]
yep, 3.14 crashes same way as 3.13. for me the downgrade to 3.12.4 not working anymore: it starts to sync, after certain time it freezes and doesn't react, so I need to kill Nextcloud task in task manager. Win11 22h2 updated

**Comment by SimJoSt** [comment]
There are some other similar issues, with different causes. They were only helped by a downgrade to an even earlier release of `3.12.x`. You can try going to `3.12.2`, etc.

**Comment by MichiS97** [comment]
Just chiming on this: I've got the exact same problem on my Windows 11 install. I'm synching to a separate HDD and any client version newer than 3.12.x just crashes without notice

**Comment by hurgelwurz666** [comment]
I have the same problem. I am syncing to a drive encrypted with Veracrypt. The client 3.12.4 works, all subsequent versions crash. The synchronization to an unencrypted drive also works with higher versions than 3.12.4.

**Comment by igorneumann** [comment]
Any way to prevent it from updating itself? 
Even with "Check updates automatically" disabled it keeps updating itself to the latest version.

Im reinstalling the 3.12.3 almost daily.

**Comment by willie68** [comment]
On every start, I'll get a box with 3 buttons, where i can select what to do.
![grafik](https://github.com/user-attachments/assets/3a358809-cb2a-4caf-ba96-5c77d0c1dd44)

I'll always take the first button. 
On the settings i have selected the stabil update channel, and i do not switch on the automatic check.

![grafik](https://github.com/user-attachments/assets/6a2a6f76-b0c1-480d-af17-ff8fe781e9a1)

**Comment by david4office** [comment]
Current the Nextcloud desktop client v3.14.1 on my Windows 10 Pro 22H2 still crashed immediately after startup, after uninstall and reinstall v3.12.7, the problem has been solved. but same client version v3.14.1 on my another Windows 11 Pro doesn't have this problem.

**Comment by tigernero79** [comment]
unfortunately even version 3.14.1 has no cirrettonil bug. on my surface with microsd nextcloud vabin ctash a few seconds after its startup. only version 3.12.x works. but damn i dont know why the bug is still there

**Comment by Aesculapius** [comment]
Same here, all is updated to the latest on server & client side (3.14.1) but it still crashes after a few seconds. Nothing in the log files to point in the right direction. What can we do to debug further, because staying on 3.12.x isn't a real solution of course...

**Comment by david4office** [comment]
Ha. Today on my Windows 11, the Nextcloud Desktop Client 3.14.1 also crashed immediately at startup, the following is error log shows in the windows application event logs..
Log Name:      Application
Source:        Application Error
Date:          10/7/2024 8:06:10 AM
Event ID:      1000
Task Category: Application Crashing Events
Level:         Error
Keywords:      
Description:
Faulting application name: nextcloud.exe, version: 3.14.1.55839, time stamp: 0x66f6776f
Faulting module name: ucrtbase.dll, version: 10.0.22621.3593, time stamp: 0x10c46e71
Exception code: 0xc0000409
Fault offset: 0x000000000007f6fe
Faulting process id: 0x0x62C0
Faulting application start time: 0x0x1DB184CB26AF9C4
Faulting application path: C:\Program Files\Nextcloud\nextcloud.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 37d38442-ad2f-40da-b658-457b7b7629a2
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-10-07T00:06:10.0664694Z" />
    <EventRecordID>37001</EventRecordID>
    <Correlation />
    <Execution ProcessID="18020" ThreadID="25620" />
    <Channel>Application</Channel>
    <Computer>...</Computer>
    <Security UserID="..." />
  </System>
  <EventData>
    <Data Name="AppName">nextcloud.exe</Data>
    <Data Name="AppVersion">3.14.1.55839</Data>
    <Data Name="AppTimeStamp">66f6776f</Data>
    <Data Name="ModuleName">ucrtbase.dll</Data>
    <Data Name="ModuleVersion">10.0.22621.3593</Data>
    <Data Name="ModuleTimeStamp">10c46e71</Data>
    <Data Name="ExceptionCode">c0000409</Data>
    <Data Name="FaultingOffset">000000000007f6fe</Data>
    <Data Name="ProcessId">0x62c0</Data>
    <Data Name="ProcessCreationTime">0x1db184cb26af9c4</Data>
    <Data Name="AppPath">C:\Program Files\Nextcloud\nextcloud.exe</Data>
    <Data Name="ModulePath">C:\WINDOWS\System32\ucrtbase.dll</Data>
    <Data Name="IntegratorReportId">37d38442-ad2f-40da-b658-457b7b7629a2</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
  </EventData>
</Event>

**Comment by Aesculapius** [comment]
So this is still an issue in the latest versions and apparently a lot of folks are getting this. How can we proceed as it seems this bug report isn't really followed up. Providing logging could prove difficult as there isn't many... Staying on old versions also is not quite the acceptable long term solution of course. Anyone?

**Comment by digimbyte** [comment]
until nextCloud becomes the next CrowdStrike - I doubt this is a high priority, since new versions are being pushed without a fix.

**Comment by Maxobus** [comment]
Also confirm crash on v3.14.3. Windows 10, folder is mapped on virtual (encrypted) drive.

v3.12.x is working fine.

**Comment by hdmr14** [comment]
I tried setting up a junction and a symbolic link to link an external storage to the C drive so that the Nextcloud client would appear to sync files to C:\Users\<username>\Nextcloud, but it still results in a silent crash.
I was considering the possibility that the drive letter or path might be the issue, so I thought this setup would work around it. I'm disappointed. I just hope we can find some kind of workaround.

Windows 11, Nextcloud client 3.14.3

**Comment by matvit92** [comment]
First test on one of my devices after update to 3.15.0 seems ok. What about the rest of you? Your experiences?

**Comment by CleyFaye** [comment]
It is a bit early to provide a definitive answer, but my setup that crashed the client almost immediately on 3.13 and 1.14 did synchronize files both way with 3.15.0 and did not crash. It is very promising.

**Comment by willie68** [comment]
Just updated to 3.15, seems to work... Promising

**Comment by 3d-pro** [comment]
another confirmed that updated from 3.12.x to 3.15.0 seems to fixed the issue.

**Comment by Maxobus** [comment]
I confirm, that on Windows 10 update from 3.12.x to 3.15.0 fixed the issue.

**Comment by hdmr14** [comment]
The application still crashes in my environment (Windows 11, Nextcloud Client 3.15.0).
However, I am not sure if the crash is caused by the same issue as before.
In any case, it seems I still need to stick with version 3.12.x.

Faulting application name: nextcloud.exe, version: 3.15.0.56037, time stamp: 0x6744f4a6
Faulting module name: ucrtbase.dll, version: 10.0.22621.3593, time stamp: 0x10c46e71
Exception code: 0xc0000409
Fault offset: 0x000000000007f6fe

**Comment by rootseeker** [comment]
> The application still crashes in my environment (Windows 11, Nextcloud Client 3.15.0). However, I am not sure if the crash is caused by the same issue as before. In any case, it seems I still need to stick with version 3.12.x.
> 
> Faulting application name: nextcloud.exe, version: 3.15.0.56037, time stamp: 0x6744f4a6 Faulting module name: ucrtbase.dll, version: 10.0.22621.3593, time stamp: 0x10c46e71 Exception code: 0xc0000409 Fault offset: 0x000000000007f6fe

same exception code 409 here. and i'm running v3.15.0 on win10. NC crashed when syncing file.

when i tried to pause the background sync task and resumed it on the settings page, it crashed on some "unresolved conflicts" message, not sure if that's the cause, but no help removing the files to sync on local machine.

**Comment by matvit92** [comment]
@hdmr14 @rootseeker I think, its different issue. In my (our) case, it instantly crashed after application start, and there was no log info. Try to open another ticket with your log informations, because this topic is in my opinion solved. I will close it soon.

**Comment by Uzurka** [comment]
Just updated from 3.12 to 3.15, seems to sync. FInally fixed ?

**Comment by rootseeker** [comment]
> [@hdmr14](https://github.com/hdmr14) [@rootseeker](https://github.com/rootseeker) I think, its different issue. In my (our) case, it instantly crashed after application start, and there was no log info. Try to open another ticket with your log informations, because this topic is in my opinion solved. I will close it soon.

i think you're right. i just saw someone opened a new ticket [#7592 ] and i left my log info there.

**Comment by steinjo** [comment]
after installing 3.15 with Nextcloud Hub 9 (30.0.2) it works again on my veracrypt drive.
Thanks for fixing it!

**Comment by matvit92** [comment]
Today i updated to 3.15.1 on 3 windows PCs with external paths and still no problem, so its finally solved. Thanks everyone :)
