### ISSUE TITLE
[Bug]: Missing icons and functionality

### ISSUE THREAD

**Issue by stevefalco** [nextcloud/desktop#6729]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I have the Nextcloud desktop installed on a Fedora 40 machine running KDE.  I built this from source (desktop-3.13.0.tar.gz).

When I click on the client icon (in the tray area) the icon in the upper right where one clicks for "File, Dashboard, Photos, and Activity" is missing.  If I click in that area, then a menu of those choices does pop up, so the action is still connected, just invisible.

More annoying, if I click on my name in the upper left, I should see a plus sign for "Add account" as well as several other functions like "Pause sync, Settings, and Exit".  None of those are visible, and clicking in that area does nothing.

Here are screenshots with the incorrect areas circled in red.

![Screenshot_20240504_100714](https://github.com/nextcloud/desktop/assets/2120316/5fb74dc5-34ea-4c4e-82ff-94d978314929)

![Screenshot_20240504_100739](https://github.com/nextcloud/desktop/assets/2120316/f868ae09-f592-492b-a031-2944e566a71b)

Note - If I right-click the client icon in the system tray then I do get a menu popup allowing me to open the settings,etc.  So the functionality is availble, just not from the main dialog.

Also, I tried installing the desktop from the native Fedora repository, and it has the same behavior.

Client log file:

[log.zip](https://github.com/nextcloud/desktop/files/15210017/log.zip)

### Steps to reproduce

1. Build desktop-3.13.0.tar.gz on a Fedora 40 system running KDE under XWindows.
2. Click on the tray icon and notice the upper right area is blank
3. Click on the user name in the upper right and notice the missing "+" and other functions

### Expected behavior

The missing icons should be present.

### Which files are affected by this bug

Files are not affected

### Operating system

Linux

### Which version of the operating system you are running.

Fedora 40, KDE, X11

### Package

Compiled it myself

### Nextcloud Server version

Nextcloud Hub 8 (29.0.0)

### Nextcloud Desktop Client version

3.13.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by stevefalco** [comment]
I should add that I just tried the appimage (Nextcloud-3.13.0-x86_64.AppImage) and it works properly, so I'll use that for now.

**Comment by claucambra** [comment]
Can reproduce

**Comment by avatar1024** [comment]
Can reproduce even with 3.12.5 in fedora 40 kde (both with wayland and x11)

**Comment by stevendbrady** [comment]
Same with OpenSuse Tumbleweed, as well as Flathub.

With this issue I seem to be unable to add accounts after the first as well.

**Comment by claucambra** [comment]
Hi all, looks like our QML code had some issues when using the Breeze QML components. This issue doesn't appear with the AppImage because the AppImage package does not use the system theme.

I've pushed a PR to fix this in #6798

**Comment by stevefalco** [comment]
I tested your changes and they look good to me.  I now see all the missing GUI items.

Thanks for the fix!

**Comment by fwsmit** [comment]
I'm on version 3.13.2 on fedora 40 and am still experiencing this issue.

**Comment by stevefalco** [comment]
I'm running 3.14.0 on Fedora 40 and it works for me.  I built it from the source available here:

https://github.com/nextcloud/desktop/releases

I'm not sure when that version will make it into Fedora.

**Comment by fwsmit** [comment]
Ah it seems the backport was released in 3.13.3, so that version should probably be released for fedora. I'll give the package maintainer a poke.

**Comment by stevefalco** [comment]
You should be able to update from the testing repo:

sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2024-dc596223ff

And if you have a login on bodhi, you could even add karma after testing:

https://bodhi.fedoraproject.org/updates/FEDORA-2024-dc596223ff

**Comment by JediBrooker** [comment]
i can confirm i have the same problem. arch linux (btw), nextcloud client 3.14.3. both apps icon missing from toolbar as well as nextcloud assistant icon missing too.

**Comment by majneb** [comment]
Icons are still missing in Fedora KDE with version 3.16.3. 
The QT_QPA_PLATFORMTHEME=gtk3 environment variable works as a workaround, but this makes the client not well integrated with plasma, as it uses the GTK theme.
Shouldn't the issue be reopened ?

**Comment by lolcabanon** [comment]
Still missing some icons as of today on a freshly installed Manjaro KDE (X11) with version `3.16.6daily (Manjaro)` from the official extra repo.

I don't really know how to provide debug logs in useful infos, but I am open to help investigate if someone can point me in the right direction for starter (direct instructions or tutorial/documentation).

<img width="473" height="597" alt="Image" src="https://github.com/user-attachments/assets/53889702-251d-43b3-916f-9ce2a195e99d" />

**Comment by Mayurifag** [comment]
latest kdeplasma, archlinux, nextcloud-client, icons are missing. X11 or wayland - doesnt matter.

Not sure why issue is closed

**Comment by avatar1024** [comment]
> latest kdeplasma, archlinux, nextcloud-client, icons are missing. X11 or wayland - doesnt matter.
> 
> Not sure why issue is closed

It's reopened here: https://github.com/nextcloud/desktop/issues/7419
