### ISSUE TITLE
[Bug]: Nextcloud Desktop crashes shortly after start in version 3.13.0

### ISSUE THREAD

**Issue by claell** [nextcloud/desktop#6793]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I know, one should maybe not update to the ...0 releases of Nextcloud Desktop.

Still, I took the risk. Now, the client closes itself/crashes after launching it.

### Steps to reproduce

Unknown

### Expected behavior

No crash

### Which files are affected by this bug

-

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Other

### Nextcloud Server version

-

### Nextcloud Desktop Client version

3.13.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by schliesser** [comment]
Heyho,

my 3.13.0 Desktop client on Windows 11 (Version 10.0.22631 Build 22631) also crashes.

So far I've investigated the following behaviour:
- Pausing all syncs immediatly after start -> Client keeps running
- Enable Sync for a folder that has no changes -> Client keeps running
- Enable Sync for a folder that has only local updates on my Windows machine -> Syncs to NC Server correctly -> No crash
- Enable Sync for a folder that has updates on server side -> Client crashes on file write

Hope that helps.

Maybe related to #6566 ?

**Comment by Aesculapius** [comment]
I'm seeing the same behavior with 3.13.0. with the same results as far as pausing sync keeping the client running.
I inspected the local log files but there's nothing interesting in it; the last lines read 

2024-06-11 22:38:54:894 [ info nextcloud.sync.statustracker C:\Users\User\AppData\Local\Temp\windows-22489\client-building\desktop\src\libsync\syncfilestatustracker.cpp:239 ]:	Investigating "InstantUpload/Camera/2024/06/20240609_184323.jpg" OCC::SyncFileItem::NoStatus CSyncEnums::CSYNC_INSTRUCTION_NEW OCC::SyncFileItem::Down

**Comment by Aesculapius** [comment]
The problem still persists in 29.0.2...

**Comment by mgscreativa** [comment]
Same [here](https://github.com/nextcloud/desktop/issues/6793), had to downgrade to v3.4.2

**Comment by rosa2** [comment]
Same problem with Ubuntu 22.04.4.
It freezes with large folders. I have several servers. I have to stop sync for all and then, one by one re-enable the sync. 
It gets very slow. 
Is it a way to downgrade with not loosing all the configuration? Thanks

**Comment by mgscreativa** [comment]
I can't find any old packages in PPA archives!

**Comment by Phx01** [comment]
Also the same on Fedora 40 with Nextcloud client v3.13.0.

Downgrading to 3.12.1 generally works.  However, even that version goes haywire if you start entirely unrelated applications, e.g. Steam client.  Once Steam is started, the Nextcloud client (v3.12.1) can be started again and it behaves normal going forward. However, it can as well be reproduced 100% by simply quitting Steam and restarting it.  I honestly do not know what is going on at the start of Steam, but it is likely the Nextcloud client is writing to memory it shouldn’t and then when the Steam client starts, it itself writes to that address making the Nextcloud client unstable.

While it is absolutely possible that the Steam client is doing something wrong, since only the Nextcloud client is affected and only during Steam startup, I tend to believe that it is likely caused by the Nextloud client, which with v3.13.0 expanded this pre-existing memory leak.

**Comment by janarzz** [comment]
Latest Nextcloud desktop still not work.
When i open it, then immediately crash.
I updated Nextcloud server to 29.0.3, but desktop still crash.

**Comment by Matth3wW** [comment]
> Downgrading to 3.12.1 generally works. However, even that version goes haywire if you start entirely unrelated applications, e.g. Steam client. 

I'm having this issue as well.

-     Operating System: Fedora 40 (latest as of 2024-06-25)
-     Nextcloud Client: 3.13.0
-     Nextcloud Server: 29.0.2 selfhosted on a proxmox debian LXC running LAMP stack.

Downgrading to 3.12.1 fixes the issue. Upgrading back to 3.13.0 has the issue return.

However, on 3.12.1, I do not have the issue you have while launching steam.

**Comment by janarzz** [comment]
I hope next desktop update fix this issue.

**Comment by mgscreativa** [comment]
Using alpha 3.13.50 from alpha PPA hangs too https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client-alpha

**Comment by EddyXorb** [comment]
I confirm the issue for Windows 11 23H2 and nextcloud client 3.13.0. Crashes after less than a minute after start, blocking the windows file explorer completely and making it impossible to open programs via right-click on the lower windows task list, which is very annoying.

**Comment by claell** [comment]
This seems to have gotten resolved for me after updating to 3.13.1. Possibly related to a host that isn't reachable anymore.

**Comment by janarzz** [comment]
> This seems to have gotten resolved for me after updating to 3.13.1. Possibly related to a host that isn't reachable anymore.

Hi, i tryng to use latest version 3.13.1.
Still crashing! I downgraded my desktop back to 3.12.4 version

**Comment by steumac** [comment]
Hi, 3.13.0 and 3.13.1 Windows 11 still crashing. Server version 27.1.11. Downgraded to 3.12.3 and working good so far.

**Comment by frivascl** [comment]
I had the same problem. Just delete .sync* and ._sync* and worked again.

**Comment by hdeppert** [comment]
> I had the same problem. Just delete .sync* and ._sync* and worked again.

This is the solution! The sync files are located inside the top level directory where you sync your Nextcloud files.

In addition, you can clean up some old config and log files folder located in %UserFolder%\AppData\Roaming\Nextcloud

This issue should can be solved if the Nextcloud client make some checks of the sync database and config files before it uses some corrupt files and crashes.

**Comment by joshtrichards** [comment]
Closing since OP's issue appears fixed as of 3.13.1:

https://github.com/nextcloud/desktop/issues/6793#issuecomment-2203343409

So anyone else on this thread likely has different underlying cause(s). Please create dedicated issues with their unique details so those situations can be looked into.

**Comment by janarzz** [comment]
Hi,
version 3.13.3 still crashing.

**Comment by rosa2** [comment]
after some days working, it started to crash again.

i have 3.13.3 and still crashing in Ubuntu 22.10
if i start it from terminal, i get
nextcloud.gui.application: Migrating old config from "/myhome/.local/share/Nextcloud" to "/myhome/.config/Nextcloud"
nextcloud.gui.application: Failed to move the old config directory to its new location ( "/myhome/.local/share/Nextcloud" to "/myhome/.config/Nextcloud" )
nextcloud.gui.application: Will move the individual files ("site_1_sync.log", "site_2_sync.log", "site_3_sync.log", "site_4_sync.log", "nextcloud_sync.log", "site_5_sync.log")
nextcloud.gui.application: Fallback move of  "site_1_sync.log" also failed
nextcloud.gui.application: Fallback move of  "site_2_sync.log" also failed
nextcloud.gui.application: Fallback move of  "site_3_sync.log" also failed
nextcloud.gui.application: Fallback move of  "site_4_sync.log" also failed
nextcloud.gui.application: Fallback move of  "nextcloud_sync.log" also failed
nextcloud.gui.application: Fallback move of  "site_5_nextcloud_sync.log" also failed

i could pass the freezing by pausing the sincronization and sincronize one by one.
if i delete the files in .loca./share/Nextcloud then they get copied but the last.

**Comment by metapublic-gbr** [comment]
Nextcloud-desktop crashes after approx. 3 seconds.
I have ubuntu 22.04, nextcloud 3.13.3.

Moving everything out of /myhome/.local/share/Nextcloud and removing the folder doesn't help: The folder will be recreated containing a file "Cloud_sync.log"

**Comment by TaegonChung** [comment]
> Hi, 3.13.0 and 3.13.1 Windows 11 still crashing. Server version 27.1.11. Downgraded to 3.12.3 and working good so far.

This was the solution. I've upgrade Nextcloud to 3.14.0 on two Windows computers and both had problems. One kept shutting down immediately after boot and the other never have shown main dialog window. Downgraded to 3.12.7 and both works fine.

**Comment by TaegonChung** [comment]
> Hi, 3.13.0 and 3.13.1 Windows 11 still crashing. Server version 27.1.11. Downgraded to 3.12.3 and working good so far.

This was the solution. I've upgrade Nextcloud to 3.14.0 on two Windows computers and both had problems. One kept shutting down immediately after boot and the other never have shown main dialog window. Downgraded to 3.12.7 and both work fine.

**Comment by rosa2** [comment]
Again I had problems. I tested Nextcloud-3.14.1-x86_64.AppImage that didn't resolve the problem.
Then I downgrade to Nextcloud-3.13.4-x86_64.AppImage in Ubuntu 22.04.5 LTS and now no problem.
Just in case people want to downgrade, here you can find the apps
https://download.nextcloud.com/desktop/releases/

I have to teach this app to people that just started with NextCloud... I hope that you can fix this before because they have different operative systems and they will not get a good image on NextCloud, will they? :)

Thanks developers and maintainers.

**Comment by rosa2** [comment]
The problem keeps returning, even with the downgrade. I found
https://github.com/nextcloud/desktop/issues/4661 
I hope this works and can upgrade o keep the Nextcloud-3.13.4-x86_64.AppImage without problems.

**Comment by rosa2** [comment]
I think that i found my problem: in the last release the NextCloud server started to disallow illegal characters https://github.com/nextcloud/server/issues/38614 and the synchronization was crashing my client. Now i am testing it but it looks that it was my problem.
I hope this will help anybody :)
After renaming the files and folders through the browser and reinstalling the last version, it seems to be working well.
I also configured the server with this new feature https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#forbidden-filename-characters

**Comment by raychani** [comment]
I upgraded to version 3.15, but the program still crashes. Version 3.12.8 works fine.
My server version is 30.0.2, and I'm using client on Windows 11.

**Comment by danielschwab** [comment]
I am running version 3.17.2daily (from `https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client`) on Ubuntu 24.04.3 and got also a lot of crashes. 
I found out that even with "Launch on System Startup" disabled the nextcloud client will start and pollute my  logs with crash infos. 

My solution was to delete `/etc/systemd/user/default.target.wants/com.nextcloud.desktopclient.nextcloud.service`.

The client still starts with "Launch on System Startup" enabled (which creates an entry in the startup programs list).

I am not sure what the service does and if deleting has some unwanted side effects but I'll test it.
