### ISSUE TITLE
[Bug]: Linux Pop!OS 22 Dialog Unusable - Possible due to Fractional Scaling of 150% on 4K monitor

### ISSUE THREAD

**Issue by p-sims** [nextcloud/desktop#6823]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The Nextcloud dialogue is unusably small so you can't see the error message/unresolve conflicts:
![Nextcloud Dialog Pop! OS 2024 Fractional Scaling 150% 4K display](https://github.com/nextcloud/desktop/assets/64636731/18bc3d8a-a554-434e-abe6-e2b180a15d17)

### Steps to reproduce

1. Click on ion in indictors bar (top right in gnome)
2. Click 'open dialogue'

### Expected behavior

The dialogue should be big enought (or resizable) so that you can see list of activity/errors and interact with them.

### Which files are affected by this bug

N/A

### Operating system

Linux

### Which version of the operating system you are running.

Pop!OS 22.04 Gnome Xorg

### Package

Distro package manager

### Nextcloud Server version

27.1.10

### Nextcloud Desktop Client version

3.4.2

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
N/A
```

### Additional info

I notice than why I move mouse over the dialgue the point icon reduces in size, and when I move mouse off dialogue it then goes back to expected size. I expect this has to do with fractional scaling which I expect nextcloud desktop client doesn't support properly.

**Comment by PhilippSchlesinger** [comment]
@p-sims  The client version you use is more than three years old and maybe the problem you describe is resolved since.

The recent stable version is 3.12.5 (3.13.0 being released but facing some bugs). Maybe you have the possibility to retest with a recent version?

**Comment by maxmellown** [comment]
@PhilippSchlesinger It seems that this issue still exists in the latest version (33.0.4), running on Gnome 49 (Ubuntu 25.10), with fractional scaling set to 150%:

<img width="648" height="547" alt="Image" src="https://github.com/user-attachments/assets/0903512f-38de-4261-a579-c6d6744c8084" />
