### ISSUE TITLE
[Bug]: 3.14.0 UI elements not working and claims sync issues (which are not existent)

### ISSUE THREAD

**Issue by cmasterdelphi** [nextcloud/desktop#7143]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Installation from 3.13.4 > 3.14 worked, but after the restart it behaved very strange and didnt work correctly
1. my taskbar had rotated 90%
2. nextcloud client claimed there are some sync conflicts
3. i was not able to display the sync conflicts (nothing happend when clicking it)
4. the general window for synconization / status was not showing
5. I downgraded back to 3.13.4 and everything worked flaweless again. (no sync conflicts, status opens, etc)

### Steps to reproduce

1) run automatic upgrade as suggested by the application (3.13.4 -> 3.14.0)
2) restart your computer

### Expected behavior

* should not mess with my general Windows UX
* should sync
* should show snyc conflicts if there are any
* should open the sync/file view when clicking the icon

### Which files are affected by this bug

none

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 22H2 Build 19045.4780

### Package

Official Windows MSI

### Nextcloud Server version

29.0.6snap1

### Nextcloud Desktop Client version

3.14.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
No older log entries available
```

### Additional info

none

**Comment by mgallien** [comment]
@cmasterdelphi
can you provide screenshots and logs ?

**Comment by ShockHouse5** [comment]
Similar boat here. Had a working 3.13.3, upgraded to 3.14. I don't get any sync issues, and everything still syncs correctly. If I right click in the task bar and select "Open main dialog" nothing happens. Selecting settings still works. 

Uninstalled 3.14, deleted all the files in the %temp% locations, reinstalled and get the same behavior. This prevents me from adding multiple accounts since that window won't open.

**Comment by PasswordIs0000** [comment]
I'm also on Windows 11 and the "Open main dialog" also doesn't work for me with version 3.14.

**Comment by MaximeMaW** [comment]
Same here: i was not able to display the sync conflicts (nothing happend when clicking it)

**Comment by jumika** [comment]
"Open main dialog" does not work. Windows 11. Version: 3.14.
I've choose not to restart my computer immediately after the installation.

**Comment by ShockHouse5** [comment]
It looks like, as listed in the #7139 comments. If you exit Nextcloud, then open Nextcloud, the "Open main dialog" works after that. So it seems like only the initial launch (launch on startup?) exhibits the issue.

**Comment by PasswordIs0000** [comment]
Yes, I can confirm that. Exit Nextcloud and start it again, then the "Open main dialog" works. Should still be fixed 😉

**Comment by cmasterdelphi** [comment]
> @cmasterdelphi can you provide screenshots and logs ?
Which log files are you referring to?
* Server doesn't show any issues in the logs 
* Not sure where I should look for the desktop client logs

About screenshots:
* What do you need to see compared to the description?
 - sync Icon is yellow and claims sync conflicts
 - settings windows shows "sync conflicts" but does not open any "sync conflict files"
 - Open main dialog" does not open (not sure how I am supposed to make a screenshot of something that does not work)

**Comment by cmasterdelphi** [comment]
> @cmasterdelphi can you provide screenshots and logs ?

* I tried to do another automatic update but it didn't work
* I manually installed 3.14 via msi to update my 3.13.4 installation

This time, I didn't restart my computer and it worked (Open Main Dialog) was opening
Also it showed me a conflict of syncinc an .htaccess file (which again on 3.13.4 was not showing) - i resolved this, but why didnt it show on 3.13.4?
After restarting the computer the Open Main Dialog was not opening again unless I closed Nexcloud and opened it again  as suggested by @ShockHouse5 which makes it work again.

**Comment by juliomaranhao** [comment]
> Yes, I can confirm that. Exit Nextcloud and start it again, then the "Open main dialog" works.

For me the main dialog shows up again, but it doesn't work as it slows down itself and it cannot do any sync activities (freeze), even pending ones. Explorer process consumes more than 20% cpu and Nextcloud 6%. Just kills Nextcloud to restore Explorer to ~0%.

I am not writing this to mix (possible?) different bugs. It is just to **recommend with my heart any Nextcloud user to downgrade to 3.13.4** to stay away from these regression issues. Yes, 3.14.1 is still unusable. And with 3.13.4 everything works.

**Comment by mgallien** [comment]
this is now solved with the release of 3.14.1

**Comment by iwo-strzebonski** [comment]
Reopening as the issue is still present

![Image](https://github.com/user-attachments/assets/a9410807-ca32-42e3-aaee-cd41542abdd9)

**Comment by thetimelord-rpi** [comment]
> this is now solved with the release of 3.14.1

No it isn't. Any idea, when it might be fixed?
