### ISSUE TITLE
[Bug]: After updating desktop client to 3.14: Uploading files fails with "Connection closed"

### ISSUE THREAD

**Issue by damoosenrw** [nextcloud/desktop#7176]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I updated to the latest stable version of the desktop client on Mac OS this morning.

After updating the dektop client to the latest version any of my uploads fail with the error message "Connection closed" and "Server is unable to maintain the header compression context for the connection".

### Steps to reproduce

1. Put a new larger file into a synced folder
2. Wait for the sync process to start
3. syncing fails

### Expected behavior

The files are synced.

**Client view:**
<img width="1517" alt="Bildschirmfoto 2024-09-20 um 22 14 44" src="https://github.com/user-attachments/assets/84b2e097-cc31-41e4-8ef6-5ec0be7211f3">

**Client Log file:**
[20240920_2230_nextcloud.log.4.gz](https://github.com/user-attachments/files/17080727/20240920_2230_nextcloud.log.4.gz)

### Which files are affected by this bug

Verdunklung (1990) - Track 01.mp3

### Operating system

macOS

### Which version of the operating system you are running.

Sonoma 14.6.1 (23G93)

### Package

Official macOS 12+ universal pkg

### Nextcloud Server version

29.0.7

### Nextcloud Desktop Client version

3.14

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

The desktop client logs zip file has a size of 324 MB. As the upload limit is 25 MB I only upload the actual .gz file containing a log entry related to the file mentioned above.

Do you need any other files? If so, please let me know I will add them here.

**Comment by eskopp** [comment]
See: #7171

**Comment by SofianeLasri** [comment]
I have this too.

**Comment by damoosenrw** [comment]
> See: #7171

I saw this defect, but was unsure if it is the same, as the mentioned error messages from the client were different.

I downgraded to 3.13.4 which I downloaded here: https://download.nextcloud.com/desktop/releases/Mac/Installer/

Solved my problem, uploadin my file works fine again.

**Comment by nguyenvanchiem** [comment]
same issue.

**Comment by andrepbento** [comment]
I have this issue

**Comment by MatthiasGer0821** [comment]
Had exactly the same issue as OP, downgraded to 3.13.4 on windows and everything works.

**Comment by lckarssen** [comment]
Same here on Ubuntu 22.04 with Nextcloud client 3.14.0. Nextcloud server version 29.0.7 self-installed (years ago), running in an LXD container with Ubuntu server 22.04.4.

**Comment by kkausu** [comment]
Same problem on Windows 10 with Nextcloud client 3.14.0.  https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-3.13.4-x64.msi works

**Comment by cetcondor** [comment]
We have encountered the same issue in a very diverse user scenario. The Nextclouds in question run on managed servers at German provider Hetzner. After some testing we **found a temporary workaround**: when **deactivating mod_http2** suddenly all synchronising worked again. Unfortunately I am not in the situation to figure out whether it's a problem with Hetzner's deployment or on the Nextcloud code side.

**Comment by cetcondor** [comment]
The developers are tackling the issue already: https://github.com/nextcloud/desktop/pull/7182

**Comment by lckarssen** [comment]
> when **deactivating mod_http2** suddenly all synchronising worked again.

Thanks! That worked for me too. :pray:

**Comment by mgallien** [comment]
solved by https://github.com/nextcloud/desktop/pull/7182

**Comment by Quietscher** [comment]
I am sorry this error is still occuring in the newest version!

**Comment by Quietscher** [comment]
im on macOS with nextcloud client 3.14.1

**Comment by Quietscher** [comment]
@mgallien @cetcondor

**Comment by tomtomme** [comment]
same issue here on manjaro with various bigger zip and pdf files on a Webo-hosted nextcloud  version 28.0.5

**Comment by Justinzobel** [comment]
Is this still happening with 3.16.4?

**Comment by damoosenrw** [comment]
Me neither

**Comment by Justinzobel** [comment]
I'm currently testing a 258.2MiB file uploading at the moment to our Nextcloud instance, it's in another region so the upload is slow but I will advise once the upload is complete if this bug affected me. Client is 3.16.4 and server 30.0.9.

**Comment by Justinzobel** [comment]
Yep, upload completed with HTTP2 enabled without any issues. @mgallien do you think we can retry making HTTP/2 the default with HTTP/1.1 as a fallback for servers that don't have HTTP/2 enabled (though they really should be encouraged to where possible as it saves a lot of resource usage for client and server).
