### ISSUE TITLE
[Bug]: Upgrade to 3.14.0 changes update channel from Stable to Daily

### ISSUE THREAD

**Issue by uselpa** [nextcloud/desktop#7178]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Version 3.14.0 changes the update channel. It should not.

### Steps to reproduce

Update Nextcloud desktop client from 3.13.4 to 3.14.0

### Expected behavior

Do not touch that setting.

### Which files are affected by this bug

none

### Operating system

macOS

### Which version of the operating system you are running.

15.0

### Package

Official macOS 12+ universal pkg

### Nextcloud Server version

28

### Nextcloud Desktop Client version

3.14.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by MariusQuabeck** [comment]
can confirm, my client on stable channel just updated itself to 3.14.0daily

**Comment by jonasgarstick** [comment]
Same here.

**Comment by mgallien** [comment]
@MariusQuabeck @jonasgarstick which OS are you using ?

**Comment by mgallien** [comment]
@uselpa @MariusQuabeck @jonasgarstick 
I just tested on Windows upgrading from 3.13.4 to 3.14.0 and could not reproduce
would you be able to reproduce it and generate a debug archive once you have the issue ?
I can provide an upload only share link if you need

**Comment by jonasgarstick** [comment]
> @MariusQuabeck @jonasgarstick which OS are you using ?

It was on a macOS with Ventura v13.6.6. My desktop client on macOS v14.6.1 installed 3.14.0daily but did not switch the update channel to daily.

**Comment by uselpa** [comment]
```
pu@Greenmac 504 ~/Library/Preferences/Nextcloud $  ls -altr *.cfg*
-rw-r--r--  1 pu  staff    37 28 Apr 13:46 nextcloud.cfg.backup_20240428_134646
-rw-------  1 pu  staff     0 22 May 18:03 nextcloud.cfg.dGbycF
-rw-r--r--  1 pu  staff     0  9 Jun 00:29 nextcloud.cfg.jeIcCg
-rw-r--r--  1 pu  staff     0 29 Jun 20:04 nextcloud.cfg.MjVWDE
-rw-r--r--  1 pu  staff  1163  4 Jul 18:35 nextcloud.cfg.backup_20240704_183504_3.13.0git (build 22490)
-rw-r--r--  1 pu  staff  1166  9 Jul 21:51 nextcloud.cfg.backup_20240709_215119_3.13.1stable (build 24143)
-rw-r--r--  1 pu  staff  1691 26 Aug 16:06 nextcloud.cfg.backup_20240826_160626_3.13.2stable (build 24386)
-rw-r--r--  1 pu  staff  1691 13 Sep 14:24 nextcloud.cfg.backup_20240913_142456_3.13.3stable (build 25180)
-rw-r--r--  1 pu  staff  1692 21 Sep 10:23 nextcloud.cfg.backup_20240921_102337_3.13.4stable (build 25658)
-rw-r--r--  1 pu  staff  2303 26 Sep 07:01 nextcloud.cfg

pu@Greenmac 505 ~/Library/Preferences/Nextcloud $  diff "nextcloud.cfg.backup_20240921_102337_3.13.4stable (build 25658)" nextcloud.cfg
2c2
< clientVersion=3.13.4stable (build 25658)
---
> clientVersion=3.14.0daily
4a5
> desktopEnterpriseChannel=daily
15a17
> updateChannel=stable
29a32,41
> 0\networkDownloadLimit=0
> 0\networkDownloadLimitSetting=-2
> 0\networkProxyHostName=
> 0\networkProxyNeedsAuth=false
> 0\networkProxyPort=0
> 0\networkProxySetting=0
> 0\networkProxyType=0
> 0\networkProxyUser=
> 0\networkUploadLimit=0
> 0\networkUploadLimitSetting=-2
30a43
> 0\serverHasValidSubscription=false
46a60,69
> 1\networkDownloadLimit=0
> 1\networkDownloadLimitSetting=-2
> 1\networkProxyHostName=
> 1\networkProxyNeedsAuth=false
> 1\networkProxyPort=0
> 1\networkProxySetting=0
> 1\networkProxyType=0
> 1\networkProxyUser=
> 1\networkUploadLimit=0
> 1\networkUploadLimitSetting=-2
47a71
> 1\serverHasValidSubscription=false
``

**Comment by stacheldrahtje** [comment]
Same here on openSUSE Tumbleweed

**Comment by core-code** [comment]
apart from the "update channel", just downloading recent releases on macOS you can see that the official releases are now being labeled "daily" instead of "stable". this should obviously not happen for official releases.

![Image](https://github.com/user-attachments/assets/3ebbf659-03b7-443f-82fc-b7f6034d348a)
![Image](https://github.com/user-attachments/assets/3b93a2a1-e1a8-4970-b1ba-6816b40592b8)

the change happend with 3.14.0, which was the first official release being labeled as "daily".

in technical terms the issue here is the in `CFBundleShortVersionString` stored in the `Info.plist` file

**Comment by MariusQuabeck** [comment]
I am also back on daily without my doing 🙃 . I had to reinstall last time to get on stable again, please let me know if you need any files for debugging before I nuke and pave again.

**Comment by core-code** [comment]
still broken in 3.15 :(

![Image](https://github.com/user-attachments/assets/2522ee2a-6365-45f4-a2f8-9363205e4fc8)

**Comment by core-code** [comment]
but fixed in 3.15.1 :)

**Comment by Rello** [comment]
Hello,
the version handling was repaired some time ago now. please test with a recent client and report back in case it still occurs

**Comment by core-code** [comment]
fixed in 3.15.1, thanks
