### ISSUE TITLE
Linux client does not scale on HighDPI displays

### ISSUE THREAD

**Issue by Redsandro** [nextcloud/desktop#72]
What is this? A client for ants?

![image](https://user-images.githubusercontent.com/1702193/33278011-7f0614c8-d39a-11e7-8315-7f153939a682.png)

Joking of course, referencing the _"Derek Zoolander Center For Kids Who Can't Read Good"._ I got myself a new 4k monitor, and noticed the NextCloud client is not playing nice. All other apps I'm using (except [Dropbox](https://twitter.com/Redsandro/status/935184995160862720)) automatically know what's going on and scale properly. Is this something the NextCloud client can do too?

I installed the version for Ubuntu 16.04 LTS (NextCloud Client Version 2.3.2).

**Comment by camilasan** [comment]
Do you still experience this problem with the 2.3.3 client?

**Comment by select** [comment]
For me the scaling worked at the first start but now I'm back to the unscaled small UI again 
Version 2.5.1git. 
Ubuntu 18.10

**Comment by select** [comment]
I solved it by adding `X-GNOME-Autostart-Delay=5` to `~/.config/autostart/Nextcloud.desktop` so gnome has time to load the scaling factor. I got the solution from https://github.com/nextcloud/desktop/issues/205

**Comment by dgerasimov** [comment]
I have the same issue. Latest Nextcloud client (appimage from site), Linux MInt Cinnamon edition. 
![Screenshot from 2019-04-07 12-24-56](https://user-images.githubusercontent.com/11664248/55681597-cd596180-5930-11e9-8d3c-d678fa9e17e7.png)

**Comment by camilasan** [comment]
I believe we have fixed this. Could you try 2.5.3 or the release candidate for 2.6?
https://github.com/nextcloud/desktop/releases

**Comment by Redsandro** [comment]
Thank you for the update. I'm not using Nextcloud at the moment. I've switched to Seafile for speed. Ironically it has the [same problem](https://github.com/haiwen/seafile-client/issues/1123). :joy:

**Comment by dgerasimov** [comment]
Nope. Still the same .
![Screenshot from 2019-09-20 22-37-35](https://user-images.githubusercontent.com/11664248/65354100-57ebff80-dbf7-11e9-97fe-c52624c1d681.png)

**Comment by theworldisnotflat** [comment]
having the exact same problem with version 2.6.1 on Ubuntu 18.04 on a high DPI screen at 200 % scale

**Comment by theworldisnotflat** [comment]
still occurring with version 2.6.4 in Ubuntu 18.04

**Comment by theworldisnotflat** [comment]
still occurring with version 2.6.4 in Ubuntu 18.04
 solved using [the solution proposed by @select](https://github.com/nextcloud/desktop/issues/72#issuecomment-461572847)

**Comment by er-vin** [comment]
This looks like an upstream bug. Either the desktop doesn't position the scale factor early enough or Qt doesn't properly get notified of scale factor changes. Not much we can do about it AFAICT.
