### ISSUE TITLE
[Bug]: Crash in 3.15.0

### ISSUE THREAD

**Issue by zen010101** [nextcloud/desktop#7610]
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I upgraded from 3.13.4 desktop to 3.15.0. The reason I didn't upgrade before was that every upgrade would cause unexpected crashes during file synchronization of Nextcloud Desktop running on two Windows 11 machines, without any prompts. I thought this issue should have been resolved after so many version updates, but after upgrading yesterday, the crash problem still occurred.

I am confused now, I can no longer find version 3.13.4 on the internet, but I can find versions 3.13.3 and 3.14.0. It seems like this version has been skipped.

### Steps to reproduce

As long as the synchronization starts, the program crashes

### Expected behavior

work normally

### Which files are affected by this bug

I don't know

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Official Windows MSI

### Nextcloud Server version

29.0.6

### Nextcloud Desktop Client version

3.15.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell

```

### Additional info

you can download the Desktop Client Log from here: https://nextcloud.cheming.top:4443/s/jZ4eGnJmkXszwgB

**Comment by ywtoly** [comment]
Me too!

**Comment by fleuus** [comment]
++1

**Comment by archmagepi** [comment]
Me too!

**Comment by Traveller23** [comment]
same here.

**Comment by yangyunzhao** [comment]
It was crashing with version 3.14.3, and after updating to 3.15, it stabilized for a while. Now it's starting to crash frequently again. It's urgent.

**Comment by Traveller23** [comment]
> > Is it on a VmWare?
> 
> No, it is not used on VMware. I think it might be related to the fact that the server runs Linux, the client is Windows, or the filenames and content contain Chinese characters.

My environment is the same as yours. I rolled back from 3.15.0 to 3.14.3 yesterday, and so far so good.

**Comment by yangyunzhao** [comment]
> > > Is it on a VmWare?
> > 
> > 
> > No, it is not used on VMware. I think it might be related to the fact that the server runs Linux, the client is Windows, or the filenames and content contain Chinese characters.
> 
> My environment is the same as yours. I rolled back from 3.15.0 to 3.14.3 yesterday, and so far so good.

Yes, my server is Ubuntu, and the client is Windows 10. In my materials, both directory names and file names contain a large number of Chinese characters. I have two clients, one of which is a Windows 10 with a Chinese system, and it crashes frequently. The other one is a Windows 10 with an English system, and no crashes have been observed so far. I used version 3.12.4, and there were no crashes.

**Comment by PiKeyAr** [comment]
I've been experiencing the same issue since version 3.14 on two machines, but the third machine which syncs to the same exact servers is fine. The crash happens when synchronization starts, there is no error message and the program just quits silently. Version 3.13.4 worked without crashes on all machines.

**Comment by zen010101** [comment]
> Is it on a VmWare?

No. It happened on the Windows 11 Home Edition 23H2 native.

**Comment by zen010101** [comment]
> In my experience, 3.13.x always worked fine, the problem started with 3.14.

YES.

**Comment by m-schmailzl** [comment]
I experienced the same issue on server 29.0.10 and client 3.15.0.
I fixed it temporarily by disabling the download and upload limits in the desktop client's network settings.
Maybe this information will help someone.

**Comment by jjasoncool** [comment]
> I've been experiencing the same issue since version 3.14 on two machines, but the third machine which syncs to the same exact servers is fine. The crash happens when synchronization starts, there is no error message and the program just quits silently. Version 3.13.4 worked without crashes on all machines. The OS on the crashing machine is Windows 10 22H2.

Really, after version 3.13.4 the app become unstable for my all machines.

**Comment by PiKeyAr** [comment]
Updated to 3.15.1. The crash is still happening.
I found out that my Windows installation had crash dialogs disabled by default so I enabled them by setting `DontShowUI` to 1 in Windows Error Reporting registry key like this
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting]
"DontShowUI"=dword:00000001
```

After that I got the crash dialog to display and opened Visual Studio to debug. I was able to gather the following:
```
>	ucrtbase.dll!abort()	Unknown
ucrtbase.dll!terminate()	Unknown
nextcloud.exe!00007ff67823628a()	Unknown
KernelBase.dll!UnhandledExceptionFilter()	Unknown
ntdll.dll!RtlUserThreadStart$filt$0()	Unknown
ntdll.dll!__C_specific_handler()	Unknown
ntdll.dll!RtlpExecuteHandlerForException()	Unknown
ntdll.dll!RtlDispatchException()	Unknown
ntdll.dll!RtlRaiseException()	Unknown
KernelBase.dll!RaiseException()	Unknown
vcruntime140.dll!_CxxThrowException(void * pExceptionObject, const _s__ThrowInfo * pThrowInfo) Line 82	C++
nextcloud_csync.dll!00007ff8213c9f08()	Unknown
nextcloud_csync.dll!00007ff8213c83c6()	Unknown
nextcloud_csync.dll!00007ff8213ca297()	Unknown
nextcloudsync.dll!00007fffe647e47a()	Unknown
nextcloudsync.dll!00007fffe6485c6e()	Unknown
nextcloudsync.dll!00007fffe6485603()	Unknown
nextcloudsync.dll!00007fffe6484b18()	Unknown
Qt6Core.dll!00007fffe484511d()	Unknown
Qt6Core.dll!00007fffe4845b48()	Unknown
nextcloudsync.dll!00007fffe646f719()	Unknown
nextcloudsync.dll!00007fffe646fbab()	Unknown
nextcloudsync.dll!00007fffe646fbab()	Unknown
nextcloudsync.dll!00007fffe646fbab()	Unknown
nextcloudsync.dll!00007fffe646fbab()	Unknown
nextcloudsync.dll!00007fffe646f76f()	Unknown
nextcloudsync.dll!00007fffe646f4d9()	Unknown
Qt6Core.dll!00007fffe4879511()	Unknown
Qt6Core.dll!00007fffe487c364()	Unknown
Qt6Core.dll!00007fffe4894fe4()	Unknown
Qt6Core.dll!00007fffe4883436()	Unknown
Qt6Widgets.dll!00007fffe57727fe()	Unknown
Qt6Widgets.dll!00007fffe577198d()	Unknown
Qt6Core.dll!00007fffe483936c()	Unknown
Qt6Core.dll!00007fffe49c5818()	Unknown
Qt6Core.dll!00007fffe49c282a()	Unknown
Qt6Widgets.dll!00007fffe57727fe()	Unknown
Qt6Widgets.dll!00007fffe577198d()	Unknown
Qt6Core.dll!00007fffe483936c()	Unknown
Qt6Core.dll!00007fffe483c12e()	Unknown
Qt6Gui.dll!00007fffe540706f()	Unknown
Qt6Core.dll!00007fffe49c2e29()	Unknown
Qt6Gui.dll!00007fffe5406fe9()	Unknown
Qt6Core.dll!00007fffe4840a64()	Unknown
Qt6Core.dll!00007fffe4836cdd()	Unknown
nextcloud.exe!00007ff67809f460()	Unknown
nextcloud.exe!00007ff678236670()	Unknown
nextcloud.exe!00007ff6782356e2()	Unknown
kernel32.dll!00007ff85d7c7374()	Unknown
ntdll.dll!RtlUserThreadStart()	Unknown
```

**Comment by karlisi** [comment]
The same as here https://github.com/nextcloud/desktop/issues/7258
Here you can find all Nextcloud client for Windows releases
https://download.nextcloud.com/desktop/releases/Windows/

**Comment by PiKeyAr** [comment]
Can confirm this is related to UTF8 filenames mentioned in the issue above. I cannot use the workaround to change system locale or enable experimental UTF8 support so I will be using 3.13.4 until the issue is resolved. 3.15.2 doesn't seem to have any fixes for it.

**Comment by AlvinCZ** [comment]
Same here. Tried updating to 3.15.2 on my win10 and win11 PCs today. It always crashes when syncing. Had to roll back to 3.13.3.

**Comment by Nrtyck** [comment]
Me too!

**Comment by jimmy5670** [comment]
crash every start up sync program, still keep using V 3.13.3

**Comment by ywtoly** [comment]
crash every start up sync program, still keep using V 3.13.4

**Comment by papamoose** [comment]
Same issue on Ubuntu 24.04. With client [v3.15.2 (PPA)](https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client?field.series_filter=noble) and [v3.14.3 (AppImage)](https://download.nextcloud.com/desktop/releases/Linux/Nextcloud-3.14.3-x86_64.AppImage). The sync will start and I either have to force quit nextcloud-desktop or alternatively my whole machine freezes and I have to power cycle to recover.

I've rolled back to [v3.13.4 (AppImage)](https://download.nextcloud.com/desktop/releases/Linux/Nextcloud-3.15.2-x86_64.AppImage). It seems to sync normally.

**Comment by Traveller23** [comment]
Why has no one tried to analyze such a serious bug in the past few months?
@kurtmckee @rullzer @Gomez

**Comment by karlisi** [comment]
Version 3.15.3 installed today, no crashes, sync OK

**Comment by zen010101** [comment]
Version 3.15.3 installed yesterday, no crashes, sync OK. Only sometimes the GUI operation will crash the program. Right or left mouse click on the trayicon , you have a chance to crash the program.
