### ISSUE TITLE
No overlay icons in nautilus on fedora 29

### ISSUE THREAD

**Issue by rmeissn** [nextcloud/desktop#795]
### Expected behaviour
I should be able to see overlay icons in nautilus file manager.

### Actual behaviour
There are no overlay icons displayed

### Steps to reproduce
1. Install Fedora 29 (Gnome)
2. Install nextcloud-client and extension `sudo dnf install nextcloud-client nextcloud-client-nautilus`
3. Set up a sync folder and let it sync
4. Open Nautilus and navigate to the sync folder

### Client configuration
Client version:
Nextcloud version 2.3.3
Git revision 57bc7918d7b0650c116f3512787f7677d4e5ab17

Operating system: Fedora 29

OS language: german

Qt version used by client package (Linux only, see also Settings dialog):
Using Qt 5.11.1, built against Qt 5.9.1
Using 'OpenSSL 1.1.1 FIPS  11 Sep 2018'

Client package (From Nextcloud or distro) (Linux only):
???

Installation path of client:
default path

### Logs

This is the log output for nautilus when starting it from cli:

```(nautilus:30882): Nautilus-Python-WARNING **: 18:05:49.282: nautilus_python_init_python failed
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/syncstate-Nextcloud.py", line 23, in <module>
    from gi.repository import GObject, Nautilus
  File "/usr/lib64/python3.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /usr/lib64/python3.7/site-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_NotImplementedError```

**Comment by rmeissn** [comment]
Fixed with recent upstream update of nautilus-python

**Comment by moedn** [comment]
Same issue (also fedora 29), but `nautilus-python-1.2.2-2.fc29.x86_64` didn't solve it for me. 
`dnf install python2-gobject`
did the job [[source]](https://bugzilla.redhat.com/show_bug.cgi?id=1541648)
