### ISSUE TITLE
[Bug]: Files are not automatically deleted when deleted through webUI, notifying about error

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/desktop#8192]
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

With the last updates of the desktop client, I am receiving sync errors that the file cannot be synced as it has been deleted earlier, so I have to delete it manually.

### Steps to reproduce

1. User A and user B are memers of the same groupX, which has groupfolderX 
2. User A deletes a file through webUI in a subfolder of the groupfolderX
3. User B is out of network at this moment
4. Through certain time user B starts his desktop client and observes error that the file cannot be synced, as it has been deleted earlier.
5. User B has to delete it manually from the list of files in his/her File Browser in order the syncing can be restarted.

### Expected behavior

Syncing has to work seamlessly, so the file has to be deleted during sync operation if it has been deleted by another user.

### Which files are affected by this bug

all shared files

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Official Windows MSI

### Nextcloud Server version

30.0.10

### Nextcloud Desktop Client version

3.16.3

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell

```

**Comment by tomdereub** [comment]
Seems to be a duplicate of https://github.com/nextcloud/desktop/issues/8179#issuecomment-2820742270 ?

**Comment by ostasevych** [comment]
> Seems to be a duplicate of [#8179 (comment)](https://github.com/nextcloud/desktop/issues/8179#issuecomment-2820742270) ?

Yes, with more details.

**Comment by ostasevych** [comment]
> Hi,
> 
> this error drives me crazy ! Found this know. Have the exact same error. idk if i deleted anything on web or local but the error is unsolvable. already tried to fix it. files are deleted localy and on web and still the error occurs. tried to upgrade to newest daily desktop version in the hope this is fixed but noo...
> 
I think, the better is to downgrade to 3.16.2 till it is solved.

**Comment by ted423** [comment]
My suggestion is to release a new version as soon as possible.

After all, the current problem shows that the existing release is not stable enough.

**Comment by supr4s** [comment]
Same for us, all our customers are affected.
Knowing that this is not the first time this has happened to desktop synchronization clients, I would suggest perhaps slowing down the rate of release but testing more ...

**Comment by ostasevych** [comment]
Why 3.16.3 is still present and not taken away from the list of releases?

My suggestion is to re-issue 3.16.2 under 3.16.3.1 and get rid of 3.16.3 till the fix is ready.

**Comment by kilrah** [comment]
Can confirm the issue and that `windows-20250424.msi` from dailies fixes it

**Comment by stefan817** [comment]
> Why 3.16.3 is still present and not taken away from the list of installation files over here https://download.nextcloud.com/desktop/releases/Windows/ ?
> 
> My suggestion is to re-issue 3.16.2 under 3.16.3.1 and get rid of 3.16.3 completely.

That's really the big question! This issue is known now since last week. More and more collegues and customers are getting mad. 3.16.3 download should be stopped immediately and replaced by 3.16.2 or a fixed 3.16.4!

**Comment by turnschuhadmin1337** [comment]
Same here. It affects round about 80 people.

NC Windows Client 1 deletes file in a shared folder - sync.
NC Windows Client 2 gets the change/sync but is not allowed to delete that file too. Only red cross in systray and the affected file inside the folder. You need to delete it by hand to get rid of the red cross. That's really bad for users.

Please check your updates before release better.

**Comment by ostasevych** [comment]
Is there any possibility to create own repository of desktop client applications which will be used by the desktop client to upgrade from? Eg, I will create in NC root public folder apps, copy there client applications which I will test myself. So, the desktop client will update itself only from there.

The main question is about releases: if I want to skip some version, and will not place an installer file of some specific release, eg. 3.16.3, the desktop client should not warn about available upgrade, but be not able to download and upgrade itself, because of not available installation file.

Please, share your advice.

**Comment by ted423** [comment]
I don't know if you are using Windows, because I use myself, corporate or organizational users, for something like NextCloud, you generally need to disable automatic upgrades.
as I understand it, Nextcloud configurations are typically managed by editing configuration files directly, but for some software, you can add parameters during installation. For example, with MSI installers, you might use flags like `/norestart AUTOUPDATECHECK=0 REBOOT=Suppress`(for SVN),`/SILENT /SUPPRESSMSGBOXES /NORESTART /SP- /NoEdgeWebView /NoChocolatey`for unigetui. It seems possible to write a script to automate this.
microsoft has something called Configuration Manager(old was SCCM)(Microsoft Intune for public)
Microsoft Endpoint Manager (MEM), which includes Intune and Configuration Manager (SCCM), can control third-party software versions through the following methods:

1. Deployment of Specific Versions

Intune (Cloud-Based Management):

Win32 App Deployment: Package third-party software (e.g., .exe, .msi) and enforce version control via detection rules (e.g., checking file versions, registry keys).
Example: Deploy Firefox 100.0 and block newer versions by detecting the exact executable version.
Microsoft Store for Business: Publish curated Store apps and restrict updates to approved versions (if supported by the app developer).

**Comment by ted423** [comment]
for linux , ubuntu 24 LTS nextcloud client version 3.11.0-1 worked fine for me

**Comment by RTechSn** [comment]
kind of critical

**Comment by mgallien** [comment]
3.16.5 should help a lot and I would like to get wider feedback about this specific error (i.e. failing to delete a file when running on Windows) with this release

**Comment by prolibre** [comment]
@mgallien This version poses no problems. Everything is resolved on my end.

**Comment by mh-tp** [comment]
successfully tested with 3.17.0
Creating and deleting both in WebUI
Creating and deleting both locally
Creating in WebUI and deleting locally

**Comment by tomdereub** [comment]
Hi, I get this same error on nextcloud desktop 3.17.2 on windows 10, nextcloud server 30.0.15, using VFS.

I get this error in the log : 
```
#=#=#=#=# Propagation starts 2025-09-30T08:30:23Z (last step: 156109 msec, total: 156109 msec)
||2_Affaires/4_Campagnes de mesures/xxx/3 Documents extérieurs/DOE - lien du 29.09.23|2|2|1754924971|689a07ab64dba|0|17387020ocax1gd7utmo|2|Erreur temporaire lors de la suppression d'un élément local supprimé du serveur.|0|0|1754924971||
```
Downgrade to 3.17.1 doesn't solve the problem.
Some other computers syncing the same folder don't have the error.

Edit : to solve the problem, I had to manually delete the folder on my computer, had a warning that it couldn't go to trashbin because it had too long file name on some files (source of the initial error ?), so delete definitely, and then restart nextcloud. Without restarting nextcloud, I still had the same error, and nextcloud consuming high CPU.

**Comment by tomdereub** [comment]
Bug still present with nextcloud desktop 3.17.4 on windows 11. I can provide logs if you give me an upload link.
This time, it's a whole folder that has been deleted server side, and the client has deleted all files, but kept lots of folders.

<img width="824" height="350" alt="Image" src="https://github.com/user-attachments/assets/f69998c9-4f1d-4680-95e9-6dd57e780459" />

Manually deleting the folder on computer solved the issue, with same warning with "too long file name".

**Comment by limatus** [comment]
The issue persist for us as well with 4.0.3. - I can also supply logs if needed!

**Comment by cyrzero** [comment]
Hi,
We are experiencing the same issue with Nextcloud Desktop 4.0.4 on Windows 11, connected to a Nextcloud Server 31.0.9 using VFS. Specifically, folders with long paths are not being deleted automatically from the desktop client. However, manual deletion works fine.
Clients are no longer focusing on legitimate actions, which leads to a cascade of other issues.

**Comment by limatus** [comment]
It's the same for us, manual deletion works fine, which confuses me even more. I also thought there is a hidden file in the folder, or our Antivir is blocking the deletion somehow, but all of this is not the case. For us, this also causes a cascade of issues. The clients are busy with displaying the issue and to scan though all the files again. It stops upload, delays the discovery and leads to loss of data in some cases. 

I've created a new report/issue: #9425
