### ISSUE TITLE
[Bug]: V4.0.0 - a folder, a subfolder with the same name as the parent folder is created

### ISSUE THREAD

**Issue by vagner-dias** [nextcloud/desktop#8915]
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

In NC Client 4.0.0, in a fresh install, After proceeding with the the initial sync, if the user enters a folder, a subfolder with the same name as the parent folder is "created"

### Steps to reproduce

1. Install the desktop client V4.0.0 (it must be a fresh install)
2. connect an account
3. Start entering any folder structure. the issue will start to manifest

### Expected behavior

No subfolder should be created.

### Which files are affected by this bug

Folders only

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Official Windows MSI

### Nextcloud Server version

31.0.8

### Nextcloud Desktop Client version

4.0.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell

```

**Comment by farhills** [comment]
We are seeing this issue after upgrade from 3.17.3  Windows 11.

**Comment by Eiernase** [comment]
Seeing this as well after the update on Windows 10. Also cool that the update starts even after dismissing the popup.

**Comment by matix24** [comment]
same for me 😔

**Comment by Mountain-song-Liaoya** [comment]
Yes, I also encountered this problem after updating to 4.0 today, but I didn't do a fresh installation; it was an automatic update to 4.0. I manually deleted the folder that was automatically created, but after a few hours the parent folder was automatically created again. I intend to temporarily downgrade.

**Comment by mayonezo** [comment]
This bug is terrible. I think it would be good to pull release 4.0.0 from the update channels.

**Comment by Nolonar** [comment]
I'm experiencing this too. Steps to reproduce (v4.0.0 on Windows 11):

- Add a new file on the desktop client
- Wait for the desktop client to sync
- A new empty directory will appear, named after the parent directory

That directory is impossible to delete. Attempts to do so result in a "remote file not found" error. Attempting to create a directory with the same name via Web UI does not trigger a sync, but allows deleting the directory on the client. Sadly, the directory reappears almost immediately afterwards.

This should be fixed ASAP, as I don't feel confident in using Nextcloud as long as there's a risk this bug could mess with my data.

**Comment by typowyfacet** [comment]
same for me... on multiple instances/ mostly on Win11

**Comment by subroutineox** [comment]
this is unbelievable ... how can sth. like this go live?! Every release i have less arguments to keep using NC for a productive environment.

**Comment by Ayush62** [comment]
Same here even when i delete the folder it comes back again when i sync back up. This only happens on the PC Version not on the phone. on the phone it is normal

**Comment by BenoitLavergne** [comment]
The same issue occurs here on Windows 11. I installed NC Client 4.0.0 over 3.17.3 this morning.
I noticed that two identical subdirectories are created at each sync, up to three levels deep: my-new-dir > my-new-dir > my-new-dir.
I rolled back immediately to avoid a major mess in my data.

**Comment by mrAceT** [comment]
> The same issue occurs here on Windows 11. I installed NC Client 4.0.0 over 3.17.3 this morning. I noticed that two identical subdirectories are created at each sync, up to three levels deep: my-new-dir > my-new-dir > my-new-dir. I rolled back immediately to avoid a major mess in my data.

Same problem, can you help me how to roll back, these ghost folders are extremely confusing..

**Comment by ThomasAndreini** [comment]
I confirm, for us that is append after automatic update to 4.0

**Comment by nilsding** [comment]
for the time being you may want to give a recent daily build `>= 20251023` a try: https://download.nextcloud.com/desktop/daily/windows/

That build contains the merged PR from yesterday which should resolve the creation of these subfolders.

**Comment by fsomenzi-ita** [comment]
> for the time being you may want to give a recent daily build `>= 20251023` a try: https://download.nextcloud.com/desktop/daily/windows/
> 
> That build contains the merged PR from yesterday which should resolve the creation of these subfolders.

Hello, I installed the new daily build and rebooted PC, but the issue still persists.

**Comment by nilsding** [comment]
@fsomenzi-ita do these folders disappear if you create a new file somewhere?

**Comment by Simi5599** [comment]
Can confirm, this happened also for me

**Comment by SebjuFrab** [comment]
I think it would be safer to stop automatic updates to version 4.0 until this issue is fixed.

The bug can easily break the local folder structure by creating duplicate subfolders (same name as parent), which is confusing and potentially risky for end users.

Please freeze automatic updates on 4.0 and keep 3.13.x as the latest recommended stable version until a corrected 4.0.x is released.

**Comment by mrAceT** [comment]
Can someone please explain to me how I roll back to the last (correctly working) 3.x version?

**Comment by kosli** [comment]
> Can someone please explain to me how I roll back to the last (correctly working) 3.x version?

I assume you can just download and install the latest release before 4.0.0, see here: https://github.com/nextcloud-releases/desktop/releases/tag/v3.17.3

**Comment by Simi5599** [comment]
> I think it would be safer to stop automatic updates to version 4.0 until this issue is fixed.
> 
> The bug can easily break the local folder structure by creating duplicate subfolders (same name as parent), which is confusing and potentially risky for end users.
> 
> Please freeze automatic updates on 4.0 and keep 3.13.x as the latest recommended stable version until a corrected 4.0.x is released.

Yeah, i was working on a C++ project and lost a lot of edits i made. Fortunately i had Git but this can be devastating

**Comment by fsomenzi-ita** [comment]
@nilsding 
when a new folder is created, another folder with the same name is automatically generated inside it. Moreover, if the folder is located within a parent folder, a subfolder with the same name as the parent folder also appears inside the parent folder.

If I create a file inside a folder, a new folder with the same name as the parent folder is created in the same location.

Long story short, it behaves the same way as before

**Comment by mrAceT** [comment]
> > I think it would be safer to stop automatic updates to version 4.0 until this issue is fixed.
> > The bug can easily break the local folder structure by creating duplicate subfolders (same name as parent), which is confusing and potentially risky for end users.
> > Please freeze automatic updates on 4.0 and keep 3.13.x as the latest recommended stable version until a corrected 4.0.x is released.
> 
> Yeah, i was working on a C++ project and lost a lot of edits i made. Fortunately i had Git but this can be devastating

**Yikes!** That might explain me losing a few images I uploaded.. and were gone. Luckaly the ware added from a "Non-Nexcloud folder" and asumed a hickup at my end..

**IDEA** Might it be a good idea to roll out (major) updates in fases, before releasing it to the big public? That being said, I saw an update option for "stable / beta / daily".. this sounds like that this update "simply" fell thrugh the cracks?

And if it does, as it did now, I completely agree with @SebjuFrab , do "damage control" and prevent further migration to this version!!

PS: the link @kosli gave ( https://github.com/nextcloud/desktop/issues/8915#issuecomment-3436629819 ) is perfect for reverting to the last stable 3.x version!

**Comment by michel-thomas** [comment]
> I think it would be safer to stop automatic updates to version 4.0 until this issue is fixed.

I also suggest releasing version x.y.0 as a limited/sampling rollout. Broad distribution of these versions frequently leads to rollbacks. If possible, of course…

**Comment by someone-somenet-org** [comment]
Please pull the 4.0.0 release and/or release a 4.0.1 asap - this is breaking productivity and since the ghost folders supposedly delete all changes immediately it leads to dataloss!

(Im currently on the road, so I cant use the official Enterprise support route)

**Comment by michel-thomas** [comment]
> I also suggest releasing version x.y.0 as a limited/sampling rollout. Broad distribution of these versions frequently leads to rollbacks. If possible, of course…

I create a Feature Request to follow or cancel the idea : #8939

**Comment by JohanBoshoffWebAware** [comment]
and we need a fix to address the incorrect duplicated folders - to try remove them manually will take ages!  Stop the release from rolling out please!

**Comment by nilsding** [comment]
The updater server rolls out 3.17.3 again.  I have also marked the 3.17.3 release on GitHub as the latest release, and turned 4.0.0 into a pre-release.

**Comment by hArDsTyLe2000** [comment]
Windows 11 after Upgrading from 3.17.3 to 4.0.0 same problem for me. He is randomly creating new subdirs in the subdirs.


<img width="1118" height="624" alt="Image" src="https://github.com/user-attachments/assets/1e7ba169-ba27-4fd1-b59b-c8b53bc21c72" />

**Comment by Christian-98** [comment]
While waiting for the bug in version 4.0.0 to be fixed, I have reverted the plugin to version 3.17.3, and everything is working correctly.
To prevent automatic updates, disable the option for automatic update checks and installations in the plugin settings.

**Comment by lucaslevi-consultor-glpi** [comment]
same problem here after update

**Comment by RenSch89** [comment]
> > Can someone please explain to me how I roll back to the last (correctly working) 3.x version?
> 
> I assume you can just download and install the latest release before 4.0.0, see here: https://github.com/nextcloud-releases/desktop/releases/tag/v3.17.3

Thanks a lot, that helped, but also destroyed the ability for Windows to access this parent folder where V4.0.0 has created those double directories.
My workaround, if you encounter the error that Windows isn't able to access the parent folder anymore (error in Windows "the service did not respond to the start or control request in a timely fashion"): go to the nextcloud web interface with all your files, rename the old (by windows) unaccessible folder, create a new folder with the original name and move all files from the "corrupted" one into the new one, after that delete the old renamed and curuppted folder.

**Comment by Christian-98** [comment]
Those folders do not exist. Nothing should be uploaded into folders created as duplicates; what occurs is an abnormal behavior of the Nextcloud client causing these issues. Check if they remain in the user's trash bin.

> > > Can someone please explain to me how I roll back to the last (correctly working) 3.x version?
> > 
> > 
> > I assume you can just download and install the latest release before 4.0.0, see here: https://github.com/nextcloud-releases/desktop/releases/tag/v3.17.3
> 
> Thanks a lot, that helped, but also destroyed the ability for Windows to access this parent folder where V4.0.0 has created those double directories. My workaround, if you encounter the error that Windows isn't able to access the parent folder anymore (error in Windows "the service did not respond to the start or control request in a timely fashion"): go to the nextcloud web interface with all your files, rename the old (by windows) unaccessible folder, create a new folder with the original name and move all files from the "corrupted" one into the new one, after that delete the old renamed and curuppted folder.

**Comment by RenSch89** [comment]
> Those folders do not exist. Nothing should be uploaded into folders created as duplicates; what occurs is an abnormal behavior of the Nextcloud client causing these issues. Check if they remain in the user's trash bin.
> 
> > > > Can someone please explain to me how I roll back to the last (correctly working) 3.x version?
> > > 
> > > 
> > > I assume you can just download and install the latest release before 4.0.0, see here: https://github.com/nextcloud-releases/desktop/releases/tag/v3.17.3
> > 
> > 
> > Thanks a lot, that helped, but also destroyed the ability for Windows to access this parent folder where V4.0.0 has created those double directories. My workaround, if you encounter the error that Windows isn't able to access the parent folder anymore (error in Windows "the service did not respond to the start or control request in a timely fashion"): go to the nextcloud web interface with all your files, rename the old (by windows) unaccessible folder, create a new folder with the original name and move all files from the "corrupted" one into the new one, after that delete the old renamed and curuppted folder.

Hi,
there was no renaming after these doubled folders were deleted. They were with the same name in the trash bin on Windows and in the trash on the web interface. They also were in the "normal" directories on the web interface.
But btw on Ubuntu I could never see them in the Nextcloud folders.

**Comment by G2G2G2G** [comment]
>Install the desktop client V4.0.0 (it must be a fresh install)

it does not have to be fresh


These do not have to be created by the user either, it can be created by a different user, even via webdav
**These are not created on the server, either. These are created in cache on WINDOWS ONLY and it says it's a "cloud file" however the secondary folders never exist on the server.**

**Comment by Sieboldianus** [comment]
For the meantime:
```cmd
choco install nextcloud-client --version=3.17.3 --allow-downgrade -y
choco pin add -n=nextcloud-client #prevent it from being accidentally updated
...
choco pin remove -n=nextcloud-client #once a fix is available
```

I saw some duplicate folder (empty) this morning on 4.0.0:
- I thought I mistakenly created it, and removed it
- then saw another one, also deleted it
- then another one: This must be a NC bug!
- looked up the bug: yes, there is a GH issue
- reverted to `3.17.3`
- noticed that the original parents of the two folders I deleted _are not accessible anymore_
- I had to open TaskManager, kill the nextcloud-client process
- a new one would automatically pop up
- the two folders still inaccessible: Online, it says I deleted _the parent folders_
- I restored the folder through nextcloud online: worked (online)
- locally: I still cannot open the two folders; it says "The cloud provider exited unexpectedly"

Luckily, I have backups. So please be aware: **Data loss is possible.**

**Comment by mmallejac** [comment]
Same issue here : NC version 30.0.16 / clients 4.0.0

These subfolders _are_ present server side, I see them while navigating within the folder tree on the server.
Sometimes they are even triple : `aFolder/aFolder/aFolder/(empty)` 

Since I see them server-side, I guess that downgrading the client to latest version 3 will help but not clean what has been done so far. So a little script to remove them is necessary.

**Comment by Rello** [comment]
Hello all,

update on this topic: 
the issue was located and fixed. This is part of the daily builds already. No new shadow-folders will be created anymore.

We are investigating the status of the sync database for possible issues and look into a possible cleanup of local shadow folders (**NOT** anything that is synced to the server already. We will not risk any data removals).

We will keep you updated...

**Comment by Erwan62** [comment]
<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/05954fae-204e-4483-99d9-19ef9f986c34" />

**Comment by mmallejac** [comment]
@Erwan62 : would be interesting to see if the ghost folder exists server-server (not as seen through the Nextcloud interface, but really on the filesystem)

**Comment by MaiuZ** [comment]
> Those folders do not exist. Nothing should be uploaded into folders created as duplicates; what occurs is an abnormal behavior of the Nextcloud client causing these issues. Check if they remain in the user's trash bin.
> 
> > > > Can someone please explain to me how I roll back to the last (correctly working) 3.x version?
> > > 
> > > 
> > > I assume you can just download and install the latest release before 4.0.0, see here: https://github.com/nextcloud-releases/desktop/releases/tag/v3.17.3
> > 
> > 
> > Thanks a lot, that helped, but also destroyed the ability for Windows to access this parent folder where V4.0.0 has created those double directories. My workaround, if you encounter the error that Windows isn't able to access the parent folder anymore (error in Windows "the service did not respond to the start or control request in a timely fashion"): go to the nextcloud web interface with all your files, rename the old (by windows) unaccessible folder, create a new folder with the original name and move all files from the "corrupted" one into the new one, after that delete the old renamed and curuppted folder.

I solved "the service did not respond to the start or control request in a timely fashion" problem downgrading to previous nextcloud client version and by disabling virtual file support in the client affected by the bug and then re-enabling virtual file support without moving the files to the server side.

**Comment by badshah400** [comment]
> update on this topic: the issue was located and fixed. This is part of the daily builds already. No new shadow-folders will be created anymore.

Please let us know if the issue and fix is restricted to Windows specifically or relevant to Linux as well. As a maintainer of the package on openSUSE, we are wondering if the update to version 4.0.0, which we pushed out a couple of days ago needs to to be reverted (or patched with the relevant commit). Thanks.

**Comment by nilsding** [comment]
@badshah400 this is only affecting VFS on Windows.  4.0.0 works fine on Linux and macOS.

**Comment by Christian-98** [comment]
> Hello all,
> 
> update on this topic: the issue was located and fixed. This is part of the daily builds already. No new shadow-folders will be created anymore.
> 
> We are investigating the status of the sync database for possible issues and look into a possible cleanup of local shadow folders (**NOT** anything that is synced to the server already. We will not risk any data removals).
> 
> We will keep you updated...

Hi, sorry, I still see the issue marked as open, so I’m not sure whether it has been resolved and if a new version of the Windows plugin has been released.
From the link https://github.com/nextcloud-releases/desktop/releases/tag/v4.0.0
I can see that the latest update dates back to October 22, 2025

**Comment by michel-thomas** [comment]
> Hi, sorry, I still see the issue marked as open, so I’m not sure whether it has been resolved and if a new version of the Windows plugin has been released.
> From the link https://github.com/nextcloud-releases/desktop/releases/tag/v4.0.0
> I can see that the latest update dates back to October 22, 2025

Looking at your right, you can see "Milestone" with 4.0.1 value. This is the target version for new release with correction of this issue

<img width="156" height="94" alt="Image" src="https://github.com/user-attachments/assets/85968e65-8dd8-4c87-927b-6b49d14ffae3" />

Following [the link](https://github.com/nextcloud/desktop/milestone/102) will show you remaining issues before publishing this release.

**Comment by toarujs** [comment]
I encountered this issue on both Windows11 and WindowsServer2025.

**Comment by nilsding** [comment]
We've decided to revert the on-demand syncing on Windows for the upcoming 4.0.1 release.

I prepared a PR for that on top of the `stable-4.0` branch (#8949) and built an installer with that change: https://cloud.nextcloud.com/s/gEX79ZJwrSm97Ep 
If all goes well this will become 4.0.1 next week.

> [!NOTE]
> The client does **not** attempt to try cleaning up the wrongfully created folders in order to reduce the cause of potential data loss.  I couldn't discover a reliable way to identify them in the short period.
>
> You may also notice a longer discovery period for certain folders as the folder tree might need to be walked through again for these.

Please give that build a try and report back with your findings.   I would also appreciate to receive debug archives so we have more samples of how this issue affected the client in different configurations -- you can upload those at https://cloud.nextcloud.com/s/37eCmr6ADHdZmsf

**Comment by vagner-dias** [comment]
@nilsding 

The initial sync seems to be running but the screen freezes / does not show in the moment you clink in the icon.

Also - when the sync screen shows, it stays like in the second video. I am not sure if this is an expected behavior.

https://github.com/user-attachments/assets/38375f6e-7c56-4b07-85b0-70b3ec017b66

https://github.com/user-attachments/assets/6eb4239b-1333-4a51-a6bc-67a5df16ac93

**Comment by NicoDreamzZ** [comment]
> We've decided to revert the on-demand syncing on Windows for the upcoming 4.0.1 release.
> 
> I prepared a PR for that on top of the `stable-4.0` branch ([#8949](https://github.com/nextcloud/desktop/pull/8949)) and built an installer with that change: https://cloud.nextcloud.com/s/gEX79ZJwrSm97Ep If all goes well this will become 4.0.1 next week.
> 
> Note
> 
> The client does **not** attempt to try cleaning up the wrongfully created folders in order to reduce the cause of potential data loss. I couldn't discover a reliable way to identify them in the short period.
> 
> You may also notice a longer discovery period for certain folders as the folder tree might need to be walked through again for these.
> 
> Please give that build a try and report back with your findings. I would also appreciate to receive debug archives so we have more samples of how this issue affected the client in different configurations -- you can upload those at https://cloud.nextcloud.com/s/37eCmr6ADHdZmsf

I didn't have much time to test it, but the behavior of creating a new subfolder with the same name no longer occurred during my initial attempts.

**Comment by RenSch89** [comment]
> > We've decided to revert the on-demand syncing on Windows for the upcoming 4.0.1 release.
> > I prepared a PR for that on top of the `stable-4.0` branch ([#8949](https://github.com/nextcloud/desktop/pull/8949)) and built an installer with that change: https://cloud.nextcloud.com/s/gEX79ZJwrSm97Ep If all goes well this will become 4.0.1 next week.
> > Note
> > The client does **not** attempt to try cleaning up the wrongfully created folders in order to reduce the cause of potential data loss. I couldn't discover a reliable way to identify them in the short period.
> > You may also notice a longer discovery period for certain folders as the folder tree might need to be walked through again for these.
> > Please give that build a try and report back with your findings. I would also appreciate to receive debug archives so we have more samples of how this issue affected the client in different configurations -- you can upload those at https://cloud.nextcloud.com/s/37eCmr6ADHdZmsf
> 
> I didn't have much time to test it, but the behavior of creating a new subfolder with the same name no longer occurred during my initial attempts.

I can confirm, the intial test shows no doubled folders or some unexpected other behaviour.

**Comment by Nolonar** [comment]
Just wanted to say that reverting to 3.17.3 isn't without problems.

I've managed to delete most of these ghost folders after reverting. They don't reappear, and 3.17.3 obviously doesn't produce new ones, which is good.

However, 2 of the folders that were affected by the ghost folder issue are now inaccessible. I tried opening them in File Explorer, but I'm getting the following error:

> The cloud operation was not completed before the time-out period expired.

I also tried to use PowerShell, but even though `cd` works, `ls` gets the same error, so I technically *can* navigate to these folders. I just can't read what's inside.

Fortunately, I managed to fix this by deleting the entire inaccessible folder on the client side, waiting for the client to sync (it'll hang for a while), and then restoring the folder from the trash on the Web UI.

**Comment by Sieboldianus** [comment]
> However, 2 of the folders that were affected by the ghost folder issue are now inaccessible. I tried opening them in File Explorer, but I'm getting the following error:
> 
> > The cloud operation was not completed before the time-out period expired.
> 
> I also tried to use PowerShell, but even though `cd` works, `ls` gets the same error, so I technically _can_ navigate to these folders. I just can't read what's inside.
> 
> Fortunately, I managed to fix this by deleting the entire inaccessible folder on the client side, waiting for the client to sync (it'll hang for a while), and then restoring the folder from the trash on the Web UI.

I had the same issue. I could solve it by a complete reboot.

**Comment by G2G2G2G** [comment]
As I said a few days ago, these folders are never created on the server
The proper way to get rid of them is to uninstall nextcloud entirely, remove all of the folders and appdata etc from the system entirely and then probably reboot and reinstall nextcloud.. and have it do the initial sync again

There should be a button in the program to "sync to what the current server is" but since there isn't, those folders never get removed and they do not exist anywhere except the windows system itself.
Thus deleting them has random side effects as windows is a black box of nobody knows what happens when stuff does stuff.

**Comment by mmallejac** [comment]
On my servers, they are created server side.

We've used a small bash script to find and delete them.

**Comment by funoftracer** [comment]
I have the same problem. But on my Windows 11 computer, the duplicate folders were not synchronized, whereas on my Windows 10 computer they were. Now I have reinstalled version 3.17.3 on both computers using the downgrade method described above. But this has led to crazy synchronization problems. The folders that were apparently still in synchronization mode from version 4.0.0 were also locked, so that only the error message “The cloud operation was not completed before the time-out period expired” appeared. When I tried to delete the duplicate folders, 3.17.3 on Windows 10 apparently got completely confused on the Windows 10 computer and started deleting data in other folders as well, which I could see in the activity tracking in the WebUI. I immediately terminated 3.17.3 and will now reinstall and recopy everything, which may take a few hours with almost 100 GB. I still have the error with the virtual folders that I cannot delete them. Error: “Cloud File Provider is Not Running.” How can I solve this problem in Windows? Maybe someone has a tip. In any case, I will no longer update the NextCloud client without further ado and will always wait for a new version first.

**Comment by G2G2G2G** [comment]
They're synchronized when you do something with them. Touch them, write something inside them, etc. The OS can be doing that by itself as well. They're not created server side by what nextcloud desktop program is doing

**Comment by Christian-98** [comment]
Good morning everyone,
could someone tell me if the resolution of this issue is expected for this week, and if so, on which day?
The Milestone 4.0.1 appears to be 80% complete, but there don’t seem to be any official resolution dates.

**Comment by nilsding** [comment]
@Christian-98 we're planning to get 4.0.1 out today

**Comment by vagner-dias** [comment]
> [@Christian-98](https://github.com/Christian-98) we're planning to get 4.0.1 out today

@RenSch89 mentioned that the on-demand syncing feature was reverted, but I just tested the daily release "windows-20251027.msi" and it seems that the on-demand syncing is back.....

Also, it seems that this on-demand syncing initially syncs the first level of folders and after it syncs the whole structure in the background. If you click in a folder and it is not synced yet, then it syncs it "on demand". Is it true?

**Comment by JohanBoshoffWebAware** [comment]
We noticed that the duplicated folders do get created at server side.  We created a fix to remove these duplicated 0 byte folders.  If anyone is interested to clean up their files/folders, please let me know and I will post the powershell script.  All the script does is to check for 0byte folders with the same name as the parent folder, list them and delete them.

**Comment by sharcslife** [comment]
@JohanBoshoffWebAware Great solution, it would be aweseome if you could share your script here.

**Comment by mrAceT** [comment]
> We noticed that the duplicated folders do get created at server side. We created a fix to remove these duplicated 0 byte folders. If anyone is interested to clean up their files/folders, please let me know and I will post the powershell script. All the script does is to check for 0byte folders with the same name as the parent folder, list them and delete them.

Just discovered the same thing, that script would be nice

**Comment by vagner-dias** [comment]
> > [@Christian-98](https://github.com/Christian-98) we're planning to get 4.0.1 out today
> 
> [@RenSch89](https://github.com/RenSch89) mentioned that the on-demand syncing feature was reverted, but I just tested the daily release "windows-20251027.msi" and it seems that the on-demand syncing is back.....
> 
> Also, it seems that this on-demand syncing initially syncs the first level of folders and after it syncs the whole structure in the background. If you click in a folder and it is not synced yet, then it syncs it "on demand". Is it true?

@Christian-98 / @nilsding 

It is worth to mention one weird behaviour of the "windows-20251027.msi" client.

After installing it, the client syncs the first folder level, makes it available, and seems to sync the rest of the folder tree in the background. If the user clicks a folder, it may take a bit but the folder is shown. So far everything is fine.

After a while the whole folder tree is synchronized.

Somehow, after a computer reboot, the whole tree is lost and only the first level is synced again. This time, the client does not synchronize the whole tree again.

**Comment by michel-thomas** [comment]
What I did to ~~solve~~ repair an instance:

- Clients side
  1. uninstall 4.0.0
  2. install 3.17.3
  3. stop nextcloud-desktop
- Server side
  1. inside problematic users root folder (/data/user/files/): `find . -empty -type d delete`
  2. `sudo -u www-data php -f occ files:scan --all`
  3. `sudo -u www-data php -f occ maintenance:data-fingerprint`
- Clients side
  1. launch nextcloud-desktop
  2. wait sync. Some errors about deleted folders on server, but after one or two rescan it is ok

My method is quite "rude" by deleting all empty folders in users folders, but they are ok as theses folders are empty. Better way would find only recent folders named as their parent.

**Comment by nilsding** [comment]
@vagner-dias the daily builds are pretty much development builds of the next 4.x version (in this case 4.1.0).  The VFS change was reverted only in the 4.0 branch.

----

To assist with identifying which folders to clean up one could analyse the server access logs as well: look out for any `MKCOL` request done by a `4.0.0` client for a path where the last two components are the equal (e.g. `[...]/folder/folder`; this could also be the account's username)

**Comment by nilsding** [comment]
I just published the binaries for v4.0.1 to GitHub: https://github.com/nextcloud-releases/desktop/releases/tag/v4.0.1

we'll make it available through updater this week, first for the beta channel and after a couple of days publish it to the stable channel

**Comment by someone-somenet-org** [comment]
We are considering to switch to ``occ config:system:set desktopEnterpriseChannel --value Enterprise`` due to this bug to prevent future unexpected breakage and our users complaining, but the question is: how does that affect Clients that use multiple Instances?

What if some other NC instance sets ``occ config:system:set desktopEnterpriseChannel --value Daily``?

Also I suspect that this doesnt change anything for Linux/other Package-Manager managed Clients, does it?

Also, since the default is supposed to be "Enterprise" ... does this enforcement really work? (we didnt touch that config option) ^^

**Comment by Rello** [comment]
> We are considering to switch to `occ config:system:set desktopEnterpriseChannel --value Enterprise` due to this bug to prevent future unexpected breakage and our users complaining, but the question is: how does that affect Clients that use multiple Instances?
> 
> What if some other NC instance sets `occ config:system:set desktopEnterpriseChannel --value Daily`?
> 
> Also I suspect that this doesnt change anything for Linux/other Package-Manager managed Clients, does it?
> 
> Also, since the default is supposed to be "Enterprise" ... does this enforcement really work? (we didnt touch that config option) ^^

Hello,

this will only work for enterprise subscriptions. Even so this bug now was very unfortunate, the stable channel is the one to go for normal operations.

**Comment by someone-somenet-org** [comment]
> Hello,
> 
> this will only work for enterprise subscriptions. Even so this bug now was very unfortunate, the stable channel is the one to go for normal operations.

Sure, we have one. But as a university we have quite an excessive usage of BYOD and cross-university Users and people have usually more than one account added to their desktop-clients and usually other universities have enterprise instances too.

Thats why Im asking: what NC instance wins when setting this? ^^

(Also your portal docs seem to be wrong: they claim that the default is "enterprise", but when looking into the source you end up with: ``apps/support/lib/Capabilities.php:38:                           'desktopEnterpriseChannel' => $this->config->getSystemValueString('desktopEnterpriseChannel', 'stable'),``)

**Comment by Sieboldianus** [comment]
FYI, After this issue with a once more NC client broken on windows, I added this topic in the discussions on Chocolatey, the package manager:
https://github.com/chocolatey/choco/discussions/3807

I think it would be possible to write a wrapper script for chocolatey for this. 

Of course, this is not a solution for Universities etc. with a diverse user base.

**Comment by G2G2G2G** [comment]
@nilsding is there a reason the stable channel updated to this version a week ago? was 4.0 set as stable?
In the desktop client I mean, where you have "check update" several of the computers here updated to this version but I see in the releases that it is only an RC?

**Comment by Rello** [comment]
> [@nilsding](https://github.com/nilsding) is there a reason the stable channel updated to this version a week ago? was 4.0 set as stable? In the desktop client I mean, where you have "check update" several of the computers here updated to this version but I see in the releases that it is only an RC?

Hello,
4.0 was released as stable. After it was recognised that there was a broader problem with the Win-Client, the release was removed from the updater to stop further distribution of the bug.
This is not a usual process - just an emergency full stop.

Current stable keeps distributing 3.17.3
4.0.1 is no on beta and will be promoted via stable later this week depending on the feedback

**Comment by Rello** [comment]
> Sure, we have one. But as a university we have quite an excessive usage of BYOD and cross-university Users and people have usually more than one account added to their desktop-clients and usually other universities have enterprise instances too.

I will double check. if I remember, the highest config will win - means if there is one enterprise account involved, it will be used.

> (Also your portal docs seem to be wrong: they claim that the default is "enterprise", but when looking into the source you end up with: `apps/support/lib/Capabilities.php:38: 'desktopEnterpriseChannel' => $this->config->getSystemValueString('desktopEnterpriseChannel', 'stable'),`)

You are correct. This was one of the findings of last week's escalation. Besides the issue itself, it showed that the PR for the default was not yet merged - even so existing since quite some time already.

**Comment by supr4s** [comment]
Hi,

We experienced some side effects following the downgrade to 3.17.3. Some folders, configured as virtual file, were no longer accessible from Windows explorer. The update to 4.0.1 fixed the problem. Thank you !

**Comment by DanScharon** [comment]
> We are considering to switch to `occ config:system:set desktopEnterpriseChannel --value Enterprise` due to this bug to prevent future unexpected breakage and our users complaining, but the question is: how does that affect Clients that use multiple Instances?


After testing this setting it also seems that cases are important in that `Enterprise` as value doesn't work but `enterprise` does,

**Comment by stumbaumr** [comment]
Chocolatey is still distributing 4.0.0 as stable...
... over 6.000 people and rising are still suffering from your quality control...
https://community.chocolatey.org/packages/nextcloud-client
Can you maybe take control over that community package to keep control over it and your reputation?

**Comment by Rello** [comment]
> Chocolatey is still distributing 4.0.0 as stable... ... over 6.000 people and rising are still suffering from your quality control... https://community.chocolatey.org/packages/nextcloud-client Can you maybe take control over that community package to keep control over it and your reputation?

see the disclaimer

> Neither this package nor Chocolatey Software, Inc. are affiliated with or endorsed by Nextcloud

Please do not post here about unsupported distribution channels

**Comment by Rudiberto** [comment]
I have a serious problem on Server 31.0.8 and any Nextcloud desktop client using virtual files (3.17.3 or 4.0.1) after having installed errantly 4.0.0: 
Since then is there a folder named like the user itself, not deleteable and not available in the cloud. This folder is a problem, because the user has a dot at the end. How can I resolve this problem caused by the faulty client version 4.0.0

**Comment by Rello** [comment]
> I have a serious problem on Server 31.0.8 and any Nextcloud desktop client using virtual files (3.17.3 or 4.0.1) after having installed errantly 4.0.0: Since then is there a folder named like the user itself, not deleteable and not available in the cloud. This folder is a problem, because the user has a dot at the end. How can I resolve this problem caused by the faulty client version 4.0.0

do you have a screenshot?

**Comment by pcjc2** [comment]
> To assist with identifying which folders to clean up one could analyse the server access logs as well: look out for any `MKCOL` request done by a `4.0.0` client for a path where the last two components are the equal (e.g. `[...]/folder/folder`; this could also be the account's username)

Is there any way to query the backend database for this, or does it need to be extracted from the log files?

**Comment by Rudiberto** [comment]
I deleted the synchronization, and I'm now resyncing to a new folder using client version 3.17.3

It seems resolved now. Unfortunately I have no screenshot, since I did not take one before beginning to sync to the new folder, but it was a folder with the username "MaxT." like the Nextcloud user to access to the cloud.

**Comment by camilasan** [comment]
> I have a serious problem on Server 31.0.8 and any Nextcloud desktop client using virtual files (3.17.3 or 4.0.1) after having installed errantly 4.0.0: Since then is there a folder named like the user itself, not deleteable and not available in the cloud. This folder is a problem, because the user has a dot at the end. How can I resolve this problem caused by the faulty client version 4.0.0

I had this when testing. After running 4.0.1, I just ran the sync again. Did you try forcing the client to sync?
With that for me, the folder was gone.

**Comment by Rudiberto** [comment]
On this special PC that did not work properly. Three other PCs affected by 4.0.0-fail worked fine, after upgrading to 4.0.1. 
Since this one uses virtual folders, I guess that's the reason for the different behaviour.

**Comment by fmkaiser** [comment]
> Is there any way to query the backend database for this, or does it need to be extracted from the log files?

I used the following mysql query to get a list of empty directories with the same name as the parent, that were created after 2025-10-21 when 4.0.0 was released:
```
SELECT f.fileid,f.storage,f.path FROM oc_filecache f JOIN oc_filecache f0 ON (f.parent=f0.fileid) 
    WHERE f.name=f0.name AND f.size = 0 AND f.mtime > UNIX_TIMESTAMP('2025-10-21');
```

Note that this may still contain some "false positives" that were not caused by the 4.0.0 client issue.

**Comment by ivanjx** [comment]
got this bug after updating to 4.0. fortunately it does not really create the ghost folder on the server itself nor the filesystem. updating to 4.0.1 fixed it for me. i will be sure to disable nextcloud client auto update on all of my pc from now on.

**Comment by someone-somenet-org** [comment]
> got this bug after updating to 4.0. fortunately it does not really create the ghost folder on the server itself nor the filesystem. updating to 4.0.1 fixed it for me. i will be sure to disable nextcloud client auto update on all of my pc from now on.

Disabling auto updates is always a bad idea as you dont know what other bugs the current release has and which might get fixed soon and which if not fixed can cause fatal dataloss or other issues.

**Comment by ivanjx** [comment]
in my case weird bugs (like this one) always happens when auto update is enabled. rather stay on the version that works fine.

**Comment by camilasan** [comment]
> Since this one uses virtual folders, I guess that's the reason for the different behaviour.

It is.

**Comment by Christian-98** [comment]
Hi everyone, I noticed that the issue on milestone has been closed. The Windows plugin version 4.0.1 is now available for download here: https://github.com/nextcloud-releases/desktop/releases/tag/v4.0.1

Can I therefore consider the folder creation issue resolved and go ahead and ask all my collaborators to download the update?

**Comment by michel-thomas** [comment]
> Can I therefore consider the folder creation issue resolved and go ahead and ask all my collaborators to download the update?

[4.0.1 release](https://github.com/nextcloud-releases/desktop/releases/download/v4.0.1/Nextcloud-4.0.1-x64.msi) is now available for download, so I think it is considered as stable.

I tested on 2 laptop affected by the issue, and 4.0.1 solves the problem. So, thanks for quickly patching to the team involved!

**Comment by Rello** [comment]
Thank you everyone for your support and the patience on this issue

**Comment by Christian-98** [comment]
Good morning, I’ve updated all my plugins to version 4.0.1, but the duplicate folders haven’t been removed automatically.
Should I delete them manually?
@fmkaiser  shared a query to identify them — could that be useful to see which ones they are and then proceed with manual removal?

**Comment by tbal82** [comment]
Hello,

I have the same issue after upgrading to 4.0.1.

I’m using virtual folders, but just to be clear : those  duplicated folders are only present in some folders (not all) and only on my computer, not on the server when I go through my browser. So the query cannot be used in this case.

**Comment by toarujs** [comment]
> 早上好，我已经将所有插件更新到 4.0.1 版本，但重复的文件夹尚未自动删除。我应该手动删除它们吗？ 共享了一个查询来识别它们——这对于查看它们是哪些，然后继续手动删除是否有用？

需要手动删除，我写了个自动脚本，你可以试试

**Comment by michel-thomas** [comment]
> I’ve updated all my plugins to version 4.0.1, but the duplicate folders haven’t been removed automatically.
> Should I delete them manually?

I suppose so, but I encourage you to follow this new issue #9036 to have a clear answer. I tried many things but these subfolders are always recreated by clients!
