### ISSUE TITLE
System-wide proxy not used when adding a new account to the client

### ISSUE THREAD

**Issue by Volker-K** [nextcloud/desktop#901]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Client configuration
Client version:

Operating system:

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Operating system:

Web server:

Database:

PHP version:

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by Volker-K** [comment]
No change of behaviour in 2.5.1final build 20181204

**Comment by Volker-K** [comment]
Still happening in version 2.5.2. Client is sort of unusable for average users behind a proxy.

**Comment by Volker-K** [comment]
And 2.5.3: Still not solved. Even no triage.

**Comment by ozzi-** [comment]
I have the same issue, seeing there is no progress since nov 18 makes me slightly unconfortable

**Comment by Volker-K** [comment]
Same here. Configuration was deleted before installation of 2.6 RC, connect to any NC instance ended with a timeout.
"Use system proxy" is set in Network Settings-
I've entered our proxy manually -> it worked, but that's a workaround and no solution.

**Comment by ozzi-** [comment]
2.3.3.84 doesn't work either. owncloud 2.5.4 it works. lol

**Comment by Volker-K** [comment]
I wished, 2.5.4 was stable...

**Comment by Volker-K** [comment]
Official 2.6.0 got still the same error.

**Comment by Volker-K** [comment]
Happy anniversary!

**Comment by Volker-K** [comment]
Still no change in 2.6.2:
![2-6-1-still-no-system-proxy](https://user-images.githubusercontent.com/34368929/69944078-b4687680-14e6-11ea-93fd-8d903a4f5577.png)

**Comment by ozzi-** [comment]
See you in a year @Volker-K  :D

**Comment by Volker-K** [comment]
We will :-D https://github.com/ozzi-
I've built a dirty workaround with changing the ini-file during SCCM distribution. Works. At least today.

**Comment by Volker-K** [comment]
Still not fixed in 2.6.3.

**Comment by Volker-K** [comment]
Found out a possible reason for this issue. Accidentally...

Have a look at the manual (https://docs.nextcloud.com/desktop/2.6/)
Look out for Advanced Usage, Config File.
[proxy] section.

type, defaut (if nothing is set) is2.
2 = no proxy used.

That's exactly what the new login flow does: Doesn't us a proxy because the default value is 2. I tried it on a blank system: The sync process acts incorrect by using a system proxy although "no proxy" is set.

So perhaps the sync process should be fixed instead and in a perfect world we would get commandline options to set a proxy address during an automatic setup?

**Comment by er-vin** [comment]
@misch7 isn't it fixed with your recent PRs ?

**Comment by Volker-K** [comment]
I'll try it tomorrow via RDP in my company. Got no windows in my homeoffice ;-)

**Comment by claucambra** [comment]
Hi @Volker-K does this issue persist with the current nextcloud stable release?

**Comment by kn0wmad** [comment]
This is still not fixed in version 3.6.4, very frustrating - is there some resources that the devs could provide pointing to where this problem may be?  We would potentially be willing to put some resources into a PR
