### ISSUE TITLE
Client 2.5.1 crashes / disappears

### ISSUE THREAD

**Issue by roots84** [nextcloud/desktop#941]
### Expected behaviour
Client should run and not crash

### Actual behaviour
Client starts sync and disappears from the taskbar  without any error messages / Windows Event log entries

### Steps to reproduce
1. Update from NextCloud 2.5.0 to 2.5.1
2. NextCloud will start after installation, run for a while and creash / disappear

### Client configuration
Client version: 2.5.1:
`Version 2.5.1final (build 20181204). For more information please visit nextcloud.com.
This release was supplied by Nextcloud GmbH
Built from Git revision b37cbe on Dec 4 2018, 13:30:31 using Qt 5.11.1, OpenSSL 1.0.1h 5 Jun 2014`
Operating system: Windows 8.1
OS language: English
Installation path of client: C:\Program Files (x86)\Nextcloud

### Server configuration

Operating system: Ubuntu 16.04.5 LTS (Xenial Xerus)
Web server: Server version: Apache/2.4.37 (Ubuntu)
Database: MySQL 5.7.24-0ubuntu0.16.04.1 - (Ubuntu)
PHP version: 7.2.13-1+ubuntu16.04.1+deb.sury.org+1
Nextcloud version: 14.0.3

Storage backend (external storage):

### Logs

1. Client logfile: Does not work. I've tried `nextcloud --logfile log.txt` and `nextcloud --logdir D:` but neither does save anything.

**Comment by alerque** [comment]
I'm seeing something very similar to this, silent crashes in the client on startup — on two different systems I'm just installing from scratch. The major difference is my desktop OS is Linux (Archlinux), so this might not be a Windows only problem.

**Comment by roots84** [comment]
Although the issues might be related my issue is at a different point than yours or the referenced one. I had 2 accounts configured in 2.5.0 (which are still present in 2.5.1) and the client is not crashing on startup but after a few seconds after starting the sync. When I press F12 right after starting the client I can see (although veeeery unresponsive) some sync messages before it freezes completely and disappears (after a seemingly random amount of time).

While testing it just "properly" crashed. Might be totally unrelated but here goes the details:
`Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	nextcloud.exe
  Application Version:	2.5.1.61652
  Application Timestamp:	5c0674e1
  Fault Module Name:	Qt5Gui.dll
  Fault Module Version:	5.11.1.0
  Fault Module Timestamp:	5b234aee
  Exception Code:	c000041d
  Exception Offset:	000000000003cf57
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	1031
  Additional Information 1:	7b5d
  Additional Information 2:	7b5df6eb88d5a4479c6e699d675e953f
  Additional Information 3:	e61f
  Additional Information 4:	e61faa1efc6fa448ff4f32eaf0dc769d

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt`

![image](https://user-images.githubusercontent.com/11146296/50009220-adcfaf00-ffb6-11e8-9523-afa031fdb974.png)

**Comment by knezi** [comment]
I get the same. Log attached. I can see nothing wrong. I don't know why, but I'm always getting this dialogue "approve login." Might be related.

[out.txt](https://github.com/nextcloud/desktop/files/2682431/out.txt)

**Comment by dvzrv** [comment]
I'm also seeing app crash (on Arch Linux) right after *Grant Access* with the following terminal output:

```
Received signal 11 SEGV_ACCERR 04058fd90600
#0 0x6a7b8815d98e <unknown>
#1 0x6a7b88156713 <unknown>
#2 0x6a7b8815d905 <unknown>
#3 0x6a7b81741e00 <unknown>
#4 0x04058fd90600 ([heap]+0x2a2e45ff)
  r8: 000004059042ccd0  r9: 0000000000000003 r10: 0000000000000000 r11: 0000000000000000
 r12: 00007e6c22952e90 r13: 00007e6c22952eb0 r14: 0000000000000001 r15: 000004058fe2dc20
  di: 000004058fe2dc20  si: 000004059042ccd0  bp: 00007e6c22952e60  bx: 000004058fd2f160
  dx: 000004058fe2dc30  ax: 000004058fd905b0  cx: 000004058fe2dc30  sp: 00007e6c22952e18
  ip: 000004058fd90600 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000015
 trp: 000000000000000e msk: 0000000000000000 cr2: 000004058fd90600
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

**Comment by kaldyr** [comment]
Also crashing for me on Arch Linux 2.5.1.  

`Received signal 11 SEGV_ACCERR 5561016e4900
#0 0x7f4b7c3d398e <unknown>
#1 0x7f4b7c3cc713 <unknown>
#2 0x7f4b7c3d3905 <unknown>
#3 0x7f4b759b7e00 <unknown>
#4 0x5561016e4900 <unknown>
  r8: 00005560fd263cb0  r9: 0000000000000003 r10: 0000000000000000 r11: 0000000000000000
 r12: 00007ffc05925750 r13: 00007ffc05925770 r14: 0000000000000001 r15: 00005560fd1ff8d0
  di: 00005560fd1ff8d0  si: 00005560fd263cb0  bp: 00007ffc05925720  bx: 00005561016d5520
  dx: 00005560fd1ff8e0  ax: 00005561016d6100  cx: 00005560fd1ff8e0  sp: 00007ffc059256d8
  ip: 00005561016e4900 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000015
 trp: 000000000000000e msk: 0000000000000000 cr2: 00005561016e4900`

**Comment by dvzrv** [comment]
I have a more detailed stack trace here:
[nextcloud-stacktrace.txt](https://github.com/nextcloud/desktop/files/2683428/nextcloud-stacktrace.txt)

**Comment by flokli** [comment]
Same issue with [nextcloud-client-2.5.0-4-x86_64.pkg.tar.xz](https://archive.archlinux.org/packages/n/nextcloud-client/nextcloud-client-2.5.0-4-x86_64.pkg.tar.xz)

**Comment by dvzrv** [comment]
Hmm, this is a little odd. At first I thought this is due to our qt being > 5.12.0, but @roots84 has qt 5.11.1 on his machine.
Maybe two different problems, but same outcome then?

**Comment by yan12125** [comment]
Here's a complete stack trace
```
#0  0x0000555556181f30 in  ()
#1  0x00007ffff2576e91 in GetStoragePartitionFromConfig() ()
    at ../../../../qtwebengine-everywhere-src-5.12.0/src/3rdparty/chromium/content/browser/browser_context.cc:155
#2  0x00007ffff257732f in content::BrowserContext::GetStoragePartition(content::BrowserContext*, content::SiteInstance*, bool)
    () at ../../../../qtwebengine-everywhere-src-5.12.0/src/3rdparty/chromium/content/browser/browser_context.cc:321
#3  0x00007ffff28add2f in ShouldUseSiteProcessTracking ()
    at ../../../../qtwebengine-everywhere-src-5.12.0/src/3rdparty/chromium/content/browser/renderer_host/render_process_host_impl.cc:990
#4  0x00007ffff28add2f in ShouldTrackProcessForSite() ()
    at ../../../../qtwebengine-everywhere-src-5.12.0/src/3rdparty/chromium/content/browser/renderer_host/render_process_host_impl.cc:1003
#5  0x00007ffff28bc31a in ShouldTrackProcessForSite ()
    at ../../../../qtwebengine-everywhere-src-5.12.0/src/3rdparty/chromium/content/browser/renderer_host/render_process_host_impl.cc:2626
#6  0x00007ffff28bc31a in content::RenderProcessHostImpl::RemoveExpectedNavigationToSite(content::BrowserContext*, content::RenderProcessHost*, GURL const&) ()
    at ../../../../qtwebengine-everywhere-src-5.12.0/src/3rdparty/chromium/content/browser/renderer_host/render_process_host_impl.cc:2627
#7  0x00007ffff26d8e39 in content::NavigationHandleImpl::~NavigationHandleImpl() ()
    at ../../../../qtwebengine-everywhere-src-5.12.0/src/3rdparty/chromium/content/browser/frame_host/navigation_handle_impl.cc:280
#8  0x00007ffff26d9001 in content::NavigationHandleImpl::~NavigationHandleImpl() ()
    at ../../../../qtwebengine-everywhere-src-5.12.0/src/3rdparty/chromium/content/browser/frame_host/navigation_handle_impl.cc:294
#9  0x00007ffff26dfbe7 in std::default_delete<content::NavigationHandleImpl>::operator()(content::NavigationHandleImpl*) const
    () at /usr/include/c++/8.2.1/bits/unique_ptr.h:81
#10 0x00007ffff26dfbe7 in std::unique_ptr<content::NavigationHandleImpl, std::default_delete<content::NavigationHandleImpl> >::~unique_ptr() () at /usr/include/c++/8.2.1/bits/unique_ptr.h:274
#11 0x00007ffff26dfbe7 in content::NavigationRequest::~NavigationRequest() ()
    at ../../../../qtwebengine-everywhere-src-5.12.0/src/3rdparty/chromium/content/browser/frame_host/navigation_request.cc:540
#12 0x00007ffff26dfe01 in content::NavigationRequest::~NavigationRequest() ()
    at ../../../../qtwebengine-everywhere-src-5.12.0/src/3rdparty/chromium/content/browser/frame_host/navigation_request.cc:546
#13 0x00007ffff26c1a51 in std::default_delete<content::NavigationRequest>::operator()(content::NavigationRequest*) const ()
    at /usr/include/c++/8.2.1/bits/unique_ptr.h:81
#14 0x00007ffff26c1a51 in std::unique_ptr<content::NavigationRequest, std::default_delete<content::NavigationRequest> >::reset(content::NavigationRequest*) () at /usr/include/c++/8.2.1/bits/unique_ptr.h:382
#15 0x00007ffff26c1a51 in content::FrameTreeNode::ResetNavigationRequest(bool, bool) ()
    at ../../../../qtwebengine-everywhere-src-5.12.0/src/3rdparty/chromium/content/browser/frame_host/frame_tree_node.cc:476
#16 0x00007ffff26e46a4 in content::NavigationRequest::OnRequestFailedInternal(network::URLLoaderCompletionStatus const&, bool, base::Optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&, bool) ()
    at ../../../../qtwebengine-everywhere-src-5.12.0/src/3rdparty/chromium/content/browser/frame_host/navigation_request.cc:1147
#17 0x00007ffff26e4809 in content::NavigationRequest::OnRequestFailed(network::URLLoaderCompletionStatus const&) ()
    at ../../../../qtwebengine-everywhere-src-5.12.0/src/3rdparty/chromium/content/browser/frame_host/navigation_request.cc:1113
#18 0x00007ffff27b37f5 in content::NavigationURLLoaderImpl::OnComplete(network::URLLoaderCompletionStatus const&) ()
    at ../../../../qtwebengine-everywhere-src-5.12.0/src/3rdparty/chromium/content/browser/loader/navigation_url_loader_impl.cc:1464
#19 0x00007ffff27b37f5 in content::NavigationURLLoaderImpl::OnComplete(network::URLLoaderCompletionStatus const&) ()
    at ../../../../qtwebengine-everywhere-src-5.12.0/src/3rdparty/chromium/content/browser/loader/navigation_url_loader_impl.cc:1456
#20 0x00007ffff2b8f280 in base::OnceCallback<void ()>::Run() && ()
    at ../../../../qtwebengine-everywhere-src-5.12.0/src/3rdparty/chromium/base/callback.h:99
#21 0x00007ffff2b8f280 in base::debug::TaskAnnotator::RunTask(char const*, base::PendingTask*) ()
    at ./../../../../qtwebengine-everywhere-src-5.12.0/src/3rdparty/chromium/base/debug/task_annotator.cc:101
#22 0x00007ffff2bb2a02 in base::MessageLoop::RunTask(base::PendingTask*) ()
    at ./../../../../qtwebengine-everywhere-src-5.12.0/src/3rdparty/chromium/base/message_loop/message_loop.cc:421
#23 0x00007ffff2bb364f in base::MessageLoop::DeferOrRunPendingTask(base::PendingTask) ()
    at ./../../../../qtwebengine-everywhere-src-5.12.0/src/3rdparty/chromium/base/message_loop/message_loop.cc:432
#24 0x00007ffff2bb37d8 in base::MessageLoop::DoWork() ()
    at ./../../../../qtwebengine-everywhere-src-5.12.0/src/3rdparty/chromium/base/message_loop/message_loop.cc:480
#25 0x00007ffff0ff2cb5 in QtWebEngineCore::(anonymous namespace)::MessagePumpForUIQt::handleScheduledWork (this=0x5555561c8450)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-everywhere-src-5.12.0/src/core/browser_main_parts_qt.cpp:157
#26 0x00007ffff0ff2cb5 in QtWebEngineCore::(anonymous namespace)::MessagePumpForUIQt::timerEvent(QTimerEvent*)
    (this=0x5555561c8450, ev=<optimized out>)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-everywhere-src-5.12.0/src/core/browser_main_parts_qt.cpp:151
#27 0x00007fffebee1b1b in QObject::event(QEvent*) (this=0x5555561c8450, e=<optimized out>) at kernel/qobject.cpp:1230
#28 0x00007fffec886e34 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    (this=this@entry=0x55555598f060, receiver=receiver@entry=0x5555561c8450, e=e@entry=0x55555a1e5c80)
    at kernel/qapplication.cpp:3752
#29 0x00007fffec88e671 in QApplication::notify(QObject*, QEvent*)
    (this=0x7fffffffdc40, receiver=0x5555561c8450, e=0x55555a1e5c80) at kernel/qapplication.cpp:3499
#30 0x00007fffebeb68f9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x5555561c8450, event=0x55555a1e5c80)
    at ../../include/QtCore/5.12.0/QtCore/private/../../../../../src/corelib/thread/qthread_p.h:322
#31 0x00007fffebeb9998 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*)
    (receiver=0x0, event_type=0, data=0x555555988980) at kernel/qcoreapplication.cpp:1800
#32 0x00007fffebf0cfd4 in postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0x5555559cd710)
    at kernel/qeventdispatcher_glib.cpp:276
#33 0x00007fffeb6133cf in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#34 0x00007fffeb614f89 in  () at /usr/lib/libglib-2.0.so.0
#35 0x00007fffeb614fce in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#36 0x00007fffebf0c5a9 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)
    (this=0x5555559dc2a0, flags=...) at kernel/qeventdispatcher_glib.cpp:422
#37 0x00007fffebeb558c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffffffdb70, flags=..., 
    flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#38 0x00007fffebebd896 in QCoreApplication::exec() () at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#39 0x00005555556a3257 in main(int, char**) (argc=1, argv=0x7fffffffde28) at /home/yen/Projects/desktop/src/gui/main.cpp:167
```

A similar issue on Qt bug tracker is fixed in 5.10.1, but reappeared in 5.11 beta: https://bugreports.qt.io/browse/QTBUG-66081

For Arch Linux users interested but too lazy to build a copy of Qt with debug symbols, here are prebuilt debug packages: https://wiki.archlinux.org/index.php/unofficial_user_repositories#qt-debug

**Comment by milouse** [comment]
For your infomation, on Archlinux, coming back to qt 5.11.2 (and qt5-webkit 5.212.0alpha2-21) resolves the problem.

**Comment by jaghili** [comment]
Same problem here with 2.5.1git  
> Received signal 11 SEGV_ACCERR 556cb4cfec70
> #0 0x7fb12f3e098e <unknown>
> #1 0x7fb12f3d9713 <unknown>
> #2 0x7fb12f3e0905 <unknown>
> #3 0x7fb1289c4e00 <unknown>
> #4 0x556cb4cfec70 ([heap]+0x11b0c6f)
>   r8: 0000556cb482c010  r9: 0000000000000003 r10: 0000000000000000 r11: 0000000000000000
>  r12: 00007ffec41140d0 r13: 00007ffec41140f0 r14: 0000000000000001 r15: 0000556cb4cfbe90
>   di: 0000556cb4cfbe90  si: 0000556cb482c010  bp: 00007ffec41140a0  bx: 0000556cb4658f50
>   dx: 0000556cb4cfbea0  ax: 0000556cb4cfec20  cx: 0000556cb4cfbea0  sp: 00007ffec4114058
>   ip: 0000556cb4cfec70 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000015
>  trp: 000000000000000e msk: 0000000000000000 cr2: 0000556cb4cfec70
> [end of stack trace]
> Calling _exit(1). Core file will not be generated.

reverting to version 2.5.0git does not solve the issue, same problem occurs.

**Comment by Celti** [comment]
On Arch Linux this is resolved by specifically downgrading qt5-webengine to 5.11.2 — the rest of Qt5 can remain at 5.12 without issue.

**Comment by jaghili** [comment]
> On Arch Linux this can be worked around by specifically downgrading qt5-webengine to 5.11.2 — the rest of Qt5 can remain at 5.12 without issue.

I downgraded qt5-webengine to 5.11.2, when I launch nextcloud I obtain 
> nextcloud: error while loading shared libraries: libicui18n.so.62: cannot open shared object file: No such file or directory

I tried to downgrade the icu package to 62 but I obtain 
> nextcloud: error while loading shared libraries: libicui18n.so.63: cannot open shared object file: No such file or directory

I symlinked libicui packages to 63 version,  then I get 
> nextcloud: symbol lookup error: /usr/lib/libQt5WebEngineCore.so.5: undefined symbol: _ZN6icu_628ByteSink15GetAppendBufferEiiPciPi

It seems that other (qt?) packages needs to be downgraded too. Can you please specify (in details) which version of qt packages work along with qt5-webengine 5.11.2 ?

**Comment by yan12125** [comment]
I managed to get rid of crashes with https://github.com/nextcloud/desktop/pull/959. For Arch Linux users, the patched version nextcloud-client 2.5.1-2 can be found from [community-testing].

**Comment by viperk15** [comment]
Hello, 

i've had the same problem with nextcloud client 2.5.4.11654.11466.msi

1 . Install Setup
2. Open Nextcloud Client
3. It shows the logon screen
4. app crashes
5. in eventlog ID 1000
Name der fehlerhaften Anwendung: nextcloud.exe, Version: 2.5.2.5231, Zeitstempel: 0x5c90e346
Name des fehlerhaften Moduls: Qt5Core.dll, Version: 5.11.1.0, Zeitstempel: 0x5b234a4c
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00000000001e134a
ID des fehlerhaften Prozesses: 0x49ec
Startzeit der fehlerhaften Anwendung: 0x01d4eecc7bf21231
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\Nextcloud\nextcloud.exe
Pfad des fehlerhaften Moduls: C:\Program Files (x86)\Nextcloud\Qt5Core.dll
Berichtskennung: 6e7e9c57-74c8-4cf2-b8ab-648debc0b53f
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

The Nextcloud Server is at a public provider...

Can anyone help me ?

**Comment by yan12125** [comment]
Can anyone get a complete stack trace like https://github.com/nextcloud/desktop/issues/941#issuecomment-447637263 for crashes in version 2.5.2? That will be useful.

If I remember it correctly Visual Studio can generate a similar stack trace.

**Comment by roots84** [comment]
I got some windows crashdumps if that helps: 
![image](https://user-images.githubusercontent.com/11146296/55871657-684d7800-5b8b-11e9-9892-c5ba84de6bc2.png)

Interestingly the crashing stopped yesterday and the sync issues went away after I added thumbs.db to the ignored file list (although I'm pretty sure it was already in there with several other files which aren't there anymore. Looks like something wiped the list)

**Comment by yan12125** [comment]
@roots84: those files should be quite useful. However, there might be your server URL, username or even password in memory dumps, I don't suggest just uploading them for debugging. You may want to filter out personal information using WinDbg as described in [1] first.

[1] https://github.com/Microsoft/WinObjC/wiki/Debugging-Stack-Traces-from-Crash-Dumps

**Comment by roots84** [comment]
@yan12125 Thanks for the reply. Although this won't help much since I don't have the symbols. Are they available somewhere?

**Comment by yan12125** [comment]
> Are they available somewhere?

Sorry I'm not sure. But I believe even incomplete stack traces like the one in https://github.com/nextcloud/desktop/issues/1110 are also useful.

**Comment by roots84** [comment]
Here you go. Did it for 2 different crash dumps.
```
Microsoft (R) Windows Debugger Version 6.3.9600.17336 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\Users\root.s\AppData\Local\CrashDumps\nextcloud.exe.10600.dmp]
User Mini Dump File: Only registers, stack and portions of memory are available

Symbol search path is: *** Invalid ***
****************************************************************************
* Symbol loading may be unreliable without a symbol search path.           *
* Use .symfix to have the debugger choose a symbol path.                   *
* After setting your symbol path, use .reload to refresh symbol locations. *
****************************************************************************
Executable search path is: 
Windows 8 Version 9600 MP (4 procs) Free x64
Product: WinNt, suite: SingleUserTS
Built by: 6.3.9600.18217 (winblue_ltsb.160124-0053)
Machine Name:
Debug session time: Tue Apr  9 15:32:56.000 2019 (UTC + 2:00)
System Uptime: not available
Process Uptime: 0 days 0:06:26.000
................................................................
................................................................
...........
Loading unloaded module list
......
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(2968.2694): Access violation - code c0000005 (first/second chance not available)
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for ntdll.dll - 
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for KERNELBASE.dll - 
ntdll!NtWaitForMultipleObjects+0xa:
00007ff8`79a50d0a c3              ret
0:007> .exepath+ C:\Program Files (x86)\Nextcloud\
Executable image search path is: C:\Program Files (x86)\Nextcloud\
Expanded Executable image search path is: c:\program files (x86)\nextcloud\

************* Symbol Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:\Program Files (x86)\Nextcloud\
0:007> .sympath+ srv*https://msdl.microsoft.com/download/symbols
Symbol search path is: srv*https://msdl.microsoft.com/download/symbols
Expanded Symbol search path is: srv*https://msdl.microsoft.com/download/symbols

************* Symbol Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*https://msdl.microsoft.com/download/symbols
0:007> .ecxr
*** WARNING: Unable to verify checksum for Qt5Core.dll
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for Qt5Core.dll - 
rax=0000007b23a8ab40 rbx=0000000000000000 rcx=0000000000000010
rdx=0000000000001000 rsi=00000000000003aa rdi=0000000000002a1d
rip=00007ff841d10981 rsp=0000007b23a8aae0 rbp=0000000000001000
 r8=0000000000000001  r9=0000007b23a8ab20 r10=0000000000000005
r11=0000007b23a89a28 r12=0000000000000000 r13=0000007b20a691c0
r14=0000007b280be040 r15=0000000000000301
iopl=0         nv up ei pl nz na pe nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010202
Qt5Core!QRingBuffer::reserve+0x31:
00007ff8`41d10981 3911            cmp     dword ptr [rcx],edx ds:00000000`00000010=????????

```




```
Microsoft (R) Windows Debugger Version 6.3.9600.17336 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\Users\root.s\AppData\Local\CrashDumps\nextcloud.exe.10480.dmp]
User Mini Dump File: Only registers, stack and portions of memory are available

Symbol search path is: *** Invalid ***
****************************************************************************
* Symbol loading may be unreliable without a symbol search path.           *
* Use .symfix to have the debugger choose a symbol path.                   *
* After setting your symbol path, use .reload to refresh symbol locations. *
****************************************************************************
Executable search path is: 
Windows 8 Version 9600 MP (4 procs) Free x64
Product: WinNt, suite: SingleUserTS
Built by: 6.3.9600.18217 (winblue_ltsb.160124-0053)
Machine Name:
Debug session time: Tue Apr  9 15:33:51.000 2019 (UTC + 2:00)
System Uptime: not available
Process Uptime: 0 days 0:00:51.000
................................................................
................................................................
...........
Loading unloaded module list
......
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(28f0.2200): Access violation - code c0000005 (first/second chance not available)
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for ntdll.dll - 
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for KERNELBASE.dll - 
ntdll!NtWaitForMultipleObjects+0xa:
00007ff8`79a50d0a c3              ret
0:009> .exepath+ C:\Program Files (x86)\Nextcloud
Executable image search path is: C:\Program Files (x86)\Nextcloud
Expanded Executable image search path is: c:\program files (x86)\nextcloud

************* Symbol Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:\Program Files (x86)\Nextcloud
0:009> .sympath+ srv*https://msdl.microsoft.com/download/symbols
Symbol search path is: srv*https://msdl.microsoft.com/download/symbols
Expanded Symbol search path is: srv*https://msdl.microsoft.com/download/symbols

************* Symbol Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*https://msdl.microsoft.com/download/symbols
0:009> .ecxr
*** WARNING: Unable to verify checksum for Qt5Core.dll
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for Qt5Core.dll - 
rax=0000003ac40cb000 rbx=0000000000000000 rcx=0000000000000010
rdx=0000000000001000 rsi=00000000000003aa rdi=0000000000002a1d
rip=00007ff841d10981 rsp=0000003ac40cafa0 rbp=0000000000001000
 r8=0000000000000001  r9=0000003ac40cafe0 r10=0000000000000009
r11=0000003ac40c9ee8 r12=0000000000000000 r13=0000003ac10a2780
r14=0000003ac9cb7050 r15=0000000000000301
iopl=0         nv up ei pl nz na pe nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010202
Qt5Core!QRingBuffer::reserve+0x31:
00007ff8`41d10981 3911            cmp     dword ptr [rcx],edx ds:00000000`00000010=????????

```

**Comment by yan12125** [comment]
From the stack trace I guess the issue is related to interaction between qt and openssl. Anyway that's a quite different issue from this one. Could you open a new issue for the crash?

**Comment by aljaxus** [comment]
I'm having some issues with latest (as of jul 3rd 2019) .appimage
##### Expected behaviour
I'd be able to simply run the .appimage and the client should work

##### Actual behaviour
The appimage crashed on every startup
The appimage does not start at system bootup

##### Environment
Running Ubuntu 18.14 with gnome
```
uname -a
Linux aljaxusPc 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

##### Other info
This is the log; https://hastebin.app/1562191114169

I read this thread and some users were mentioning having issues on Arch. I recently switched to Arch on my laptop, using KDE as desktop environment, and I haven't had any issues whatsoever.

**Comment by yan12125** [comment]
From this line in your log:

> nouveau_pushbuf_data: Assertion `kref' failed.

I found another issue: https://github.com/rstudio/rstudio/issues/3781#issuecomment-434148237. Looks like there is some bug in the nouveau driver. Switching to nvidia driver may help.

> I recently switched to Arch on my laptop, using KDE as desktop environment, and I haven't had any issues whatsoever.

Arch comes with a newer nouveau ([1.0.16](https://www.archlinux.org/packages/extra/x86_64/xf86-video-nouveau/)) driver than Ubuntu ([1.0.15](https://packages.ubuntu.com/source/bionic/xserver-xorg-video-nouveau)). The nouveau bug may have been fixed.
