### ISSUE TITLE
Client does not recover from standby

### ISSUE THREAD

**Issue by kevinkk525** [nextcloud/desktop#970]
### Expected behaviour
After Windows was in standby, the client should recover correctly.

### Actual behaviour
Synchronization shows the error: "Beim Öffnen eines Ordners ist ein Fehler aufgetreten. Der Zugriff auf das Netzwerk ist nicht gestattet."
Which translates loosely into "Error opening a folder, access to the network is not granted."
Even a forced synchronization does ont fix it, only exiting the client and starting it again works.

### Steps to reproduce
1. Put PC into standby
2. Wake up
3. Try to synchronize

### Client configuration
Client version: 2.5.1final

Operating system: Windows 10

OS language: German

Installation path of client: Standard

**Comment by nicogodet** [comment]
Have the same issue with the same configuration.
Win10 & Client 2.5.1final.

I downgrade to a previous version waiting for a fix

**Comment by Kalekulan** [comment]
Same issue here.

**Comment by MorphBonehunter** [comment]
As mentioned in #980 (dup to this one) this isn't an Windows only problem, it also happens on Linux.
Furthermore the "forced synchronization" as mentioned in the description isn't even an option on my systems as the clients crash after the error on Windows and Linux.

**Comment by anatomism** [comment]
Confirm this is an issue for me 2.5.1, Windows 10 x64 October 18 update

**Comment by vasyugan** [comment]
same here, observing it here only on Windows, not on Linux. Forced synchronisation does not help. Reproduced on several Windows machines.

**Comment by strassea** [comment]
I have the same issue in Win10 Home 1809, the language is also German

**Comment by omocinteractive** [comment]
Same issue WIN 10 Pro, NC 15.02 and NC Client 2.5.1 (german). After downgrade to 2.3.3 everything allright.

**Comment by pmoser1976** [comment]
I have same issue on Win10Pro 1809, NC 15.0.5 and Windows Client 2.5.1final.

**Comment by ReinhardBiegelIntech** [comment]
Same issue here. In addition, the client crashes after viewing the application window containing the error message.

**Comment by yvesle** [comment]
I updated to the windows client 2.5.2git (build 20190319) yesterday manually. It seems to have fixed it for me (Windows 7, server 15.0.7)

**Comment by fkbreitl** [comment]
I notice this problem too with version 2.5.2git (build 20190319).

**Comment by Schleichmichl** [comment]
Same issue here on a Acer Convertible, when sending to sleep, which happens often...
Microsoft Windows [Version 10.0.17763.437]
Version 2.5.1final (build 20181204).

**Comment by luixxiul** [comment]
it looks fixed on 2.5.2

**Comment by ReinhardBiegelIntech** [comment]
For me, 2.5.2 fixed that issue

**Comment by paveldvorak5** [comment]
still crashing on debian with 2.5.2

**Comment by kevinkk525** [comment]
Fixed for everyone now? On windows 10 it is working fine.

**Comment by luixxiul** [comment]
> 
> 
> Fixed for everyone now? On windows 10 it is working fine.

Yeah me too, it looks like fixed since several (minor) versions.

**Comment by fkbreitl** [comment]
I still have the same problem with Version 2.6.0stable-Win32 (build 20190927) from https://portapps.io/app/nextcloud-portable/ on Windows 10.
`"An error occurred while opening a folder Network access is disabled."`

**Comment by kevinkk525** [comment]
Please open a bug for your specific environment. It seems to be fixed for everyone else and I don't like to keep my issues open forever.

**Comment by huste** [comment]
Is there any log file to examine for issues like that? The log files in %APPDATA% don't list eny errors.

I am seeing a similar problem on my Win10 64bit with  2.6.1 stable build 20191105. I have three folder synchronsations added and one of them occasionally fails with a double message "Beim Öffnen des Ordners ist ein Fehler aufgetreten." and *only* after pausing and continuing synchronization, the nextcloud client crashes without any further notice and has to be restarted. After which the error message ist gone and I can't tell for sure, if there's more information. I'll take screenshots next time.

**Comment by fefrei** [comment]
This issue has started to affect me now, every time after the system was hibernated.
If it happens, it affects all folders and accounts, and forced synchronization does not help, only a restart of the client does.
This is on Windows 10 20H2, client version 3.0.3.

**Comment by sude22** [comment]
Please reopen, see @fefrei comment

**Comment by fkbreitl** [comment]
@sude22 Thanks for pointing this out.
According to https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github I reopened #2678.
